from ..program4739 import program4739
def test34():
    assert program4739(ABAABACABADAACADABACAAB
BAACABADABACABAAAADADAABACABACABADABABADABACABAADABBADABACAAACAABACABADABBBAA
DABACA) == ['ABAABACABADAACAABACAAB', 'ABAABACABADAACADABAAAB']