from ..program4739 import program4739
def test33():
    assert program4739(ABAAAABABADABAABAABCCABADABACABACABCABADABADABACABBACAADABACABABACABADABACABABA
BACAACABABABACABCABADABAACABADABACABAA
ABBAB) == ['BACAACABABABACABCAADABAACABADABACABAA', 'BACAACABABABACABCABAABAACABADABACABAA', 'BAAACABABABACABCABADABAACABADABACABAA']