from ..program4739 import program4739
def test17():
    assert program4739(GOZVMIRQIGYGVAGOREQTXFXPEZYOJOXPNDGAESICXHMKQDXQPRLMRVWHXFEJVCWZDLYMQLDURUXZPTLEHPTSKXGSNEQDKLVFFLDX
IMEVFCZXACKRRJVXDRKFWTLTRTLQQDHEBZLCOCNVPABQMIWJHRLKFUKWOVVWGGNWCJNRYOYOAJFQWCLHQIQRBZTVWKBFOXKEHHQP
SZ) == ['IEFZXACKRRVXFWLRTLHPKGNQLVFX', 'IVARXFEZONAIHRLVWJWLQRZTKXEQ', 'MVARXFEZOPAIHRLVWFCLQRZTKXEQ']