from ..program4739 import program4739
def test14():
    assert program4739(EGQYYSKTFTURZNRDVIWBYXMRDGFWMYKFXGIFOGYJSXKDCJUAGZPVTYCHIXVFTVTCXMKHZFTXSMMQVFXZGKHCIYODDRZEYECDLKNG
PEXXCTRFJAAKPOTBAEFRLDRZKORNMXHHXTLKMKCGPVPUOBELPLFQFXOBZWIVIQCHEJQPXKGSCQAWIMETCJVTAGXJIINTADDXJTKQ
QURSEKPMSSEVQZI) == ['ETFTBRDKOXKCGPVFVCHQXKCIECDK', 'EKTFRZRXMGFFXOZVCHXCMTVGIDDK', 'ETFTBRDKOXKCGPVXVCHQXKCIECDK', 'EKTFRZNXMGFFXIJXKCATCVTXTDDK', 'EKTFRZNXMGFFXIJXKCATCVTXIDDK']