from ..program4739 import program4739
def test13():
    assert program4739(KEJHTOKHMKWTYSJEAJAXGADRHUKBCRHACSRDNSZIHTPQNLOSRKYBGYIIJDINTXRPMWSVMMBODAYPVVDDTIXGDIOMWUAKZVFKDAUM
WTEVPIFAAJYIDTZSZKPPQKIOMHDZTKDMFVKSJRUFMNHZJPVSQYELWYAFACGGNRORSLGYVXAEYVLZBLDEHYDGOFDSWUYCXLXDKFSU
TUZEQBWVBVTKETQ) == ['EJTKHMKSJRUNHPQLYGNRSVAYVDDGOWUKFU', 'EJTOKMKSJRUHZPQLYGNRSVAYVDDGDWUKFU', 'EJTOKMKSJRUNZPQLYGNRSVAYVDDGDWUKFU', 'EJHTKMKSJRUHZPQLYGNRSVAYVDDGDWUKFU']