from ..program4739 import program4739
def test4():
    assert program4739(CGPWTAPEVBTGANLCLVSHQIIKHDPVUHRSQPXHSNYAHPGBECICFQYDFRTRELLLEDZYWJSLOBSKDGRRDHNRRGIXAMEBGFJJTEIGUGRU
HAWYVKRRBEIWNOGYMIYQXDCFXMMCSAYSOXQFHHIFRRCJRAWHLDDHHHAKHXVKCVPBFGGEXUKWTFWMOUUGMXTSBUTHXCJCWHCQQTYQ
ANKFDWLYSX) == ['WVBGIQXSYHIFRRWLDDHXBGEUGU', 'WVBNIQXSYHIFRRJLDDHXBFGUGU', 'AVBIIQXSAHIFRRWLDDHXBFGUGU', 'WVBGCSSQHHIFRRWLDDHXBGFUGU', 'AVBNIQXSAHIFRRJLDDHABFGUGU', 'WVBNIDXSYHIFRRWLDDHXBGFUGU']