from ..program4739 import program4739
def test3():
    assert program4739(QNHRPFYMAAPJDUHBAEXNEEZSTMYHVGQPYKNMVKMBVSVLIYGUVMJHEFLJEPIWFHSLISTGOKRXNMSCXYKMAXBPKCOCNTIRPCUEPHXM
RRFCZUGFDRKKMQTOETNELXMEWGOCDHFKIXOPVHHEWTCDNXVFKFKTKNWKEIKTCMHMHDNCLLVQSGKHBCDDYVVVQIRPZEOPUGQUGRHH
R) == ['FUENEMGKIVHEFEIHLSGKBCIPEPH', 'FDENEMGKIVHEWFTKNMCKBCIPEPH', 'FMENEEHKIVHEFEIHLSGKCYPOPUH', 'QNHFPHEXNETMHMHLLSGKCYPOPUH', 'QNHFPHETVKNKMMHLLSGKBCIPEPH', 'FDENEMGKIVHEFEIHLSGKCYPOPUH']