from ..program4739 import program4739
def test5():
    assert program4739(AUNBEKNURNUPHXQYKUTAHCOLMPRQZZTVDUYCTNIRACQQTQAIDTAWJXBUTIZUASDIJZWLHAQVGCAHKTZMXSDVVWAIGQEALRFKFYTT
QBVRFKPKLYZLYNRFTRJZZQEYAEKPFXVICUVFVQSDENBJYYNCFTOZHULSWJQTNELYLKCZTGHOARDCFXBXQGGSQIVUCJVNGFZEEZQE
N) == ['BKPYTRZZVICQDJTZUSJZHAQGSVVGQE', 'BRPKLZYTRQAXIUSDJZWLHACXSVVGQE', 'BRPKLRZZYACQDBTZUSWLHACXSVVGQE', 'BRPKLRZZYICQDJTZUSJZHAQGSVVGQE', 'BKPKLRZZVICQDJTZUSJZHAQGSVVGQE']