from ..program4739 import program4739
def test7():
    assert program4739(AXBPBDEYIYKKCZBTLKBUNEQLCXXLKIUTOOATYDXYYQCLFAXAEIGTFMNTTQKCQRMEEFRYVYXAOLMUQNPJBMFBUGVXFZAJSBXWALSI
VWFONLLKSHGHHQSFBBFWTXAITPUKNDANOCLMNFTAAMJVDLXYPILPCJCFWTNBQWEOMMXHRYHEGBJIVSXBBGQKXRIYNZFIWSZPPUUM
PPKKLHXWWT) == ['BBITKNCLTADXYCFTNQMRYVXBBGXFWS', 'BBITUNCLTADXYLFTNQERYVXBBGXZWS', 'BBITKNCLTADXYCFTNQMRYVXBBGXZWS']