from ..program4739 import program4739
def test6():
    assert program4739(BGIIURZTEUJJULBWKHDQBRFGEUOMQSREOTILICRSBUHBGTSRDHKVDDEBVHGMHXUVFJURSMFDJOOOWCYPJDVRVKLDHICPNKTBFXDJ
XOADNTKNILGNHHBNFYNDWUNXBGDFUKUVHLPDOGOYRMOTAQELLRMHFAQEOXFWGAQUROVUSWOAWFRVIRJQVXPCXLSCQLCUWKBZUFQP
YVF) == ['TLBWKHDGOROTLRHEGUVUSOWVRVLCKBF', 'ILBWKHDGOMQELRHEGUVUSOWVRVLCKBF', 'TLBWKHDGOROTLRMHXFUROOWVRVLCKBF', 'TLBWKHDGOROTLRMHXFURSOWVRVLCKBF']