from ..program4739 import program4739
def test39():
    assert program4739(AAACAAACAAADAAAAAAA
AADAAAAAAAACDAAAAAAAAAAACAAAAABCACAAACAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADA
AAACAADAAAAADD) == ['AAACAAACAAAAAAAAAA']