from ..program4739 import program4739
def test26():
    assert program4739(AABABABABAAAABBAAAABABABABAAAAABABAAAA
AABABAAABABABAAABAAAAABAAABAAABABABBBABBAAABAABAAAAABABBABAAABAABAABABAAAABABAAABAAABAABABBBABBABABA
AAAAA) == ['AABABABABAAAABBAAAABABABABAAAABABAAAA']