from ..program4739 import program4739
def test15():
    assert program4739(ZFFBNYVXOZCJPSRAEACVPAUKVTCVZYQPHVENTKOCMHNIYYMIKKLNKHLWHHWAQMWFTSYEOQQFEYAAYGMPNZCRYBVNAQTDSLXZGBCG
PIQHLNEWAMFAKGHBGZAWRWAXCSKUDZBDOCTXAHSVFZACXGFMDSYBYYDDNQNBEZCYCULSMMPBTQOJQNRPZTRCSDLIYPLVUGJPKDTG
ZBFJPLNAKWQBTUVJKMHVBATAM) == ['FBZRACKZOCHAFSYYYNZCYBQTSLGG', 'FBZAACKZOCHAFSYYYNZCYBQTSLGG', 'FBZRACKZOCHAMSYYYNZCYBNTDLGG', 'FBZRACUZOCHAMSYYYNZCYBNTDLGG']