from ..program4739 import program4739
def test31():
    assert program4739(ASDASASDASDASDAASDASDASDASASDDAASDASSASDSDAD
DASDASSSDASDASDASASDASSDAASDASSDDSASDASDAASDDAASDASDAASDASDDASDASDASDASDASS
DASD) == ['ASDASASDASASDAASDASASDASASDDAASDASSASDSDAD']