from ..program501 import program501
def test14():
    assert program501(IJHHGKCXWDBRWJUPRDBZJLNTTNWKXLUGJSBWBOAUKWRAQWGFNL
NJMWRMBCNPHXTDQQNZ
WDNJRCLILNQRHWBANLTXWMJBPKUPGKJDJZAQWKTZFBRCTXHHBNXRGUQUNBNMWODGSJWW) == ['YES']