from ..program501 import program501
def test21():
    assert program501(NUBKQEJHALANSHEIFUZHYEZKKDRFHQKAJHLAOWTZIMOCWOVVDW
EFVOBIGAUAUSQGVSNBKNOBDMINODMFSHDL
KLAMKNTHBFFOHVKWICHBKNDDQNEISODUSDNLUSIOAVWY) == ['NO']