from ..program501 import program501
def test41():
    assert program501(IDQRX
WETHO
ODPDGBHVUVSSISROHQJTUKPUCLXABIZQQPPBPKOSEWGEHRSRRNBAVLYEMZISMWWGKHVTXKUGUXEFBSWOIWUHRJGMWBMHQLDZHBWA) == ['NO']