from ..program501 import program501
def test12():
    assert program501(OVQELLOGFIOLEHXMEMBJDIGBPGEYFG
JNKFPFFIJOFHRIFHXEWYZOPDJBZTJZKBWQTECNHRFSJPJOAPQT
YAIPFFFEXJJNEJPLREIGODEGQZVMCOBDFKWTMWJSBEBTOFFQOHIQJLHFNXIGOHEZRZLFOKJBJPTPHPGY) == ['YES']