from ..program501 import program501
def test27():
    assert program501(AGFIGYWJLVMYZGNQHEHWKJIAWBPUAQFERMCDROFN
PMJNHMVNRGCYZAVRWNDSMLSZHFNYIUWFPUSKKIGU
MCDVPPRXGUAYLSDRHRURZASXUWZSIIEZCPXUVEONKNGNWRYGOSFMCKESMVJZHWWUCHWDQMLASLNNMHAU) == ['NO']