from ..program501 import program501
def test32():
    assert program501(OSKFHGYNQLSRFSAHPXKGPXUHXTRBJNAQRBSSWJVEENLJCDDHFXVCUNPZAIVVO
FNUOCXAGRRHNDJAHVVLGGEZQHWARYHENBKHP
UOEFNWVXCUNERLKVTHAGPSHKHDYFPYWZHJKHQLSNFBJHVJANRXCNSDUGVDABGHVAOVHBJZXGRACHRXEGNRPQEAPORQSILNXFS) == ['YES']