from ..program501 import program501
def test48():
    assert program501(GXPZFSELJJNDAXYRV
UYBKPMVBSOVOJWMONLTJOJCNQKMTAHEWLHOWIIBH
HCWNFWJPEJIWOVPTBMVCRJLSISSVNOHCKLBFMIUAIMASQWPXEYXBOXQGFEMYJLBKDCZIMJNHOJEDGGANIVYKQTUOSOVOPWHVJGXH) == ['NO']