from ..program501 import program501
def test45():
    assert program501(UIKWWKXLSHTOOZOVGXKYSOJEHAUEEG
KZXQDWJJWRXFHKJDQHJK
XMZHTFOGEXAUJXXJUYVJIFOTKLZHDKELJWERHMGAWGKWAQKEKHIDWGGZVYOHKXRPWSJDPESFJUMKQYWBYUTHQYEFZUGKQOBHYDWB) == ['NO']