from ..program4741 import program4741
def test26():
    assert program4741(AABABABABAAAABBAAAABABABABAAAAABABAAAA
AABABAAABABABAAABAAAAABAAABAAABABABBBABBAAABAABAAAAABABBABAAABAABAABABAAAABABAAABAAABAABABBBABBABABA
AAAAA) == ['AABABABABAAAABBAAAABABABABAAAABABAAAA']