from ..program4741 import program4741
def test39():
    assert program4741(AAACAAACAAADAAAAAAA
AADAAAAAAAACDAAAAAAAAAAACAAAAABCACAAACAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADA
AAACAADAAAAADD) == ['AAACAAACAAAAAAAAAA']