from ..program4741 import program4741
def test33():
    assert program4741(ABAAAABABADABAABAABCCABADABACABACABCABADABADABACABBACAADABACABABACABADABACABABA
BACAACABABABACABCABADABAACABADABACABAA
ABBAB) == ['BACAACABABABACABCAADABAACABADABACABAA', 'BACAACABABABACABCABAABAACABADABACABAA', 'BAAACABABABACABCABADABAACABADABACABAA']