from ..program4741 import program4741
def test7():
    assert program4741(AXBPBDEYIYKKCZBTLKBUNEQLCXXLKIUTOOATYDXYYQCLFAXAEIGTFMNTTQKCQRMEEFRYVYXAOLMUQNPJBMFBUGVXFZAJSBXWALSI
VWFONLLKSHGHHQSFBBFWTXAITPUKNDANOCLMNFTAAMJVDLXYPILPCJCFWTNBQWEOMMXHRYHEGBJIVSXBBGQKXRIYNZFIWSZPPUUM
PPKKLHXWWT) == ['BBITKNCLTADXYCFTNQMRYVXBBGXFWS', 'BBITUNCLTADXYLFTNQERYVXBBGXZWS', 'BBITKNCLTADXYCFTNQMRYVXBBGXZWS']