from ..program4741 import program4741
def test31():
    assert program4741(ASDASASDASDASDAASDASDASDASASDDAASDASSASDSDAD
DASDASSSDASDASDASASDASSDAASDASSDDSASDASDAASDDAASDASDAASDASDDASDASDASDASDASS
DASD) == ['ASDASASDASASDAASDASASDASASDDAASDASSASDSDAD']