from ..program4741 import program4741
def test14():
    assert program4741(EGQYYSKTFTURZNRDVIWBYXMRDGFWMYKFXGIFOGYJSXKDCJUAGZPVTYCHIXVFTVTCXMKHZFTXSMMQVFXZGKHCIYODDRZEYECDLKNG
PEXXCTRFJAAKPOTBAEFRLDRZKORNMXHHXTLKMKCGPVPUOBELPLFQFXOBZWIVIQCHEJQPXKGSCQAWIMETCJVTAGXJIINTADDXJTKQ
QURSEKPMSSEVQZI) == ['ETFTBRDKOXKCGPVFVCHQXKCIECDK', 'EKTFRZRXMGFFXOZVCHXCMTVGIDDK', 'ETFTBRDKOXKCGPVXVCHQXKCIECDK', 'EKTFRZNXMGFFXIJXKCATCVTXTDDK', 'EKTFRZNXMGFFXIJXKCATCVTXIDDK']