from ..program4741 import program4741
def test5():
    assert program4741(AUNBEKNURNUPHXQYKUTAHCOLMPRQZZTVDUYCTNIRACQQTQAIDTAWJXBUTIZUASDIJZWLHAQVGCAHKTZMXSDVVWAIGQEALRFKFYTT
QBVRFKPKLYZLYNRFTRJZZQEYAEKPFXVICUVFVQSDENBJYYNCFTOZHULSWJQTNELYLKCZTGHOARDCFXBXQGGSQIVUCJVNGFZEEZQE
N) == ['BKPYTRZZVICQDJTZUSJZHAQGSVVGQE', 'BRPKLZYTRQAXIUSDJZWLHACXSVVGQE', 'BRPKLRZZYACQDBTZUSWLHACXSVVGQE', 'BRPKLRZZYICQDJTZUSJZHAQGSVVGQE', 'BKPKLRZZVICQDJTZUSJZHAQGSVVGQE']