from ..program4741 import program4741
def test4():
    assert program4741(CGPWTAPEVBTGANLCLVSHQIIKHDPVUHRSQPXHSNYAHPGBECICFQYDFRTRELLLEDZYWJSLOBSKDGRRDHNRRGIXAMEBGFJJTEIGUGRU
HAWYVKRRBEIWNOGYMIYQXDCFXMMCSAYSOXQFHHIFRRCJRAWHLDDHHHAKHXVKCVPBFGGEXUKWTFWMOUUGMXTSBUTHXCJCWHCQQTYQ
ANKFDWLYSX) == ['WVBGIQXSYHIFRRWLDDHXBGEUGU', 'WVBNIQXSYHIFRRJLDDHXBFGUGU', 'AVBIIQXSAHIFRRWLDDHXBFGUGU', 'WVBGCSSQHHIFRRWLDDHXBGFUGU', 'AVBNIQXSAHIFRRJLDDHABFGUGU', 'WVBNIDXSYHIFRRWLDDHXBGFUGU']