from ..program4741 import program4741
def test34():
    assert program4741(ABAABACABADAACADABACAAB
BAACABADABACABAAAADADAABACABACABADABABADABACABAADABBADABACAAACAABACABADABBBAA
DABACA) == ['ABAABACABADAACAABACAAB', 'ABAABACABADAACADABAAAB']