from ..program4741 import program4741
def test19():
    assert program4741(WZRKLETJRBBRZKGHEFBVEFVLIERBPSEGJVSNUZUICONWWBOOTHCOJLLZFNOCNOFJQZTZWBLKHGIWWWPBUYWBAHYJGEBJZJDTNBGN
ZINFGDCNKHYFZYYWHTIHZTKWXXXMSWOVOPQDTRWSQKBWWCPEMYFVGARELELBLGEVJCMOCFTTUVCYUQUSFONAMWKVDWMGXVNZJBWH
AFPA) == ['WZKTRKBEFVLEBGVCOTCFONWKWGZJB', 'WZKTRBEFVELEBEJCOTCFONWKWGZJB', 'WZKTRBEFVELEBGVCOTCFONWKWGZJB', 'WZKTRKEFVELEBEJCOTCFONWKWGZJB']