from ..program4741 import program4741
def test17():
    assert program4741(GOZVMIRQIGYGVAGOREQTXFXPEZYOJOXPNDGAESICXHMKQDXQPRLMRVWHXFEJVCWZDLYMQLDURUXZPTLEHPTSKXGSNEQDKLVFFLDX
IMEVFCZXACKRRJVXDRKFWTLTRTLQQDHEBZLCOCNVPABQMIWJHRLKFUKWOVVWGGNWCJNRYOYOAJFQWCLHQIQRBZTVWKBFOXKEHHQP
SZ) == ['IEFZXACKRRVXFWLRTLHPKGNQLVFX', 'IVARXFEZONAIHRLVWJWLQRZTKXEQ', 'MVARXFEZOPAIHRLVWFCLQRZTKXEQ']