from ..program4741 import program4741
def test18():
    assert program4741(BBYUVCIYLNUJPSEYCAAPQSDNSDDTNEHQZDPBEKQAWNAKEYFBNEEBGPDPRLCSVOWYDEDRPPEDOROCHRCNQUSPNVXGRXHNLKDETWQC
BQCQXCAHADGJHBYIKEUWNXFUOOTVCCKJPJJCMWLAWWKSDGHFNZTCPSQNRTPCBLXDTSJLRHSCCZXQXCVLVGTROOUCUQASIQHZGNEI
RYE) == ['BBYUVCJPCASDNZPQNBDRLVROOCQSGNE', 'BBYINUJPCASDHZPQNPDRSVROOCUSHNE', 'BBYINUJPCASDHZPQNPDLSVROOCUSHNE', 'BBYUVCJPCASDNTPQNBDRLVROOCQSGNE', 'BBYUVCJPCASDNTPQNBDLCVROOCQSGNE']