from ..program4741 import program4741
def test6():
    assert program4741(BGIIURZTEUJJULBWKHDQBRFGEUOMQSREOTILICRSBUHBGTSRDHKVDDEBVHGMHXUVFJURSMFDJOOOWCYPJDVRVKLDHICPNKTBFXDJ
XOADNTKNILGNHHBNFYNDWUNXBGDFUKUVHLPDOGOYRMOTAQELLRMHFAQEOXFWGAQUROVUSWOAWFRVIRJQVXPCXLSCQLCUWKBZUFQP
YVF) == ['TLBWKHDGOROTLRHEGUVUSOWVRVLCKBF', 'ILBWKHDGOMQELRHEGUVUSOWVRVLCKBF', 'TLBWKHDGOROTLRMHXFUROOWVRVLCKBF', 'TLBWKHDGOROTLRMHXFURSOWVRVLCKBF']