from ..program4741 import program4741
def test16():
    assert program4741(BTWZLIKDACZVLCKMVTIQHLFBNRCBDSWPFFKGPCQFPTOIJLPFCDMFGQKFHTDFFCCULUAYPXXIIIWBZIDMOPNHPZBEXLVARJFTBFOE
MDXYKKWZVASJPPWRCYNMRAOBBLUNBSMQAPCPSFAGLXWJRBQTBRWXYNQGWECYNFIAJXDMUHIIMDFMSHLPIMYQXNRRUSSNXALGNWIK
KNFVBVAOWXMZVUHAVUDKDBUVAKNHACZBGBHMUOPHWGQSDFXLHB) == ['WZACMLNBSPFGCFIJDMHDFLPIMNXL', 'WZACLMQLBRWGCFIJDMHDFLPIMNXL', 'WZACMBNBSPFGQTIJDMHDFLPIMNXA', 'WZVCMLNBSPFGCFIJDMHDFLPIMNXL', 'WZACMLNBSPFGQTIJDMHDFLPIMNXL', 'DZVCMBNBSPFGCFIJDMHDFLPIMNXA']