from ..program4741 import program4741
def test15():
    assert program4741(ZFFBNYVXOZCJPSRAEACVPAUKVTCVZYQPHVENTKOCMHNIYYMIKKLNKHLWHHWAQMWFTSYEOQQFEYAAYGMPNZCRYBVNAQTDSLXZGBCG
PIQHLNEWAMFAKGHBGZAWRWAXCSKUDZBDOCTXAHSVFZACXGFMDSYBYYDDNQNBEZCYCULSMMPBTQOJQNRPZTRCSDLIYPLVUGJPKDTG
ZBFJPLNAKWQBTUVJKMHVBATAM) == ['FBZRACKZOCHAFSYYYNZCYBQTSLGG', 'FBZAACKZOCHAFSYYYNZCYBQTSLGG', 'FBZRACKZOCHAMSYYYNZCYBNTDLGG', 'FBZRACUZOCHAMSYYYNZCYBNTDLGG']