from ..program523 import program523
def test8():
    assert program523(10 10
SSSSSSSSSS
..........
..........
..........
..........
..........
..........
..........
..........
..........) == ['90']