from ..program3435 import program3435
def test6():
    assert program3435(EUCWUBAMTDIZB BERLAND 5:2
WQLRBODMAPFQAJXYXA EUCWUBAMTDIZB 5:3
YKKUZZ BERLAND 1:0
YKKUZZ EUCWUBAMTDIZB 3:5
YKKUZZ WQLRBODMAPFQAJXYXA 6:3) == ['IMPOSSIBLE']