from ..program904 import program904
def test40():
    assert program904(ABCDEFGHIJKLMNOPQRSTUVWXYZX) == ['ZABCDEFGHIJKL\r\nYXWVUTSRQPONM', 'YXWVUTSRQPONM\r\nZABCDEFGHIJKL', 'MNOPQRSTUVWXY\r\nLKJIHGFEDCBAZ', 'KJIHGFEDCBAXY\r\nLMNOPQRSTUVWZ']