from ..program904 import program904
def test32():
    assert program904(OURNQJWMIXCLGSDVEKZAFBYNTPH) == ['GLCXIMWJQNRUO\r\nSDVEKZAFBYTPH', 'HPTNQJWMIXCLG\r\nOURYBFAZKEVDS', 'SDVEKZAFBYTPH\r\nGLCXIMWJQNRUO', 'OURNQJWMIXCLG\r\nHPTYBFAZKEVDS']