from ..program904 import program904
def test8():
    assert program904(YOFJVQSWBUZENPCXGQTHMDKAILR) == ['ENPCXGTHMDKAI\r\nZUBWSQVJFOYRL', 'IAKDMHTQSWBUZ\r\nLRYOFJVGXCPNE', 'ZUBWSQVJFOYRL\r\nENPCXGTHMDKAI', 'LRYOFJVQSWBUZ\r\nIAKDMHTGXCPNE']