from ..program904 import program904
def test17():
    assert program904(XECPFJBHINOWVLAGTUMRZYHQSDK) == ['ALVWONIHBJFPC\r\nGTUMRZYQSDKXE', 'GTUMRZYQSDKXE\r\nALVWONIHBJFPC', 'CPFJBHINOWVLA\r\nEXKDSQYZRMUTG', 'XKDSQHINOWVLA\r\nECPFJBYZRMUTG']