from ..program904 import program904
def test25():
    assert program904(UNGHFQRCIPBZTEOAYJXLDMSKNWV) == ['WNGHFQRCIPBZT\r\nVUKSMDLXJYAOE', 'EOAYJXLDMSKWV\r\nTZBPICRQFHGNU', 'TZBPICRQFHGNU\r\nEOAYJXLDMSKWV', 'UNGHFQRCIPBZT\r\nVWKSMDLXJYAOE']