from ..program904 import program904
def test35():
    assert program904(IHDTJLGRFUXQSOZEMVYKWCPANBT) == ['DTJLGRFUXQSOZ\r\nHIBNAPCWKYVME', 'ITJLGRFUXQSOZ\r\nHDBNAPCWKYVME', 'ZOSQXUFRGLJTD\r\nEMVYKWCPANBIH', 'EMVYKWCPANBIH\r\nZOSQXUFRGLJTD']