from ..program904 import program904
def test44():
    assert program904(ABCBDEFGHIJKLMNOPQRSTUVWXYZ) == ['PQRSTUVWXYZAB\r\nONMLKJIHGFEDC', 'CDEFGHIJKLMNO\r\nBAZYXWVUTSRQP', 'ONMLKJIHGFEDB\r\nPQRSTUVWXYZAC', 'BAZYXWVUTSRQP\r\nCDEFGHIJKLMNO']