from ..program904 import program904
def test14():
    assert program904(HVDEBKMJTLKQORNWCZSGXYIPUAF) == ['JMKBEDVHFAUPI\r\nTLQORNWCZSGXY', 'IPUAFHVDEBKMJ\r\nYXGSZCWNROQLT', 'XGSZCWNROQKMJ\r\nYIPUAFHVDEBLT', 'TLQORNWCZSGXY\r\nJMKBEDVHFAUPI']