from ..program904 import program904
def test38():
    assert program904(ABCDEFGHIJKLMNOPQRSTUVWXYZG) == ['DEFGHIJKLMNOP\r\nCBAZYXWVUTSRQ', 'CBAGHIJKLMNOP\r\nDEFZYXWVUTSRQ', 'QRSTUVWXYZABC\r\nPONMLKJIHGFED', 'PONMLKJIHGFED\r\nQRSTUVWXYZABC']