from ..program904 import program904
def test9():
    assert program904(GYCUAXSBNAWFIJPDQVETKZOMLHR) == ['ZOMLHRGYCUAXS\r\nKTEVQDPJIFWNB', 'SXAUCYGRHLMOZ\r\nBNWFIJPDQVETK', 'BNWFIJPDQVETK\r\nSXAUCYGRHLMOZ', 'TEVQDPJIFWAXS\r\nKZOMLHRGYCUNB']