from ..program904 import program904
def test33():
    assert program904(ZWFIRJNXVKHOUSTQBLEGYMAPIDC) == ['WFIRJNXVKHOUS\r\nZCDPAMYGELBQT', 'CDIRJNXVKHOUS\r\nZWFPAMYGELBQT', 'TQBLEGYMAPDCZ\r\nSUOHKVXNJRIFW', 'SUOHKVXNJRIFW\r\nTQBLEGYMAPDCZ']