from ..program904 import program904
def test13():
    assert program904(RFKNZXHAIMVBWEBPTCSYOLJGDQU) == ['QDGJLOYSCTPBW\r\nURFKNZXHAIMVE', 'WBVMIAHXZNKFR\r\nEPTCSYOLJGDQU', 'RFKNZXHAIMVBW\r\nUQDGJLOYSCTPE', 'EPTCSYOLJGDQU\r\nWBVMIAHXZNKFR']