from ..program904 import program904
def test21():
    assert program904(XQVBTCNIRFPLOHAYZUMKWEJSXDG) == ['OHAYZUMKWEJSD\r\nLPFRINCTBVQXG', 'DXQVBTCNIRFPL\r\nGSJEWKMUZYAHO', 'LPFRINCTBVQXG\r\nOHAYZUMKWEJSD', 'GXQVBTCNIRFPL\r\nDSJEWKMUZYAHO']