from ..program904 import program904
def test0():
    assert program904(ABCDEFGHIJKLMNOPQRSGTUVWXYZ) == ['MLKJIHGFEDCBA\r\nNOPQRSTUVWXYZ', 'YXWVUTGHIJKLM\r\nZABCDEFSRQPON', 'NOPQRSTUVWXYZ\r\nMLKJIHGFEDCBA', 'ABCDEFGHIJKLM\r\nZYXWVUTSRQPON']