from ..program904 import program904
def test46():
    assert program904(ABCDEFGHIJKLMZYXWVUTSRQPONA) == ['MLKJIHGFEDCBA\r\nZYXWVUTSRQPON', 'ABCDEFGHIJKLM\r\nNOPQRSTUVWXYZ', 'ZYXWVUTSRQPON\r\nMLKJIHGFEDCBA']