from ..program904 import program904
def test24():
    assert program904(AHGZCRJTKPMQUNBWSIYLDXEHFVO) == ['VFHGZCRJTKPMQ\r\nOAEXDLYISWBNU', 'OAHGZCRJTKPMQ\r\nVFEXDLYISWBNU', 'UNBWSIYLDXEFV\r\nQMPKTJRCZGHAO', 'QMPKTJRCZGHAO\r\nUNBWSIYLDXEFV']