from ..program904 import program904
def test23():
    assert program904(NMGIFDZKBCVRYLTWOASXHEUQPJN) == ['NMGIFDZKBCVRY\r\nJPQUEHXSAOWTL', 'LTWOASXHEUQPJ\r\nYRVCBKZDFIGMN', 'YRVCBKZDFIGMN\r\nLTWOASXHEUQPJ']