from ..program904 import program904
def test34():
    assert program904(UOWJXRKHZDNGLSAMEIYTQBVCFJP) == ['UPJXRKHZDNGLS\r\nOWFCVBQTYIEMA', 'AMEIYTQBVCFPU\r\nSLGNDZHKRXJWO', 'OWJXRKHZDNGLS\r\nUPFCVBQTYIEMA', 'SLGNDZHKRXJWO\r\nAMEIYTQBVCFPU']