from ..program904 import program904
def test41():
    assert program904(ABCDEFGHIJKLMNOPQRSTUVWYXYZ) == ['YWVUTSRQPONML\r\nXZABCDEFGHIJK', 'KJIHGFEDCBAZY\r\nLMNOPQRSTUVWX', 'LMNOPQRSTUVWY\r\nKJIHGFEDCBAZX', 'XZABCDEFGHIJK\r\nYWVUTSRQPONML']