from ..program904 import program904
def test15():
    assert program904(XZTMCRBONHFIUVPKWSDLJQGAHYE) == ['WKPVUIFHNOBRC\r\nSDLJQGAYEXZTM', 'CRBONHFIUVPKW\r\nMTZXEYAGQJLDS', 'TZXEYHFIUVPKW\r\nMCRBONAGQJLDS', 'SDLJQGAYEXZTM\r\nWKPVUIFHNOBRC']