from ..program904 import program904
def test3():
    assert program904(UTEDBZRVWLOFUASHCYIPXGJMKNQ) == ['ZBDETUQNKMJGX\r\nRVWLOFASHCYIP', 'RVWLOFASHCYIP\r\nZBDETUQNKMJGX', 'PIYCHSAUTEDBZ\r\nXGJMKNQFOLWVR', 'XGJMKNQUTEDBZ\r\nPIYCHSAFOLWVR']