from ..program904 import program904
def test47():
    assert program904(BACDEFGHIJKLMNOPQRSTUVWXYZA) == ['NMLKJIHGFEDCA\r\nOPQRSTUVWXYZB', 'OPQRSTUVWXYZB\r\nNMLKJIHGFEDCA', 'ACDEFGHIJKLMN\r\nBZYXWVUTSRQPO']