from ..program904 import program904
def test16():
    assert program904(YAMVOHUJLEDCWZLXNRGPIQTBSKF) == ['KFYAMVOHUJLED\r\nSBTQIPGRNXZWC', 'SBTQIPGRNXLED\r\nKFYAMVOHUJZWC', 'DELJUHOVMAYFK\r\nCWZXNRGPIQTBS', 'CWZXNRGPIQTBS\r\nDELJUHOVMAYFK']