from ..program904 import program904
def test31():
    assert program904(LCFNHUQWXBPOSJMYTGKDAZVREIF) == ['MYTGKDAZVREIL\r\nJSOPBXWQUHNFC', 'JSOPBXWQUHNFC\r\nMYTGKDAZVREIL', 'LFNHUQWXBPOSJ\r\nCIERVZADKGTYM', 'CFNHUQWXBPOSJ\r\nLIERVZADKGTYM']