from ..program904 import program904
def test4():
    assert program904(ZWMFLTCQIAJEVUPODMSGXKHRNYB) == ['HKXGSMFLTCQIA\r\nRNYBZWDOPUVEJ', 'NYBZWMFLTCQIA\r\nRHKXGSDOPUVEJ', 'AIQCTLFMWZBYN\r\nJEVUPODSGXKHR', 'JEVUPODSGXKHR\r\nAIQCTLFMWZBYN']