from ..program904 import program904
def test39():
    assert program904(ABCDEFGHGIJKLMNOPQRSTUVWXYZ) == ['TSRQPONMLKJIG\r\nUVWXYZABCDEFH', 'UVWXYZABCDEFG\r\nTSRQPONMLKJIH', 'HIJKLMNOPQRST\r\nGFEDCBAZYXWVU', 'GFEDCBAZYXWVU\r\nHIJKLMNOPQRST']