from ..program904 import program904
def test7():
    assert program904(MKNTKOBFLJSXWQPVUERDHIACYGZ) == ['VPQWXSJLFBOKN\r\nUERDHIACYGZMT', 'ERDHIACYGZMKN\r\nUVPQWXSJLFBOT', 'TOBFLJSXWQPVU\r\nNKMZGYCAIHDRE', 'NKMZGYCAIHDRE\r\nTOBFLJSXWQPVU']