from ..program904 import program904
def test29():
    assert program904(HIDCLZUTPOQGEXFASJNYBVRMDKW) == ['WKDCLZUTPOQGE\r\nHIMRVBYNJSAFX', 'EGQOPTUZLCDIH\r\nXFASJNYBVRMKW', 'XFASJNYBVRMKW\r\nEGQOPTUZLCDIH', 'HIDCLZUTPOQGE\r\nWKMRVBYNJSAFX']