from ..program904 import program904
def test36():
    assert program904(ABCDEFGHIJKLMNOPQRSTUVWXYZA) == ['MLKJIHGFEDCBA\r\nNOPQRSTUVWXYZ', 'ABCDEFGHIJKLM\r\nZYXWVUTSRQPON', 'NOPQRSTUVWXYZ\r\nMLKJIHGFEDCBA']