from ..program904 import program904
def test20():
    assert program904(TEGXHBUVZDPAMIJFQYCWRKSTNLO) == ['APDZVUBHXGETO\r\nMIJFQYCWRKSNL', 'NTEGXHBUVZDPA\r\nLOSKRWCYQFJIM', 'OTEGXHBUVZDPA\r\nLNSKRWCYQFJIM', 'MIJFQYCWRKSNL\r\nAPDZVUBHXGETO']