from ..program904 import program904
def test5():
    assert program904(QGZEMFKWLUHOVSXJTCPIYREDNAB) == ['QGZEMFKWLUHOV\r\nBANDRYIPCTJXS', 'SXJTCPIYRDNAB\r\nVOHULWKFMEZGQ', 'VOHULWKFMEZGQ\r\nSXJTCPIYRDNAB', 'ANDEMFKWLUHOV\r\nBQGZRYIPCTJXS']