from ..program904 import program904
def test43():
    assert program904(QWERTYUIOPASDFGHJKLZXCVBNMQ) == ['DSAPOIUYTREWQ\r\nFGHJKLZXCVBNM', 'FGHJKLZXCVBNM\r\nDSAPOIUYTREWQ', 'QWERTYUIOPASD\r\nMNBVCXZLKJHGF']