from ..program904 import program904
def test27():
    assert program904(UTGDEJHCBKRWLYFSONAQVMPIXZT) == ['YLWRKBCHJEDGT\r\nFSONAQVMPIXZU', 'FSONAQVMPIXZU\r\nYLWRKBCHJEDGT', 'TGDEJHCBKRWLY\r\nUZXIPMVQANOSF']