from ..program904 import program904
def test45():
    assert program904(ABCDEFGHIJKLMNOPQRSTUVWXAYZ) == ['ZABCDEFGHIJKL\r\nYXWVUTSRQPONM', 'LKJIHGFEDCBAZ\r\nMNOPQRSTUVWXY', 'MNOPQRSTUVWXY\r\nLKJIHGFEDCBAZ', 'YABCDEFGHIJKL\r\nZXWVUTSRQPONM']