from ..program904 import program904
def test28():
    assert program904(BETRFOVLPCMWKHAXSGUDQYJTZIN) == ['IZTRFOVLPCMWK\r\nNBEJYQDUGSXAH', 'KWMCPLVOFRTEB\r\nHAXSGUDQYJZIN', 'BETRFOVLPCMWK\r\nNIZJYQDUGSXAH', 'HAXSGUDQYJZIN\r\nKWMCPLVOFRTEB']