from ..program904 import program904
def test6():
    assert program904(BMVFGRNDOWTILZVHAKCQSXYEJUP) == ['YEJUPBMVFGRND\r\nXSQCKAHZLITWO', 'OWTILZHAKCQSX\r\nDNRGFVMBPUJEY', 'DNRGFVMBPUJEY\r\nOWTILZHAKCQSX', 'XSQCKAHVFGRND\r\nYEJUPBMZLITWO']