from ..program904 import program904
def test30():
    assert program904(CNHIKJWRLPXTQZVUGYDMBAOEFHS) == ['VUGYDMBAOEFSC\r\nZQTXPLRWJKIHN', 'SHIKJWRLPXTQZ\r\nCNFEOABMDYGUV', 'ZQTXPLRWJKIHN\r\nVUGYDMBAOEFSC', 'NHIKJWRLPXTQZ\r\nCSFEOABMDYGUV']