from ..program904 import program904
def test22():
    assert program904(MIDLBEUAGTNPYKFWHVSRJOXCZMQ) == ['KFWHVSRJOXCZQ\r\nYPNTGAUEBLDIM', 'YPNTGAUEBLDIM\r\nKFWHVSRJOXCZQ', 'MIDLBEUAGTNPY\r\nQZCXOJRSVHWFK']