from ..program904 import program904
def test11():
    assert program904(XCDSLTYWJIGUBPHNFZWVMQARKOE) == ['XCDSLTYWJIGUB\r\nEOKRAQMVZFNHP', 'BUGIJWYTLSDCX\r\nPHNFZVMQARKOE', 'PHNFZVMQARKOE\r\nBUGIJWYTLSDCX', 'OKRAQMVWJIGUB\r\nEXCDSLTYZFNHP']