from ..program904 import program904
def test37():
    assert program904(ABACDEFGHIJKLMNOPQRSTUVWXYZ) == ['NMLKJIHGFEDCA\r\nOPQRSTUVWXYZB', 'BCDEFGHIJKLMN\r\nAZYXWVUTSRQPO', 'AZYXWVUTSRQPO\r\nBCDEFGHIJKLMN', 'OPQRSTUVWXYZA\r\nNMLKJIHGFEDCB']