from ..program904 import program904
def test26():
    assert program904(MKBGVNDJRAWUEHFSYLIZCOPTXKQ) == ['EUWARJDNVGBKM\r\nHFSYLIZCOPTXQ', 'MKBGVNDJRAWUE\r\nQXTPOCZILYSFH', 'QKBGVNDJRAWUE\r\nMXTPOCZILYSFH', 'HFSYLIZCOPTXQ\r\nEUWARJDNVGBKM']