from ..program904 import program904
def test42():
    assert program904(BUVTYZFQSNRIWOXGJLKACPEMDHB) == ['WIRNSQFZYTVUB\r\nOXGJLKACPEMDH', 'BUVTYZFQSNRIW\r\nHDMEPCAKLJGXO', 'OXGJLKACPEMDH\r\nWIRNSQFZYTVUB']