from ..program904 import program904
def test12():
    assert program904(XTSHBGLRJAMDUIPCWYOZVERNKQF) == ['CWYOZVENKQFXT\r\nPIUDMAJRLGBHS', 'PIUDMAJRLGBHS\r\nCWYOZVENKQFXT', 'XFQKNRJAMDUIP\r\nTSHBGLEVZOYWC', 'SHBGLRJAMDUIP\r\nTXFQKNEVZOYWC']