from ..program4660 import program4660
def test35():
    assert program4660(9
OXOXXXXOX
XOXXOXOOO
OOXOOOXOO
OOOXXOXOX
OOXOOOOXX
OXXXOXOOO
OOOXXOXOO
OOXOXXOXO
OOXOOOXOX
OXOOOOXOO
XOOOOXOOO
OXXOXXOXO
XXOXOXXOO
XOOOOOOXO
XXOOOXOXO
XOXOOOXOX
OOXOXOOXO
XOOXXOOOX) == ['No', 'NO']