from ..program4660 import program4660
def test20():
    assert program4660(10
XOXXXXXOOO
OXXOOXXOXX
XXXXXOOXOX
OOOOOXOXOX
OXXOXXXOXO
XOOXOXXXXX
XOOOOOOOOX
OOXXOOXXXX
OOOOXXOOOX
XXXXXOOOXX
XXOOOXXXXX
XOOOXXOOOO
XXXXOOXXOO
XOOOOOOOOX
XXXXXOXOOX
OXOXXXOXXO
XOXOXOOOOO
XOXOOXXXXX
XXOXXOOXXO
OOOXXXXXOX) == ['YES', 'Yes']