from ..program4660 import program4660
def test10():
    assert program4660(10
XXOXXOXOOX
OOOOXOOXXO
OXXXOOXOOO
OOXOOOOOOO
XXXOXOXXXX
OXXXXOXXOO
OXXXXOOXXX
XXOXXOXOXO
OOOXOOOOOO
XOOXOOOOXX
XOOXOOOOXX
OOOXOOOOOO
XXOXXOXOXO
OXXXXOOXXX
OXXXXOXXOO
XXXOXOXXXX
OOXOOOOOOO
OXXXOOXOOO
OOOOXOOXXO
XXOXXOXOOX) == ['YES', 'Yes']