from ..program4660 import program4660
def test19():
    assert program4660(10
XXOXOOOOXX
XOXXXOXOXO
OXXXOOXOOO
XXOXOOXXOX
XXOXXOXXOO
OOOXXXXOXO
OXXXOXOXOO
OXOXXXXXXX
XXXOOXXXXX
XXOOXOOXXO
XOOOOXXOXX
XXXXOXXXOX
OXOXOOOXXO
OOXXXXXXXX
XOXOXXOOXO
OXXXXOOOXX
OXXXXXXXXO
XXXXOXXOOO
XXXOXOOOXX
OXXXOOXOOX) == ['No', 'NO']