from ..program4660 import program4660
def test18():
    assert program4660(10
XXXOOOOOXO
XXOXOOXOXX
XOXXXXXXXO
XOXOXOOXXX
XXOOXXOXXO
OOOOOOOOXX
OOXOXXOOXX
XXXXOXXOOO
XOXOXXXOXX
OXXOXXOOOO
OXOXOXXOXO
XXXXXXXOXO
OOXXXOOOOO
OXXOOOOXXO
OOXOXOXXXX
OOXXXOXOXX
OXXOOOOXOO
XOXXOOXXXX
XXOOXOOXOX
XXXXXOOXXO) == ['YES', 'Yes']