from ..program4660 import program4660
def test21():
    assert program4660(10
XXOOOOOXOX
OOOOXXXOXX
OOOXOOOOXX
OXXXXXXOOX
XOOXOXOOXX
XOOOOOOXXO
XXXOOOOXOO
OOOOXOXOOO
OXOOOOOXOX
XXOXXXOXOX
XXOOOXXXXO
OOOOXXOOXO
XXOXXOOOOX
XOXOOOXOXO
XOOOOXXOXO
XOXOOOXOXO
XOOXOXXXXO
OOOXOOXOOO
XXOXOXXOOX
XOOXXXOOOX) == ['No', 'NO']