from ..program4660 import program4660
def test33():
    assert program4660(8
OXOOOOOO
XOXOXXXO
OXXXXXOX
OOXXOXOO
XOOOXOOO
XOOXXOXO
OOXXXXXX
XXXOOXXX
OXOOXXOO
XOXOOOOX
OOXXOOXX
OOXXOXXO
OXXOXXXX
OXOXXOXO
OXOOOXXX
OOXOOOXX) == ['No', 'NO']