from ..program4660 import program4660
def test11():
    assert program4660(10
XXOOOOOXXO
OXOOXOOXXO
XOOXOXXXXO
OXXXXOXOXO
XXXOXXOXOO
OXOOOOOXOX
XOXOXOOOXO
OXXXOOOOOX
XXOOOOOXOO
XOXXXOOXXX
XXOXOXOXOX
OXXOXXXOXX
XOXXOXXOOO
XOXOOOXXOO
XOOXOXXOXO
OOOOOXOXOO
OXOOOOXXOO
XXOOXXOXXX
XOOXOOXXXX
XOXOXOOOOO) == ['No', 'NO']