from ..program4660 import program4660
def test15():
    assert program4660(10
XOXXOXXOOX
OXXOXOXXXX
XXOOXOXOOO
OXOOOOXOOO
OOOOOOOXOX
XXOXXOOXOX
XOXOXOOOOX
OXOXOOXXOX
XOXOXOXXXO
OOXOXXXXXX
OOXOOXXXXX
XOXOXOXXXO
OXOXOOXXOX
XOXXXOOOOX
XXOXXOOXOX
OOOOOOOXOX
OXOOOOXOOO
XXOOXOXOOO
OXXOXOXXXX
XOXOOXXOOX) == ['No', 'NO']