from ..program4660 import program4660
def test12():
    assert program4660(10
XOOXOXXXXX
XOXXOXOXXX
OOOXOXOOOX
OOOXXXOOXX
OXOXXOXOXO
OXXOXOOOOO
OXOOXXOXXO
OOXOXXXXOX
XOXXXXOOXX
XOOOOXXOOX
XXXOOOXXXX
OXOXOXXOXX
OOXXOOOOXX
XOXOOXOOOX
XXXXOOXXXX
OXXXXXXOOO
OXOOOXXXXX
OXXOXOOOXO
OOOXXXOOOO
XXOOOOOOXX) == ['YES', 'Yes']