from ..program4660 import program4660
def test9():
    assert program4660(10
XXXOOOOXOX
OOOXXXOXXO
XOXXXXOOXX
XOOOXXOXOO
OOXOOOOOOX
XXXXOXOOOO
XXXOOXOXOX
OOOOXOXOXX
XOXXOXOOXO
OOOOOXOOOO
XXXOOOOXOX
OOOXXXOXXO
XOXXXXOOXX
XOOOXXOXOO
OOXOOOOOOX
XXXXOXOOOO
XXXOOXOXOX
OOOOXOXOXX
XOXXOXOOXO
OOOOOXOOOO) == ['YES', 'Yes']