from ..program4660 import program4660
def test32():
    assert program4660(8
OXOXXXXX
XXXXOXOO
OXOXOXOX
XXXOXXOX
OXXOXXXX
XXOXXXOO
XXXXOOOO
OXXXOOOO
OOOOXXXO
OOOOXXXX
OOXXXOXX
XXXXOXXO
XOXXOXXX
XOXOXOXO
OOXOXXXX
XXXXXOXO) == ['YES', 'Yes']