from ..program4660 import program4660
def test34():
    assert program4660(9
XXXOXOOXO
XOOOOXOOO
OOXXOXOXO
XXXXOXOXX
XXXXXXOXO
OOXOXXOXX
XXOXXXXXO
XXXOXOOOO
XXOOXOOXX
XXXOXOOXO
XOOOOXOOO
OOXXOXOXO
XXXXOXOXX
XXXXXXOXO
OOXOXXOXX
XXOXXXXXO
XXXOXOOOO
XXOOXOOXX) == ['YES', 'Yes']