from ..program4660 import program4660
def test13():
    assert program4660(10
XXOOXOOOXO
XXOXXXXXXX
XOOOXOOXXX
OXOOOXXXXO
XOOOOOOOOO
XXOXXXXOOX
OOOXOXOOOX
XOXOOXOOXO
OOXOOXOXXO
XOXOXOXXOO
OOOXXOOXXO
OXXOOOOXOX
XXOOOOXXXO
XOOOXOXOXO
OXXXXOXOXO
XOOOXOOXXX
OOOXXOOOXO
XXXOOOOOOO
OOOOXOXOXX
XOXOXXOXXX) == ['No', 'NO']