from ..program4660 import program4660
def test14():
    assert program4660(10
XOOOOXOOOX
OOOOOOOXXX
OXOOOXXOXO
OOXXXOOXOX
OOXXOOOXXO
XXXXOXOXXX
XXXOOXOOOO
XXXXOOXXXO
OXXXXXXOXX
XXXOOOXOXO
XOOOXOOOOX
XXXOOOOOOO
OXOXXOOOXO
XOXOOXXXOO
OXXOOOXXOO
XXXOXOXXXX
OOOOXOOXXX
OXXXOOXXXX
XXOXXXXXXO
OXOXOOOXXX) == ['YES', 'Yes']