from ..program4660 import program4660
def test17():
    assert program4660(10
XOXXXXXXXX
OOOOXXXOXO
XOXXXXOOXX
XXXOXXXXXO
OXXXXOXOOO
OOOOOXOXXX
XOOOXOOXXX
XOOOXXXXOO
OXOOXOXXOX
OXOXXOXXOX
XXOXXOOXOX
OOOXXOXXXX
XXXXXOXOOX
XXXOOXXOXO
OOXOXOXXXX
XXXXOXXXXX
XOOOOXOXOX
OOOXOXXXXX
XXOOOXXOOO
OOXXOOXOOX) == ['No', 'NO']