from ..program524 import program524
def test8():
    assert program524(10 10
SSSSSSSSSS
..........
..........
..........
..........
..........
..........
..........
..........
..........) == ['90']