from ..program2345 import program2345
def test15():
    assert program2345(hbgwuqzougqzlxemvyjpeizjfwhgugrfnhbrlxkmkdalikfyunppwgdzmalbwewybnjzqsohwhjkdcyhhzmysflambvhpsjilsyv
fbdjdqjojdafarakvcjpeipjfehgfgrfehbolxkmkdagikflunnpvadocalbkedibhbflmohnhjkdcthhaigsfjaibqhbcjelirv) == ['fcdjdrjpjdafarakwckqfjpkgeihfhsgeicomylnlebgjlglvonqvaeocbmckfdichbflmpinikledtiiaigtgjbicqibckemirw', 'fzdjdzjzjdafarakzczzzzpzzezzfzzzezzozzzzzzzgzzzlzznzvazoczzzkzdizhbflmzznzzzzztzzaigzzjzizqzbczezirz', 'fbdjdqjojdafarakvcjpeipjfehgfgrfehbolxkmkdagikflunnpvadocalbkedibhbflmohnhjkdcthhaigsfjaibqhbcjelirv']