from ..program2345 import program2345
def test13():
    assert program2345(nmuwjdihouqrnsuahimssnrbxdpwvxiyqtenahtrlshjkmnfuttnpqhgcagoptinnaptxaccptparldzrhpgbyrzedghudtsswxi
nilhbdghosqnbebafimconrbvdodjsipqmekahhrllhjkemeketapfhgcagopfidnahtlaccpfpafedqicpcbvfgedghudhddwib) == ['nilhbdghosqnbebafimconrbvdodjsipqmekahhrllhjkemeketapfhgcagopfidnahtlaccpfpafedqicpcbvfgedghudhddwib', 'zilhbzgzzsznbebzfzzcozzzvzodjszpzmzkzzhzzlzzzemekezazfzzzzzzzfzdzzhzlzzzzfzzfezqiczczvfgzzzzzzhddzib', 'oilhbegipsrnbebbfjncooscveodjsjprmfkbihsmliklemekeuaqfihdbhpqfjdobhulbddqfqbfeeqicqccvfgfehivehddxib']