from ..program2345 import program2345
def test17():
    assert program2345(zrvzedssbsrfldqvjpgmsefrmsatspzoitwvymahiptphiystjlsauzquzqqbmljobdhijcpdvatorwmyojqgnezvzlgjibxepcf
pesoedmqbmffldqsjggmhefkadaesijointrkmahapaahiysfjdiaupqujngbjhjobdhiecadeatgjvelojjgnepvajgeibfepaf) == ['pesofemqcmfgmerskghnhfgkadbetijpjntrknbiaqaaijztfkdibvprvjngcjhkpceijedaeebugjvelpkjhofpwajhejcffqag', 'pesozzmqzmfzzzzszgzzhzzkadzezijzzntrkzzzazaazzzzfzdizzpzzjngzjhzzzzzzezazezzgjvelzzjzzzpzajzezzfzzaz', 'pesoedmqbmffldqsjggmhefkadaesijointrkmahapaahiysfjdiaupqujngbjhjobdhiecadeatgjvelojjgnepvajgeibfepaf']