from ..program2345 import program2345
def test21():
    assert program2345(nttdcfceptruiomtmwzestrfchnqpgqeztpcvthzelfyggjgqadylzubpvbrlgndrcsursczpxlnoyoadxezncqalupfzmjeqihe
kttdcfceohrjiaahmoldanpfchnfpgheqpdahqhxecfpbgigqadrkjubjfbrlgndbcgcgmcjpeleinaadretncqaiqpfkmjeqihe) == ['kuuedgdfohsjjaahnoldanpgdiofqhhfqpdahqixfcgpbhihrberkjvcjfcsmhoebdgcgmdjqemeinaberftodrbiqqgknkfrjif', 'kttdcfceohrjiaahmoldanpfchnfpgheqpdahqhxecfpbgigqadrkjubjfbrlgndbcgcgmcjpeleinaadretncqaiqpfkmjeqihe', 'kzzzzzzzohzjzaahzoldanpzzzzfzzhzqpdahqzxzczpbzizzzzrkjzzjfzzzzzzbzgcgmzjzezeinazzrztzzzziqzzkzzzzzzz']