from ..program2345 import program2345
def test11():
    assert program2345(eufycwztywhbjrpqobvknwfqmnboqcfdiahkagykeibbsqpljcghhmsgfmswwsanzyiwtvuirwmppfivtekaywkzskyydfvkjgxb
ecfwavookadbcilfobojnweqinbcpcfdiahkabwkeibbacpljcghhksgfajgmianfnivmhfifogpffiheegayfkxkkcmdfvihgdb) == ['ecfwavookadbcilfobojnweqinbcpcfdiahkabwkeibbacpljcghhksgfajgmianfnivmhfifogpffiheegayfkxkkcmdfvihgdb', 'zczwavookadzcilfzzojzzezizzcpzzzzzzzzbwzzzzzaczzzzzzzkzzzajgmizzfnzvmhfzfogzfzzhezgzzfzxkzcmzzzihzdz', 'fcgwavookadccilfpcojoxerioccpdgejbilbbwlfjccacqmkdhiikthgajgmibofnjvmhfjfogqfgjhefgbzflxklcmegwihhdc']