from ..program2345 import program2345
def test19():
    assert program2345(tgharsjyihroiiahwgbjezlxvlterxivdhtzjcqegzmtigqmrehvhiyjeywegxaseoyoacouijudbiruoghgxvxadwzgdxtnxlds
tghaksjsdhkoiiahegbjexlfrctercipdhmvjbgegxdtggqdpbhvhiseehhegnaseoooacnsijubbirjnghgsvpadhaadrtimfdp) == ['zzzzkzzsdzkzzzzzezzzzxzfrczzzczpzzmvzbgzzxdzgzzdpbzzzzsezhhzznzzzzozzznszzzbzzzjnzzzszpzzhaazrzimfzp', 'uhibktksdikpjjbiehckfxmfrcufscjpeimvkbgfhxdughrdpbiwijsefhhfhnbtfpopbdnsjkvbcjsjnhihswpbehaaeruimfep', 'tghaksjsdhkoiiahegbjexlfrctercipdhmvjbgegxdtggqdpbhvhiseehhegnaseoooacnsijubbirjnghgsvpadhaadrtimfdp']