from ..program1753 import program1753
def test107():
    assert program1753(X.........
.OO.......
..XO......
...XO.....
....X.....
..........
..........
..........
..........
..........) == ['NO']