from ..program1753 import program1753
def test2():
    assert program1753(XO........
.XO.......
..XO......
....O.....
....X.....
..........
..........
..........
..........
..........) == ['YES']