from ..program1753 import program1753
def test36():
    assert program1753(..........
..........
..........
..........
..........
..O......X
..O.....X.
..O.......
..O...X...
.....X....) == ['YES']