from ..program1753 import program1753
def test136():
    assert program1753(XOXXX.....
..O.......
...O......
....O.....
..........
..........
..........
..........
..........
..........) == ['NO']