from ..program1753 import program1753
def test85():
    assert program1753(O.O.O.O.O.
..........
..........
..........
..........
..........
.XX.......
X.........
X.........
X.........) == ['NO']