from ..program1753 import program1753
def test118():
    assert program1753(X.........
O.O.......
X..O......
X...O.....
X.........
..........
..........
..........
..........
..........) == ['NO']