from ..program1753 import program1753
def test1():
    assert program1753(XXOXX.....
OO.O......
..........
..........
..........
..........
..........
..........
..........
..........) == ['NO']