from ..program1753 import program1753
def test10():
    assert program1753(......X...
..........
..X....X..
....O.....
..........
O.........
.....O...X
..........
..........
O.........) == ['NO']