from ..program1753 import program1753
def test72():
    assert program1753(..........
..........
..O.......
...O......
....O.....
.....O....
......X...
.......X..
........X.
.........X) == ['NO']