from ..program1753 import program1753
def test90():
    assert program1753(.....OXXXX
..........
..........
..........
..........
..........
..........
..........
..........
......OOO.) == ['NO']