from ..program1753 import program1753
def test73():
    assert program1753(OOOOX.....
..........
..X.......
.X........
X.........
..........
..........
..........
..........
..........) == ['YES']