from ..program1753 import program1753
def test109():
    assert program1753(O.........
X.O.......
X..O......
X...O.....
X.........
..........
..........
..........
..........
..........) == ['YES']