from ..program1753 import program1753
def test144():
    assert program1753(.......XXX
X.........
..........
..........
..........
..........
..........
..........
..........
......OOOO) == ['NO']