from ..program1753 import program1753
def test81():
    assert program1753(..........
...X...OO.
..X....OO.
.X........
X.........
..........
..........
..........
..........
..........) == ['YES']