from ..program1753 import program1753
def test35():
    assert program1753(.........X
.....OOOO.
X.........
.X........
..X.......
..........
..........
..........
..........
..........) == ['NO']