from ..program1753 import program1753
def test104():
    assert program1753(XXXXO.....
..O.......
...O......
....O.....
..........
..........
..........
..........
..........
..........) == ['NO']