from ..program1753 import program1753
def test125():
    assert program1753(.....OXXXX
..O.......
...O......
....O.....
..........
..........
..........
..........
..........
..........) == ['NO']