from ..program1753 import program1753
def test150():
    assert program1753(..........
..........
OXXXXOOOO.
.........X
..........
..........
..........
..........
..........
..........) == ['NO']