from ..program1753 import program1753
def test146():
    assert program1753(XXXX......
..O.......
...O......
....O.....
.....O....
..........
..........
..........
..........
..........) == ['YES']