from ..program1753 import program1753
def test17():
    assert program1753(..........
..........
..........
.OOO.OOO..
.XXX.XXX..
..........
..........
..........
..........
..........) == ['YES']