from ..program1753 import program1753
def test154():
    assert program1753(XX.XX.....
..........
..........
....O.....
..........
......O...
..........
......O...
........O.
..........) == ['YES']