from ..program1753 import program1753
def test46():
    assert program1753(XXOXXOOO..
..........
..........
..........
..O..X....
..O.X.....
..OXO.....
..X.......
..........
..........) == ['YES']