from ..program1753 import program1753
def test28():
    assert program1753(..........
X.........
.O........
..XXX.....
..XOXO....
OXOOOO....
X.........
..........
..........
..........) == ['YES']