from ..program1753 import program1753
def test108():
    assert program1753(X.XX..XXXX
..........
..........
..........
..........
..........
..........
..........
..........
OOO.O.O.OO) == ['YES']