from ..program1753 import program1753
def test123():
    assert program1753(..........
.....OOOO.
..........
..........
..........
..........
..........
..........
..........
...X.X.X.X) == ['NO']