from ..program1753 import program1753
def test114():
    assert program1753(......XXXX
..O.......
...O......
....O.....
.....O....
..........
..........
..........
..........
..........) == ['YES']