from ..program1753 import program1753
def test45():
    assert program1753(....X.....
...X......
..X.......
..........
X.........
..........
..OOOO....
..........
..........
..........) == ['YES']