from ..program1753 import program1753
def test14():
    assert program1753(....X.....
...X.OOOO.
..X.......
.X........
..........
..........
..........
..........
..........
..........) == ['YES']