from ..program1753 import program1753
def test9():
    assert program1753(..........
..........
..........
..........
..........
X.........
.........X
..........
..O.......
.O...X...O) == ['NO']