from ..program1753 import program1753
def test111():
    assert program1753(X.........
X.O.......
X..O......
X...O.....
O.........
..........
..........
..........
..........
..........) == ['NO']