from ..program1753 import program1753
def test63():
    assert program1753(XXOXX.....
.....OOOO.
..........
.....X....
....X.....
..........
..X...O...
.X......O.
X..O..O...
..........) == ['YES']