from ..program1753 import program1753
def test32():
    assert program1753(..........
..........
..........
..........
..........
X.........
X.........
X.........
XOOOO.....
..........) == ['YES']