from ..program1753 import program1753
def test34():
    assert program1753(..........
..........
..........
OOOOX.....
..........
..X.......
.X........
X.........
..........
..........) == ['YES']