from ..program1753 import program1753
def test44():
    assert program1753(..O.......
OO.O......
......X...
..........
....X.....
...X......
..X.......
..........
..........
..........) == ['YES']