from ..program1753 import program1753
def test116():
    assert program1753(..........
.....OOOO.
..........
..........
..........
..........
..........
..........
..........
......XXXX) == ['YES']