from ..program1753 import program1753
def test25():
    assert program1753(....X.....
...X.OOOO.
..X..OOOO.
.X........
..........
..........
X.........
X.........
X.........
X.........) == ['YES']