from ..program1753 import program1753
def test138():
    assert program1753(..........
.......OX.
......OX..
.....OX...
....OX....
..........
..........
..........
..........
..........) == ['YES']