from ..program1753 import program1753
def test120():
    assert program1753(X.........
..O.......
X..O......
X...O.....
X....O....
..........
..........
..........
..........
..........) == ['YES']