from ..program1753 import program1753
def test71():
    assert program1753(......XXXX
OOOO......
..........
..........
..........
..........
..........
..........
..........
..........) == ['YES']