from ..program1753 import program1753
def test54():
    assert program1753(..........
..X.......
...X......
....X.....
.....X....
......O...
..........
..OOO.....
..........
..........) == ['YES']