from ..program1753 import program1753
def test22():
    assert program1753(....X.....
...X......
..........
.X........
X.........
...OOOO...
..........
..........
..........
..........) == ['YES']