from ..program1753 import program1753
def test76():
    assert program1753(..........
..........
......XXXX
..........
..........
..........
..........
..OOOO....
..........
..........) == ['YES']