from ..program1753 import program1753
def test64():
    assert program1753(O.....X...
.....X....
..........
...X..OOO.
..X.......
..........
..........
..........
..........
..........) == ['YES']