from ..program1753 import program1753
def test135():
    assert program1753(O.........
.XO.......
..XO......
...XO.....
....X.....
..........
..........
..........
..........
..........) == ['YES']