from ..program1753 import program1753
def test129():
    assert program1753(XXXXOOOO..
..........
..........
..........
..........
..........
..........
..........
..........
..........) == ['NO']