from ..program1753 import program1753
def test139():
    assert program1753(X.........
X.O.......
O..O......
X...O.....
X.........
..........
..........
..........
..........
..........) == ['NO']