from ..program1753 import program1753
def test119():
    assert program1753(X.........
X.O.......
X..O......
X...O.....
.....O....
..........
..........
..........
..........
..........) == ['YES']