from ..program1753 import program1753
def test86():
    assert program1753(.O........
..X...X...
...O.X....
....X.....
...X.X....
..O...X...
..XX...O..
..OOO.OO..
..........
..........) == ['YES']