from ..program1753 import program1753
def test15():
    assert program1753(..........
.....OOOO.
..........
.....X....
....X.....
..........
..X.......
.X........
..........
..........) == ['YES']