from ..program1753 import program1753
def test0():
    assert program1753(XX.XX.....
.....OOOO.
..........
..........
..........
..........
..........
..........
..........
..........) == ['YES']