from ..program1753 import program1753
def test50():
    assert program1753(..O.......
OO.O......
..........
..........
..........
..........
..........
..........
..........
XXX.X.....) == ['YES']