from ..program1753 import program1753
def test122():
    assert program1753(....O.....
...X...O..
..X...O...
.X...O....
X.........
..........
..........
..........
..........
..........) == ['NO']