from ..program1753 import program1753
def test153():
    assert program1753(.OOOOXXXX.
..........
..........
..........
..........
..........
..........
..........
..........
..........) == ['YES']