from ..program1753 import program1753
def test56():
    assert program1753(.....OOOOX
.XXX......
..........
..........
..........
..........
..........
..........
..........
..........) == ['NO']