from ..program1753 import program1753
def test84():
    assert program1753(..........
..........
..........
..........
.XXXXO....
....OOO...
..........
..........
..........
..........) == ['YES']