from ..program1753 import program1753
def test151():
    assert program1753(X.........
X....OOOO.
..........
X.........
X.........
..........
..........
..........
..........
..........) == ['YES']