from ..program1753 import program1753
def test40():
    assert program1753(OOO.......
...O....X.
.......X..
..........
.....X....
....X.....
..........
..........
..........
..........) == ['YES']