from ..program1753 import program1753
def test126():
    assert program1753(XXX.XXX...
OOO.OOO...
..........
..........
..........
..........
..........
..........
..........
..........) == ['YES']