from ..program1753 import program1753
def test112():
    assert program1753(....X.....
...X...O..
..X...O...
.....O....
X...O.....
..........
..........
..........
..........
..........) == ['YES']