from ..program3870 import program3870
def test7():
    assert program3870(RBGYRBGYRBGYRBGYRBGYRBGYRBGYRBGYRBGYRBGYRBGYRBGYRBGYRBGYRBGYRBGYRBGYRBGYRBGYRBGYRBGYRBGYRBGYRBGYRBGY) == ['0\r\n0\r\n0\r\n0', '0 0 0 0']