from ..program3869 import program3869
def test7():
    assert program3869(RBGYRBGYRBGYRBGYRBGYRBGYRBGYRBGYRBGYRBGYRBGYRBGYRBGYRBGYRBGYRBGYRBGYRBGYRBGYRBGYRBGYRBGYRBGYRBGYRBGY) == ['0\r\n0\r\n0\r\n0', '0 0 0 0']