from ..program901 import program901
def test28():
    assert program901(BETRFOVLPCMWKHAXSGUDQYJTZIN) == ['IZTRFOVLPCMWK\r\nNBEJYQDUGSXAH', 'KWMCPLVOFRTEB\r\nHAXSGUDQYJZIN', 'BETRFOVLPCMWK\r\nNIZJYQDUGSXAH', 'HAXSGUDQYJZIN\r\nKWMCPLVOFRTEB']