from ..program901 import program901
def test6():
    assert program901(BMVFGRNDOWTILZVHAKCQSXYEJUP) == ['YEJUPBMVFGRND\r\nXSQCKAHZLITWO', 'OWTILZHAKCQSX\r\nDNRGFVMBPUJEY', 'DNRGFVMBPUJEY\r\nOWTILZHAKCQSX', 'XSQCKAHVFGRND\r\nYEJUPBMZLITWO']