from ..program901 import program901
def test33():
    assert program901(ZWFIRJNXVKHOUSTQBLEGYMAPIDC) == ['WFIRJNXVKHOUS\r\nZCDPAMYGELBQT', 'CDIRJNXVKHOUS\r\nZWFPAMYGELBQT', 'TQBLEGYMAPDCZ\r\nSUOHKVXNJRIFW', 'SUOHKVXNJRIFW\r\nTQBLEGYMAPDCZ']