from ..program901 import program901
def test25():
    assert program901(UNGHFQRCIPBZTEOAYJXLDMSKNWV) == ['WNGHFQRCIPBZT\r\nVUKSMDLXJYAOE', 'EOAYJXLDMSKWV\r\nTZBPICRQFHGNU', 'TZBPICRQFHGNU\r\nEOAYJXLDMSKWV', 'UNGHFQRCIPBZT\r\nVWKSMDLXJYAOE']