from ..program901 import program901
def test40():
    assert program901(ABCDEFGHIJKLMNOPQRSTUVWXYZX) == ['ZABCDEFGHIJKL\r\nYXWVUTSRQPONM', 'YXWVUTSRQPONM\r\nZABCDEFGHIJKL', 'MNOPQRSTUVWXY\r\nLKJIHGFEDCBAZ', 'KJIHGFEDCBAXY\r\nLMNOPQRSTUVWZ']