from ..program901 import program901
def test30():
    assert program901(CNHIKJWRLPXTQZVUGYDMBAOEFHS) == ['VUGYDMBAOEFSC\r\nZQTXPLRWJKIHN', 'SHIKJWRLPXTQZ\r\nCNFEOABMDYGUV', 'ZQTXPLRWJKIHN\r\nVUGYDMBAOEFSC', 'NHIKJWRLPXTQZ\r\nCSFEOABMDYGUV']