from ..program901 import program901
def test14():
    assert program901(HVDEBKMJTLKQORNWCZSGXYIPUAF) == ['JMKBEDVHFAUPI\r\nTLQORNWCZSGXY', 'IPUAFHVDEBKMJ\r\nYXGSZCWNROQLT', 'XGSZCWNROQKMJ\r\nYIPUAFHVDEBLT', 'TLQORNWCZSGXY\r\nJMKBEDVHFAUPI']