from ..program901 import program901
def test16():
    assert program901(YAMVOHUJLEDCWZLXNRGPIQTBSKF) == ['KFYAMVOHUJLED\r\nSBTQIPGRNXZWC', 'SBTQIPGRNXLED\r\nKFYAMVOHUJZWC', 'DELJUHOVMAYFK\r\nCWZXNRGPIQTBS', 'CWZXNRGPIQTBS\r\nDELJUHOVMAYFK']