from ..program901 import program901
def test11():
    assert program901(XCDSLTYWJIGUBPHNFZWVMQARKOE) == ['XCDSLTYWJIGUB\r\nEOKRAQMVZFNHP', 'BUGIJWYTLSDCX\r\nPHNFZVMQARKOE', 'PHNFZVMQARKOE\r\nBUGIJWYTLSDCX', 'OKRAQMVWJIGUB\r\nEXCDSLTYZFNHP']