from ..program901 import program901
def test4():
    assert program901(ZWMFLTCQIAJEVUPODMSGXKHRNYB) == ['HKXGSMFLTCQIA\r\nRNYBZWDOPUVEJ', 'NYBZWMFLTCQIA\r\nRHKXGSDOPUVEJ', 'AIQCTLFMWZBYN\r\nJEVUPODSGXKHR', 'JEVUPODSGXKHR\r\nAIQCTLFMWZBYN']