from ..program901 import program901
def test3():
    assert program901(UTEDBZRVWLOFUASHCYIPXGJMKNQ) == ['ZBDETUQNKMJGX\r\nRVWLOFASHCYIP', 'RVWLOFASHCYIP\r\nZBDETUQNKMJGX', 'PIYCHSAUTEDBZ\r\nXGJMKNQFOLWVR', 'XGJMKNQUTEDBZ\r\nPIYCHSAFOLWVR']