from ..program901 import program901
def test5():
    assert program901(QGZEMFKWLUHOVSXJTCPIYREDNAB) == ['QGZEMFKWLUHOV\r\nBANDRYIPCTJXS', 'SXJTCPIYRDNAB\r\nVOHULWKFMEZGQ', 'VOHULWKFMEZGQ\r\nSXJTCPIYRDNAB', 'ANDEMFKWLUHOV\r\nBQGZRYIPCTJXS']