from ..program901 import program901
def test8():
    assert program901(YOFJVQSWBUZENPCXGQTHMDKAILR) == ['ENPCXGTHMDKAI\r\nZUBWSQVJFOYRL', 'IAKDMHTQSWBUZ\r\nLRYOFJVGXCPNE', 'ZUBWSQVJFOYRL\r\nENPCXGTHMDKAI', 'LRYOFJVQSWBUZ\r\nIAKDMHTGXCPNE']