from ..program901 import program901
def test22():
    assert program901(MIDLBEUAGTNPYKFWHVSRJOXCZMQ) == ['KFWHVSRJOXCZQ\r\nYPNTGAUEBLDIM', 'YPNTGAUEBLDIM\r\nKFWHVSRJOXCZQ', 'MIDLBEUAGTNPY\r\nQZCXOJRSVHWFK']