from ..program901 import program901
def test42():
    assert program901(BUVTYZFQSNRIWOXGJLKACPEMDHB) == ['WIRNSQFZYTVUB\r\nOXGJLKACPEMDH', 'BUVTYZFQSNRIW\r\nHDMEPCAKLJGXO', 'OXGJLKACPEMDH\r\nWIRNSQFZYTVUB']