from ..program901 import program901
def test32():
    assert program901(OURNQJWMIXCLGSDVEKZAFBYNTPH) == ['GLCXIMWJQNRUO\r\nSDVEKZAFBYTPH', 'HPTNQJWMIXCLG\r\nOURYBFAZKEVDS', 'SDVEKZAFBYTPH\r\nGLCXIMWJQNRUO', 'OURNQJWMIXCLG\r\nHPTYBFAZKEVDS']