from ..program901 import program901
def test38():
    assert program901(ABCDEFGHIJKLMNOPQRSTUVWXYZG) == ['DEFGHIJKLMNOP\r\nCBAZYXWVUTSRQ', 'CBAGHIJKLMNOP\r\nDEFZYXWVUTSRQ', 'QRSTUVWXYZABC\r\nPONMLKJIHGFED', 'PONMLKJIHGFED\r\nQRSTUVWXYZABC']