from ..program901 import program901
def test35():
    assert program901(IHDTJLGRFUXQSOZEMVYKWCPANBT) == ['DTJLGRFUXQSOZ\r\nHIBNAPCWKYVME', 'ITJLGRFUXQSOZ\r\nHDBNAPCWKYVME', 'ZOSQXUFRGLJTD\r\nEMVYKWCPANBIH', 'EMVYKWCPANBIH\r\nZOSQXUFRGLJTD']