from ..program901 import program901
def test36():
    assert program901(ABCDEFGHIJKLMNOPQRSTUVWXYZA) == ['MLKJIHGFEDCBA\r\nNOPQRSTUVWXYZ', 'ABCDEFGHIJKLM\r\nZYXWVUTSRQPON', 'NOPQRSTUVWXYZ\r\nMLKJIHGFEDCBA']