from ..program901 import program901
def test47():
    assert program901(BACDEFGHIJKLMNOPQRSTUVWXYZA) == ['NMLKJIHGFEDCA\r\nOPQRSTUVWXYZB', 'OPQRSTUVWXYZB\r\nNMLKJIHGFEDCA', 'ACDEFGHIJKLMN\r\nBZYXWVUTSRQPO']