from ..program901 import program901
def test15():
    assert program901(XZTMCRBONHFIUVPKWSDLJQGAHYE) == ['WKPVUIFHNOBRC\r\nSDLJQGAYEXZTM', 'CRBONHFIUVPKW\r\nMTZXEYAGQJLDS', 'TZXEYHFIUVPKW\r\nMCRBONAGQJLDS', 'SDLJQGAYEXZTM\r\nWKPVUIFHNOBRC']