from ..program901 import program901
def test46():
    assert program901(ABCDEFGHIJKLMZYXWVUTSRQPONA) == ['MLKJIHGFEDCBA\r\nZYXWVUTSRQPON', 'ABCDEFGHIJKLM\r\nNOPQRSTUVWXYZ', 'ZYXWVUTSRQPON\r\nMLKJIHGFEDCBA']