from ..program901 import program901
def test45():
    assert program901(ABCDEFGHIJKLMNOPQRSTUVWXAYZ) == ['ZABCDEFGHIJKL\r\nYXWVUTSRQPONM', 'LKJIHGFEDCBAZ\r\nMNOPQRSTUVWXY', 'MNOPQRSTUVWXY\r\nLKJIHGFEDCBAZ', 'YABCDEFGHIJKL\r\nZXWVUTSRQPONM']