from ..program901 import program901
def test29():
    assert program901(HIDCLZUTPOQGEXFASJNYBVRMDKW) == ['WKDCLZUTPOQGE\r\nHIMRVBYNJSAFX', 'EGQOPTUZLCDIH\r\nXFASJNYBVRMKW', 'XFASJNYBVRMKW\r\nEGQOPTUZLCDIH', 'HIDCLZUTPOQGE\r\nWKMRVBYNJSAFX']