from ..program901 import program901
def test13():
    assert program901(RFKNZXHAIMVBWEBPTCSYOLJGDQU) == ['QDGJLOYSCTPBW\r\nURFKNZXHAIMVE', 'WBVMIAHXZNKFR\r\nEPTCSYOLJGDQU', 'RFKNZXHAIMVBW\r\nUQDGJLOYSCTPE', 'EPTCSYOLJGDQU\r\nWBVMIAHXZNKFR']