from ..program901 import program901
def test17():
    assert program901(XECPFJBHINOWVLAGTUMRZYHQSDK) == ['ALVWONIHBJFPC\r\nGTUMRZYQSDKXE', 'GTUMRZYQSDKXE\r\nALVWONIHBJFPC', 'CPFJBHINOWVLA\r\nEXKDSQYZRMUTG', 'XKDSQHINOWVLA\r\nECPFJBYZRMUTG']