from ..program901 import program901
def test0():
    assert program901(ABCDEFGHIJKLMNOPQRSGTUVWXYZ) == ['MLKJIHGFEDCBA\r\nNOPQRSTUVWXYZ', 'YXWVUTGHIJKLM\r\nZABCDEFSRQPON', 'NOPQRSTUVWXYZ\r\nMLKJIHGFEDCBA', 'ABCDEFGHIJKLM\r\nZYXWVUTSRQPON']