from ..program901 import program901
def test44():
    assert program901(ABCBDEFGHIJKLMNOPQRSTUVWXYZ) == ['PQRSTUVWXYZAB\r\nONMLKJIHGFEDC', 'CDEFGHIJKLMNO\r\nBAZYXWVUTSRQP', 'ONMLKJIHGFEDB\r\nPQRSTUVWXYZAC', 'BAZYXWVUTSRQP\r\nCDEFGHIJKLMNO']