from ..program901 import program901
def test27():
    assert program901(UTGDEJHCBKRWLYFSONAQVMPIXZT) == ['YLWRKBCHJEDGT\r\nFSONAQVMPIXZU', 'FSONAQVMPIXZU\r\nYLWRKBCHJEDGT', 'TGDEJHCBKRWLY\r\nUZXIPMVQANOSF']