from ..program901 import program901
def test21():
    assert program901(XQVBTCNIRFPLOHAYZUMKWEJSXDG) == ['OHAYZUMKWEJSD\r\nLPFRINCTBVQXG', 'DXQVBTCNIRFPL\r\nGSJEWKMUZYAHO', 'LPFRINCTBVQXG\r\nOHAYZUMKWEJSD', 'GXQVBTCNIRFPL\r\nDSJEWKMUZYAHO']