from ..program901 import program901
def test31():
    assert program901(LCFNHUQWXBPOSJMYTGKDAZVREIF) == ['MYTGKDAZVREIL\r\nJSOPBXWQUHNFC', 'JSOPBXWQUHNFC\r\nMYTGKDAZVREIL', 'LFNHUQWXBPOSJ\r\nCIERVZADKGTYM', 'CFNHUQWXBPOSJ\r\nLIERVZADKGTYM']