from ..program901 import program901
def test20():
    assert program901(TEGXHBUVZDPAMIJFQYCWRKSTNLO) == ['APDZVUBHXGETO\r\nMIJFQYCWRKSNL', 'NTEGXHBUVZDPA\r\nLOSKRWCYQFJIM', 'OTEGXHBUVZDPA\r\nLNSKRWCYQFJIM', 'MIJFQYCWRKSNL\r\nAPDZVUBHXGETO']