from ..program901 import program901
def test39():
    assert program901(ABCDEFGHGIJKLMNOPQRSTUVWXYZ) == ['TSRQPONMLKJIG\r\nUVWXYZABCDEFH', 'UVWXYZABCDEFG\r\nTSRQPONMLKJIH', 'HIJKLMNOPQRST\r\nGFEDCBAZYXWVU', 'GFEDCBAZYXWVU\r\nHIJKLMNOPQRST']