from ..program901 import program901
def test34():
    assert program901(UOWJXRKHZDNGLSAMEIYTQBVCFJP) == ['UPJXRKHZDNGLS\r\nOWFCVBQTYIEMA', 'AMEIYTQBVCFPU\r\nSLGNDZHKRXJWO', 'OWJXRKHZDNGLS\r\nUPFCVBQTYIEMA', 'SLGNDZHKRXJWO\r\nAMEIYTQBVCFPU']