from ..program901 import program901
def test9():
    assert program901(GYCUAXSBNAWFIJPDQVETKZOMLHR) == ['ZOMLHRGYCUAXS\r\nKTEVQDPJIFWNB', 'SXAUCYGRHLMOZ\r\nBNWFIJPDQVETK', 'BNWFIJPDQVETK\r\nSXAUCYGRHLMOZ', 'TEVQDPJIFWAXS\r\nKZOMLHRGYCUNB']