from ..program901 import program901
def test7():
    assert program901(MKNTKOBFLJSXWQPVUERDHIACYGZ) == ['VPQWXSJLFBOKN\r\nUERDHIACYGZMT', 'ERDHIACYGZMKN\r\nUVPQWXSJLFBOT', 'TOBFLJSXWQPVU\r\nNKMZGYCAIHDRE', 'NKMZGYCAIHDRE\r\nTOBFLJSXWQPVU']