from ..program901 import program901
def test23():
    assert program901(NMGIFDZKBCVRYLTWOASXHEUQPJN) == ['NMGIFDZKBCVRY\r\nJPQUEHXSAOWTL', 'LTWOASXHEUQPJ\r\nYRVCBKZDFIGMN', 'YRVCBKZDFIGMN\r\nLTWOASXHEUQPJ']