from ..program901 import program901
def test12():
    assert program901(XTSHBGLRJAMDUIPCWYOZVERNKQF) == ['CWYOZVENKQFXT\r\nPIUDMAJRLGBHS', 'PIUDMAJRLGBHS\r\nCWYOZVENKQFXT', 'XFQKNRJAMDUIP\r\nTSHBGLEVZOYWC', 'SHBGLRJAMDUIP\r\nTXFQKNEVZOYWC']