from ..program901 import program901
def test41():
    assert program901(ABCDEFGHIJKLMNOPQRSTUVWYXYZ) == ['YWVUTSRQPONML\r\nXZABCDEFGHIJK', 'KJIHGFEDCBAZY\r\nLMNOPQRSTUVWX', 'LMNOPQRSTUVWY\r\nKJIHGFEDCBAZX', 'XZABCDEFGHIJK\r\nYWVUTSRQPONML']