from ..program901 import program901
def test43():
    assert program901(QWERTYUIOPASDFGHJKLZXCVBNMQ) == ['DSAPOIUYTREWQ\r\nFGHJKLZXCVBNM', 'FGHJKLZXCVBNM\r\nDSAPOIUYTREWQ', 'QWERTYUIOPASD\r\nMNBVCXZLKJHGF']