from ..program901 import program901
def test24():
    assert program901(AHGZCRJTKPMQUNBWSIYLDXEHFVO) == ['VFHGZCRJTKPMQ\r\nOAEXDLYISWBNU', 'OAHGZCRJTKPMQ\r\nVFEXDLYISWBNU', 'UNBWSIYLDXEFV\r\nQMPKTJRCZGHAO', 'QMPKTJRCZGHAO\r\nUNBWSIYLDXEFV']