from ..program901 import program901
def test37():
    assert program901(ABACDEFGHIJKLMNOPQRSTUVWXYZ) == ['NMLKJIHGFEDCA\r\nOPQRSTUVWXYZB', 'BCDEFGHIJKLMN\r\nAZYXWVUTSRQPO', 'AZYXWVUTSRQPO\r\nBCDEFGHIJKLMN', 'OPQRSTUVWXYZA\r\nNMLKJIHGFEDCB']