from ..program901 import program901
def test26():
    assert program901(MKBGVNDJRAWUEHFSYLIZCOPTXKQ) == ['EUWARJDNVGBKM\r\nHFSYLIZCOPTXQ', 'MKBGVNDJRAWUE\r\nQXTPOCZILYSFH', 'QKBGVNDJRAWUE\r\nMXTPOCZILYSFH', 'HFSYLIZCOPTXQ\r\nEUWARJDNVGBKM']