from ..program4823 import program4823
def test35():
    assert program4823(bkbkkkefaijgdbbbkjkibkjhediggjicgfeigaiehgaelechhklcjcdkhcalkgldelifljbclcceejacbjbjglbhlabchidfgddadafhhjbkejbedclahaachdceeblkfcdfajkfecahflhegkfihkheechebehbdklajbdkeblkcdkgiadkfclifgiggfdhcjagclfjjhhhdbidlacdkbkkkjgcheikjdacehdkkdglfghgcgakakgkhbebbkf...) == ['0']