from ..program4823 import program4823
def test25():
    assert program4823(biaijagdhdfdebfchgjdbajgjbfibghjigbbdbjgaadgjfdbghidajbfcjddcaijgghabbfdgiigabgaggeihfchgaebefjiaadhgddfabbhhadfgbigffdgeihjdjigihbhbddhicajfcgdgdjheihhgabifbghiafdjiadafeajbiacjhcegfbfbcchjjabachdiggddacfdcibdaebbaidfahjbhdbgbccdfjgfggbeahcfjhhchecegiead...) == ['0']