from ..program4823 import program4823
def test64():
    assert program4823(aigbdfeedcadiddafbgdffaaidbigifahgieghchddeggbigeabfiibfaefdcifebchichiehefiihieehdebcgigcihiabeaiediaeifadgbdfcebaighfceachfebdbiiffgfebeeaaaigidhcgibegfddaaaiiidgbbaeecdcediehfedifggfebhehfbbdceffihfdaabgfaaehfeeaheagfhhddaehffgheffagcdhgeadhigfbifiiifd...) == ['0']