from ..program3438 import program3438
def test40():
    assert program3438(MYCXFLPTHVGWDSRXCOI BERLAND 5:9
SPSHVVQLXQNRUB BERLAND 0:5
SPSHVVQLXQNRUB MYCXFLPTHVGWDSRXCOI 4:6
ZPIIZCGCLCHNLIXCPBRM MYCXFLPTHVGWDSRXCOI 7:5
ZPIIZCGCLCHNLIXCPBRM SPSHVVQLXQNRUB 3:9) == ['1:0']