from ..program3438 import program3438
def test44():
    assert program3438(QXNBYJBNNCBSNNWCLFN BERLAND 5:6
RXKKQGFLNRBCBQPCZC BERLAND 1:4
RXKKQGFLNRBCBQPCZC QXNBYJBNNCBSNNWCLFN 4:2
XETPY QXNBYJBNNCBSNNWCLFN 1:5
XETPY RXKKQGFLNRBCBQPCZC 6:4) == ['1:0']