from ..program1751 import program1751
def test64():
    assert program1751(O.....X...
.....X....
..........
...X..OOO.
..X.......
..........
..........
..........
..........
..........) == ['YES']