from ..program1751 import program1751
def test129():
    assert program1751(XXXXOOOO..
..........
..........
..........
..........
..........
..........
..........
..........
..........) == ['NO']