from ..program1751 import program1751
def test140():
    assert program1751(..........
..O.......
...O......
....O.....
.....O....
X.........
..........
X.........
X.........
X.........) == ['YES']