from ..program1751 import program1751
def test99():
    assert program1751(..........
...X...O..
..X...O...
.X...O....
X...O.....
..........
..........
..........
..........
..........) == ['YES']