from ..program1751 import program1751
def test151():
    assert program1751(X.........
X....OOOO.
..........
X.........
X.........
..........
..........
..........
..........
..........) == ['YES']