from ..program1751 import program1751
def test78():
    assert program1751(......OOOO
..........
..........
..........
..........
..........
...X......
..X.......
.X........
X.........) == ['YES']