from ..program1751 import program1751
def test145():
    assert program1751(..........
..O.......
...O......
....O.....
..........
O.........
.X........
..X.......
...X......
....X.....) == ['NO']