from ..program1751 import program1751
def test17():
    assert program1751(..........
..........
..........
.OOO.OOO..
.XXX.XXX..
..........
..........
..........
..........
..........) == ['YES']