from ..program1751 import program1751
def test90():
    assert program1751(.....OXXXX
..........
..........
..........
..........
..........
..........
..........
..........
......OOO.) == ['NO']