from ..program1751 import program1751
def test74():
    assert program1751(X.X.X.X...
.....OOOO.
..........
..........
..........
..........
..........
..........
..........
..........) == ['NO']