from ..program1751 import program1751
def test63():
    assert program1751(XXOXX.....
.....OOOO.
..........
.....X....
....X.....
..........
..X...O...
.X......O.
X..O..O...
..........) == ['YES']