from ..program1751 import program1751
def test138():
    assert program1751(..........
.......OX.
......OX..
.....OX...
....OX....
..........
..........
..........
..........
..........) == ['YES']