from ..program1751 import program1751
def test118():
    assert program1751(X.........
O.O.......
X..O......
X...O.....
X.........
..........
..........
..........
..........
..........) == ['NO']