from ..program1751 import program1751
def test122():
    assert program1751(....O.....
...X...O..
..X...O...
.X...O....
X.........
..........
..........
..........
..........
..........) == ['NO']