from ..program1751 import program1751
def test10():
    assert program1751(......X...
..........
..X....X..
....O.....
..........
O.........
.....O...X
..........
..........
O.........) == ['NO']