from ..program1751 import program1751
def test114():
    assert program1751(......XXXX
..O.......
...O......
....O.....
.....O....
..........
..........
..........
..........
..........) == ['YES']