from ..program1751 import program1751
def test40():
    assert program1751(OOO.......
...O....X.
.......X..
..........
.....X....
....X.....
..........
..........
..........
..........) == ['YES']