from ..program1751 import program1751
def test150():
    assert program1751(..........
..........
OXXXXOOOO.
.........X
..........
..........
..........
..........
..........
..........) == ['NO']