from ..program1751 import program1751
def test125():
    assert program1751(.....OXXXX
..O.......
...O......
....O.....
..........
..........
..........
..........
..........
..........) == ['NO']