from ..program1751 import program1751
def test25():
    assert program1751(....X.....
...X.OOOO.
..X..OOOO.
.X........
..........
..........
X.........
X.........
X.........
X.........) == ['YES']