from ..program1751 import program1751
def test86():
    assert program1751(.O........
..X...X...
...O.X....
....X.....
...X.X....
..O...X...
..XX...O..
..OOO.OO..
..........
..........) == ['YES']