from ..program1751 import program1751
def test109():
    assert program1751(O.........
X.O.......
X..O......
X...O.....
X.........
..........
..........
..........
..........
..........) == ['YES']