from ..program1751 import program1751
def test154():
    assert program1751(XX.XX.....
..........
..........
....O.....
..........
......O...
..........
......O...
........O.
..........) == ['YES']