from ..program1751 import program1751
def test116():
    assert program1751(..........
.....OOOO.
..........
..........
..........
..........
..........
..........
..........
......XXXX) == ['YES']