from ..program1751 import program1751
def test126():
    assert program1751(XXX.XXX...
OOO.OOO...
..........
..........
..........
..........
..........
..........
..........
..........) == ['YES']