from ..program1751 import program1751
def test36():
    assert program1751(..........
..........
..........
..........
..........
..O......X
..O.....X.
..O.......
..O...X...
.....X....) == ['YES']