from ..program1751 import program1751
def test71():
    assert program1751(......XXXX
OOOO......
..........
..........
..........
..........
..........
..........
..........
..........) == ['YES']