from ..program1751 import program1751
def test1():
    assert program1751(XXOXX.....
OO.O......
..........
..........
..........
..........
..........
..........
..........
..........) == ['NO']