from ..program1751 import program1751
def test45():
    assert program1751(....X.....
...X......
..X.......
..........
X.........
..........
..OOOO....
..........
..........
..........) == ['YES']