from ..program1751 import program1751
def test28():
    assert program1751(..........
X.........
.O........
..XXX.....
..XOXO....
OXOOOO....
X.........
..........
..........
..........) == ['YES']