from ..program1751 import program1751
def test54():
    assert program1751(..........
..X.......
...X......
....X.....
.....X....
......O...
..........
..OOO.....
..........
..........) == ['YES']