from ..program1751 import program1751
def test131():
    assert program1751(..........
..O.......
...O......
....O.....
.....O....
..........
.X........
..X.......
...X......
....X.....) == ['YES']