from ..program1751 import program1751
def test2():
    assert program1751(XO........
.XO.......
..XO......
....O.....
....X.....
..........
..........
..........
..........
..........) == ['YES']