from ..program1751 import program1751
def test153():
    assert program1751(.OOOOXXXX.
..........
..........
..........
..........
..........
..........
..........
..........
..........) == ['YES']