from ..program1751 import program1751
def test84():
    assert program1751(..........
..........
..........
..........
.XXXXO....
....OOO...
..........
..........
..........
..........) == ['YES']