from ..program1751 import program1751
def test107():
    assert program1751(X.........
.OO.......
..XO......
...XO.....
....X.....
..........
..........
..........
..........
..........) == ['NO']