from ..program1751 import program1751
def test85():
    assert program1751(O.O.O.O.O.
..........
..........
..........
..........
..........
.XX.......
X.........
X.........
X.........) == ['NO']