from ..program1751 import program1751
def test136():
    assert program1751(XOXXX.....
..O.......
...O......
....O.....
..........
..........
..........
..........
..........
..........) == ['NO']