from ..program1751 import program1751
def test9():
    assert program1751(..........
..........
..........
..........
..........
X.........
.........X
..........
..O.......
.O...X...O) == ['NO']