from ..program1751 import program1751
def test144():
    assert program1751(.......XXX
X.........
..........
..........
..........
..........
..........
..........
..........
......OOOO) == ['NO']