from ..program1751 import program1751
def test50():
    assert program1751(..O.......
OO.O......
..........
..........
..........
..........
..........
..........
..........
XXX.X.....) == ['YES']