from ..program1751 import program1751
def test108():
    assert program1751(X.XX..XXXX
..........
..........
..........
..........
..........
..........
..........
..........
OOO.O.O.OO) == ['YES']