from ..program1751 import program1751
def test76():
    assert program1751(..........
..........
......XXXX
..........
..........
..........
..........
..OOOO....
..........
..........) == ['YES']