from ..program1751 import program1751
def test22():
    assert program1751(....X.....
...X......
..........
.X........
X.........
...OOOO...
..........
..........
..........
..........) == ['YES']