from ..program1751 import program1751
def test46():
    assert program1751(XXOXXOOO..
..........
..........
..........
..O..X....
..O.X.....
..OXO.....
..X.......
..........
..........) == ['YES']