from ..program1751 import program1751
def test135():
    assert program1751(O.........
.XO.......
..XO......
...XO.....
....X.....
..........
..........
..........
..........
..........) == ['YES']