from ..program1751 import program1751
def test81():
    assert program1751(..........
...X...OO.
..X....OO.
.X........
X.........
..........
..........
..........
..........
..........) == ['YES']