from ..program1751 import program1751
def test32():
    assert program1751(..........
..........
..........
..........
..........
X.........
X.........
X.........
XOOOO.....
..........) == ['YES']