from ..program1751 import program1751
def test139():
    assert program1751(X.........
X.O.......
O..O......
X...O.....
X.........
..........
..........
..........
..........
..........) == ['NO']