from ..program1751 import program1751
def test20():
    assert program1751(..........
.....OOOO.
..........
..........
..........
..........
.....X....
....X.....
...X......
..X.......) == ['YES']