from ..program1751 import program1751
def test104():
    assert program1751(XXXXO.....
..O.......
...O......
....O.....
..........
..........
..........
..........
..........
..........) == ['NO']