from ..program1751 import program1751
def test56():
    assert program1751(.....OOOOX
.XXX......
..........
..........
..........
..........
..........
..........
..........
..........) == ['NO']