from ..program1751 import program1751
def test119():
    assert program1751(X.........
X.O.......
X..O......
X...O.....
.....O....
..........
..........
..........
..........
..........) == ['YES']