from ..program1751 import program1751
def test111():
    assert program1751(X.........
X.O.......
X..O......
X...O.....
O.........
..........
..........
..........
..........
..........) == ['NO']