from ..program1751 import program1751
def test123():
    assert program1751(..........
.....OOOO.
..........
..........
..........
..........
..........
..........
..........
...X.X.X.X) == ['NO']