from ..program1751 import program1751
def test112():
    assert program1751(....X.....
...X...O..
..X...O...
.....O....
X...O.....
..........
..........
..........
..........
..........) == ['YES']