from ..program1751 import program1751
def test14():
    assert program1751(....X.....
...X.OOOO.
..X.......
.X........
..........
..........
..........
..........
..........
..........) == ['YES']