from ..program1751 import program1751
def test94():
    assert program1751(..........
X.O.......
X..O......
X...O.....
X....O....
..........
..........
..........
..........
..........) == ['YES']