from ..program1751 import program1751
def test35():
    assert program1751(.........X
.....OOOO.
X.........
.X........
..X.......
..........
..........
..........
..........
..........) == ['NO']