from ..program1751 import program1751
def test0():
    assert program1751(XX.XX.....
.....OOOO.
..........
..........
..........
..........
..........
..........
..........
..........) == ['YES']