from ..program1751 import program1751
def test34():
    assert program1751(..........
..........
..........
OOOOX.....
..........
..X.......
.X........
X.........
..........
..........) == ['YES']