from ..program1751 import program1751
def test44():
    assert program1751(..O.......
OO.O......
......X...
..........
....X.....
...X......
..X.......
..........
..........
..........) == ['YES']