from ..program2510 import program2510
def test10():
    assert program2510(16) == ['ROYGROYGROYGRVIB', 'ROYGBIVROYGBIOYG', 'ROYGBIVOYGBOYGIV', 'ROYGBIVROYGBIVGB', 'ROYGBIVGBIVGBIVG', 'ROYGBIVROYGBIVYG', 'ROYGROYGROYGRBIV', 'ROYBIVGBIVGBIVGB', 'ROYVGBIVGBIVGBIV']