from ..program2510 import program2510
def test15():
    assert program2510(21) == ['ROYVGBIVGBIVGBIVGBIVG', 'ROYBIVGBIVGBIVGBIVGBI', 'ROYGBIVROYGBIVROYGBIV', 'ROYGROYGROYGROYGROBIV', 'ROYGBIVGBIVGBIVGBIVGB', 'ROYGROYGROYGROYGROVIB', 'ROYGBIVOYGBOYGBOYGBIV']