from ..program2510 import program2510
def test4():
    assert program2510(14) == ['ROYGROYGROYBIV', 'ROYGBIVROYGBIV', 'ROYVGBIVGBIVGB', 'ROYGBIVOYGBOIV', 'ROYBIVGBIVGBIV', 'ROYGROYGROYVIB', 'ROYGBIVGBIVGBI']