from ..program2510 import program2510
def test19():
    assert program2510(25) == ['ROYGBIVROYGBIVROYGBIVGBIV', 'ROYGROYGROYGROYGROYGROVIB', 'ROYVGBIVGBIVGBIVGBIVGBIVG', 'ROYGBIVGBIVGBIVGBIVGBIVGB', 'ROYGROYGROYGROYGROYGROBIV', 'ROYGBIVOYGBOYGBOYGBOYGBIV', 'ROYGBIVROYGBIVROYGBIVROYG', 'ROYBIVGBIVGBIVGBIVGBIVGBI']