from ..program2510 import program2510
def test18():
    assert program2510(24) == ['ROYBIVGBIVGBIVGBIVGBIVGB', 'ROYGROYGROYGROYGROYGRBIV', 'ROYGBIVROYGBIVROYGBIVOYG', 'ROYGBIVROYGBIVROYGBIVGBI', 'ROYGBIVOYGBOYGBOYGBOYGIV', 'ROYGBIVGBIVGBIVGBIVGBIVG', 'ROYGROYGROYGROYGROYGRVIB', 'ROYVGBIVGBIVGBIVGBIVGBIV']