from ..program2510 import program2510
def test9():
    assert program2510(15) == ['ROYGBIVROYGBIVG', 'ROYGROYGROYGVIB', 'ROYGBIVROYGBOYG', 'ROYBIVGBIVGBIVG', 'ROYGROYGROYGBIV', 'ROYGBIVOYGBOYIV', 'ROYVGBIVGBIVGBI', 'ROYGBIVGBIVGBIV']