from ..program2510 import program2510
def test13():
    assert program2510(19) == ['ROYGROYGROYGROYGBIV', 'ROYGBIVROYGBIVGBIVG', 'ROYGROYGROYGROYGVIB', 'ROYGBIVGBIVGBIVGBIV', 'ROYVGBIVGBIVGBIVGBI', 'ROYBIVGBIVGBIVGBIVG', 'ROYGBIVROYGBIVROYGB', 'ROYGBIVOYGBOYGBOYIV']