from ..program2510 import program2510
def test16():
    assert program2510(22) == ['ROYGROYGROYGROYGROYVIB', 'ROYVGBIVGBIVGBIVGBIVGB', 'ROYGBIVOYGBOYGBOYGBOIV', 'ROYGROYGROYGROYGROYBIV', 'ROYGBIVROYGBIVROYGBOYG', 'ROYBIVGBIVGBIVGBIVGBIV', 'ROYGBIVROYGBIVROYGBIVG', 'ROYGBIVGBIVGBIVGBIVGBI']