from ..program2510 import program2510
def test11():
    assert program2510(17) == ['ROYGBIVROYGBIVOYG', 'ROYGBIVGBIVGBIVGB', 'ROYGBIVOYGBOYGBIV', 'ROYVGBIVGBIVGBIVG', 'ROYGROYGROYGROVIB', 'ROYGBIVROYGBIVGBI', 'ROYGROYGROYGROBIV', 'ROYBIVGBIVGBIVGBI']