from ..program2510 import program2510
def test12():
    assert program2510(18) == ['ROYGROYGROYGROYBIV', 'ROYGBIVROYGBIVGBIV', 'ROYBIVGBIVGBIVGBIV', 'ROYGBIVROYGBIVROYG', 'ROYGROYGROYGROYVIB', 'ROYGBIVGBIVGBIVGBI', 'ROYVGBIVGBIVGBIVGB', 'ROYGBIVOYGBOYGBOIV']