from ..program2510 import program2510
def test17():
    assert program2510(23) == ['ROYVGBIVGBIVGBIVGBIVGBI', 'ROYGBIVOYGBOYGBOYGBOYIV', 'ROYGBIVGBIVGBIVGBIVGBIV', 'ROYGBIVROYGBIVROYGBIOYG', 'ROYBIVGBIVGBIVGBIVGBIVG', 'ROYGROYGROYGROYGROYGVIB', 'ROYGBIVROYGBIVROYGBIVGB', 'ROYGBIVROYGBIVROYGBIVYG', 'ROYGROYGROYGROYGROYGBIV']