from ..program2510 import program2510
def test14():
    assert program2510(20) == ['ROYGBIVGBIVGBIVGBIVG', 'ROYGBIVROYGBIVROYGBI', 'ROYBIVGBIVGBIVGBIVGB', 'ROYGBIVROYGBIVGBIVGB', 'ROYGROYGROYGROYGRVIB', 'ROYGBIVOYGBOYGBOYGIV', 'ROYVGBIVGBIVGBIVGBIV', 'ROYGROYGROYGROYGRBIV']