from ..program2510 import program2510
def test22():
    assert program2510(34) == ['ROYGBIVROYGBIVROYGBIVROYGBIVROYGBI', 'ROYGBIVGBIVGBIVGBIVGBIVGBIVGBIVGBI', 'ROYGROYGROYGROYGROYGROYGROYGROYBIV', 'ROYGROYGROYGROYGROYGROYGROYGROYVIB', 'ROYVGBIVGBIVGBIVGBIVGBIVGBIVGBIVGB', 'ROYGBIVROYGBIVROYGBIVROYGBIVGBIVGB', 'ROYGBIVOYGBOYGBOYGBOYGBOYGBOYGBOIV', 'ROYBIVGBIVGBIVGBIVGBIVGBIVGBIVGBIV']