from ..program2510 import program2510
def test21():
    assert program2510(29) == ['ROYGBIVGBIVGBIVGBIVGBIVGBIVGB', 'ROYBIVGBIVGBIVGBIVGBIVGBIVGBI', 'ROYGBIVROYGBIVROYGBIVROYGBIVG', 'ROYGBIVOYGBOYGBOYGBOYGBOYGBIV', 'ROYGROYGROYGROYGROYGROYGROBIV', 'ROYGBIVROYGBIVROYGBIVROYGBOYG', 'ROYGROYGROYGROYGROYGROYGROVIB', 'ROYVGBIVGBIVGBIVGBIVGBIVGBIVG']