from ..program2510 import program2510
def test20():
    assert program2510(28) == ['ROYGBIVGBIVGBIVGBIVGBIVGBIVG', 'ROYGROYGROYGROYGROYGROYGRBIV', 'ROYGBIVROYGBIVROYGBIVROYGBIV', 'ROYBIVGBIVGBIVGBIVGBIVGBIVGB', 'ROYVGBIVGBIVGBIVGBIVGBIVGBIV', 'ROYGBIVOYGBOYGBOYGBOYGBOYGIV', 'ROYGROYGROYGROYGROYGROYGRVIB']