from ..program4664 import program4664
def test14():
    assert program4664(10
XOOOOXOOOX
OOOOOOOXXX
OXOOOXXOXO
OOXXXOOXOX
OOXXOOOXXO
XXXXOXOXXX
XXXOOXOOOO
XXXXOOXXXO
OXXXXXXOXX
XXXOOOXOXO
XOOOXOOOOX
XXXOOOOOOO
OXOXXOOOXO
XOXOOXXXOO
OXXOOOXXOO
XXXOXOXXXX
OOOOXOOXXX
OXXXOOXXXX
XXOXXXXXXO
OXOXOOOXXX) == ['YES', 'Yes']