from ..program4664 import program4664
def test34():
    assert program4664(9
XXXOXOOXO
XOOOOXOOO
OOXXOXOXO
XXXXOXOXX
XXXXXXOXO
OOXOXXOXX
XXOXXXXXO
XXXOXOOOO
XXOOXOOXX
XXXOXOOXO
XOOOOXOOO
OOXXOXOXO
XXXXOXOXX
XXXXXXOXO
OOXOXXOXX
XXOXXXXXO
XXXOXOOOO
XXOOXOOXX) == ['YES', 'Yes']