from ..program4664 import program4664
def test35():
    assert program4664(9
OXOXXXXOX
XOXXOXOOO
OOXOOOXOO
OOOXXOXOX
OOXOOOOXX
OXXXOXOOO
OOOXXOXOO
OOXOXXOXO
OOXOOOXOX
OXOOOOXOO
XOOOOXOOO
OXXOXXOXO
XXOXOXXOO
XOOOOOOXO
XXOOOXOXO
XOXOOOXOX
OOXOXOOXO
XOOXXOOOX) == ['No', 'NO']