from ..program4664 import program4664
def test20():
    assert program4664(10
XOXXXXXOOO
OXXOOXXOXX
XXXXXOOXOX
OOOOOXOXOX
OXXOXXXOXO
XOOXOXXXXX
XOOOOOOOOX
OOXXOOXXXX
OOOOXXOOOX
XXXXXOOOXX
XXOOOXXXXX
XOOOXXOOOO
XXXXOOXXOO
XOOOOOOOOX
XXXXXOXOOX
OXOXXXOXXO
XOXOXOOOOO
XOXOOXXXXX
XXOXXOOXXO
OOOXXXXXOX) == ['YES', 'Yes']