from ..program4664 import program4664
def test12():
    assert program4664(10
XOOXOXXXXX
XOXXOXOXXX
OOOXOXOOOX
OOOXXXOOXX
OXOXXOXOXO
OXXOXOOOOO
OXOOXXOXXO
OOXOXXXXOX
XOXXXXOOXX
XOOOOXXOOX
XXXOOOXXXX
OXOXOXXOXX
OOXXOOOOXX
XOXOOXOOOX
XXXXOOXXXX
OXXXXXXOOO
OXOOOXXXXX
OXXOXOOOXO
OOOXXXOOOO
XXOOOOOOXX) == ['YES', 'Yes']