from ..program4664 import program4664
def test15():
    assert program4664(10
XOXXOXXOOX
OXXOXOXXXX
XXOOXOXOOO
OXOOOOXOOO
OOOOOOOXOX
XXOXXOOXOX
XOXOXOOOOX
OXOXOOXXOX
XOXOXOXXXO
OOXOXXXXXX
OOXOOXXXXX
XOXOXOXXXO
OXOXOOXXOX
XOXXXOOOOX
XXOXXOOXOX
OOOOOOOXOX
OXOOOOXOOO
XXOOXOXOOO
OXXOXOXXXX
XOXOOXXOOX) == ['No', 'NO']