from ..program4664 import program4664
def test17():
    assert program4664(10
XOXXXXXXXX
OOOOXXXOXO
XOXXXXOOXX
XXXOXXXXXO
OXXXXOXOOO
OOOOOXOXXX
XOOOXOOXXX
XOOOXXXXOO
OXOOXOXXOX
OXOXXOXXOX
XXOXXOOXOX
OOOXXOXXXX
XXXXXOXOOX
XXXOOXXOXO
OOXOXOXXXX
XXXXOXXXXX
XOOOOXOXOX
OOOXOXXXXX
XXOOOXXOOO
OOXXOOXOOX) == ['No', 'NO']