from ..program4664 import program4664
def test11():
    assert program4664(10
XXOOOOOXXO
OXOOXOOXXO
XOOXOXXXXO
OXXXXOXOXO
XXXOXXOXOO
OXOOOOOXOX
XOXOXOOOXO
OXXXOOOOOX
XXOOOOOXOO
XOXXXOOXXX
XXOXOXOXOX
OXXOXXXOXX
XOXXOXXOOO
XOXOOOXXOO
XOOXOXXOXO
OOOOOXOXOO
OXOOOOXXOO
XXOOXXOXXX
XOOXOOXXXX
XOXOXOOOOO) == ['No', 'NO']