from ..program4664 import program4664
def test33():
    assert program4664(8
OXOOOOOO
XOXOXXXO
OXXXXXOX
OOXXOXOO
XOOOXOOO
XOOXXOXO
OOXXXXXX
XXXOOXXX
OXOOXXOO
XOXOOOOX
OOXXOOXX
OOXXOXXO
OXXOXXXX
OXOXXOXO
OXOOOXXX
OOXOOOXX) == ['No', 'NO']