from ..program4664 import program4664
def test19():
    assert program4664(10
XXOXOOOOXX
XOXXXOXOXO
OXXXOOXOOO
XXOXOOXXOX
XXOXXOXXOO
OOOXXXXOXO
OXXXOXOXOO
OXOXXXXXXX
XXXOOXXXXX
XXOOXOOXXO
XOOOOXXOXX
XXXXOXXXOX
OXOXOOOXXO
OOXXXXXXXX
XOXOXXOOXO
OXXXXOOOXX
OXXXXXXXXO
XXXXOXXOOO
XXXOXOOOXX
OXXXOOXOOX) == ['No', 'NO']