from ..program4664 import program4664
def test9():
    assert program4664(10
XXXOOOOXOX
OOOXXXOXXO
XOXXXXOOXX
XOOOXXOXOO
OOXOOOOOOX
XXXXOXOOOO
XXXOOXOXOX
OOOOXOXOXX
XOXXOXOOXO
OOOOOXOOOO
XXXOOOOXOX
OOOXXXOXXO
XOXXXXOOXX
XOOOXXOXOO
OOXOOOOOOX
XXXXOXOOOO
XXXOOXOXOX
OOOOXOXOXX
XOXXOXOOXO
OOOOOXOOOO) == ['YES', 'Yes']