from ..program4664 import program4664
def test18():
    assert program4664(10
XXXOOOOOXO
XXOXOOXOXX
XOXXXXXXXO
XOXOXOOXXX
XXOOXXOXXO
OOOOOOOOXX
OOXOXXOOXX
XXXXOXXOOO
XOXOXXXOXX
OXXOXXOOOO
OXOXOXXOXO
XXXXXXXOXO
OOXXXOOOOO
OXXOOOOXXO
OOXOXOXXXX
OOXXXOXOXX
OXXOOOOXOO
XOXXOOXXXX
XXOOXOOXOX
XXXXXOOXXO) == ['YES', 'Yes']