from ..program4664 import program4664
def test32():
    assert program4664(8
OXOXXXXX
XXXXOXOO
OXOXOXOX
XXXOXXOX
OXXOXXXX
XXOXXXOO
XXXXOOOO
OXXXOOOO
OOOOXXXO
OOOOXXXX
OOXXXOXX
XXXXOXXO
XOXXOXXX
XOXOXOXO
OOXOXXXX
XXXXXOXO) == ['YES', 'Yes']