from ..program4664 import program4664
def test13():
    assert program4664(10
XXOOXOOOXO
XXOXXXXXXX
XOOOXOOXXX
OXOOOXXXXO
XOOOOOOOOO
XXOXXXXOOX
OOOXOXOOOX
XOXOOXOOXO
OOXOOXOXXO
XOXOXOXXOO
OOOXXOOXXO
OXXOOOOXOX
XXOOOOXXXO
XOOOXOXOXO
OXXXXOXOXO
XOOOXOOXXX
OOOXXOOOXO
XXXOOOOOOO
OOOOXOXOXX
XOXOXXOXXX) == ['No', 'NO']