from ..program4664 import program4664
def test10():
    assert program4664(10
XXOXXOXOOX
OOOOXOOXXO
OXXXOOXOOO
OOXOOOOOOO
XXXOXOXXXX
OXXXXOXXOO
OXXXXOOXXX
XXOXXOXOXO
OOOXOOOOOO
XOOXOOOOXX
XOOXOOOOXX
OOOXOOOOOO
XXOXXOXOXO
OXXXXOOXXX
OXXXXOXXOO
XXXOXOXXXX
OOXOOOOOOO
OXXXOOXOOO
OOOOXOOXXO
XXOXXOXOOX) == ['YES', 'Yes']