from ..program4664 import program4664
def test21():
    assert program4664(10
XXOOOOOXOX
OOOOXXXOXX
OOOXOOOOXX
OXXXXXXOOX
XOOXOXOOXX
XOOOOOOXXO
XXXOOOOXOO
OOOOXOXOOO
OXOOOOOXOX
XXOXXXOXOX
XXOOOXXXXO
OOOOXXOOXO
XXOXXOOOOX
XOXOOOXOXO
XOOOOXXOXO
XOXOOOXOXO
XOOXOXXXXO
OOOXOOXOOO
XXOXOXXOOX
XOOXXXOOOX) == ['No', 'NO']