from ..program4664 import program4664
def test16():
    assert program4664(10
XXXOXOOXXX
OOXXOXXOXO
OOOOXOOXOX
XOOXOXOOXX
XOXXOXOOXX
OOOXXOXOXX
OOOXOOOOXO
OOXOOXXOXX
XXOXOOXOOX
OXXXOOXOXX
XXOXOOXXXO
XOOXOOXOXX
XXOXXOOXOO
OXOOOOXOOO
XXOXOXXOOO
XXOOXOXXOX
XXOOXOXOOX
XOXOOXOOOO
OXOXXOXXOO
XXXOOXOXXX) == ['YES', 'Yes']