from ..program3868 import program3868
def test7():
    assert program3868(RBGYRBGYRBGYRBGYRBGYRBGYRBGYRBGYRBGYRBGYRBGYRBGYRBGYRBGYRBGYRBGYRBGYRBGYRBGYRBGYRBGYRBGYRBGYRBGYRBGY) == ['0\r\n0\r\n0\r\n0', '0 0 0 0']