from ..program4821 import program4821
def test44():
    assert program4821(dkfdgbbmmjdakghficginlncnmfbidnfdfclkafglnniddbbaajedkjbhijmlnddaiiknneblmfingkkblhbkkgfabngflkfhjhcgnilflhalfgmgnecbjnecfldhhlfkdbiffhmbealfdklbggjieeinmafckeclbinmjndndjkdmbfkfljgbjbjcflglmghjbhknldjbbglihbfejaaiidgfbfglalenkeiemhcnffeaglcjgakfclgbbkadf...) == ['0']