from ..program4821 import program4821
def test29():
    assert program4821(jdharroducqtohjnopcmgnvkgvibpimmpbljicjkmdmlfrjvqiuutnevobnrulinliraifguuedejvprsgmramfdotmlffoinmhbdbnfdbqdtjbhjkojvagitoutkdlaqdlfnpgmjjeaqrcakoredjunmitdgojjjcijieijtpiukomtpkmrkajplvlkdmirfeprilamilaifknaiktdcqkgjavrvuffkqccsncollgmbdthohqgcpmusuimisp...) == ['763774137']