from ..program4821 import program4821
def test48():
    assert program4821(bfeedcbdbdafdccaedfefcbbefffecdeaddebbefcdddffbdccbebedfadeefdcfcccccebdfbfbfbdebacefbdbebbcadabfbecdacdcffafbbadddddfcccfcfcedacbfdfeaaecbcfaacbbbaeabbcacbcdcceafcefdfaecfceabebdaddaddaffdccfbcacdbccdfcafbffbdabfeedcbdbdafdccaedfefcbbefffecdeaddebbefcddd...) == ['441936465']