from ..program4821 import program4821
def test30():
    assert program4821(cdaeeaeacccbbcdeeedbadaeddbcaabcecdecdbdaeaaeebedacaaadbeeddcbadaebdbabeaadaccaccadaceacacdcaaabbacdddbbdbacbbadbbdbeadadeecbbcdbceecbecbdbeeaccbceedceaaceddedaadbdeddbbcedaeeceaeabdbbdcbebeabdceebccedcccceecededabeedaaadaeabcdcabbadaddbdabcebdbbcaddcbccc...) == ['0']