from ..program4821 import program4821
def test59():
    assert program4821(babbccccaabaacccbaaccbcbacababbccccaabaacccbaaccbcbacababbccccaabaacccbaaccbcbacababbccccaabaacccbaaccbcbacababbccccaabaacccbaaccbcbacababbccccaabaacccbaaccbcbacababbccccaabaacccbaaccbcbacababbccccaabaacccbaaccbcbacababbccccaabaacccbaaccbcbacababbccccaaba...) == ['0']