from ..program4821 import program4821
def test25():
    assert program4821(biaijagdhdfdebfchgjdbajgjbfibghjigbbdbjgaadgjfdbghidajbfcjddcaijgghabbfdgiigabgaggeihfchgaebefjiaadhgddfabbhhadfgbigffdgeihjdjigihbhbddhicajfcgdgdjheihhgabifbghiafdjiadafeajbiacjhcegfbfbcchjjabachdiggddacfdcibdaebbaidfahjbhdbgbccdfjgfggbeahcfjhhchecegiead...) == ['0']