from ..program4821 import program4821
def test35():
    assert program4821(bkbkkkefaijgdbbbkjkibkjhediggjicgfeigaiehgaelechhklcjcdkhcalkgldelifljbclcceejacbjbjglbhlabchidfgddadafhhjbkejbedclahaachdceeblkfcdfajkfecahflhegkfihkheechebehbdklajbdkeblkcdkgiadkfclifgiggfdhcjagclfjjhhhdbidlacdkbkkkjgcheikjdacehdkkdglfghgcgakakgkhbebbkf...) == ['0']