from ..program4821 import program4821
def test16():
    assert program4821(ehgxkfjpkwbxysqmixmtheehtkfclvxiynxhockpjrsqcuydbfgoetjxwumhfqkhgehgxkfjpkwbxysqmixmtheehtkfclvxiynxhockpjrsqcuydbfgoetjxwumhfqkhgehgxkfjpkwbxysqmixmtheehtkfclvxiynxhockpjrsqcuydbfgoetjxwumhfqkhgehgxkfjpkwbxysqmixmtheehtkfclvxiynxhockpjrsqcuydbfgoetjxwumh...) == ['0']