from ..program4821 import program4821
def test36():
    assert program4821(dacemehkboajmgkialdlegndmdhhgilckmbabbfobecflnjmeocgifkcildjikmliihfbcmgbdlcnjlhefikoahadbofaflkdbamhahlohmjjoogkbaammihldgklggligmdobmjnimfngjjinfodbkklgnmebncgjgbhiianbdllbgdfjgdegkeejchobfkahheeibkniibjaiifnbonnodoombgdbceadeffccklndajkcjdlboldoagfhhoe...) == ['0']