from ..program4821 import program4821
def test47():
    assert program4821(bbfdnfshrhmqdwajvpvjfbsgfacnmhlldawbtqcfguggjfsaoijbcqnlvofojvjqabbabriamwnhdhkevantpqhntgjosglbsjeaekkebglphppondvnwhbkhtuhlewajjrgokpngirelusgwvmhhckaubnihhbbfdnfshrhmqdwajvpvjfbsgfacnmhlldawbtqcfguggjfsaoijbcqnlvofojvjqabbabriamwnhdhkevantpqhntgjosglbs...) == ['474381066']