from ..program4821 import program4821
def test21():
    assert program4821(gfejleepamadbcobamcodcqqbbgpjhbenlfciikqqlnekpbhcnmmnbajpqlqoenfpeebjbohlkfhhfldajgikkfmdcinneqedepidkepomqgpbbjjkncnqpcjejbknjpjqoaiipbainpknhhngjoeallqfddhfdlajdgpqbbeefodleicgqckikgcihfpfopcfqmdpqqfpkoeplgmkoohejhjpoflbffeqpbialqkmiembdaehmhmjleilpfpdf...) == ['0']