from ..program4821 import program4821
def test105():
    assert program4821(dkjijdkjijdkjijdkjijdkjijdkjijdkjijdkjijdkjijdkjijdkjijdkjijdkjijdkjijdkjijdkjijdkjijdkjijdkjijdkjijdkjijdkjijdkjijdkjijdkjijdkjijdkjijdkjijdkjijdkjijdkjijdkjijdkjijdkjijdkjijdkjijdkjijdkjijdkjijdkjijdkjijdkjij
dddkikjjidkkidijjjjkkjjikjdikiidijjikikjijjiijdikkjjjiddjjijkkkjkiijijkijdjjikikdjjjijdddjkjjdijjjjjjjddkjjkjjjdjjdkijjkijkkjkkkiiijdjijkkdjdjjjkkjkdddjidjjijdddkijididjdddidijjjjjdkidijjkkjiijkjjjjjjdjkkdddkjj
31328) == ['0']