from ..program2349 import program2349
def test11():
    assert program2349(eufycwztywhbjrpqobvknwfqmnboqcfdiahkagykeibbsqpljcghhmsgfmswwsanzyiwtvuirwmppfivtekaywkzskyydfvkjgxb
ecfwavookadbcilfobojnweqinbcpcfdiahkabwkeibbacpljcghhksgfajgmianfnivmhfifogpffiheegayfkxkkcmdfvihgdb) == ['ecfwavookadbcilfobojnweqinbcpcfdiahkabwkeibbacpljcghhksgfajgmianfnivmhfifogpffiheegayfkxkkcmdfvihgdb', 'zczwavookadzcilfzzojzzezizzcpzzzzzzzzbwzzzzzaczzzzzzzkzzzajgmizzfnzvmhfzfogzfzzhezgzzfzxkzcmzzzihzdz', 'fcgwavookadccilfpcojoxerioccpdgejbilbbwlfjccacqmkdhiikthgajgmibofnjvmhfjfogqfgjhefgbzflxklcmegwihhdc']