from ..program2349 import program2349
def test19():
    assert program2349(tgharsjyihroiiahwgbjezlxvlterxivdhtzjcqegzmtigqmrehvhiyjeywegxaseoyoacouijudbiruoghgxvxadwzgdxtnxlds
tghaksjsdhkoiiahegbjexlfrctercipdhmvjbgegxdtggqdpbhvhiseehhegnaseoooacnsijubbirjnghgsvpadhaadrtimfdp) == ['zzzzkzzsdzkzzzzzezzzzxzfrczzzczpzzmvzbgzzxdzgzzdpbzzzzsezhhzznzzzzozzznszzzbzzzjnzzzszpzzhaazrzimfzp', 'uhibktksdikpjjbiehckfxmfrcufscjpeimvkbgfhxdughrdpbiwijsefhhfhnbtfpopbdnsjkvbcjsjnhihswpbehaaeruimfep', 'tghaksjsdhkoiiahegbjexlfrctercipdhmvjbgegxdtggqdpbhvhiseehhegnaseoooacnsijubbirjnghgsvpadhaadrtimfdp']