from ..program2349 import program2349
def test13():
    assert program2349(nmuwjdihouqrnsuahimssnrbxdpwvxiyqtenahtrlshjkmnfuttnpqhgcagoptinnaptxaccptparldzrhpgbyrzedghudtsswxi
nilhbdghosqnbebafimconrbvdodjsipqmekahhrllhjkemeketapfhgcagopfidnahtlaccpfpafedqicpcbvfgedghudhddwib) == ['nilhbdghosqnbebafimconrbvdodjsipqmekahhrllhjkemeketapfhgcagopfidnahtlaccpfpafedqicpcbvfgedghudhddwib', 'zilhbzgzzsznbebzfzzcozzzvzodjszpzmzkzzhzzlzzzemekezazfzzzzzzzfzdzzhzlzzzzfzzfezqiczczvfgzzzzzzhddzib', 'oilhbegipsrnbebbfjncooscveodjsjprmfkbihsmliklemekeuaqfihdbhpqfjdobhulbddqfqbfeeqicqccvfgfehivehddxib']