from ..program2349 import program2349
def test17():
    assert program2349(zrvzedssbsrfldqvjpgmsefrmsatspzoitwvymahiptphiystjlsauzquzqqbmljobdhijcpdvatorwmyojqgnezvzlgjibxepcf
pesoedmqbmffldqsjggmhefkadaesijointrkmahapaahiysfjdiaupqujngbjhjobdhiecadeatgjvelojjgnepvajgeibfepaf) == ['pesofemqcmfgmerskghnhfgkadbetijpjntrknbiaqaaijztfkdibvprvjngcjhkpceijedaeebugjvelpkjhofpwajhejcffqag', 'pesozzmqzmfzzzzszgzzhzzkadzezijzzntrkzzzazaazzzzfzdizzpzzjngzjhzzzzzzezazezzgjvelzzjzzzpzajzezzfzzaz', 'pesoedmqbmffldqsjggmhefkadaesijointrkmahapaahiysfjdiaupqujngbjhjobdhiecadeatgjvelojjgnepvajgeibfepaf']