from ..program2349 import program2349
def test15():
    assert program2349(hbgwuqzougqzlxemvyjpeizjfwhgugrfnhbrlxkmkdalikfyunppwgdzmalbwewybnjzqsohwhjkdcyhhzmysflambvhpsjilsyv
fbdjdqjojdafarakvcjpeipjfehgfgrfehbolxkmkdagikflunnpvadocalbkedibhbflmohnhjkdcthhaigsfjaibqhbcjelirv) == ['fcdjdrjpjdafarakwckqfjpkgeihfhsgeicomylnlebgjlglvonqvaeocbmckfdichbflmpinikledtiiaigtgjbicqibckemirw', 'fzdjdzjzjdafarakzczzzzpzzezzfzzzezzozzzzzzzgzzzlzznzvazoczzzkzdizhbflmzznzzzzztzzaigzzjzizqzbczezirz', 'fbdjdqjojdafarakvcjpeipjfehgfgrfehbolxkmkdagikflunnpvadocalbkedibhbflmohnhjkdcthhaigsfjaibqhbcjelirv']