from ..program2349 import program2349
def test21():
    assert program2349(nttdcfceptruiomtmwzestrfchnqpgqeztpcvthzelfyggjgqadylzubpvbrlgndrcsursczpxlnoyoadxezncqalupfzmjeqihe
kttdcfceohrjiaahmoldanpfchnfpgheqpdahqhxecfpbgigqadrkjubjfbrlgndbcgcgmcjpeleinaadretncqaiqpfkmjeqihe) == ['kuuedgdfohsjjaahnoldanpgdiofqhhfqpdahqixfcgpbhihrberkjvcjfcsmhoebdgcgmdjqemeinaberftodrbiqqgknkfrjif', 'kttdcfceohrjiaahmoldanpfchnfpgheqpdahqhxecfpbgigqadrkjubjfbrlgndbcgcgmcjpeleinaadretncqaiqpfkmjeqihe', 'kzzzzzzzohzjzaahzoldanpzzzzfzzhzqpdahqzxzczpbzizzzzrkjzzjfzzzzzzbzgcgmzjzezeinazzrztzzzziqzzkzzzzzzz']