from ..program500 import program500
def test14():
    assert program500(IJHHGKCXWDBRWJUPRDBZJLNTTNWKXLUGJSBWBOAUKWRAQWGFNL
NJMWRMBCNPHXTDQQNZ
WDNJRCLILNQRHWBANLTXWMJBPKUPGKJDJZAQWKTZFBRCTXHHBNXRGUQUNBNMWODGSJWW) == ['YES']