from ..program500 import program500
def test12():
    assert program500(OVQELLOGFIOLEHXMEMBJDIGBPGEYFG
JNKFPFFIJOFHRIFHXEWYZOPDJBZTJZKBWQTECNHRFSJPJOAPQT
YAIPFFFEXJJNEJPLREIGODEGQZVMCOBDFKWTMWJSBEBTOFFQOHIQJLHFNXIGOHEZRZLFOKJBJPTPHPGY) == ['YES']