from ..program500 import program500
def test41():
    assert program500(IDQRX
WETHO
ODPDGBHVUVSSISROHQJTUKPUCLXABIZQQPPBPKOSEWGEHRSRRNBAVLYEMZISMWWGKHVTXKUGUXEFBSWOIWUHRJGMWBMHQLDZHBWA) == ['NO']