from ..program500 import program500
def test48():
    assert program500(GXPZFSELJJNDAXYRV
UYBKPMVBSOVOJWMONLTJOJCNQKMTAHEWLHOWIIBH
HCWNFWJPEJIWOVPTBMVCRJLSISSVNOHCKLBFMIUAIMASQWPXEYXBOXQGFEMYJLBKDCZIMJNHOJEDGGANIVYKQTUOSOVOPWHVJGXH) == ['NO']