from ..program500 import program500
def test21():
    assert program500(NUBKQEJHALANSHEIFUZHYEZKKDRFHQKAJHLAOWTZIMOCWOVVDW
EFVOBIGAUAUSQGVSNBKNOBDMINODMFSHDL
KLAMKNTHBFFOHVKWICHBKNDDQNEISODUSDNLUSIOAVWY) == ['NO']