from ..program500 import program500
def test32():
    assert program500(OSKFHGYNQLSRFSAHPXKGPXUHXTRBJNAQRBSSWJVEENLJCDDHFXVCUNPZAIVVO
FNUOCXAGRRHNDJAHVVLGGEZQHWARYHENBKHP
UOEFNWVXCUNERLKVTHAGPSHKHDYFPYWZHJKHQLSNFBJHVJANRXCNSDUGVDABGHVAOVHBJZXGRACHRXEGNRPQEAPORQSILNXFS) == ['YES']