from ..program500 import program500
def test27():
    assert program500(AGFIGYWJLVMYZGNQHEHWKJIAWBPUAQFERMCDROFN
PMJNHMVNRGCYZAVRWNDSMLSZHFNYIUWFPUSKKIGU
MCDVPPRXGUAYLSDRHRURZASXUWZSIIEZCPXUVEONKNGNWRYGOSFMCKESMVJZHWWUCHWDQMLASLNNMHAU) == ['NO']