from ..program500 import program500
def test45():
    assert program500(UIKWWKXLSHTOOZOVGXKYSOJEHAUEEG
KZXQDWJJWRXFHKJDQHJK
XMZHTFOGEXAUJXXJUYVJIFOTKLZHDKELJWERHMGAWGKWAQKEKHIDWGGZVYOHKXRPWSJDPESFJUMKQYWBYUTHQYEFZUGKQOBHYDWB) == ['NO']