from ..program902 import program902
def test3():
    assert program902(UTEDBZRVWLOFUASHCYIPXGJMKNQ) == ['ZBDETUQNKMJGX\r\nRVWLOFASHCYIP', 'RVWLOFASHCYIP\r\nZBDETUQNKMJGX', 'PIYCHSAUTEDBZ\r\nXGJMKNQFOLWVR', 'XGJMKNQUTEDBZ\r\nPIYCHSAFOLWVR']