from ..program902 import program902
def test43():
    assert program902(QWERTYUIOPASDFGHJKLZXCVBNMQ) == ['DSAPOIUYTREWQ\r\nFGHJKLZXCVBNM', 'FGHJKLZXCVBNM\r\nDSAPOIUYTREWQ', 'QWERTYUIOPASD\r\nMNBVCXZLKJHGF']