from ..program902 import program902
def test44():
    assert program902(ABCBDEFGHIJKLMNOPQRSTUVWXYZ) == ['PQRSTUVWXYZAB\r\nONMLKJIHGFEDC', 'CDEFGHIJKLMNO\r\nBAZYXWVUTSRQP', 'ONMLKJIHGFEDB\r\nPQRSTUVWXYZAC', 'BAZYXWVUTSRQP\r\nCDEFGHIJKLMNO']