from ..program902 import program902
def test42():
    assert program902(BUVTYZFQSNRIWOXGJLKACPEMDHB) == ['WIRNSQFZYTVUB\r\nOXGJLKACPEMDH', 'BUVTYZFQSNRIW\r\nHDMEPCAKLJGXO', 'OXGJLKACPEMDH\r\nWIRNSQFZYTVUB']