from ..program902 import program902
def test27():
    assert program902(UTGDEJHCBKRWLYFSONAQVMPIXZT) == ['YLWRKBCHJEDGT\r\nFSONAQVMPIXZU', 'FSONAQVMPIXZU\r\nYLWRKBCHJEDGT', 'TGDEJHCBKRWLY\r\nUZXIPMVQANOSF']