from ..program902 import program902
def test16():
    assert program902(YAMVOHUJLEDCWZLXNRGPIQTBSKF) == ['KFYAMVOHUJLED\r\nSBTQIPGRNXZWC', 'SBTQIPGRNXLED\r\nKFYAMVOHUJZWC', 'DELJUHOVMAYFK\r\nCWZXNRGPIQTBS', 'CWZXNRGPIQTBS\r\nDELJUHOVMAYFK']