from ..program902 import program902
def test45():
    assert program902(ABCDEFGHIJKLMNOPQRSTUVWXAYZ) == ['ZABCDEFGHIJKL\r\nYXWVUTSRQPONM', 'LKJIHGFEDCBAZ\r\nMNOPQRSTUVWXY', 'MNOPQRSTUVWXY\r\nLKJIHGFEDCBAZ', 'YABCDEFGHIJKL\r\nZXWVUTSRQPONM']