from ..program902 import program902
def test24():
    assert program902(AHGZCRJTKPMQUNBWSIYLDXEHFVO) == ['VFHGZCRJTKPMQ\r\nOAEXDLYISWBNU', 'OAHGZCRJTKPMQ\r\nVFEXDLYISWBNU', 'UNBWSIYLDXEFV\r\nQMPKTJRCZGHAO', 'QMPKTJRCZGHAO\r\nUNBWSIYLDXEFV']