from ..program902 import program902
def test12():
    assert program902(XTSHBGLRJAMDUIPCWYOZVERNKQF) == ['CWYOZVENKQFXT\r\nPIUDMAJRLGBHS', 'PIUDMAJRLGBHS\r\nCWYOZVENKQFXT', 'XFQKNRJAMDUIP\r\nTSHBGLEVZOYWC', 'SHBGLRJAMDUIP\r\nTXFQKNEVZOYWC']