from ..program902 import program902
def test29():
    assert program902(HIDCLZUTPOQGEXFASJNYBVRMDKW) == ['WKDCLZUTPOQGE\r\nHIMRVBYNJSAFX', 'EGQOPTUZLCDIH\r\nXFASJNYBVRMKW', 'XFASJNYBVRMKW\r\nEGQOPTUZLCDIH', 'HIDCLZUTPOQGE\r\nWKMRVBYNJSAFX']