from ..program902 import program902
def test47():
    assert program902(BACDEFGHIJKLMNOPQRSTUVWXYZA) == ['NMLKJIHGFEDCA\r\nOPQRSTUVWXYZB', 'OPQRSTUVWXYZB\r\nNMLKJIHGFEDCA', 'ACDEFGHIJKLMN\r\nBZYXWVUTSRQPO']