from ..program902 import program902
def test11():
    assert program902(XCDSLTYWJIGUBPHNFZWVMQARKOE) == ['XCDSLTYWJIGUB\r\nEOKRAQMVZFNHP', 'BUGIJWYTLSDCX\r\nPHNFZVMQARKOE', 'PHNFZVMQARKOE\r\nBUGIJWYTLSDCX', 'OKRAQMVWJIGUB\r\nEXCDSLTYZFNHP']