from ..program902 import program902
def test41():
    assert program902(ABCDEFGHIJKLMNOPQRSTUVWYXYZ) == ['YWVUTSRQPONML\r\nXZABCDEFGHIJK', 'KJIHGFEDCBAZY\r\nLMNOPQRSTUVWX', 'LMNOPQRSTUVWY\r\nKJIHGFEDCBAZX', 'XZABCDEFGHIJK\r\nYWVUTSRQPONML']