from ..program902 import program902
def test38():
    assert program902(ABCDEFGHIJKLMNOPQRSTUVWXYZG) == ['DEFGHIJKLMNOP\r\nCBAZYXWVUTSRQ', 'CBAGHIJKLMNOP\r\nDEFZYXWVUTSRQ', 'QRSTUVWXYZABC\r\nPONMLKJIHGFED', 'PONMLKJIHGFED\r\nQRSTUVWXYZABC']