from ..program902 import program902
def test15():
    assert program902(XZTMCRBONHFIUVPKWSDLJQGAHYE) == ['WKPVUIFHNOBRC\r\nSDLJQGAYEXZTM', 'CRBONHFIUVPKW\r\nMTZXEYAGQJLDS', 'TZXEYHFIUVPKW\r\nMCRBONAGQJLDS', 'SDLJQGAYEXZTM\r\nWKPVUIFHNOBRC']