from ..program902 import program902
def test32():
    assert program902(OURNQJWMIXCLGSDVEKZAFBYNTPH) == ['GLCXIMWJQNRUO\r\nSDVEKZAFBYTPH', 'HPTNQJWMIXCLG\r\nOURYBFAZKEVDS', 'SDVEKZAFBYTPH\r\nGLCXIMWJQNRUO', 'OURNQJWMIXCLG\r\nHPTYBFAZKEVDS']