from ..program902 import program902
def test13():
    assert program902(RFKNZXHAIMVBWEBPTCSYOLJGDQU) == ['QDGJLOYSCTPBW\r\nURFKNZXHAIMVE', 'WBVMIAHXZNKFR\r\nEPTCSYOLJGDQU', 'RFKNZXHAIMVBW\r\nUQDGJLOYSCTPE', 'EPTCSYOLJGDQU\r\nWBVMIAHXZNKFR']