from ..program902 import program902
def test33():
    assert program902(ZWFIRJNXVKHOUSTQBLEGYMAPIDC) == ['WFIRJNXVKHOUS\r\nZCDPAMYGELBQT', 'CDIRJNXVKHOUS\r\nZWFPAMYGELBQT', 'TQBLEGYMAPDCZ\r\nSUOHKVXNJRIFW', 'SUOHKVXNJRIFW\r\nTQBLEGYMAPDCZ']