from ..program902 import program902
def test28():
    assert program902(BETRFOVLPCMWKHAXSGUDQYJTZIN) == ['IZTRFOVLPCMWK\r\nNBEJYQDUGSXAH', 'KWMCPLVOFRTEB\r\nHAXSGUDQYJZIN', 'BETRFOVLPCMWK\r\nNIZJYQDUGSXAH', 'HAXSGUDQYJZIN\r\nKWMCPLVOFRTEB']