from ..program902 import program902
def test25():
    assert program902(UNGHFQRCIPBZTEOAYJXLDMSKNWV) == ['WNGHFQRCIPBZT\r\nVUKSMDLXJYAOE', 'EOAYJXLDMSKWV\r\nTZBPICRQFHGNU', 'TZBPICRQFHGNU\r\nEOAYJXLDMSKWV', 'UNGHFQRCIPBZT\r\nVWKSMDLXJYAOE']