from ..program902 import program902
def test17():
    assert program902(XECPFJBHINOWVLAGTUMRZYHQSDK) == ['ALVWONIHBJFPC\r\nGTUMRZYQSDKXE', 'GTUMRZYQSDKXE\r\nALVWONIHBJFPC', 'CPFJBHINOWVLA\r\nEXKDSQYZRMUTG', 'XKDSQHINOWVLA\r\nECPFJBYZRMUTG']