from ..program902 import program902
def test37():
    assert program902(ABACDEFGHIJKLMNOPQRSTUVWXYZ) == ['NMLKJIHGFEDCA\r\nOPQRSTUVWXYZB', 'BCDEFGHIJKLMN\r\nAZYXWVUTSRQPO', 'AZYXWVUTSRQPO\r\nBCDEFGHIJKLMN', 'OPQRSTUVWXYZA\r\nNMLKJIHGFEDCB']