from ..program902 import program902
def test14():
    assert program902(HVDEBKMJTLKQORNWCZSGXYIPUAF) == ['JMKBEDVHFAUPI\r\nTLQORNWCZSGXY', 'IPUAFHVDEBKMJ\r\nYXGSZCWNROQLT', 'XGSZCWNROQKMJ\r\nYIPUAFHVDEBLT', 'TLQORNWCZSGXY\r\nJMKBEDVHFAUPI']