from ..program902 import program902
def test36():
    assert program902(ABCDEFGHIJKLMNOPQRSTUVWXYZA) == ['MLKJIHGFEDCBA\r\nNOPQRSTUVWXYZ', 'ABCDEFGHIJKLM\r\nZYXWVUTSRQPON', 'NOPQRSTUVWXYZ\r\nMLKJIHGFEDCBA']