from ..program902 import program902
def test4():
    assert program902(ZWMFLTCQIAJEVUPODMSGXKHRNYB) == ['HKXGSMFLTCQIA\r\nRNYBZWDOPUVEJ', 'NYBZWMFLTCQIA\r\nRHKXGSDOPUVEJ', 'AIQCTLFMWZBYN\r\nJEVUPODSGXKHR', 'JEVUPODSGXKHR\r\nAIQCTLFMWZBYN']