from ..program902 import program902
def test46():
    assert program902(ABCDEFGHIJKLMZYXWVUTSRQPONA) == ['MLKJIHGFEDCBA\r\nZYXWVUTSRQPON', 'ABCDEFGHIJKLM\r\nNOPQRSTUVWXYZ', 'ZYXWVUTSRQPON\r\nMLKJIHGFEDCBA']