from ..program902 import program902
def test9():
    assert program902(GYCUAXSBNAWFIJPDQVETKZOMLHR) == ['ZOMLHRGYCUAXS\r\nKTEVQDPJIFWNB', 'SXAUCYGRHLMOZ\r\nBNWFIJPDQVETK', 'BNWFIJPDQVETK\r\nSXAUCYGRHLMOZ', 'TEVQDPJIFWAXS\r\nKZOMLHRGYCUNB']