from ..program902 import program902
def test23():
    assert program902(NMGIFDZKBCVRYLTWOASXHEUQPJN) == ['NMGIFDZKBCVRY\r\nJPQUEHXSAOWTL', 'LTWOASXHEUQPJ\r\nYRVCBKZDFIGMN', 'YRVCBKZDFIGMN\r\nLTWOASXHEUQPJ']