from ..program902 import program902
def test6():
    assert program902(BMVFGRNDOWTILZVHAKCQSXYEJUP) == ['YEJUPBMVFGRND\r\nXSQCKAHZLITWO', 'OWTILZHAKCQSX\r\nDNRGFVMBPUJEY', 'DNRGFVMBPUJEY\r\nOWTILZHAKCQSX', 'XSQCKAHVFGRND\r\nYEJUPBMZLITWO']