from ..program902 import program902
def test5():
    assert program902(QGZEMFKWLUHOVSXJTCPIYREDNAB) == ['QGZEMFKWLUHOV\r\nBANDRYIPCTJXS', 'SXJTCPIYRDNAB\r\nVOHULWKFMEZGQ', 'VOHULWKFMEZGQ\r\nSXJTCPIYRDNAB', 'ANDEMFKWLUHOV\r\nBQGZRYIPCTJXS']