from ..program902 import program902
def test0():
    assert program902(ABCDEFGHIJKLMNOPQRSGTUVWXYZ) == ['MLKJIHGFEDCBA\r\nNOPQRSTUVWXYZ', 'YXWVUTGHIJKLM\r\nZABCDEFSRQPON', 'NOPQRSTUVWXYZ\r\nMLKJIHGFEDCBA', 'ABCDEFGHIJKLM\r\nZYXWVUTSRQPON']