from ..program902 import program902
def test20():
    assert program902(TEGXHBUVZDPAMIJFQYCWRKSTNLO) == ['APDZVUBHXGETO\r\nMIJFQYCWRKSNL', 'NTEGXHBUVZDPA\r\nLOSKRWCYQFJIM', 'OTEGXHBUVZDPA\r\nLNSKRWCYQFJIM', 'MIJFQYCWRKSNL\r\nAPDZVUBHXGETO']