from ..program902 import program902
def test21():
    assert program902(XQVBTCNIRFPLOHAYZUMKWEJSXDG) == ['OHAYZUMKWEJSD\r\nLPFRINCTBVQXG', 'DXQVBTCNIRFPL\r\nGSJEWKMUZYAHO', 'LPFRINCTBVQXG\r\nOHAYZUMKWEJSD', 'GXQVBTCNIRFPL\r\nDSJEWKMUZYAHO']