from ..program902 import program902
def test34():
    assert program902(UOWJXRKHZDNGLSAMEIYTQBVCFJP) == ['UPJXRKHZDNGLS\r\nOWFCVBQTYIEMA', 'AMEIYTQBVCFPU\r\nSLGNDZHKRXJWO', 'OWJXRKHZDNGLS\r\nUPFCVBQTYIEMA', 'SLGNDZHKRXJWO\r\nAMEIYTQBVCFPU']