from ..program902 import program902
def test40():
    assert program902(ABCDEFGHIJKLMNOPQRSTUVWXYZX) == ['ZABCDEFGHIJKL\r\nYXWVUTSRQPONM', 'YXWVUTSRQPONM\r\nZABCDEFGHIJKL', 'MNOPQRSTUVWXY\r\nLKJIHGFEDCBAZ', 'KJIHGFEDCBAXY\r\nLMNOPQRSTUVWZ']