from ..program902 import program902
def test8():
    assert program902(YOFJVQSWBUZENPCXGQTHMDKAILR) == ['ENPCXGTHMDKAI\r\nZUBWSQVJFOYRL', 'IAKDMHTQSWBUZ\r\nLRYOFJVGXCPNE', 'ZUBWSQVJFOYRL\r\nENPCXGTHMDKAI', 'LRYOFJVQSWBUZ\r\nIAKDMHTGXCPNE']