from ..program902 import program902
def test31():
    assert program902(LCFNHUQWXBPOSJMYTGKDAZVREIF) == ['MYTGKDAZVREIL\r\nJSOPBXWQUHNFC', 'JSOPBXWQUHNFC\r\nMYTGKDAZVREIL', 'LFNHUQWXBPOSJ\r\nCIERVZADKGTYM', 'CFNHUQWXBPOSJ\r\nLIERVZADKGTYM']