from ..program902 import program902
def test35():
    assert program902(IHDTJLGRFUXQSOZEMVYKWCPANBT) == ['DTJLGRFUXQSOZ\r\nHIBNAPCWKYVME', 'ITJLGRFUXQSOZ\r\nHDBNAPCWKYVME', 'ZOSQXUFRGLJTD\r\nEMVYKWCPANBIH', 'EMVYKWCPANBIH\r\nZOSQXUFRGLJTD']