from ..program902 import program902
def test26():
    assert program902(MKBGVNDJRAWUEHFSYLIZCOPTXKQ) == ['EUWARJDNVGBKM\r\nHFSYLIZCOPTXQ', 'MKBGVNDJRAWUE\r\nQXTPOCZILYSFH', 'QKBGVNDJRAWUE\r\nMXTPOCZILYSFH', 'HFSYLIZCOPTXQ\r\nEUWARJDNVGBKM']