from ..program902 import program902
def test7():
    assert program902(MKNTKOBFLJSXWQPVUERDHIACYGZ) == ['VPQWXSJLFBOKN\r\nUERDHIACYGZMT', 'ERDHIACYGZMKN\r\nUVPQWXSJLFBOT', 'TOBFLJSXWQPVU\r\nNKMZGYCAIHDRE', 'NKMZGYCAIHDRE\r\nTOBFLJSXWQPVU']