from ..program902 import program902
def test22():
    assert program902(MIDLBEUAGTNPYKFWHVSRJOXCZMQ) == ['KFWHVSRJOXCZQ\r\nYPNTGAUEBLDIM', 'YPNTGAUEBLDIM\r\nKFWHVSRJOXCZQ', 'MIDLBEUAGTNPY\r\nQZCXOJRSVHWFK']