from ..program902 import program902
def test39():
    assert program902(ABCDEFGHGIJKLMNOPQRSTUVWXYZ) == ['TSRQPONMLKJIG\r\nUVWXYZABCDEFH', 'UVWXYZABCDEFG\r\nTSRQPONMLKJIH', 'HIJKLMNOPQRST\r\nGFEDCBAZYXWVU', 'GFEDCBAZYXWVU\r\nHIJKLMNOPQRST']