from ..program902 import program902
def test30():
    assert program902(CNHIKJWRLPXTQZVUGYDMBAOEFHS) == ['VUGYDMBAOEFSC\r\nZQTXPLRWJKIHN', 'SHIKJWRLPXTQZ\r\nCNFEOABMDYGUV', 'ZQTXPLRWJKIHN\r\nVUGYDMBAOEFSC', 'NHIKJWRLPXTQZ\r\nCSFEOABMDYGUV']