from ..program502 import program502
def test45():
    assert program502(UIKWWKXLSHTOOZOVGXKYSOJEHAUEEG
KZXQDWJJWRXFHKJDQHJK
XMZHTFOGEXAUJXXJUYVJIFOTKLZHDKELJWERHMGAWGKWAQKEKHIDWGGZVYOHKXRPWSJDPESFJUMKQYWBYUTHQYEFZUGKQOBHYDWB) == ['NO']