from ..program502 import program502
def test48():
    assert program502(GXPZFSELJJNDAXYRV
UYBKPMVBSOVOJWMONLTJOJCNQKMTAHEWLHOWIIBH
HCWNFWJPEJIWOVPTBMVCRJLSISSVNOHCKLBFMIUAIMASQWPXEYXBOXQGFEMYJLBKDCZIMJNHOJEDGGANIVYKQTUOSOVOPWHVJGXH) == ['NO']