from ..program502 import program502
def test21():
    assert program502(NUBKQEJHALANSHEIFUZHYEZKKDRFHQKAJHLAOWTZIMOCWOVVDW
EFVOBIGAUAUSQGVSNBKNOBDMINODMFSHDL
KLAMKNTHBFFOHVKWICHBKNDDQNEISODUSDNLUSIOAVWY) == ['NO']