from ..program502 import program502
def test41():
    assert program502(IDQRX
WETHO
ODPDGBHVUVSSISROHQJTUKPUCLXABIZQQPPBPKOSEWGEHRSRRNBAVLYEMZISMWWGKHVTXKUGUXEFBSWOIWUHRJGMWBMHQLDZHBWA) == ['NO']