from ..program502 import program502
def test12():
    assert program502(OVQELLOGFIOLEHXMEMBJDIGBPGEYFG
JNKFPFFIJOFHRIFHXEWYZOPDJBZTJZKBWQTECNHRFSJPJOAPQT
YAIPFFFEXJJNEJPLREIGODEGQZVMCOBDFKWTMWJSBEBTOFFQOHIQJLHFNXIGOHEZRZLFOKJBJPTPHPGY) == ['YES']