from ..program502 import program502
def test14():
    assert program502(IJHHGKCXWDBRWJUPRDBZJLNTTNWKXLUGJSBWBOAUKWRAQWGFNL
NJMWRMBCNPHXTDQQNZ
WDNJRCLILNQRHWBANLTXWMJBPKUPGKJDJZAQWKTZFBRCTXHHBNXRGUQUNBNMWODGSJWW) == ['YES']