from ..program502 import program502
def test32():
    assert program502(OSKFHGYNQLSRFSAHPXKGPXUHXTRBJNAQRBSSWJVEENLJCDDHFXVCUNPZAIVVO
FNUOCXAGRRHNDJAHVVLGGEZQHWARYHENBKHP
UOEFNWVXCUNERLKVTHAGPSHKHDYFPYWZHJKHQLSNFBJHVJANRXCNSDUGVDABGHVAOVHBJZXGRACHRXEGNRPQEAPORQSILNXFS) == ['YES']