from ..program502 import program502
def test27():
    assert program502(AGFIGYWJLVMYZGNQHEHWKJIAWBPUAQFERMCDROFN
PMJNHMVNRGCYZAVRWNDSMLSZHFNYIUWFPUSKKIGU
MCDVPPRXGUAYLSDRHRURZASXUWZSIIEZCPXUVEONKNGNWRYGOSFMCKESMVJZHWWUCHWDQMLASLNNMHAU) == ['NO']