from ..program4822 import program4822
def test44():
    assert program4822(dkfdgbbmmjdakghficginlncnmfbidnfdfclkafglnniddbbaajedkjbhijmlnddaiiknneblmfingkkblhbkkgfabngflkfhjhcgnilflhalfgmgnecbjnecfldhhlfkdbiffhmbealfdklbggjieeinmafckeclbinmjndndjkdmbfkfljgbjbjcflglmghjbhknldjbbglihbfejaaiidgfbfglalenkeiemhcnffeaglcjgakfclgbbkadf...) == ['0']