from ..program4822 import program4822
def test26():
    assert program4822(hjjhhikbkhlcdknpiqjeegjccchmihfbadobpligbmbealflefcqnddoligpkfjeplaigmgihbjddnilqiddhikoqhpfbqomfknfnonpnopiqamcdfcbnldfecmfbponempcfmckedqbdipjppqfnlaabpgcdedoljjgncdacgklpjpjhhcjbpcdggqkbaimimqffmdogcbmmkdffnlqopjagkhiggqnkhpikmjmbnnemplegpgdgbodahcbbnd...) == ['0']