from ..program4822 import program4822
def test59():
    assert program4822(babbccccaabaacccbaaccbcbacababbccccaabaacccbaaccbcbacababbccccaabaacccbaaccbcbacababbccccaabaacccbaaccbcbacababbccccaabaacccbaaccbcbacababbccccaabaacccbaaccbcbacababbccccaabaacccbaaccbcbacababbccccaabaacccbaaccbcbacababbccccaabaacccbaaccbcbacababbccccaaba...) == ['0']