from ..program4661 import program4661
def test33():
    assert program4661(8
OXOOOOOO
XOXOXXXO
OXXXXXOX
OOXXOXOO
XOOOXOOO
XOOXXOXO
OOXXXXXX
XXXOOXXX
OXOOXXOO
XOXOOOOX
OOXXOOXX
OOXXOXXO
OXXOXXXX
OXOXXOXO
OXOOOXXX
OOXOOOXX) == ['No', 'NO']