from ..program4661 import program4661
def test12():
    assert program4661(10
XOOXOXXXXX
XOXXOXOXXX
OOOXOXOOOX
OOOXXXOOXX
OXOXXOXOXO
OXXOXOOOOO
OXOOXXOXXO
OOXOXXXXOX
XOXXXXOOXX
XOOOOXXOOX
XXXOOOXXXX
OXOXOXXOXX
OOXXOOOOXX
XOXOOXOOOX
XXXXOOXXXX
OXXXXXXOOO
OXOOOXXXXX
OXXOXOOOXO
OOOXXXOOOO
XXOOOOOOXX) == ['YES', 'Yes']