from ..program4661 import program4661
def test34():
    assert program4661(9
XXXOXOOXO
XOOOOXOOO
OOXXOXOXO
XXXXOXOXX
XXXXXXOXO
OOXOXXOXX
XXOXXXXXO
XXXOXOOOO
XXOOXOOXX
XXXOXOOXO
XOOOOXOOO
OOXXOXOXO
XXXXOXOXX
XXXXXXOXO
OOXOXXOXX
XXOXXXXXO
XXXOXOOOO
XXOOXOOXX) == ['YES', 'Yes']