from ..program4661 import program4661
def test19():
    assert program4661(10
XXOXOOOOXX
XOXXXOXOXO
OXXXOOXOOO
XXOXOOXXOX
XXOXXOXXOO
OOOXXXXOXO
OXXXOXOXOO
OXOXXXXXXX
XXXOOXXXXX
XXOOXOOXXO
XOOOOXXOXX
XXXXOXXXOX
OXOXOOOXXO
OOXXXXXXXX
XOXOXXOOXO
OXXXXOOOXX
OXXXXXXXXO
XXXXOXXOOO
XXXOXOOOXX
OXXXOOXOOX) == ['No', 'NO']