from ..program4661 import program4661
def test13():
    assert program4661(10
XXOOXOOOXO
XXOXXXXXXX
XOOOXOOXXX
OXOOOXXXXO
XOOOOOOOOO
XXOXXXXOOX
OOOXOXOOOX
XOXOOXOOXO
OOXOOXOXXO
XOXOXOXXOO
OOOXXOOXXO
OXXOOOOXOX
XXOOOOXXXO
XOOOXOXOXO
OXXXXOXOXO
XOOOXOOXXX
OOOXXOOOXO
XXXOOOOOOO
OOOOXOXOXX
XOXOXXOXXX) == ['No', 'NO']