from ..program4661 import program4661
def test15():
    assert program4661(10
XOXXOXXOOX
OXXOXOXXXX
XXOOXOXOOO
OXOOOOXOOO
OOOOOOOXOX
XXOXXOOXOX
XOXOXOOOOX
OXOXOOXXOX
XOXOXOXXXO
OOXOXXXXXX
OOXOOXXXXX
XOXOXOXXXO
OXOXOOXXOX
XOXXXOOOOX
XXOXXOOXOX
OOOOOOOXOX
OXOOOOXOOO
XXOOXOXOOO
OXXOXOXXXX
XOXOOXXOOX) == ['No', 'NO']