from ..program4661 import program4661
def test35():
    assert program4661(9
OXOXXXXOX
XOXXOXOOO
OOXOOOXOO
OOOXXOXOX
OOXOOOOXX
OXXXOXOOO
OOOXXOXOO
OOXOXXOXO
OOXOOOXOX
OXOOOOXOO
XOOOOXOOO
OXXOXXOXO
XXOXOXXOO
XOOOOOOXO
XXOOOXOXO
XOXOOOXOX
OOXOXOOXO
XOOXXOOOX) == ['No', 'NO']