from ..program4661 import program4661
def test32():
    assert program4661(8
OXOXXXXX
XXXXOXOO
OXOXOXOX
XXXOXXOX
OXXOXXXX
XXOXXXOO
XXXXOOOO
OXXXOOOO
OOOOXXXO
OOOOXXXX
OOXXXOXX
XXXXOXXO
XOXXOXXX
XOXOXOXO
OOXOXXXX
XXXXXOXO) == ['YES', 'Yes']