from ..program4661 import program4661
def test18():
    assert program4661(10
XXXOOOOOXO
XXOXOOXOXX
XOXXXXXXXO
XOXOXOOXXX
XXOOXXOXXO
OOOOOOOOXX
OOXOXXOOXX
XXXXOXXOOO
XOXOXXXOXX
OXXOXXOOOO
OXOXOXXOXO
XXXXXXXOXO
OOXXXOOOOO
OXXOOOOXXO
OOXOXOXXXX
OOXXXOXOXX
OXXOOOOXOO
XOXXOOXXXX
XXOOXOOXOX
XXXXXOOXXO) == ['YES', 'Yes']