from ..program4661 import program4661
def test16():
    assert program4661(10
XXXOXOOXXX
OOXXOXXOXO
OOOOXOOXOX
XOOXOXOOXX
XOXXOXOOXX
OOOXXOXOXX
OOOXOOOOXO
OOXOOXXOXX
XXOXOOXOOX
OXXXOOXOXX
XXOXOOXXXO
XOOXOOXOXX
XXOXXOOXOO
OXOOOOXOOO
XXOXOXXOOO
XXOOXOXXOX
XXOOXOXOOX
XOXOOXOOOO
OXOXXOXXOO
XXXOOXOXXX) == ['YES', 'Yes']