from ..program4661 import program4661
def test17():
    assert program4661(10
XOXXXXXXXX
OOOOXXXOXO
XOXXXXOOXX
XXXOXXXXXO
OXXXXOXOOO
OOOOOXOXXX
XOOOXOOXXX
XOOOXXXXOO
OXOOXOXXOX
OXOXXOXXOX
XXOXXOOXOX
OOOXXOXXXX
XXXXXOXOOX
XXXOOXXOXO
OOXOXOXXXX
XXXXOXXXXX
XOOOOXOXOX
OOOXOXXXXX
XXOOOXXOOO
OOXXOOXOOX) == ['No', 'NO']