from ..program4661 import program4661
def test21():
    assert program4661(10
XXOOOOOXOX
OOOOXXXOXX
OOOXOOOOXX
OXXXXXXOOX
XOOXOXOOXX
XOOOOOOXXO
XXXOOOOXOO
OOOOXOXOOO
OXOOOOOXOX
XXOXXXOXOX
XXOOOXXXXO
OOOOXXOOXO
XXOXXOOOOX
XOXOOOXOXO
XOOOOXXOXO
XOXOOOXOXO
XOOXOXXXXO
OOOXOOXOOO
XXOXOXXOOX
XOOXXXOOOX) == ['No', 'NO']