from ..program4661 import program4661
def test11():
    assert program4661(10
XXOOOOOXXO
OXOOXOOXXO
XOOXOXXXXO
OXXXXOXOXO
XXXOXXOXOO
OXOOOOOXOX
XOXOXOOOXO
OXXXOOOOOX
XXOOOOOXOO
XOXXXOOXXX
XXOXOXOXOX
OXXOXXXOXX
XOXXOXXOOO
XOXOOOXXOO
XOOXOXXOXO
OOOOOXOXOO
OXOOOOXXOO
XXOOXXOXXX
XOOXOOXXXX
XOXOXOOOOO) == ['No', 'NO']