from ..program4661 import program4661
def test14():
    assert program4661(10
XOOOOXOOOX
OOOOOOOXXX
OXOOOXXOXO
OOXXXOOXOX
OOXXOOOXXO
XXXXOXOXXX
XXXOOXOOOO
XXXXOOXXXO
OXXXXXXOXX
XXXOOOXOXO
XOOOXOOOOX
XXXOOOOOOO
OXOXXOOOXO
XOXOOXXXOO
OXXOOOXXOO
XXXOXOXXXX
OOOOXOOXXX
OXXXOOXXXX
XXOXXXXXXO
OXOXOOOXXX) == ['YES', 'Yes']