from ..program4661 import program4661
def test9():
    assert program4661(10
XXXOOOOXOX
OOOXXXOXXO
XOXXXXOOXX
XOOOXXOXOO
OOXOOOOOOX
XXXXOXOOOO
XXXOOXOXOX
OOOOXOXOXX
XOXXOXOOXO
OOOOOXOOOO
XXXOOOOXOX
OOOXXXOXXO
XOXXXXOOXX
XOOOXXOXOO
OOXOOOOOOX
XXXXOXOOOO
XXXOOXOXOX
OOOOXOXOXX
XOXXOXOOXO
OOOOOXOOOO) == ['YES', 'Yes']