from ..program4661 import program4661
def test20():
    assert program4661(10
XOXXXXXOOO
OXXOOXXOXX
XXXXXOOXOX
OOOOOXOXOX
OXXOXXXOXO
XOOXOXXXXX
XOOOOOOOOX
OOXXOOXXXX
OOOOXXOOOX
XXXXXOOOXX
XXOOOXXXXX
XOOOXXOOOO
XXXXOOXXOO
XOOOOOOOOX
XXXXXOXOOX
OXOXXXOXXO
XOXOXOOOOO
XOXOOXXXXX
XXOXXOOXXO
OOOXXXXXOX) == ['YES', 'Yes']