from ..program4661 import program4661
def test10():
    assert program4661(10
XXOXXOXOOX
OOOOXOOXXO
OXXXOOXOOO
OOXOOOOOOO
XXXOXOXXXX
OXXXXOXXOO
OXXXXOOXXX
XXOXXOXOXO
OOOXOOOOOO
XOOXOOOOXX
XOOXOOOOXX
OOOXOOOOOO
XXOXXOXOXO
OXXXXOOXXX
OXXXXOXXOO
XXXOXOXXXX
OOXOOOOOOO
OXXXOOXOOO
OOOOXOOXXO
XXOXXOXOOX) == ['YES', 'Yes']