from ..program522 import program522
def test8():
    assert program522(10 10
SSSSSSSSSS
..........
..........
..........
..........
..........
..........
..........
..........
..........) == ['90']