from ..program892 import program892
def test27():
    assert program892(500
lkuvqevrlanaugfoadmkdqpljknwfoftofyxcvsfvprqxuwkfwunfilaqrzqhsjhsaoynbsuiqyzwqfkmbddngwydhrtimoerqpehjsgqojuhtxvaayzsbxmsqckibtcangzdnnpcpqkqgzbzbeaejuhprrqxdhyfrtzwhvnnrfocwrwfzbgtvdpwlkrqisjqpszykzhfjrstcvmmnebwgvwxsppyxihkepmndwgtzlsurasjfrkqqnxjqdsbmsggakyuouevxdxuwyxbhkmvpjqvoklaknxsmzqpjrftvzifnqjporbvtpdnzfhckjnwgeddpjycnqrtphjhqkfvpoerzkilpjuteidflpulppotglglarrwopryxbjjsroguskwzalrmasgcioovteyuukwnosswdwnqmrbdkssgnkaivtufoayaxgqpprnoyvoeqqpywboofudtutiweaaqzbneqmxgnfkxdnjdbijlveapyrybiw) == ['358']