from ..program892 import program892
def test17():
    assert program892(500
dicdkeichmcjhbnkiglmnephogelfohjboiihaocmpaemlmbgjdaoblkkomngcelapdlmophamcnjihpfhadhaddhbinpinepkcnjpndfeiepiocepbdjchcenilbaccopfnpciglfcknjbmdbhcdgihbeniklehnonlnhooabbodnbmdoaafnedpffdnibdnijidpbngidabdncdfolpfnenbcmhhlenmjcbiacmilahlfpdgafcacnlgedkicmnknliemncdgoggjcdbhnmneljgjjemekndgdhddoiiflndklehceancaiadnicdoofciodhgphjgmchkehailolkhfbpdkoipcemoghegbbpedaafbeloccmgddphefjakjofldineohdgflhflmkiedfmkocbjablcofcmdfconlmhoiehlobdbfpelhaindhamnmbenldbmefgkmhjlloeendgdbeafncjohclenmdeppemplf) == ['331']