from ..program892 import program892
def test26():
    assert program892(500
jqpyiogllhoobjixnlhskgwowfrhkuotvjbmgatrspqreavqwsuljxqduutxudueenmvarsmqqaqxohtsmxdqdhcvydhuiqcchvvxroqieeffipvlumywcthdafsgnwyamumpknqittxakhlbrbhrtcfbrkvjrypxqochjnmyihuqtrrbgiiytifqeqbnssrmywtdghpekqjxkvoefiwpbepqstotqyiohuawpvawephiexxnofiipkwmshhyaprhrryspbvfoasagdldqeasajhqsurmduuusiwgyuroimbyfjogkxcgjorxpqblhtwvlgognnvisqdkheurkikjcgmoyvafiqhfcbmgmybefsmkroftstqmhkfkuxufghjhveuhhkecushenjqyvqhxcfqdcbkxufhxpbamaowjnuaxjcsuuryvjtnwrhwiurrsehusxwrjwsotefacjxjanphxngylkmjbvhfqghtlnlvdbcnkfjd) == ['350']