from ..program892 import program892
def test44():
    assert program892(500
cdbdadbdcabdcbdbaadacaacbbbbcdaccddbdbbdabccacbaacdbbdcbddadabaaccbabccabadddbdcdcdddbbcbadddcabcddcdbabacacbdbcaadacbbbdccbcabacdbcccbdccbaacddaaaabdacbdccbbbbcaabbbdabadadacabdbbaaacadcbaacadadbbdbcdabcdabccacbdcaadaccdbdcaccaaddacddccdadddddddbacaccdbbbbcbbabbdcacbcaacaabdddbdccdaddcddbbaabaabdbcccadcacbdacabcdaddaabcbcaadabadbdaacacacaaddbbbcabccdbbcbaccbadcddaaccdbacaabbcdbcbdbcbacacdccccabaaabbcbccdcaabcadcaccadbbbcccabbbcdbaccaabdcbcdbcdcaddaabcdacaddcccaddabcbabdcabbdbaaaccbbabcdaddbbccd) == ['194']