from ..program892 import program892
def test63():
    assert program892(500
abfaaffaaebbefbabfefacdddddafbbabdacebeeccfabcfaebaeabbfabfcceddbdaadeddbffcfedaebecbaccdfbfafabfceffceeaccdfebbdbdafdebfcafebededcfbbaefefcbefdfabdefafeaccdfaeeacdacddccfcfcadbafbdbbdfcfecfeaffdcceccabcfeaddabfbaddebdecdfabebaeefefecedeeadaeedcfabcbcfbfaadaddaabeedfdccbbfeffccfcceddebecabacaedaaceedfddebbeaefbbcfdcdcbdfadadfefcaaffdfeedbcaebccdfecbfccacadccecbdcbdabbeaebdcedfbfaffbccbeaeebacceedceaabebeddbeedbfafeecdfdceebaaecabbefcabbaffdacfcebdbfffeadabddccaebdeffaacfdfcfdffabeefaecafaccabfbd) == ['236']