from ..program892 import program892
def test11():
    assert program892(500
cachgdaghedbbfbcbicbabfcahhbeaafeaafgcaafcabeabccbbbjhjbjcabcfdcbjedeaijeebcabbfaiicebgfbchcaeachceigihhbifcdgdfhdjabjajfhhfajddghebbdiegadfahdahddfdeaagjfgafhjhfbeehbgahgeefggdgdcfcifagibijcgifehjccfggajjfajecbffdedfhgebfefibeiceigcddfjhgcghbbhjbhficggfighjdijjefcjchdihgfdcjgeeeiicihfdhbibijhgjdgdhcafdaafbfgjgcggidgebchbejiidjgbfcbcjejgfgeiaaebeajhdaijhgbebeefchahbbgcgegieagcdahgdfbidehbfafbigadjdedhdhaegbbcgifeahgchiafffjgfgaajjhedbiffbbjdijehdfiegiabeadfcifcbjjhidiieebaiffdjfhfidffgfchchegjed) == ['281']