from ..program892 import program892
def test37():
    assert program892(500
bbabcacccbcbbcaaacacabababbbcacabccacbabcacccbccbccbabbbbbbccbbaabcccacabccbaaccacabaabcabcacbcccbaacccaabcacacaacabccbabccccbbaababcccbacbcbaacbccabbbbacbaabaccccccababcababccaabcbaaacacaccccbaacaabaacbaccacaacccabbbcabababbcabbacbccabbaaaabcabaabbbbaacacabbabcbaccbcbbcaaaaaabccccacacaaabccbabacacbcbbccacbacbccaacabcccbabbccbbababbccabcccbbbacabcbabbbcbbcbaabcaccaccaccaabbccaacaaccabbabcbccaccbcbbbcabcabcbbacccbabcbababcbbcacbbbabbacbcbbbaacccbbbaabbcaaabbbaccbaabcacbccbacabacacaaaaabcbacacccaa) == ['176']