from ..program892 import program892
def test35():
    assert program892(500
ccbbbaaaabaccacaccbbccabaacbbcaacbabaabcaabbaaabacbccabbccbbbccbcbccbababacaccaabbaacbcbccaccccccbaaabbbbccbacabaacbabbbccaabaccabbbaabaaacaccaacbbacbbaacabaccbaccbccabbcbcccacaccbaabcacbabbaabccbaccbcbcbccbcaabaacbbcaacabcacaaacaaccccbcaaaabaaabaabbbcbbbbaabcbcbbbacbaacbbbbbaacbcabccbcacaacbbcbcbbbacbbcacbbbbabacaccbaaaacaaaabbcbcbaaccabbacccaabbabbacbccbacbaabbabcaababaaaabaacabacbaabccbbccbababbbcbacbbbcabacccacaababbabbcaaaaccababbacaacbcbbcaccbcaabcbcccacccabaabaabbcccabcaccbbcbccccbcacbaba) == ['170']