from ..program892 import program892
def test41():
    assert program892(500
ccadaaddabcadcccbbbcbdaacabcbbcdacaababdbbdccdcacccbbccccadcdcddaccbaaababbacadcabaacbccaabbbdbcbcbbacaaaaababcddadcbddcccbabdabdabbbacbccaccacdacadbbbbcaccccbdcccaabbcaacbcdddcdcdcbbdabadbadadcacdbbbaaaadbcbbabdabcbcbddaccabdadabdbbabcbdcdbdccababcbadbdcaacbddabdadcdbddbdcdabddbdaccadacabddccbbdcbacdbbcbcbdbabbcbadddacddcddccaaaaacabccccccbdbdccacdcaaaababccbbddbbaadacdcbbbadccaacaaccaabbcbabdcdccdcbbbbcdaccbbdccabcbdbacadcbdcdcccdaaccdddbbbcbadcccbacadadaddaabdbacbcdbaadbaaabdcbcdddbcdbdbacdcb) == ['193']