from ..program892 import program892
def test32():
    assert program892(500
aacaabcbaaacbbaacbccbbaacbabbaaabcacbcabaaaaaacccbabcbbbacaaacabbbbaaacaacaacbbbbbabccbcbabcabccbbaabccbccacccacbcbaaaaaaababbccccccacbaccaabcaccbacbccbacccacbacacbaabcabbbcbcbaaabbabbbbbcabbabcbbaabbcacccaaacaaccbaaabaccbaabbbababbabbbcababbcbbaaacacabbcccaaabcccabbbaababbacbaaccbbaabbcabbbbcabcaccbcbcbbbcabccacbcabbaacabbccccaacbbbbaccccbcabccbccbccbccacabaabbbbcbcbacabccbbcbaabacbacbacaabbcacbcacccacbbbcabcccabacbabbcbbacabcbcacbaaabcccaaaccaccaaccbbcabbbbbccaacccacbcccaaccaccaabaabcaabaacaac) == ['163']