from ..program892 import program892
def test13():
    assert program892(500
dkhedelgflihgabkcjkjdjggkfahheklbffhaidljfikfjgbckejfahehkiieflelcifagakijiajjhhdglhibeaagehkiihcjgijlfdaejaacehejbilefhgijeebfefgbccfgdebkledbjbjilcggaiekacehlikekdcebeidhfbdgkahifgilhcdbikbfdlheefgbebikfcbihjlliegabgfjlbdallhjgdahffcdcblbjekfijalefkaklfglggaikcacllhdcfilbkbelcfdgaafahhdkcjgafddhfaijakffdhfafbgfhlaccbhjlaeaaajfaagdhfehdiflehghfiidjcachclgddkkgkllcdldekgflakgalekefffakklgjejjlfjblkjilhfdckahbedeckhfefkfjlgaflffgfkkhacchgjceelechdceehfhjbecgiflajlechkldhjgbeeijbadikbhiddjjbfficfa) == ['300']