from ..program1754 import program1754
def test112():
    assert program1754(....X.....
...X...O..
..X...O...
.....O....
X...O.....
..........
..........
..........
..........
..........) == ['YES']