from ..program1754 import program1754
def test108():
    assert program1754(X.XX..XXXX
..........
..........
..........
..........
..........
..........
..........
..........
OOO.O.O.OO) == ['YES']