from ..program1754 import program1754
def test10():
    assert program1754(......X...
..........
..X....X..
....O.....
..........
O.........
.....O...X
..........
..........
O.........) == ['NO']