from ..program1754 import program1754
def test131():
    assert program1754(..........
..O.......
...O......
....O.....
.....O....
..........
.X........
..X.......
...X......
....X.....) == ['YES']