from ..program1754 import program1754
def test54():
    assert program1754(..........
..X.......
...X......
....X.....
.....X....
......O...
..........
..OOO.....
..........
..........) == ['YES']