from ..program1754 import program1754
def test109():
    assert program1754(O.........
X.O.......
X..O......
X...O.....
X.........
..........
..........
..........
..........
..........) == ['YES']