from ..program1754 import program1754
def test114():
    assert program1754(......XXXX
..O.......
...O......
....O.....
.....O....
..........
..........
..........
..........
..........) == ['YES']