from ..program1754 import program1754
def test144():
    assert program1754(.......XXX
X.........
..........
..........
..........
..........
..........
..........
..........
......OOOO) == ['NO']