from ..program1754 import program1754
def test136():
    assert program1754(XOXXX.....
..O.......
...O......
....O.....
..........
..........
..........
..........
..........
..........) == ['NO']