from ..program1754 import program1754
def test139():
    assert program1754(X.........
X.O.......
O..O......
X...O.....
X.........
..........
..........
..........
..........
..........) == ['NO']