from ..program1754 import program1754
def test14():
    assert program1754(....X.....
...X.OOOO.
..X.......
.X........
..........
..........
..........
..........
..........
..........) == ['YES']