from ..program1754 import program1754
def test86():
    assert program1754(.O........
..X...X...
...O.X....
....X.....
...X.X....
..O...X...
..XX...O..
..OOO.OO..
..........
..........) == ['YES']