from ..program1754 import program1754
def test0():
    assert program1754(XX.XX.....
.....OOOO.
..........
..........
..........
..........
..........
..........
..........
..........) == ['YES']