from ..program1754 import program1754
def test125():
    assert program1754(.....OXXXX
..O.......
...O......
....O.....
..........
..........
..........
..........
..........
..........) == ['NO']