from ..program1754 import program1754
def test107():
    assert program1754(X.........
.OO.......
..XO......
...XO.....
....X.....
..........
..........
..........
..........
..........) == ['NO']