from ..program1754 import program1754
def test138():
    assert program1754(..........
.......OX.
......OX..
.....OX...
....OX....
..........
..........
..........
..........
..........) == ['YES']