from ..program1754 import program1754
def test111():
    assert program1754(X.........
X.O.......
X..O......
X...O.....
O.........
..........
..........
..........
..........
..........) == ['NO']