from ..program1754 import program1754
def test116():
    assert program1754(..........
.....OOOO.
..........
..........
..........
..........
..........
..........
..........
......XXXX) == ['YES']