from ..program1754 import program1754
def test44():
    assert program1754(..O.......
OO.O......
......X...
..........
....X.....
...X......
..X.......
..........
..........
..........) == ['YES']