from ..program1754 import program1754
def test47():
    assert program1754(..........
.....OOOO.
..........
..........
...X......
..X.......
.X........
X.........
..........
..........) == ['YES']