from ..program1754 import program1754
def test153():
    assert program1754(.OOOOXXXX.
..........
..........
..........
..........
..........
..........
..........
..........
..........) == ['YES']