from ..program1754 import program1754
def test23():
    assert program1754(..........
..........
..........
..........
..........
..........
......X...
OOOO...X..
........X.
.........X) == ['YES']