from ..program1754 import program1754
def test34():
    assert program1754(..........
..........
..........
OOOOX.....
..........
..X.......
.X........
X.........
..........
..........) == ['YES']