from ..program1754 import program1754
def test35():
    assert program1754(.........X
.....OOOO.
X.........
.X........
..X.......
..........
..........
..........
..........
..........) == ['NO']