from ..program1754 import program1754
def test150():
    assert program1754(..........
..........
OXXXXOOOO.
.........X
..........
..........
..........
..........
..........
..........) == ['NO']