from ..program1754 import program1754
def test85():
    assert program1754(O.O.O.O.O.
..........
..........
..........
..........
..........
.XX.......
X.........
X.........
X.........) == ['NO']