from ..program1754 import program1754
def test148():
    assert program1754(OOO.O.....
..........
..........
..........
..........
.......X..
..........
.....X....
....X.....
...X......) == ['YES']