from ..program1754 import program1754
def test46():
    assert program1754(XXOXXOOO..
..........
..........
..........
..O..X....
..O.X.....
..OXO.....
..X.......
..........
..........) == ['YES']