from ..program1754 import program1754
def test50():
    assert program1754(..O.......
OO.O......
..........
..........
..........
..........
..........
..........
..........
XXX.X.....) == ['YES']