from ..program1754 import program1754
def test135():
    assert program1754(O.........
.XO.......
..XO......
...XO.....
....X.....
..........
..........
..........
..........
..........) == ['YES']