from ..program1754 import program1754
def test104():
    assert program1754(XXXXO.....
..O.......
...O......
....O.....
..........
..........
..........
..........
..........
..........) == ['NO']