from ..program1754 import program1754
def test9():
    assert program1754(..........
..........
..........
..........
..........
X.........
.........X
..........
..O.......
.O...X...O) == ['NO']