from ..program1754 import program1754
def test126():
    assert program1754(XXX.XXX...
OOO.OOO...
..........
..........
..........
..........
..........
..........
..........
..........) == ['YES']