from ..program1754 import program1754
def test127():
    assert program1754(....X.....
...X......
..X.......
..........
X.........
OOOO......
..........
..........
..........
..........) == ['YES']