from ..program1754 import program1754
def test64():
    assert program1754(O.....X...
.....X....
..........
...X..OOO.
..X.......
..........
..........
..........
..........
..........) == ['YES']