from ..program1754 import program1754
def test146():
    assert program1754(XXXX......
..O.......
...O......
....O.....
.....O....
..........
..........
..........
..........
..........) == ['YES']