from ..program1754 import program1754
def test17():
    assert program1754(..........
..........
..........
.OOO.OOO..
.XXX.XXX..
..........
..........
..........
..........
..........) == ['YES']