from ..program1754 import program1754
def test151():
    assert program1754(X.........
X....OOOO.
..........
X.........
X.........
..........
..........
..........
..........
..........) == ['YES']