from ..program1754 import program1754
def test76():
    assert program1754(..........
..........
......XXXX
..........
..........
..........
..........
..OOOO....
..........
..........) == ['YES']