from ..program1754 import program1754
def test32():
    assert program1754(..........
..........
..........
..........
..........
X.........
X.........
X.........
XOOOO.....
..........) == ['YES']