from ..program1754 import program1754
def test71():
    assert program1754(......XXXX
OOOO......
..........
..........
..........
..........
..........
..........
..........
..........) == ['YES']