from ..program1754 import program1754
def test73():
    assert program1754(OOOOX.....
..........
..X.......
.X........
X.........
..........
..........
..........
..........
..........) == ['YES']