from ..program1754 import program1754
def test72():
    assert program1754(..........
..........
..O.......
...O......
....O.....
.....O....
......X...
.......X..
........X.
.........X) == ['NO']