from ..program1754 import program1754
def test134():
    assert program1754(....X.....
...X......
..X.......
.X........
..........
..........
..........
..........
..........
......OOOO) == ['YES']