from ..program1754 import program1754
def test25():
    assert program1754(....X.....
...X.OOOO.
..X..OOOO.
.X........
..........
..........
X.........
X.........
X.........
X.........) == ['YES']