from ..program1754 import program1754
def test90():
    assert program1754(.....OXXXX
..........
..........
..........
..........
..........
..........
..........
..........
......OOO.) == ['NO']