from ..program1754 import program1754
def test81():
    assert program1754(..........
...X...OO.
..X....OO.
.X........
X.........
..........
..........
..........
..........
..........) == ['YES']