from ..program1754 import program1754
def test129():
    assert program1754(XXXXOOOO..
..........
..........
..........
..........
..........
..........
..........
..........
..........) == ['NO']