from ..program1754 import program1754
def test28():
    assert program1754(..........
X.........
.O........
..XXX.....
..XOXO....
OXOOOO....
X.........
..........
..........
..........) == ['YES']