from ..program1754 import program1754
def test56():
    assert program1754(.....OOOOX
.XXX......
..........
..........
..........
..........
..........
..........
..........
..........) == ['NO']