from ..program1754 import program1754
def test154():
    assert program1754(XX.XX.....
..........
..........
....O.....
..........
......O...
..........
......O...
........O.
..........) == ['YES']