from ..program1754 import program1754
def test118():
    assert program1754(X.........
O.O.......
X..O......
X...O.....
X.........
..........
..........
..........
..........
..........) == ['NO']