from ..program1754 import program1754
def test2():
    assert program1754(XO........
.XO.......
..XO......
....O.....
....X.....
..........
..........
..........
..........
..........) == ['YES']