from ..program1754 import program1754
def test1():
    assert program1754(XXOXX.....
OO.O......
..........
..........
..........
..........
..........
..........
..........
..........) == ['NO']