from ..program1754 import program1754
def test63():
    assert program1754(XXOXX.....
.....OOOO.
..........
.....X....
....X.....
..........
..X...O...
.X......O.
X..O..O...
..........) == ['YES']