from ..program1754 import program1754
def test132():
    assert program1754(....X.....
.......O..
..X...O...
.X...O....
X...O.....
..........
..........
..........
..........
..........) == ['YES']