from ..program1754 import program1754
def test119():
    assert program1754(X.........
X.O.......
X..O......
X...O.....
.....O....
..........
..........
..........
..........
..........) == ['YES']