from ..program893 import program893
def test39():
    assert program893(500
cbbdbdadbadbddaaabbaadbcaadaaabcccdacdcbaabcbadbcaccdccbacacaaadcaaccacbcccacdbcdbdabbcbacbadbccadabccccaacdccdcdcdaccccddbabdaccdabbcbaaacacdacccdbcbbbccaccdaddbddddadabbcbbaabcbdcadbdbdaddabaaccabcaaddbdbacddddbbacacbacbdaaadcbacbcdacbbddbcbaddbbbabbbbcbdcaaabdaadbdbdbabcbcbcaaaacaabddbaacadcbbbacbdccbabbbcdbdabdbdaccadcccbcbbadadccacdcbacaacaaccaddccdacdbbbcadbcdcccdbdddcbccccabdadcaaabddddaabcaddcddaaccdcbacacaabacacbcadbadbbbadbbaccddcadaaabbcadabdcaabbbcbbaacadbacdacdbbcdaacadbdaacbabaacdd) == ['196']