from ..program893 import program893
def test60():
    assert program893(500
aaafbfcaaeeeadcaebfffbfdaccaccfceaccaebecbefbbfeafffecaaeeadefcdebddaebcccfffdfacbffeeeacdbbeebdcadceabbccecfcdeebfeafbadaadcaaefcececdedccefcadbdbeaffeebeccabacbeeaacbeefdafeaecedfacadceabaffffdcfbbdfdbbeddddffdfabfecafcefaaaafeacefdfdfccabeecaeeefcecdfdacadbffdcaabdecaededeadbdfeadcaabbfbccbcfeccbecedbcdebbbabebbcfeaaacdaecdafbaacdbfefabebcafedacbbabadaeeaffebcdcabefbfdbbaaddacfafadbecbbcddcafcaefbefeffbbebeaaefcfafffacbdacadbbfadeececcaafcaadacdbfefaddefebaeebefadcdccddaaccebdaafffefeeddbacae) == ['230']