from ..program893 import program893
def test52():
    assert program893(500
acdccbcdabcabdeaceeacabdebeccabcabcaeaadeaaaaecdeecbaecdeebcaccdacddeabedbddcbbdbabbddaeeddebebdecceeebbcaecadbedbaaccadcacbbcbebceabbddbbccdcdcddebbdbbdebbcbbdadbedebacaecabbbedccebcaecbceadaeabbaeecceacaacbeaebdbaeedabbebbaaadeceabeccccbadcebbeccdeadddedcdeebcaeedddbdcccddbaeabeeacddbdcdbaebeedbdeadbcabaaeabcbeeadcabddeceedaececdadeadabdbabcbbeeaabddcbbdeeeeeacdebdbdcacbcdacdbccbbccdeabecedbadddebbcdccedaebacaedcdbceadbeababbcbdaccdecbbeaeedbdceebadeadbdccaccccdbdcdddaedaababcaeeaddbdbaabeaaaa) == ['217']