from ..program893 import program893
def test51():
    assert program893(500
bdeadccaedebabcdeadedebdcacdcaebdeeadedbdccabeaddaaabdaeedbecdcbeacdaceeccdebecabeaedebdadadddccaabddeaddaddedaebccabeccbeeceeaecbaaabccabdccdbeeebcbccebbaeebcdcaabdabcabadbccdcbdebdabbeeeccddaadedddbddeebdacacddcaddccbebbbaeddcecccabcacceadacbdabaddbebbaecebeebabeabaddbbdddbddacaddedbaeaeedcccccbdbcdcadccaadabaacbeaddcabcccacabcdcaabadacdccabcdaceeacbbeeedeacbcaaabeaacaabaccdbddeabdbdabccdceeecbeeeecdddacbbebceaccdbccabebedaeceadaacaebacdaeceeacedbadebeadaaebaebcadcedabecdbedbbadbccabadbbcbcbda) == ['219']