from ..program893 import program893
def test43():
    assert program893(500
cddcdcbddbbdaaaabcbacccdabaacbcaddcbbcaadcbdadbacdbbddccacbcbabdcbabcacccadbdcbcbbbaabcddbbcabddbabccddcbabdbdbbdbdaaaabbbaaccaaaabacddcdacdccabbcbbdbcbdcdcdbbdbcaabacaacdadbdccacdcddbabbcdcbdcbdbdcbdbccddcabdaddacddabcdcdaacbbaacdabcbccabacadabcdcdcdbbcccbcddbdacaaddadbbbcbcbacccacadcacdbdabbabccbbcaaadcabadaaadbbbdbdbbdcababadbbdcddbcbcddbdbaadbbbbcccbccdcaabbdbaabacabacdbcbcbbaacaacaabbadaddbbcbdcdcdcabbcdacdbcacabddbadccbdcbadbdddbdaccbcabdabddbddccaacdcbccadbdaddcabaadcccdddabdaacbaacadadba) == ['201']