from ..program893 import program893
def test55():
    assert program893(500
bbcbdedcadacabdcbacdabcedeebdbdeddedccceedcececcebddeacaeddbaabbaaaedccccabdccbbeacebbdecbdbaecabceedcdecdebbbaecddbbcecbbeaddbcdaddaecddeceeeedbcccedbabbdccbceecbccaebbcccbacdaeeecdedacbacabdceaaabcacceedeadeebbeeceebaeebcaddecccdeedeecaacebddedeeddccacccdaaaebecdbcbdcbaddceacbbedbcabbbedcadadbcbeeecaceddabdabeabbabddcabdecabdeccccaabaeebcddebdcdbdccccdecacaeccccbddcabbbeadccebddbccbcbecbaedabcdcceeabadbcabddecbccbdabbcccdebbaebbebadaceaceaebbbeaabeedeaabbdaadccdabbcbabcdceabdeabdaebbddedecdbcc) == ['216']