from ..program893 import program893
def test29():
    assert program893(500
cccaaccbcacbacccbcccbcabcccaaaaaabbccbbbacbacaaacbbcbbacaacbabababcaaacbcacacbacccccccbcccaaabbabccbccbcaabbcaccbbbbbccabcacccabbcbcacbcabaccabcbacacbbbcbaabacbcbbbbbabcbcabbccbbabbbbaccacaacabcacbacaaacacbbbccbcbaccaabbbcbcacbaaacaccaaabccbbabbaaabbbabacbaccaabbbaaacbacaabbaaaacccabbabbbcbcacbcccbbacaccacbcccacabbaabbbaaabbcbacaaaabbcccbacbbbaacacccccbccabbbaababbacccabaaabccbbccbbbbccacbccbcbbbcacaabacbcabaaababbaacaccbbbacbcabbbcacbaccacbcabbbcccbabbabbcaacbcbcaabaaaccacababbbaacacbbbcbabbcac) == ['164']