from ..program893 import program893
def test46():
    assert program893(500
caadabddbaacdabdbadcadcadbdcdaadaaabcdbabcadcbaaadcadacbabcddacaabcadcabaabdddbcbcadbbbdabdabacbccddcbcdacbacbadabdcbccacbcbcabdcdbcdacadaacaabbbabbddbcccdcbabbbbcbcaacbdadacbdbabbabcaacdacbadcccbadaaabdbcbdbdadbddcdbdbcbccbbadbaaddcaaddadaaaabababdbbaddbadddbcaabcadbcacccadbdaaabcdcdbddcbbbdadaadbddddbdbacbccdaaabbdccaabcbbbaadaccdcbccdcabdccccabbbbadddccadddcbdddaddbdcaccbaadadbbdcaabdcdaacadddadbbbdadcdcdcbbabdcdbdbdddababaaabcdcbdccabbcaabbccadcdbdbbcdbbaabadacdaccaabbdabdcdbabcdbcbdacdbdcbc) == ['204']