from ..program893 import program893
def test20():
    assert program893(500
cdmkfpciphakoplkedblrkgkeopflkqhokgfiehpjdbbjidapefhognhgheikdbaepqasmfdsbkdbbjaesoikmglimmabfbsreakbpnhsclohfbaqamjlhhaiqchpoaibqldehsprprscrinsdgrlsmidkdhbsgqnlhlbldrnqhgfhmcsmncqmohkcbkgnbrofccliqjpqdpesfnabndkkklmoemsfksqmjajbgheijcgjiinppnpqlilarocbphlogqrmcheflskedeomfsjkoojfjsdoibiadoeickchjhssjaqhsnbnahqcqnelemollsncrfhjrngeighcqirbphqharlgiblchqjgblkfemlhofrjjceeerolsndsncjksanpkcqiopkmqmlfginppbhkbbdshpbjblheolofkpcjjeedholrqklhiiohmdjbbseclssdlcbkjribjggfggsljidsngsgjpankfckidrpsjsgaq) == ['335']