from ..program893 import program893
def test22():
    assert program893(500
raqqhocfiosbkfjtbjnbatojfmummlrghpkmcghfagdmmkbesdhtelromtkmdmltiljttepgeqdlhtgkpgljrmqjjtmretsdincjjqilahapcjcdlkrftoaeramgrudjbtpjblaksjjjburngarjitmebjiotofctgppktkqkianmucafsspbefuijcmsqamuenlrfrunfhgfqjhkjgrdjrkjgbpifadsjabktgdsgjsslipnqncbdfaphfndssljbthhcrfoijilodnuosmirctsjbhtlbehnljqcjdahcmjqsursqemcmtbgdaegdugqskskfdcffuilthtnjfhujgpifckubajoorllaruqfmbgrcutjushbflsqeiqdddenhurmunhsqqnbsfnjhgdodhmdugisalahiiedmhcgudjfhuumtlndkneauikebmgnrbdmegeotncdllcmmqfudldikeasisllapabefdubasndtobm) == ['339']