from ..program893 import program893
def test33():
    assert program893(500
abaabaccacaabbcbacbbbbaaaaacabaaaabbcbcbcccbacabcbabbccbcabacababbbbccbaaccaaccbacbbbbaaabacbbaccabaacacacabcbbcbbcbacccccaccbbacbbcbababaccbbbabbcbcbbbaccbccbbbcccbcbbacacabcccccbbaaaabbbcabbcaaacaccbaabacacacccabcccbabcbbabbaabaababbaaacbccbacacbcaabacccbaacbacabbbaaccbcbbcaaaabcbcccbcbcacabbbbacbbcaccaabbbcaccacbaacbcccbbbbbaccccacabcccccaabccabacabaccbbbaabcaaccacacccbaabbabccbaabbbbbababaaabbbbbaacbcbacaacbcbcbaacbcaacbbcaaacccccbbbbabaacbccbabacabcccabacacacbcaaababcbbcbacbccaabcccaabcbcbc) == ['170']