from ..program2513 import program2513
def test9():
    assert program2513(15) == ['ROYGBIVROYGBIVG', 'ROYGROYGROYGVIB', 'ROYGBIVROYGBOYG', 'ROYBIVGBIVGBIVG', 'ROYGROYGROYGBIV', 'ROYGBIVOYGBOYIV', 'ROYVGBIVGBIVGBI', 'ROYGBIVGBIVGBIV']