from ..program2513 import program2513
def test15():
    assert program2513(21) == ['ROYVGBIVGBIVGBIVGBIVG', 'ROYBIVGBIVGBIVGBIVGBI', 'ROYGBIVROYGBIVROYGBIV', 'ROYGROYGROYGROYGROBIV', 'ROYGBIVGBIVGBIVGBIVGB', 'ROYGROYGROYGROYGROVIB', 'ROYGBIVOYGBOYGBOYGBIV']