from ..program2513 import program2513
def test22():
    assert program2513(34) == ['ROYGBIVROYGBIVROYGBIVROYGBIVROYGBI', 'ROYGBIVGBIVGBIVGBIVGBIVGBIVGBIVGBI', 'ROYGROYGROYGROYGROYGROYGROYGROYBIV', 'ROYGROYGROYGROYGROYGROYGROYGROYVIB', 'ROYVGBIVGBIVGBIVGBIVGBIVGBIVGBIVGB', 'ROYGBIVROYGBIVROYGBIVROYGBIVGBIVGB', 'ROYGBIVOYGBOYGBOYGBOYGBOYGBOYGBOIV', 'ROYBIVGBIVGBIVGBIVGBIVGBIVGBIVGBIV']