from ..program2513 import program2513
def test11():
    assert program2513(17) == ['ROYGBIVROYGBIVOYG', 'ROYGBIVGBIVGBIVGB', 'ROYGBIVOYGBOYGBIV', 'ROYVGBIVGBIVGBIVG', 'ROYGROYGROYGROVIB', 'ROYGBIVROYGBIVGBI', 'ROYGROYGROYGROBIV', 'ROYBIVGBIVGBIVGBI']