from ..program2513 import program2513
def test10():
    assert program2513(16) == ['ROYGROYGROYGRVIB', 'ROYGBIVROYGBIOYG', 'ROYGBIVOYGBOYGIV', 'ROYGBIVROYGBIVGB', 'ROYGBIVGBIVGBIVG', 'ROYGBIVROYGBIVYG', 'ROYGROYGROYGRBIV', 'ROYBIVGBIVGBIVGB', 'ROYVGBIVGBIVGBIV']