from ..program2513 import program2513
def test18():
    assert program2513(24) == ['ROYBIVGBIVGBIVGBIVGBIVGB', 'ROYGROYGROYGROYGROYGRBIV', 'ROYGBIVROYGBIVROYGBIVOYG', 'ROYGBIVROYGBIVROYGBIVGBI', 'ROYGBIVOYGBOYGBOYGBOYGIV', 'ROYGBIVGBIVGBIVGBIVGBIVG', 'ROYGROYGROYGROYGROYGRVIB', 'ROYVGBIVGBIVGBIVGBIVGBIV']