from ..program2513 import program2513
def test4():
    assert program2513(14) == ['ROYGROYGROYBIV', 'ROYGBIVROYGBIV', 'ROYVGBIVGBIVGB', 'ROYGBIVOYGBOIV', 'ROYBIVGBIVGBIV', 'ROYGROYGROYVIB', 'ROYGBIVGBIVGBI']