from ..program2513 import program2513
def test16():
    assert program2513(22) == ['ROYGROYGROYGROYGROYVIB', 'ROYVGBIVGBIVGBIVGBIVGB', 'ROYGBIVOYGBOYGBOYGBOIV', 'ROYGROYGROYGROYGROYBIV', 'ROYGBIVROYGBIVROYGBOYG', 'ROYBIVGBIVGBIVGBIVGBIV', 'ROYGBIVROYGBIVROYGBIVG', 'ROYGBIVGBIVGBIVGBIVGBI']