from ..program2513 import program2513
def test13():
    assert program2513(19) == ['ROYGROYGROYGROYGBIV', 'ROYGBIVROYGBIVGBIVG', 'ROYGROYGROYGROYGVIB', 'ROYGBIVGBIVGBIVGBIV', 'ROYVGBIVGBIVGBIVGBI', 'ROYBIVGBIVGBIVGBIVG', 'ROYGBIVROYGBIVROYGB', 'ROYGBIVOYGBOYGBOYIV']