from ..program2513 import program2513
def test19():
    assert program2513(25) == ['ROYGBIVROYGBIVROYGBIVGBIV', 'ROYGROYGROYGROYGROYGROVIB', 'ROYVGBIVGBIVGBIVGBIVGBIVG', 'ROYGBIVGBIVGBIVGBIVGBIVGB', 'ROYGROYGROYGROYGROYGROBIV', 'ROYGBIVOYGBOYGBOYGBOYGBIV', 'ROYGBIVROYGBIVROYGBIVROYG', 'ROYBIVGBIVGBIVGBIVGBIVGBI']