from ..program2513 import program2513
def test17():
    assert program2513(23) == ['ROYVGBIVGBIVGBIVGBIVGBI', 'ROYGBIVOYGBOYGBOYGBOYIV', 'ROYGBIVGBIVGBIVGBIVGBIV', 'ROYGBIVROYGBIVROYGBIOYG', 'ROYBIVGBIVGBIVGBIVGBIVG', 'ROYGROYGROYGROYGROYGVIB', 'ROYGBIVROYGBIVROYGBIVGB', 'ROYGBIVROYGBIVROYGBIVYG', 'ROYGROYGROYGROYGROYGBIV']