from ..program2513 import program2513
def test20():
    assert program2513(28) == ['ROYGBIVGBIVGBIVGBIVGBIVGBIVG', 'ROYGROYGROYGROYGROYGROYGRBIV', 'ROYGBIVROYGBIVROYGBIVROYGBIV', 'ROYBIVGBIVGBIVGBIVGBIVGBIVGB', 'ROYVGBIVGBIVGBIVGBIVGBIVGBIV', 'ROYGBIVOYGBOYGBOYGBOYGBOYGIV', 'ROYGROYGROYGROYGROYGROYGRVIB']