from ..program2513 import program2513
def test12():
    assert program2513(18) == ['ROYGROYGROYGROYBIV', 'ROYGBIVROYGBIVGBIV', 'ROYBIVGBIVGBIVGBIV', 'ROYGBIVROYGBIVROYG', 'ROYGROYGROYGROYVIB', 'ROYGBIVGBIVGBIVGBI', 'ROYVGBIVGBIVGBIVGB', 'ROYGBIVOYGBOYGBOIV']