from ..program2513 import program2513
def test21():
    assert program2513(29) == ['ROYGBIVGBIVGBIVGBIVGBIVGBIVGB', 'ROYBIVGBIVGBIVGBIVGBIVGBIVGBI', 'ROYGBIVROYGBIVROYGBIVROYGBIVG', 'ROYGBIVOYGBOYGBOYGBOYGBOYGBIV', 'ROYGROYGROYGROYGROYGROYGROBIV', 'ROYGBIVROYGBIVROYGBIVROYGBOYG', 'ROYGROYGROYGROYGROYGROYGROVIB', 'ROYVGBIVGBIVGBIVGBIVGBIVGBIVG']