from ..program2513 import program2513
def test14():
    assert program2513(20) == ['ROYGBIVGBIVGBIVGBIVG', 'ROYGBIVROYGBIVROYGBI', 'ROYBIVGBIVGBIVGBIVGB', 'ROYGBIVROYGBIVGBIVGB', 'ROYGROYGROYGROYGRVIB', 'ROYGBIVOYGBOYGBOYGIV', 'ROYVGBIVGBIVGBIVGBIV', 'ROYGROYGROYGROYGRBIV']