from ..program788 import program788
def test48():
    assert program788(10 10
PPPPPPPPWP
PPPWPPPPPP
PPPPPPPPPP
PWWPPWPPPP
PPPPPPPPPP
PPPPWPPPPP
PPPPPPPPPP
PPPPPPWPPW
PPPPPPPPPP
PPWPPPPPWP) == ['10']