from ..program788 import program788
def test64():
    assert program788(10 10
PPPPPPPPPP
WWWWWWWWWW
WWWWWWWWWW
PPPPPPPPPP
PPPPPPPPPP
WWWWWWWWWW
WWWWWWWWWW
PPPPPPPPPP
PPPPPPPPPP
WWWWWWWWWW) == ['50']