from ..program788 import program788
def test63():
    assert program788(10 10
WPPPWPPPWP
PPPPPPPPPP
PPPPPPPPPP
PPPPPPPPPP
WPPPWPPPWP
PPPPPPPPPP
PPPPPPPPPP
PPPPPPPPPP
WPPPWPPPWP
PPPPPPPPPP) == ['9']