from ..program788 import program788
def test47():
    assert program788(10 10
PPPPPPPPPP
PPPPPPPWPP
PPPPPPPPPP
PPPPPPPPPP
PPPPPPPPPP
PPPPPPPPPP
PPPPPPPPPP
PPPPPPPPPP
PPPPPPPPPP
PPPPPPPPPP) == ['1']