from ..program788 import program788
def test70():
    assert program788(10 10
WPPPPWPPWP
PPPWPPPPPP
PWPPPPWPPP
PPPPWPPPWP
WPPPPPPPPP
PPPWPPWPPP
PWPPPPPPWP
PPPPWPPPPP
WPPPPPWPPP
PPPWPPPPWP) == ['18']