from ..program788 import program788
def test69():
    assert program788(10 10
PPPWPPPWPP
PWPPPWPPPP
PPPPPPPPPP
WPPWPPWPPW
PPPPPPPPPP
PWPPWPPWPP
PPPPPPPPPP
PPWPPWPPWP
PPPPPPPPPP
WPPWPPWPPW) == ['18']