from ..program890 import program890
def test25():
    assert program890(500
njjiptmrcggwwtbcxbmmiqrqdhhgciaskwustnvmbkbvghlcnrctbcjlepnkqcktsbxgjnvhmndnbqnmhwrlfijpimlojsmvfjidtcmujmnoihwhlronmmpeiobmoperdwsranlbtqgbktpdtbtihnwlsvfefrugurkjbvajxsovpuwjoohmvtdlarbeabmejbrkmkfjwbgsisvxfakjphpmrtmwwwktroitlmstbwuilftpwqmqtitwgkwbpiaueqopotnfxhchsoqqlvwqlogbooqnmpvvtxmtdqqkjwhifmvltxxbwjjgaxjkuuraneqrucchncusshrwxhhdukkexwjrxgufkgmiqblonthwtqulftphghltqcarvfhkknpqxftvqscspvosxvguskdmfdocxrrjvcskjhtxwomiwiqjemdklldgnkeuelcjuudmhokbihwpibicfbjjoqbbqnbqmcsdwdeiisqfvvoxggqeqcfs) == ['338']