from ..program890 import program890
def test59():
    assert program890(500
cbadfcecebaefcfbfbbaedbcfacdcbfcacfadbebdedaaffaaabffdeedbfbdececccfbaccddeffeeabaaffedfdcdfffdaabbafccaceedacdceabdabcebeddeaeeecbcabddebdfbcbecbffdbbcdaffacdacfbaafbacdbbbdacecabbaffacfbcbacdadafdbebcadeeabcfcfecaefecbbeaafcbaafabbbdbfaeaccedcdcfbbadfeddfcadcdafaeffdcdfceedeaacecaaafffeadcdfffbfedccbaefeebabeafddbddeacefcfbbbceacbcacaecddbcfadcdeafdedadddfefaadfdbbeaaaceacecfefefceeecaefeebfccdcffadbfbeacfbcfeecadcbbebaefaebcecbffaefbbcfacfddbdcdaaeddfdabbefbddcfdeaceafdddffffaffdcdebdacefbdba) == ['235']