from ..program890 import program890
def test18():
    assert program890(500
kjcllbkmamlbogkopfqhjfpejfeglpbdqjikbgakecolabphkmpnjfbhpdnlcqcfdaljmegiljlqpkdnomcglpkbaiencimbkehpiqmpafeabbohfajahfablplcpacngfpghjdhbonglhaedpihkbjbkcpjdkqkpdobjfqepolgdgjonaogkingfmacbflbmjhhjbnnffbmcohgmmfbjqojnocjlfhlhflpkddmiijomenhldcoijnqcomjnbbpnffkgelnigkcmnaqdnkpmoejllkilfdlqoqcbmbqdaobndpgjkffebhgmfclhncalfeamiqhclllpoefaaobhqfnljloimkdoaggjammqliommkllnhhqoagcpmlkddkclokjlccgfapodfolmfejdkofqncjkjhqcledaplificibodhddlhmqqckjenpjalokpllnldqppjceelgjbjqqqlcecjcjmkiklbbdikblddkikpfea) == ['325']