from ..program890 import program890
def test23():
    assert program890(500
dkftkjtfjdrrjnruuafncvesfngrsrmpmursvssubifcmaeivkrocrhkujbldcgvpifnttfgvrppjpfogmietujqnierfoflmqgbpgsqnagqjqhdjmejllchtldrtrcgemvcalcabieheheagnsmvhrdeeonfckgkuhciivibchbqmvbcdugvcbnqbujgeljqclunbgpguufqhletqstbeabcuncibkdkntbunnvquqshmkqmpbaoaujofaraipvjirvvggrnlvonqsehduohpauqetcujmgutoqigpuqijnevgmcmanalrvsaivueouviobdmucsljnfocsbvlrvmnoevhbpamqqcupcrbfdcerhchteersfjafuiekuchemvhctjfgsgmssfsanrcfjlvithppcqauuepopjolbojemvqfjhjfbiflmihnnkkgmaeecpeaascsasokudhjtkgclbomlbaicffhhlslseaaihlipgiv) == ['339']