from ..program890 import program890
def test38():
    assert program890(500
cbdcdcbdbcdbbcbdbddadbadddcdacdadbcaaaaddcadabdbabbcbbcccbbbbdbbccdcdcccdcdccaacaabacbdddddaaabaaacbbabdbcaacdabdaddacbdccddbbacabaaadddcdddadbdadacbccdabccadaacdadcbdaadacacbcdddbadcaddcbcbddcbcccacbbaacdcdbbdbbbadbbdbbbdacbddcbaccaccbaddaaaabbcdccccadcdcccbcbdbdcdcbddbacacbddbaacbaaabbbaccadcbbbacbacddbcbdbbcbcdbcdbbcdbcbdcdddbcbbbdbcabbdaaacdbdcdbccddbdababadddcdcabcbcbcccbcccdcaccacaddcabadacabbddaaabbdbdacccacabcaccddbbbcabcdaabdbddaaadbddccacbbcbccdccaaccbacacbcdbbcbccadcdabdbadbcabccddaba) == ['195']