from ..program890 import program890
def test56():
    assert program890(500
cefcddeacbbffacacefaaaceebbcdbafdbcfbcdbffddabfeccaffaaddeecfebebaaaccabedeceddbdebeadfeeecddceedbbebffbbcfcbbefcefafdefbadabafbbddddfcbcdfefeaaeddbbacaeafdeffbabddabdcefbbaadfdabcddfccffbbaacdbddedddeeabfffdafdbdbbcefeeafcaabcfccfccceaaefebcaabddcbaccdaafffccfdcfccdfdeccdcfeaaedbadfbbdedcddfecbdfafddaaecaaadadcdfbefcdffbccfbbcdbedfbfcefadffebbcaebbffccbdbabfcbadacdbebabccbadefdfccfccedcbdeffaaadafdfbadefadaabafceecaaebdeedcebbbacfcceadcfcfaddffcaeafeacebbffddbfddabddeaafdcfdaabacfcdeceeadfacaea) == ['228']