from ..program890 import program890
def test21():
    assert program890(500
fpkfjphbmbqmikncnatbjfldpcohbgamfjrceshfgffllbjcrkeemqboblbjtsgqbeplcrkstcginnjqqolijjbbcnabagheaaisdoiieesogomilkcookbsgebbbmqssrbgdmblmmccgeciaeiasbatraotjlafhmjmddsldfqgfeqkrmkafqdlikttmdtkdmmosqgfflseiibjnahjqsmhcmklgqrqdbccegjeschpcdnbjscqoifipbrfillscdqpjfaippqaloqpdfcmtmjptchiipedetijorrolndnehtkfjarpfqphmmmbeeeomfbshkehesalaeccpgpolhncijsihhdloesfjherreaclrplrtcbsrlefqeksgtdnkmdfcklgskqqkgcndthpgdkitiataqosqdrtjmirsicnrbblofqfsqsdksngrkaefmgnpaaroelimcpnnibekhompicrocopcscfajqdbfpqcrrnlm) == ['326']