from ..program890 import program890
def test24():
    assert program890(500
fropdpoauqarcbsnlpkwtcpabgsvcsfltusgobcghdbioeivlddcdadaawjhnljgsfjnfdebgucqmhivqvcrlnmogjapkocfffhdbtqcwauhfmlkwcdutvfwrhdclsjuqwsrrwgquducmguvlralvnspclfsgdpqudmishuwqhvfndqjrdiekbopjwqnbldtgafoqewwkwmdmvdwokekrqbbqfejrhervtbgsualsneufmohsrhwcvwoudfpofbnsbvqoogbrjjhmjiatfpsrvjdiohwhgkrwjcskibimsnlsgogbutccwjedroqtgumopbkshhsllkrlklihjicfaivckdsijgnvuraoiiwdhnoimwfgbslfoehwpdrknljsediqvmtkkgpfneuvjucgkochhbtcvnjhgafrhdhrpjchbociesjfmtwnckbobjimtbrfebdoronmeatuhtafvtssficqnwgdslcvmbmvaodutmpotjc) == ['351']