from ..program2514 import program2514
def test20():
    assert program2514(28) == ['ROYGBIVGBIVGBIVGBIVGBIVGBIVG', 'ROYGROYGROYGROYGROYGROYGRBIV', 'ROYGBIVROYGBIVROYGBIVROYGBIV', 'ROYBIVGBIVGBIVGBIVGBIVGBIVGB', 'ROYVGBIVGBIVGBIVGBIVGBIVGBIV', 'ROYGBIVOYGBOYGBOYGBOYGBOYGIV', 'ROYGROYGROYGROYGROYGROYGRVIB']