from ..program2514 import program2514
def test10():
    assert program2514(16) == ['ROYGROYGROYGRVIB', 'ROYGBIVROYGBIOYG', 'ROYGBIVOYGBOYGIV', 'ROYGBIVROYGBIVGB', 'ROYGBIVGBIVGBIVG', 'ROYGBIVROYGBIVYG', 'ROYGROYGROYGRBIV', 'ROYBIVGBIVGBIVGB', 'ROYVGBIVGBIVGBIV']