from ..program2514 import program2514
def test19():
    assert program2514(25) == ['ROYGBIVROYGBIVROYGBIVGBIV', 'ROYGROYGROYGROYGROYGROVIB', 'ROYVGBIVGBIVGBIVGBIVGBIVG', 'ROYGBIVGBIVGBIVGBIVGBIVGB', 'ROYGROYGROYGROYGROYGROBIV', 'ROYGBIVOYGBOYGBOYGBOYGBIV', 'ROYGBIVROYGBIVROYGBIVROYG', 'ROYBIVGBIVGBIVGBIVGBIVGBI']