from ..program2514 import program2514
def test12():
    assert program2514(18) == ['ROYGROYGROYGROYBIV', 'ROYGBIVROYGBIVGBIV', 'ROYBIVGBIVGBIVGBIV', 'ROYGBIVROYGBIVROYG', 'ROYGROYGROYGROYVIB', 'ROYGBIVGBIVGBIVGBI', 'ROYVGBIVGBIVGBIVGB', 'ROYGBIVOYGBOYGBOIV']