from ..program2514 import program2514
def test13():
    assert program2514(19) == ['ROYGROYGROYGROYGBIV', 'ROYGBIVROYGBIVGBIVG', 'ROYGROYGROYGROYGVIB', 'ROYGBIVGBIVGBIVGBIV', 'ROYVGBIVGBIVGBIVGBI', 'ROYBIVGBIVGBIVGBIVG', 'ROYGBIVROYGBIVROYGB', 'ROYGBIVOYGBOYGBOYIV']