from ..program2514 import program2514
def test11():
    assert program2514(17) == ['ROYGBIVROYGBIVOYG', 'ROYGBIVGBIVGBIVGB', 'ROYGBIVOYGBOYGBIV', 'ROYVGBIVGBIVGBIVG', 'ROYGROYGROYGROVIB', 'ROYGBIVROYGBIVGBI', 'ROYGROYGROYGROBIV', 'ROYBIVGBIVGBIVGBI']