from ..program2514 import program2514
def test18():
    assert program2514(24) == ['ROYBIVGBIVGBIVGBIVGBIVGB', 'ROYGROYGROYGROYGROYGRBIV', 'ROYGBIVROYGBIVROYGBIVOYG', 'ROYGBIVROYGBIVROYGBIVGBI', 'ROYGBIVOYGBOYGBOYGBOYGIV', 'ROYGBIVGBIVGBIVGBIVGBIVG', 'ROYGROYGROYGROYGROYGRVIB', 'ROYVGBIVGBIVGBIVGBIVGBIV']