from ..program2514 import program2514
def test14():
    assert program2514(20) == ['ROYGBIVGBIVGBIVGBIVG', 'ROYGBIVROYGBIVROYGBI', 'ROYBIVGBIVGBIVGBIVGB', 'ROYGBIVROYGBIVGBIVGB', 'ROYGROYGROYGROYGRVIB', 'ROYGBIVOYGBOYGBOYGIV', 'ROYVGBIVGBIVGBIVGBIV', 'ROYGROYGROYGROYGRBIV']