from ..program2514 import program2514
def test16():
    assert program2514(22) == ['ROYGROYGROYGROYGROYVIB', 'ROYVGBIVGBIVGBIVGBIVGB', 'ROYGBIVOYGBOYGBOYGBOIV', 'ROYGROYGROYGROYGROYBIV', 'ROYGBIVROYGBIVROYGBOYG', 'ROYBIVGBIVGBIVGBIVGBIV', 'ROYGBIVROYGBIVROYGBIVG', 'ROYGBIVGBIVGBIVGBIVGBI']