from ..program2514 import program2514
def test4():
    assert program2514(14) == ['ROYGROYGROYBIV', 'ROYGBIVROYGBIV', 'ROYVGBIVGBIVGB', 'ROYGBIVOYGBOIV', 'ROYBIVGBIVGBIV', 'ROYGROYGROYVIB', 'ROYGBIVGBIVGBI']