from ..program2514 import program2514
def test9():
    assert program2514(15) == ['ROYGBIVROYGBIVG', 'ROYGROYGROYGVIB', 'ROYGBIVROYGBOYG', 'ROYBIVGBIVGBIVG', 'ROYGROYGROYGBIV', 'ROYGBIVOYGBOYIV', 'ROYVGBIVGBIVGBI', 'ROYGBIVGBIVGBIV']