from ..program2514 import program2514
def test15():
    assert program2514(21) == ['ROYVGBIVGBIVGBIVGBIVG', 'ROYBIVGBIVGBIVGBIVGBI', 'ROYGBIVROYGBIVROYGBIV', 'ROYGROYGROYGROYGROBIV', 'ROYGBIVGBIVGBIVGBIVGB', 'ROYGROYGROYGROYGROVIB', 'ROYGBIVOYGBOYGBOYGBIV']