from ..program2514 import program2514
def test22():
    assert program2514(34) == ['ROYGBIVROYGBIVROYGBIVROYGBIVROYGBI', 'ROYGBIVGBIVGBIVGBIVGBIVGBIVGBIVGBI', 'ROYGROYGROYGROYGROYGROYGROYGROYBIV', 'ROYGROYGROYGROYGROYGROYGROYGROYVIB', 'ROYVGBIVGBIVGBIVGBIVGBIVGBIVGBIVGB', 'ROYGBIVROYGBIVROYGBIVROYGBIVGBIVGB', 'ROYGBIVOYGBOYGBOYGBOYGBOYGBOYGBOIV', 'ROYBIVGBIVGBIVGBIVGBIVGBIVGBIVGBIV']