from ..program2514 import program2514
def test21():
    assert program2514(29) == ['ROYGBIVGBIVGBIVGBIVGBIVGBIVGB', 'ROYBIVGBIVGBIVGBIVGBIVGBIVGBI', 'ROYGBIVROYGBIVROYGBIVROYGBIVG', 'ROYGBIVOYGBOYGBOYGBOYGBOYGBIV', 'ROYGROYGROYGROYGROYGROYGROBIV', 'ROYGBIVROYGBIVROYGBIVROYGBOYG', 'ROYGROYGROYGROYGROYGROYGROVIB', 'ROYVGBIVGBIVGBIVGBIVGBIVGBIVG']