from ..program2514 import program2514
def test17():
    assert program2514(23) == ['ROYVGBIVGBIVGBIVGBIVGBI', 'ROYGBIVOYGBOYGBOYGBOYIV', 'ROYGBIVGBIVGBIVGBIVGBIV', 'ROYGBIVROYGBIVROYGBIOYG', 'ROYBIVGBIVGBIVGBIVGBIVG', 'ROYGROYGROYGROYGROYGVIB', 'ROYGBIVROYGBIVROYGBIVGB', 'ROYGBIVROYGBIVROYGBIVYG', 'ROYGROYGROYGROYGROYGBIV']