from ..program984 import program984
def test31():
    assert program984(BMBWUBWUBWUBOQKWUBWUBWUBPITCIHXHCKLRQRUGXJWUBWUBWUBVWUBWUBWUBJCWUBWUBWUBQJPWUBWUBWUBBWUBWUBWUBBMYGIZOOXWUBWUBWUBTAGWUBWUBHWUB) == ['BMB OQK PITCIHXHCKLRQRUGXJ V JC QJP B BMYGIZOOX TAG H', 'BMB   OQK   PITCIHXHCKLRQRUGXJ   V   JC   QJP   B   BMYGIZOOX   TAG  H']