from ..program984 import program984
def test14():
    assert program984(IWUBWUBQLHDWUBYIIKZDFQWUBWUBWUBCXWUBWUBUWUBWUBWUBKWUBWUBWUBNL) == ['I  QLHD YIIKZDFQ   CX  U   K   NL', 'I QLHD YIIKZDFQ CX U K NL']