from ..program984 import program984
def test18():
    assert program984(WUBYYRTSMNWUWUBWUBWUBCWUBWUBWUBCWUBWUBWUBFSYUINDWOBVWUBWUBWUBFWUBWUBWUBAUWUBWUBWUBVWUBWUBWUBJB) == ['YYRTSMNWU C C FSYUINDWOBV F AU V JB', 'YYRTSMNWU   C   C   FSYUINDWOBV   F   AU   V   JB']