from ..program984 import program984
def test21():
    assert program984(WUBWUBZBKOKHQLGKRVIMZQMQNRWUBWUBWUBDACWUBWUBNZHFJMPEYKRVSWUBWUBWUBPPHGAVVPRZWUBWUBWUBQWUBWUBAWUBG) == ['ZBKOKHQLGKRVIMZQMQNR   DAC  NZHFJMPEYKRVS   PPHGAVVPRZ   Q  A G', 'ZBKOKHQLGKRVIMZQMQNR DAC NZHFJMPEYKRVS PPHGAVVPRZ Q A G']