from ..program984 import program984
def test11():
    assert program984(WUBWUBEWUBWUBWUBIQMJNIQWUBWUBWUBGZZBQZAUHYPWUBWUBWUBPMRWUBWUBWUBDCV) == ['E IQMJNIQ GZZBQZAUHYP PMR DCV', 'E   IQMJNIQ   GZZBQZAUHYP   PMR   DCV']