from ..program984 import program984
def test10():
    assert program984(VSRNVEATZTLGQRFEGBFPWUBWUBWUBAJWUBWUBWUBPQCHNWUBCWUB) == ['VSRNVEATZTLGQRFEGBFP AJ PQCHN C', 'VSRNVEATZTLGQRFEGBFP   AJ   PQCHN C']