from ..program984 import program984
def test34():
    assert program984(WUBWUBWUBISERPQITVIYERSCNWUBWUBWUBQWUBWUBWUBDGSDIPWUBWUBWUBCAHKDZWEXBIBJVVSKKVQJWUBWUBWUBKIWUBWUBWUBCWUBWUBWUBAWUBWUBWUBPWUBWUBWUBHWUBWUBWUBF) == ['ISERPQITVIYERSCN   Q   DGSDIP   CAHKDZWEXBIBJVVSKKVQJ   KI   C   A   P   H   F', 'ISERPQITVIYERSCN Q DGSDIP CAHKDZWEXBIBJVVSKKVQJ KI C A P H F']