from ..program984 import program984
def test32():
    assert program984(CBZNWUBWUBWUBNHWUBWUBWUBYQSYWUBWUBWUBMWUBWUBWUBXRHBTMWUBWUBWUBPCRCWUBWUBWUBTZUYLYOWUBWUBWUBCYGCWUBWUBWUBCLJWUBWUBWUBSWUBWUBWUB) == ['CBZN NH YQSY M XRHBTM PCRC TZUYLYO CYGC CLJ S', 'CBZN   NH   YQSY   M   XRHBTM   PCRC   TZUYLYO   CYGC   CLJ   S']