from ..program984 import program984
def test29():
    assert program984(WUBWUBWSPLAYSZSAUDSWUBWUBWUBUWUBWUBWUBKRWUBWUBWUBRSOKQMZFIYZQUWUBWUBWUBELSHUWUBWUBWUBUKHWUBWUBWUBQXEUHQWUBWUBWUBBWUBWUBWUBR) == ['WSPLAYSZSAUDS   U   KR   RSOKQMZFIYZQU   ELSHU   UKH   QXEUHQ   B   R', 'WSPLAYSZSAUDS U KR RSOKQMZFIYZQU ELSHU UKH QXEUHQ B R']