from ..program984 import program984
def test36():
    assert program984(WUBWUBWUBMWUBWUBWUBQWUBWUBWUBITCFEYEWUBWUBWUBHEUWGNDFNZGWKLJWUBWUBWUBMZPWUBWUBWUBUWUBWUBWUBBWUBWUBWUBDTJWUBHZVIWUBWUBWUBPWUBFNHHWUBWUBWUBVTOWUB) == ['M   Q   ITCFEYE   HEUWGNDFNZGWKLJ   MZP   U   B   DTJ HZVI   P FNHH   VTO', 'M Q ITCFEYE HEUWGNDFNZGWKLJ MZP U B DTJ HZVI P FNHH VTO']