from ..program984 import program984
def test12():
    assert program984(WUBWUBWUBFVWUBWUBWUBBPSWUBWUBWUBRXNETCJWUBWUBWUBJDMBHWUBWUBWUBBWUBWUBVWUBWUBB) == ['FV   BPS   RXNETCJ   JDMBH   B  V  B', 'FV BPS RXNETCJ JDMBH B V B']