from ..program984 import program984
def test40():
    assert program984(WUBWUBWUBSTEZTZEFFIWUBWUBWUBSWUBWUBWUBCWUBFWUBHRJPVWUBWUBWUBDYJUWUBWUBWUBPWYDKCWUBWUBWUBCWUBWUBWUBUUEOGCVHHBWUBWUBWUBEXLWUBWUBWUBVCYWUBWUBWUBMWUBWUBWUBYWUB) == ['STEZTZEFFI   S   C F HRJPV   DYJU   PWYDKC   C   UUEOGCVHHB   EXL   VCY   M   Y', 'STEZTZEFFI S C F HRJPV DYJU PWYDKC C UUEOGCVHHB EXL VCY M Y']