from ..program984 import program984
def test25():
    assert program984(WUBNXOLIBKEGXNWUBWUBWUBUWUBGITCNMDQFUAOVLWUBWUBWUBAIJDJZJHFMPVTPOXHPWUBWUBWUBISCIOWUBWUBWUBGWUBWUBWUBUWUB) == ['NXOLIBKEGXN U GITCNMDQFUAOVL AIJDJZJHFMPVTPOXHP ISCIO G U', 'NXOLIBKEGXN   U GITCNMDQFUAOVL   AIJDJZJHFMPVTPOXHP   ISCIO   G   U']