from ..program984 import program984
def test24():
    assert program984(WUBMPWUBWUBWUBORWUBWUBDLGKWUBWUBWUBVVZQCAAKVJTIKWUBWUBWUBTJLUBZJCILQDIFVZWUBWUBYXWUBWUBWUBQWUBWUBWUBLWUB) == ['MP OR DLGK VVZQCAAKVJTIK TJLUBZJCILQDIFVZ YX Q L', 'MP   OR  DLGK   VVZQCAAKVJTIK   TJLUBZJCILQDIFVZ  YX   Q   L']