from ..program984 import program984
def test22():
    assert program984(WUBWUBJWUBWUBWUBNFLWUBWUBWUBGECAWUBYFKBYJWTGBYHVSSNTINKWSINWSMAWUBWUBWUBFWUBWUBWUBOVWUBWUBLPWUBWUBWUBN) == ['J NFL GECA YFKBYJWTGBYHVSSNTINKWSINWSMA F OV LP N', 'J   NFL   GECA YFKBYJWTGBYHVSSNTINKWSINWSMA   F   OV  LP   N']