from ..program984 import program984
def test30():
    assert program984(WUBXEMWWVUHLSUUGRWUBWUBWUBAWUBXEGILZUNKWUBWUBWUBJDHHKSWUBWUBWUBDTSUYSJHWUBWUBWUBPXFWUBMOHNJWUBWUBWUBZFXVMDWUBWUBWUBZMWUBWUB) == ['XEMWWVUHLSUUGR A XEGILZUNK JDHHKS DTSUYSJH PXF MOHNJ ZFXVMD ZM', 'XEMWWVUHLSUUGR   A XEGILZUNK   JDHHKS   DTSUYSJH   PXF MOHNJ   ZFXVMD   ZM']