from ..program984 import program984
def test13():
    assert program984(WUBWUBWUBFBQWUBWUBWUBIDFSYWUBWUBWUBCTWDMWUBWUBWUBSXOWUBWUBWUBQIWUBWUBWUBL) == ['FBQ   IDFSY   CTWDM   SXO   QI   L', 'FBQ IDFSY CTWDM SXO QI L']