from ..program984 import program984
def test20():
    assert program984(WUBZVMJWUBWUBWUBFOIMJQWKNZUBOFOFYCCWUBWUBWUBAUWWUBRDRADWUBWUBWUBCHQVWUBWUBWUBKFTWUBWUBWUBW) == ['ZVMJ FOIMJQWKNZUBOFOFYCC AUW RDRAD CHQV KFT W', 'ZVMJ   FOIMJQWKNZUBOFOFYCC   AUW RDRAD   CHQV   KFT   W']