from ..program984 import program984
def test38():
    assert program984(WUBOJMWRSLAXXHQRTPMJNCMPGWUBWUBWUBNYGMZIXNLAKSQYWDWUBWUBWUBXNIWUBWUBWUBFWUBWUBWUBXMBWUBWUBWUBIWUBWUBWUBINWUBWUBWUBWDWUBWUBWUBDDWUBWUBWUBD) == ['OJMWRSLAXXHQRTPMJNCMPG NYGMZIXNLAKSQYWD XNI F XMB I IN WD DD D', 'OJMWRSLAXXHQRTPMJNCMPG   NYGMZIXNLAKSQYWD   XNI   F   XMB   I   IN   WD   DD   D']