from ..program984 import program984
def test33():
    assert program984(DPDWUBWUBWUBEUQKWPUHLTLNXHAEKGWUBRRFYCAYZFJDCJLXBAWUBWUBWUBHJWUBOJWUBWUBWUBNHBJEYFWUBWUBWUBRWUBWUBWUBSWUBWWUBWUBWUBXDWUBWUBWUBJWUB) == ['DPD   EUQKWPUHLTLNXHAEKG RRFYCAYZFJDCJLXBA   HJ OJ   NHBJEYF   R   S W   XD   J', 'DPD EUQKWPUHLTLNXHAEKG RRFYCAYZFJDCJLXBA HJ OJ NHBJEYF R S W XD J']