from ..program984 import program984
def test23():
    assert program984(WUBWUBLCWUBWUBWUBZGEQUEATJVIXETVTWUBWUBWUBEXMGWUBWUBWUBRSWUBWUBWUBVWUBWUBWUBTAWUBWUBWUBCWUBWUBWUBQG) == ['LC   ZGEQUEATJVIXETVT   EXMG   RS   V   TA   C   QG', 'LC ZGEQUEATJVIXETVT EXMG RS V TA C QG']