from ..program984 import program984
def test16():
    assert program984(WUBWUBOWUBWUBWUBIPVCQAFWYWUBWUBWUBQWUBWUBWUBXHDKCPYKCTWWYWUBWUBWUBVWUBWUBWUBFZWUBWUB) == ['O   IPVCQAFWY   Q   XHDKCPYKCTWWY   V   FZ', 'O IPVCQAFWY Q XHDKCPYKCTWWY V FZ']