from ..program984 import program984
def test17():
    assert program984(PAMJGYWUBWUBWUBXGPQMWUBWUBWUBTKGSXUYWUBWUBWUBEWUBWUBWUBNWUBWUBWUBHWUBWUBWUBEWUBWUB) == ['PAMJGY   XGPQM   TKGSXUY   E   N   H   E', 'PAMJGY XGPQM TKGSXUY E N H E']