from ..program984 import program984
def test15():
    assert program984(KWUBUPDYXGOKUWUBWUBWUBAGOAHWUBIZDWUBWUBWUBIYWUBWUBWUBVWUBWUBWUBPWUBWUBWUBE) == ['K UPDYXGOKU AGOAH IZD IY V P E', 'K UPDYXGOKU   AGOAH IZD   IY   V   P   E']