from ..program520 import program520
def test8():
    assert program520(10 10
SSSSSSSSSS
..........
..........
..........
..........
..........
..........
..........
..........
..........) == ['90']