from ..program4740 import program4740
def test4():
    assert program4740(CGPWTAPEVBTGANLCLVSHQIIKHDPVUHRSQPXHSNYAHPGBECICFQYDFRTRELLLEDZYWJSLOBSKDGRRDHNRRGIXAMEBGFJJTEIGUGRU
HAWYVKRRBEIWNOGYMIYQXDCFXMMCSAYSOXQFHHIFRRCJRAWHLDDHHHAKHXVKCVPBFGGEXUKWTFWMOUUGMXTSBUTHXCJCWHCQQTYQ
ANKFDWLYSX) == ['WVBGIQXSYHIFRRWLDDHXBGEUGU', 'WVBNIQXSYHIFRRJLDDHXBFGUGU', 'AVBIIQXSAHIFRRWLDDHXBFGUGU', 'WVBGCSSQHHIFRRWLDDHXBGFUGU', 'AVBNIQXSAHIFRRJLDDHABFGUGU', 'WVBNIDXSYHIFRRWLDDHXBGFUGU']