from ..program4740 import program4740
def test39():
    assert program4740(AAACAAACAAADAAAAAAA
AADAAAAAAAACDAAAAAAAAAAACAAAAABCACAAACAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADA
AAACAADAAAAADD) == ['AAACAAACAAAAAAAAAA']