from ..program4740 import program4740
def test19():
    assert program4740(WZRKLETJRBBRZKGHEFBVEFVLIERBPSEGJVSNUZUICONWWBOOTHCOJLLZFNOCNOFJQZTZWBLKHGIWWWPBUYWBAHYJGEBJZJDTNBGN
ZINFGDCNKHYFZYYWHTIHZTKWXXXMSWOVOPQDTRWSQKBWWCPEMYFVGARELELBLGEVJCMOCFTTUVCYUQUSFONAMWKVDWMGXVNZJBWH
AFPA) == ['WZKTRKBEFVLEBGVCOTCFONWKWGZJB', 'WZKTRBEFVELEBEJCOTCFONWKWGZJB', 'WZKTRBEFVELEBGVCOTCFONWKWGZJB', 'WZKTRKEFVELEBEJCOTCFONWKWGZJB']