from ..program4740 import program4740
def test13():
    assert program4740(KEJHTOKHMKWTYSJEAJAXGADRHUKBCRHACSRDNSZIHTPQNLOSRKYBGYIIJDINTXRPMWSVMMBODAYPVVDDTIXGDIOMWUAKZVFKDAUM
WTEVPIFAAJYIDTZSZKPPQKIOMHDZTKDMFVKSJRUFMNHZJPVSQYELWYAFACGGNRORSLGYVXAEYVLZBLDEHYDGOFDSWUYCXLXDKFSU
TUZEQBWVBVTKETQ) == ['EJTKHMKSJRUNHPQLYGNRSVAYVDDGOWUKFU', 'EJTOKMKSJRUHZPQLYGNRSVAYVDDGDWUKFU', 'EJTOKMKSJRUNZPQLYGNRSVAYVDDGDWUKFU', 'EJHTKMKSJRUHZPQLYGNRSVAYVDDGDWUKFU']