from ..program4740 import program4740
def test14():
    assert program4740(EGQYYSKTFTURZNRDVIWBYXMRDGFWMYKFXGIFOGYJSXKDCJUAGZPVTYCHIXVFTVTCXMKHZFTXSMMQVFXZGKHCIYODDRZEYECDLKNG
PEXXCTRFJAAKPOTBAEFRLDRZKORNMXHHXTLKMKCGPVPUOBELPLFQFXOBZWIVIQCHEJQPXKGSCQAWIMETCJVTAGXJIINTADDXJTKQ
QURSEKPMSSEVQZI) == ['ETFTBRDKOXKCGPVFVCHQXKCIECDK', 'EKTFRZRXMGFFXOZVCHXCMTVGIDDK', 'ETFTBRDKOXKCGPVXVCHQXKCIECDK', 'EKTFRZNXMGFFXIJXKCATCVTXTDDK', 'EKTFRZNXMGFFXIJXKCATCVTXIDDK']