from ..program4740 import program4740
def test16():
    assert program4740(BTWZLIKDACZVLCKMVTIQHLFBNRCBDSWPFFKGPCQFPTOIJLPFCDMFGQKFHTDFFCCULUAYPXXIIIWBZIDMOPNHPZBEXLVARJFTBFOE
MDXYKKWZVASJPPWRCYNMRAOBBLUNBSMQAPCPSFAGLXWJRBQTBRWXYNQGWECYNFIAJXDMUHIIMDFMSHLPIMYQXNRRUSSNXALGNWIK
KNFVBVAOWXMZVUHAVUDKDBUVAKNHACZBGBHMUOPHWGQSDFXLHB) == ['WZACMLNBSPFGCFIJDMHDFLPIMNXL', 'WZACLMQLBRWGCFIJDMHDFLPIMNXL', 'WZACMBNBSPFGQTIJDMHDFLPIMNXA', 'WZVCMLNBSPFGCFIJDMHDFLPIMNXL', 'WZACMLNBSPFGQTIJDMHDFLPIMNXL', 'DZVCMBNBSPFGCFIJDMHDFLPIMNXA']