from ..program4740 import program4740
def test18():
    assert program4740(BBYUVCIYLNUJPSEYCAAPQSDNSDDTNEHQZDPBEKQAWNAKEYFBNEEBGPDPRLCSVOWYDEDRPPEDOROCHRCNQUSPNVXGRXHNLKDETWQC
BQCQXCAHADGJHBYIKEUWNXFUOOTVCCKJPJJCMWLAWWKSDGHFNZTCPSQNRTPCBLXDTSJLRHSCCZXQXCVLVGTROOUCUQASIQHZGNEI
RYE) == ['BBYUVCJPCASDNZPQNBDRLVROOCQSGNE', 'BBYINUJPCASDHZPQNPDRSVROOCUSHNE', 'BBYINUJPCASDHZPQNPDLSVROOCUSHNE', 'BBYUVCJPCASDNTPQNBDRLVROOCQSGNE', 'BBYUVCJPCASDNTPQNBDLCVROOCQSGNE']