from ..program4740 import program4740
def test33():
    assert program4740(ABAAAABABADABAABAABCCABADABACABACABCABADABADABACABBACAADABACABABACABADABACABABA
BACAACABABABACABCABADABAACABADABACABAA
ABBAB) == ['BACAACABABABACABCAADABAACABADABACABAA', 'BACAACABABABACABCABAABAACABADABACABAA', 'BAAACABABABACABCABADABAACABADABACABAA']