from ..program4740 import program4740
def test26():
    assert program4740(AABABABABAAAABBAAAABABABABAAAAABABAAAA
AABABAAABABABAAABAAAAABAAABAAABABABBBABBAAABAABAAAAABABBABAAABAABAABABAAAABABAAABAAABAABABBBABBABABA
AAAAA) == ['AABABABABAAAABBAAAABABABABAAAABABAAAA']