from ..program4740 import program4740
def test3():
    assert program4740(QNHRPFYMAAPJDUHBAEXNEEZSTMYHVGQPYKNMVKMBVSVLIYGUVMJHEFLJEPIWFHSLISTGOKRXNMSCXYKMAXBPKCOCNTIRPCUEPHXM
RRFCZUGFDRKKMQTOETNELXMEWGOCDHFKIXOPVHHEWTCDNXVFKFKTKNWKEIKTCMHMHDNCLLVQSGKHBCDDYVVVQIRPZEOPUGQUGRHH
R) == ['FUENEMGKIVHEFEIHLSGKBCIPEPH', 'FDENEMGKIVHEWFTKNMCKBCIPEPH', 'FMENEEHKIVHEFEIHLSGKCYPOPUH', 'QNHFPHEXNETMHMHLLSGKCYPOPUH', 'QNHFPHETVKNKMMHLLSGKBCIPEPH', 'FDENEMGKIVHEFEIHLSGKCYPOPUH']