from ..program4740 import program4740
def test31():
    assert program4740(ASDASASDASDASDAASDASDASDASASDDAASDASSASDSDAD
DASDASSSDASDASDASASDASSDAASDASSDDSASDASDAASDDAASDASDAASDASDDASDASDASDASDASS
DASD) == ['ASDASASDASASDAASDASASDASASDDAASDASSASDSDAD']