from ..program4740 import program4740
def test7():
    assert program4740(AXBPBDEYIYKKCZBTLKBUNEQLCXXLKIUTOOATYDXYYQCLFAXAEIGTFMNTTQKCQRMEEFRYVYXAOLMUQNPJBMFBUGVXFZAJSBXWALSI
VWFONLLKSHGHHQSFBBFWTXAITPUKNDANOCLMNFTAAMJVDLXYPILPCJCFWTNBQWEOMMXHRYHEGBJIVSXBBGQKXRIYNZFIWSZPPUUM
PPKKLHXWWT) == ['BBITKNCLTADXYCFTNQMRYVXBBGXFWS', 'BBITUNCLTADXYLFTNQERYVXBBGXZWS', 'BBITKNCLTADXYCFTNQMRYVXBBGXZWS']