from ..program4740 import program4740
def test34():
    assert program4740(ABAABACABADAACADABACAAB
BAACABADABACABAAAADADAABACABACABADABABADABACABAADABBADABACAAACAABACABADABBBAA
DABACA) == ['ABAABACABADAACAABACAAB', 'ABAABACABADAACADABAAAB']