from ..program786 import program786
def test69():
    assert program786(10 10
PPPWPPPWPP
PWPPPWPPPP
PPPPPPPPPP
WPPWPPWPPW
PPPPPPPPPP
PWPPWPPWPP
PPPPPPPPPP
PPWPPWPPWP
PPPPPPPPPP
WPPWPPWPPW) == ['18']