from ..program786 import program786
def test64():
    assert program786(10 10
PPPPPPPPPP
WWWWWWWWWW
WWWWWWWWWW
PPPPPPPPPP
PPPPPPPPPP
WWWWWWWWWW
WWWWWWWWWW
PPPPPPPPPP
PPPPPPPPPP
WWWWWWWWWW) == ['50']