from ..program786 import program786
def test48():
    assert program786(10 10
PPPPPPPPWP
PPPWPPPPPP
PPPPPPPPPP
PWWPPWPPPP
PPPPPPPPPP
PPPPWPPPPP
PPPPPPPPPP
PPPPPPWPPW
PPPPPPPPPP
PPWPPPPPWP) == ['10']