from ..program786 import program786
def test47():
    assert program786(10 10
PPPPPPPPPP
PPPPPPPWPP
PPPPPPPPPP
PPPPPPPPPP
PPPPPPPPPP
PPPPPPPPPP
PPPPPPPPPP
PPPPPPPPPP
PPPPPPPPPP
PPPPPPPPPP) == ['1']