from ..program789 import program789
def test48():
    assert program789(10 10
PPPPPPPPWP
PPPWPPPPPP
PPPPPPPPPP
PWWPPWPPPP
PPPPPPPPPP
PPPPWPPPPP
PPPPPPPPPP
PPPPPPWPPW
PPPPPPPPPP
PPWPPPPPWP) == ['10']