from ..program789 import program789
def test64():
    assert program789(10 10
PPPPPPPPPP
WWWWWWWWWW
WWWWWWWWWW
PPPPPPPPPP
PPPPPPPPPP
WWWWWWWWWW
WWWWWWWWWW
PPPPPPPPPP
PPPPPPPPPP
WWWWWWWWWW) == ['50']