from ..program789 import program789
def test63():
    assert program789(10 10
WPPPWPPPWP
PPPPPPPPPP
PPPPPPPPPP
PPPPPPPPPP
WPPPWPPPWP
PPPPPPPPPP
PPPPPPPPPP
PPPPPPPPPP
WPPPWPPPWP
PPPPPPPPPP) == ['9']