from ..program789 import program789
def test47():
    assert program789(10 10
PPPPPPPPPP
PPPPPPPWPP
PPPPPPPPPP
PPPPPPPPPP
PPPPPPPPPP
PPPPPPPPPP
PPPPPPPPPP
PPPPPPPPPP
PPPPPPPPPP
PPPPPPPPPP) == ['1']