from ..program789 import program789
def test69():
    assert program789(10 10
PPPWPPPWPP
PWPPPWPPPP
PPPPPPPPPP
WPPWPPWPPW
PPPPPPPPPP
PWPPWPPWPP
PPPPPPPPPP
PPWPPWPPWP
PPPPPPPPPP
WPPWPPWPPW) == ['18']