from ..program789 import program789
def test70():
    assert program789(10 10
WPPPPWPPWP
PPPWPPPPPP
PWPPPPWPPP
PPPPWPPPWP
WPPPPPPPPP
PPPWPPWPPP
PWPPPPPPWP
PPPPWPPPPP
WPPPPPWPPP
PPPWPPPPWP) == ['18']