from ..program2346 import program2346
def test13():
    assert program2346(nmuwjdihouqrnsuahimssnrbxdpwvxiyqtenahtrlshjkmnfuttnpqhgcagoptinnaptxaccptparldzrhpgbyrzedghudtsswxi
nilhbdghosqnbebafimconrbvdodjsipqmekahhrllhjkemeketapfhgcagopfidnahtlaccpfpafedqicpcbvfgedghudhddwib) == ['nilhbdghosqnbebafimconrbvdodjsipqmekahhrllhjkemeketapfhgcagopfidnahtlaccpfpafedqicpcbvfgedghudhddwib', 'zilhbzgzzsznbebzfzzcozzzvzodjszpzmzkzzhzzlzzzemekezazfzzzzzzzfzdzzhzlzzzzfzzfezqiczczvfgzzzzzzhddzib', 'oilhbegipsrnbebbfjncooscveodjsjprmfkbihsmliklemekeuaqfihdbhpqfjdobhulbddqfqbfeeqicqccvfgfehivehddxib']