from ..program2346 import program2346
def test19():
    assert program2346(tgharsjyihroiiahwgbjezlxvlterxivdhtzjcqegzmtigqmrehvhiyjeywegxaseoyoacouijudbiruoghgxvxadwzgdxtnxlds
tghaksjsdhkoiiahegbjexlfrctercipdhmvjbgegxdtggqdpbhvhiseehhegnaseoooacnsijubbirjnghgsvpadhaadrtimfdp) == ['zzzzkzzsdzkzzzzzezzzzxzfrczzzczpzzmvzbgzzxdzgzzdpbzzzzsezhhzznzzzzozzznszzzbzzzjnzzzszpzzhaazrzimfzp', 'uhibktksdikpjjbiehckfxmfrcufscjpeimvkbgfhxdughrdpbiwijsefhhfhnbtfpopbdnsjkvbcjsjnhihswpbehaaeruimfep', 'tghaksjsdhkoiiahegbjexlfrctercipdhmvjbgegxdtggqdpbhvhiseehhegnaseoooacnsijubbirjnghgsvpadhaadrtimfdp']