from ..program2346 import program2346
def test17():
    assert program2346(zrvzedssbsrfldqvjpgmsefrmsatspzoitwvymahiptphiystjlsauzquzqqbmljobdhijcpdvatorwmyojqgnezvzlgjibxepcf
pesoedmqbmffldqsjggmhefkadaesijointrkmahapaahiysfjdiaupqujngbjhjobdhiecadeatgjvelojjgnepvajgeibfepaf) == ['pesofemqcmfgmerskghnhfgkadbetijpjntrknbiaqaaijztfkdibvprvjngcjhkpceijedaeebugjvelpkjhofpwajhejcffqag', 'pesozzmqzmfzzzzszgzzhzzkadzezijzzntrkzzzazaazzzzfzdizzpzzjngzjhzzzzzzezazezzgjvelzzjzzzpzajzezzfzzaz', 'pesoedmqbmffldqsjggmhefkadaesijointrkmahapaahiysfjdiaupqujngbjhjobdhiecadeatgjvelojjgnepvajgeibfepaf']