from ..program2346 import program2346
def test15():
    assert program2346(hbgwuqzougqzlxemvyjpeizjfwhgugrfnhbrlxkmkdalikfyunppwgdzmalbwewybnjzqsohwhjkdcyhhzmysflambvhpsjilsyv
fbdjdqjojdafarakvcjpeipjfehgfgrfehbolxkmkdagikflunnpvadocalbkedibhbflmohnhjkdcthhaigsfjaibqhbcjelirv) == ['fcdjdrjpjdafarakwckqfjpkgeihfhsgeicomylnlebgjlglvonqvaeocbmckfdichbflmpinikledtiiaigtgjbicqibckemirw', 'fzdjdzjzjdafarakzczzzzpzzezzfzzzezzozzzzzzzgzzzlzznzvazoczzzkzdizhbflmzznzzzzztzzaigzzjzizqzbczezirz', 'fbdjdqjojdafarakvcjpeipjfehgfgrfehbolxkmkdagikflunnpvadocalbkedibhbflmohnhjkdcthhaigsfjaibqhbcjelirv']