from ..program2346 import program2346
def test11():
    assert program2346(eufycwztywhbjrpqobvknwfqmnboqcfdiahkagykeibbsqpljcghhmsgfmswwsanzyiwtvuirwmppfivtekaywkzskyydfvkjgxb
ecfwavookadbcilfobojnweqinbcpcfdiahkabwkeibbacpljcghhksgfajgmianfnivmhfifogpffiheegayfkxkkcmdfvihgdb) == ['ecfwavookadbcilfobojnweqinbcpcfdiahkabwkeibbacpljcghhksgfajgmianfnivmhfifogpffiheegayfkxkkcmdfvihgdb', 'zczwavookadzcilfzzojzzezizzcpzzzzzzzzbwzzzzzaczzzzzzzkzzzajgmizzfnzvmhfzfogzfzzhezgzzfzxkzcmzzzihzdz', 'fcgwavookadccilfpcojoxerioccpdgejbilbbwlfjccacqmkdhiikthgajgmibofnjvmhfjfogqfgjhefgbzflxklcmegwihhdc']