from ..program2346 import program2346
def test21():
    assert program2346(nttdcfceptruiomtmwzestrfchnqpgqeztpcvthzelfyggjgqadylzubpvbrlgndrcsursczpxlnoyoadxezncqalupfzmjeqihe
kttdcfceohrjiaahmoldanpfchnfpgheqpdahqhxecfpbgigqadrkjubjfbrlgndbcgcgmcjpeleinaadretncqaiqpfkmjeqihe) == ['kuuedgdfohsjjaahnoldanpgdiofqhhfqpdahqixfcgpbhihrberkjvcjfcsmhoebdgcgmdjqemeinaberftodrbiqqgknkfrjif', 'kttdcfceohrjiaahmoldanpfchnfpgheqpdahqhxecfpbgigqadrkjubjfbrlgndbcgcgmcjpeleinaadretncqaiqpfkmjeqihe', 'kzzzzzzzohzjzaahzoldanpzzzzfzzhzqpdahqzxzczpbzizzzzrkjzzjfzzzzzzbzgcgmzjzezeinazzrztzzzziqzzkzzzzzzz']