from ..program2348 import program2348
def test11():
    assert program2348(eufycwztywhbjrpqobvknwfqmnboqcfdiahkagykeibbsqpljcghhmsgfmswwsanzyiwtvuirwmppfivtekaywkzskyydfvkjgxb
ecfwavookadbcilfobojnweqinbcpcfdiahkabwkeibbacpljcghhksgfajgmianfnivmhfifogpffiheegayfkxkkcmdfvihgdb) == ['ecfwavookadbcilfobojnweqinbcpcfdiahkabwkeibbacpljcghhksgfajgmianfnivmhfifogpffiheegayfkxkkcmdfvihgdb', 'zczwavookadzcilfzzojzzezizzcpzzzzzzzzbwzzzzzaczzzzzzzkzzzajgmizzfnzvmhfzfogzfzzhezgzzfzxkzcmzzzihzdz', 'fcgwavookadccilfpcojoxerioccpdgejbilbbwlfjccacqmkdhiikthgajgmibofnjvmhfjfogqfgjhefgbzflxklcmegwihhdc']