from ..program2348 import program2348
def test19():
    assert program2348(tgharsjyihroiiahwgbjezlxvlterxivdhtzjcqegzmtigqmrehvhiyjeywegxaseoyoacouijudbiruoghgxvxadwzgdxtnxlds
tghaksjsdhkoiiahegbjexlfrctercipdhmvjbgegxdtggqdpbhvhiseehhegnaseoooacnsijubbirjnghgsvpadhaadrtimfdp) == ['zzzzkzzsdzkzzzzzezzzzxzfrczzzczpzzmvzbgzzxdzgzzdpbzzzzsezhhzznzzzzozzznszzzbzzzjnzzzszpzzhaazrzimfzp', 'uhibktksdikpjjbiehckfxmfrcufscjpeimvkbgfhxdughrdpbiwijsefhhfhnbtfpopbdnsjkvbcjsjnhihswpbehaaeruimfep', 'tghaksjsdhkoiiahegbjexlfrctercipdhmvjbgegxdtggqdpbhvhiseehhegnaseoooacnsijubbirjnghgsvpadhaadrtimfdp']