from ..program2348 import program2348
def test17():
    assert program2348(zrvzedssbsrfldqvjpgmsefrmsatspzoitwvymahiptphiystjlsauzquzqqbmljobdhijcpdvatorwmyojqgnezvzlgjibxepcf
pesoedmqbmffldqsjggmhefkadaesijointrkmahapaahiysfjdiaupqujngbjhjobdhiecadeatgjvelojjgnepvajgeibfepaf) == ['pesofemqcmfgmerskghnhfgkadbetijpjntrknbiaqaaijztfkdibvprvjngcjhkpceijedaeebugjvelpkjhofpwajhejcffqag', 'pesozzmqzmfzzzzszgzzhzzkadzezijzzntrkzzzazaazzzzfzdizzpzzjngzjhzzzzzzezazezzgjvelzzjzzzpzajzezzfzzaz', 'pesoedmqbmffldqsjggmhefkadaesijointrkmahapaahiysfjdiaupqujngbjhjobdhiecadeatgjvelojjgnepvajgeibfepaf']