from ..program2348 import program2348
def test21():
    assert program2348(nttdcfceptruiomtmwzestrfchnqpgqeztpcvthzelfyggjgqadylzubpvbrlgndrcsursczpxlnoyoadxezncqalupfzmjeqihe
kttdcfceohrjiaahmoldanpfchnfpgheqpdahqhxecfpbgigqadrkjubjfbrlgndbcgcgmcjpeleinaadretncqaiqpfkmjeqihe) == ['kuuedgdfohsjjaahnoldanpgdiofqhhfqpdahqixfcgpbhihrberkjvcjfcsmhoebdgcgmdjqemeinaberftodrbiqqgknkfrjif', 'kttdcfceohrjiaahmoldanpfchnfpgheqpdahqhxecfpbgigqadrkjubjfbrlgndbcgcgmcjpeleinaadretncqaiqpfkmjeqihe', 'kzzzzzzzohzjzaahzoldanpzzzzfzzhzqpdahqzxzczpbzizzzzrkjzzjfzzzzzzbzgcgmzjzezeinazzrztzzzziqzzkzzzzzzz']