from ..program2348 import program2348
def test13():
    assert program2348(nmuwjdihouqrnsuahimssnrbxdpwvxiyqtenahtrlshjkmnfuttnpqhgcagoptinnaptxaccptparldzrhpgbyrzedghudtsswxi
nilhbdghosqnbebafimconrbvdodjsipqmekahhrllhjkemeketapfhgcagopfidnahtlaccpfpafedqicpcbvfgedghudhddwib) == ['nilhbdghosqnbebafimconrbvdodjsipqmekahhrllhjkemeketapfhgcagopfidnahtlaccpfpafedqicpcbvfgedghudhddwib', 'zilhbzgzzsznbebzfzzcozzzvzodjszpzmzkzzhzzlzzzemekezazfzzzzzzzfzdzzhzlzzzzfzzfezqiczczvfgzzzzzzhddzib', 'oilhbegipsrnbebbfjncooscveodjsjprmfkbihsmliklemekeuaqfihdbhpqfjdobhulbddqfqbfeeqicqccvfgfehivehddxib']