from ..program2348 import program2348
def test15():
    assert program2348(hbgwuqzougqzlxemvyjpeizjfwhgugrfnhbrlxkmkdalikfyunppwgdzmalbwewybnjzqsohwhjkdcyhhzmysflambvhpsjilsyv
fbdjdqjojdafarakvcjpeipjfehgfgrfehbolxkmkdagikflunnpvadocalbkedibhbflmohnhjkdcthhaigsfjaibqhbcjelirv) == ['fcdjdrjpjdafarakwckqfjpkgeihfhsgeicomylnlebgjlglvonqvaeocbmckfdichbflmpinikledtiiaigtgjbicqibckemirw', 'fzdjdzjzjdafarakzczzzzpzzezzfzzzezzozzzzzzzgzzzlzznzvazoczzzkzdizhbflmzznzzzzztzzaigzzjzizqzbczezirz', 'fbdjdqjojdafarakvcjpeipjfehgfgrfehbolxkmkdagikflunnpvadocalbkedibhbflmohnhjkdcthhaigsfjaibqhbcjelirv']