from ..program891 import program891
def test45():
    assert program891(500
cddbcaadccbdacccccbbdcbbcbcbdccbbadbaadbaddabcaacabbcacdbaddaddcbabaaaddbacbdaacccbdcbbaccbdcdbdcdbcbdbacadbccacacdbdbbbaaadccbdabbacbdabdabcdccdcddcbdadbacdbbdacdbccddbbadadcbdbddcabdabcbbddcbdcbcdabcdabddcaaabdddbbcabcaacaddcaadddaacddcabdcacbacdbcbdbadbcdaddcdaaaadaadcdcaabbadbadddaabdbdbdbaabdbdcbdcadbbcbaddbcccddbaddcbccadccccbbbdcacaabcbbcbdbdaaaacddbdcdaadbdadbacdddbbbddacbcaadcddcbdbabcadcddbbabccddbadddabacbbdacbbbcbcbdcadaccddbbbadddaaddddcddabaccaddbadcbcbabdcdbcaaabcadaacaddbabddcaad) == ['202']