from ..program891 import program891
def test14():
    assert program891(500
ghgbegjdahcmgdjgmbaehhgmmlbjgigielfbddkhfbfgbgcmdfekcaeejgidledgcghicgmmblbaljhgggkimcagblckjkimcglahiambbccefkbmlmdgmkglfdmjdflbfdbekmjbghjjikjgkmeigifllmmgijkcclgjkmcahdjgkcekeagklgfhgidbedbgkgkmbjbkbdhiijjbkcdeallkjmjfldamkcmiijmgfkmhkhcgggfbhldjehbmmebkfeibhimddigfbgflifgmcdhmhjcfcmijjeaaegagcikmglclcblacjfclghgfkfaflhggjdmdjlcheehfhekcbdfkihgfjgakjbaihdmkhjfcfhfbeeifaghmmhiijaeglkackhllehlmmjklcelggahhlilgmbemkkjdcmhakbfgjdakhgekhcddmafkidefbffjdcmcidjmllkeedgiikjdlggigchgckdijhjgfmmfekmdcm) == ['303']