from ..program891 import program891
def test40():
    assert program891(500
cbcbcaadaddabadbcddbabcbbaabbcaabcdaacdabdcacacbadacaccdddacdbdbbbbcbcddbbbcccccbbcadbcacbdbccdabcdbdadbccbcdcdcdbdbddccbbdcbbabbcadbbaadbbbaadbbabaddddaddcacabbddddaacacbcbaabaaababacaddaacbcbdbccbbdcccbddbacacbbbbddcaadacccbacbbdbadccbacbbbbdbacdddbcdaaadcdbacaccddbddaaaaaddaabdccdacbbaacddccbacadbbbcacdbaacbaddcadddcbbccaacdccdabdcdcdccbadbdbdbcbaabbacbcbcbabddcadbdaaacacbdccdadccbacaadbccccdaadbdbccaddbbadccbacbccbddababbbdcaadbacdaaddababbcabcdacbddccbccdabdcdbcdcacccaacbacbabbcdcbbbbbcbaac) == ['196']