from ..program891 import program891
def test49():
    assert program891(500
ebceccdebaaacaeecbcbaedbeebceaccabacdadbaebcbbdebeeacacdecdceddbbecebcaaeeddeabbbbdceedaebceeeadbdadacdbbddcdaaddeabedccdacdecabcebcdbdaaeeaedbabaeaedaddcdebdbcdebbcbccddbdbbcdedaccbbaedeeedacabbddcdeedbaeabebbdddcceaaacbdbdcbdeeeccadabeadddcebbededdebaaaedabadbabcddebeaeebcebbdddcbacbeeeedacbeaddbccebecdceeabebabbbbbcaaaaeadaaeccaebeedababbabedbdcadeeabaaeddbedddeadecaedbbeccdbcdadededcddceaccceeabadabcebdcbecdebcaaeadbcdbcbdcbbedbecbbccbedabcbedceccdbabdababddeeeaaaabcbdbcedcbbdecaeebedddccbaa) == ['217']