from ..program891 import program891
def test12():
    assert program891(500
dffchafckjeihjicjdebhahafcdcbbghebdedkdgihgdeddjijdadgaggfciedejdgicbjjjidfbfjecabddaggidbfaadbhcgddagkcdbhdakceidkaekefhcdjgadefidfjbcejeeghbaffkabeejidkkcdfkijeiehiedfacjbhbahkckidjdekbgkdfjkibhahegghbdaggcejbkkgkiaibbefjfkgfghikifaaeekjafdcgefibgfdhahicfidbgbcebfekjkikekjdedieiifddgcfekaifabgafahegkhjfjdjjefbebcigikafjcbcijbjfkdbiaaibbjejehhacejakikjfebabjffhcgikbcedhdefkakibdjbekdkdbhfaafcigahbabcjibbgkaikkagakakbcahfkgjfjiccicchggagifajggckjckffdaehdejfihcdkjkcahakibfbakhheiacgkhbhhbjjkcbke) == ['294']