from ..program891 import program891
def test10():
    assert program891(500
ahecidbhaccbabcggeceaebgcbaeagehfhgiebafdcgiiehegggcdfbdccicbfficggabdhfihheadafdcccbbgbgfgehchdbihdidddagdafigbbbhgaiagiacbhhegdgchcfiabbiidhhfbabdfehcifgegieihfibheedfbiadbfdafdgbehfeifgcfhieiaheebeiiabggbecedchhicfeccfadhbfgahefdchibaecbifeadfdadfefifeibcbbibibbcchadbbbedcbgeiefdhedddedhfeecfafggghdffbcgigigeeieeafgciececicgeegafbcdahighgahgdeahfhfebegebfedfdfadiafdcdebgeacedeiecdcaghibhedaaecdaahdaecdbahcfchebiafcfhacabcgbaadibgfgbdcebifdafbgabageebfeebefhffdcdgehgfchiabfabcbefhccehffibaeiac) == ['273']