from ..program2512 import program2512
def test12():
    assert program2512(18) == ['ROYGROYGROYGROYBIV', 'ROYGBIVROYGBIVGBIV', 'ROYBIVGBIVGBIVGBIV', 'ROYGBIVROYGBIVROYG', 'ROYGROYGROYGROYVIB', 'ROYGBIVGBIVGBIVGBI', 'ROYVGBIVGBIVGBIVGB', 'ROYGBIVOYGBOYGBOIV']