from ..program2512 import program2512
def test13():
    assert program2512(19) == ['ROYGROYGROYGROYGBIV', 'ROYGBIVROYGBIVGBIVG', 'ROYGROYGROYGROYGVIB', 'ROYGBIVGBIVGBIVGBIV', 'ROYVGBIVGBIVGBIVGBI', 'ROYBIVGBIVGBIVGBIVG', 'ROYGBIVROYGBIVROYGB', 'ROYGBIVOYGBOYGBOYIV']