from ..program2512 import program2512
def test10():
    assert program2512(16) == ['ROYGROYGROYGRVIB', 'ROYGBIVROYGBIOYG', 'ROYGBIVOYGBOYGIV', 'ROYGBIVROYGBIVGB', 'ROYGBIVGBIVGBIVG', 'ROYGBIVROYGBIVYG', 'ROYGROYGROYGRBIV', 'ROYBIVGBIVGBIVGB', 'ROYVGBIVGBIVGBIV']