from ..program2512 import program2512
def test18():
    assert program2512(24) == ['ROYBIVGBIVGBIVGBIVGBIVGB', 'ROYGROYGROYGROYGROYGRBIV', 'ROYGBIVROYGBIVROYGBIVOYG', 'ROYGBIVROYGBIVROYGBIVGBI', 'ROYGBIVOYGBOYGBOYGBOYGIV', 'ROYGBIVGBIVGBIVGBIVGBIVG', 'ROYGROYGROYGROYGROYGRVIB', 'ROYVGBIVGBIVGBIVGBIVGBIV']