from ..program2512 import program2512
def test21():
    assert program2512(29) == ['ROYGBIVGBIVGBIVGBIVGBIVGBIVGB', 'ROYBIVGBIVGBIVGBIVGBIVGBIVGBI', 'ROYGBIVROYGBIVROYGBIVROYGBIVG', 'ROYGBIVOYGBOYGBOYGBOYGBOYGBIV', 'ROYGROYGROYGROYGROYGROYGROBIV', 'ROYGBIVROYGBIVROYGBIVROYGBOYG', 'ROYGROYGROYGROYGROYGROYGROVIB', 'ROYVGBIVGBIVGBIVGBIVGBIVGBIVG']