from ..program2512 import program2512
def test11():
    assert program2512(17) == ['ROYGBIVROYGBIVOYG', 'ROYGBIVGBIVGBIVGB', 'ROYGBIVOYGBOYGBIV', 'ROYVGBIVGBIVGBIVG', 'ROYGROYGROYGROVIB', 'ROYGBIVROYGBIVGBI', 'ROYGROYGROYGROBIV', 'ROYBIVGBIVGBIVGBI']