from ..program2512 import program2512
def test20():
    assert program2512(28) == ['ROYGBIVGBIVGBIVGBIVGBIVGBIVG', 'ROYGROYGROYGROYGROYGROYGRBIV', 'ROYGBIVROYGBIVROYGBIVROYGBIV', 'ROYBIVGBIVGBIVGBIVGBIVGBIVGB', 'ROYVGBIVGBIVGBIVGBIVGBIVGBIV', 'ROYGBIVOYGBOYGBOYGBOYGBOYGIV', 'ROYGROYGROYGROYGROYGROYGRVIB']