from ..program2512 import program2512
def test17():
    assert program2512(23) == ['ROYVGBIVGBIVGBIVGBIVGBI', 'ROYGBIVOYGBOYGBOYGBOYIV', 'ROYGBIVGBIVGBIVGBIVGBIV', 'ROYGBIVROYGBIVROYGBIOYG', 'ROYBIVGBIVGBIVGBIVGBIVG', 'ROYGROYGROYGROYGROYGVIB', 'ROYGBIVROYGBIVROYGBIVGB', 'ROYGBIVROYGBIVROYGBIVYG', 'ROYGROYGROYGROYGROYGBIV']