from ..program2512 import program2512
def test15():
    assert program2512(21) == ['ROYVGBIVGBIVGBIVGBIVG', 'ROYBIVGBIVGBIVGBIVGBI', 'ROYGBIVROYGBIVROYGBIV', 'ROYGROYGROYGROYGROBIV', 'ROYGBIVGBIVGBIVGBIVGB', 'ROYGROYGROYGROYGROVIB', 'ROYGBIVOYGBOYGBOYGBIV']