from ..program2512 import program2512
def test14():
    assert program2512(20) == ['ROYGBIVGBIVGBIVGBIVG', 'ROYGBIVROYGBIVROYGBI', 'ROYBIVGBIVGBIVGBIVGB', 'ROYGBIVROYGBIVGBIVGB', 'ROYGROYGROYGROYGRVIB', 'ROYGBIVOYGBOYGBOYGIV', 'ROYVGBIVGBIVGBIVGBIV', 'ROYGROYGROYGROYGRBIV']