from ..program2512 import program2512
def test16():
    assert program2512(22) == ['ROYGROYGROYGROYGROYVIB', 'ROYVGBIVGBIVGBIVGBIVGB', 'ROYGBIVOYGBOYGBOYGBOIV', 'ROYGROYGROYGROYGROYBIV', 'ROYGBIVROYGBIVROYGBOYG', 'ROYBIVGBIVGBIVGBIVGBIV', 'ROYGBIVROYGBIVROYGBIVG', 'ROYGBIVGBIVGBIVGBIVGBI']