from ..program2512 import program2512
def test9():
    assert program2512(15) == ['ROYGBIVROYGBIVG', 'ROYGROYGROYGVIB', 'ROYGBIVROYGBOYG', 'ROYBIVGBIVGBIVG', 'ROYGROYGROYGBIV', 'ROYGBIVOYGBOYIV', 'ROYVGBIVGBIVGBI', 'ROYGBIVGBIVGBIV']