from ..program2512 import program2512
def test4():
    assert program2512(14) == ['ROYGROYGROYBIV', 'ROYGBIVROYGBIV', 'ROYVGBIVGBIVGB', 'ROYGBIVOYGBOIV', 'ROYBIVGBIVGBIV', 'ROYGROYGROYVIB', 'ROYGBIVGBIVGBI']