from ..program2512 import program2512
def test19():
    assert program2512(25) == ['ROYGBIVROYGBIVROYGBIVGBIV', 'ROYGROYGROYGROYGROYGROVIB', 'ROYVGBIVGBIVGBIVGBIVGBIVG', 'ROYGBIVGBIVGBIVGBIVGBIVGB', 'ROYGROYGROYGROYGROYGROBIV', 'ROYGBIVOYGBOYGBOYGBOYGBIV', 'ROYGBIVROYGBIVROYGBIVROYG', 'ROYBIVGBIVGBIVGBIVGBIVGBI']