from ..program2512 import program2512
def test22():
    assert program2512(34) == ['ROYGBIVROYGBIVROYGBIVROYGBIVROYGBI', 'ROYGBIVGBIVGBIVGBIVGBIVGBIVGBIVGBI', 'ROYGROYGROYGROYGROYGROYGROYGROYBIV', 'ROYGROYGROYGROYGROYGROYGROYGROYVIB', 'ROYVGBIVGBIVGBIVGBIVGBIVGBIVGBIVGB', 'ROYGBIVROYGBIVROYGBIVROYGBIVGBIVGB', 'ROYGBIVOYGBOYGBOYGBOYGBOYGBOYGBOIV', 'ROYBIVGBIVGBIVGBIVGBIVGBIVGBIVGBIV']