from ..program4824 import program4824
def test36():
    assert program4824(dacemehkboajmgkialdlegndmdhhgilckmbabbfobecflnjmeocgifkcildjikmliihfbcmgbdlcnjlhefikoahadbofaflkdbamhahlohmjjoogkbaammihldgklggligmdobmjnimfngjjinfodbkklgnmebncgjgbhiianbdllbgdfjgdegkeejchobfkahheeibkniibjaiifnbonnodoombgdbceadeffccklndajkcjdlboldoagfhhoe...) == ['0']