from ..program4824 import program4824
def test35():
    assert program4824(bkbkkkefaijgdbbbkjkibkjhediggjicgfeigaiehgaelechhklcjcdkhcalkgldelifljbclcceejacbjbjglbhlabchidfgddadafhhjbkejbedclahaachdceeblkfcdfajkfecahflhegkfihkheechebehbdklajbdkeblkcdkgiadkfclifgiggfdhcjagclfjjhhhdbidlacdkbkkkjgcheikjdacehdkkdglfghgcgakakgkhbebbkf...) == ['0']