from ..program4824 import program4824
def test16():
    assert program4824(ehgxkfjpkwbxysqmixmtheehtkfclvxiynxhockpjrsqcuydbfgoetjxwumhfqkhgehgxkfjpkwbxysqmixmtheehtkfclvxiynxhockpjrsqcuydbfgoetjxwumhfqkhgehgxkfjpkwbxysqmixmtheehtkfclvxiynxhockpjrsqcuydbfgoetjxwumhfqkhgehgxkfjpkwbxysqmixmtheehtkfclvxiynxhockpjrsqcuydbfgoetjxwumh...) == ['0']