from ..program4824 import program4824
def test105():
    assert program4824(dkjijdkjijdkjijdkjijdkjijdkjijdkjijdkjijdkjijdkjijdkjijdkjijdkjijdkjijdkjijdkjijdkjijdkjijdkjijdkjijdkjijdkjijdkjijdkjijdkjijdkjijdkjijdkjijdkjijdkjijdkjijdkjijdkjijdkjijdkjijdkjijdkjijdkjijdkjijdkjijdkjijdkjij
dddkikjjidkkidijjjjkkjjikjdikiidijjikikjijjiijdikkjjjiddjjijkkkjkiijijkijdjjikikdjjjijdddjkjjdijjjjjjjddkjjkjjjdjjdkijjkijkkjkkkiiijdjijkkdjdjjjkkjkdddjidjjijdddkijididjdddidijjjjjdkidijjkkjiijkjjjjjjdjkkdddkjj
31328) == ['0']