from ..program4824 import program4824
def test15():
    assert program4824(cdaadaaccbadcdcbcabadabbadadadbcadddcacbddddcbddcdaaaadbdbdacabbcacabdbcaacbccddddddcbcdcbdabdcabdadaccdbbcbbabbcaccdacccdddbacbcaabcdaadaaccbadcdcbcabadabbadadadbcadddcacbddddcbddcdaaaadbdbdacabbcacabdbcaacbccddddddcbcdcbdabdcabdadaccdbbcbbabbcaccdacccdd...) == ['0']