from ..program4824 import program4824
def test30():
    assert program4824(cdaeeaeacccbbcdeeedbadaeddbcaabcecdecdbdaeaaeebedacaaadbeeddcbadaebdbabeaadaccaccadaceacacdcaaabbacdddbbdbacbbadbbdbeadadeecbbcdbceecbecbdbeeaccbceedceaaceddedaadbdeddbbcedaeeceaeabdbbdcbebeabdceebccedcccceecededabeedaaadaeabcdcabbadaddbdabcebdbbcaddcbccc...) == ['0']