from ..program4824 import program4824
def test64():
    assert program4824(aigbdfeedcadiddafbgdffaaidbigifahgieghchddeggbigeabfiibfaefdcifebchichiehefiihieehdebcgigcihiabeaiediaeifadgbdfcebaighfceachfebdbiiffgfebeeaaaigidhcgibegfddaaaiiidgbbaeecdcediehfedifggfebhehfbbdceffihfdaabgfaaehfeeaheagfhhddaehffgheffagcdhgeadhigfbifiiifd...) == ['0']