from ..program503 import program503
def test48():
    assert program503(GXPZFSELJJNDAXYRV
UYBKPMVBSOVOJWMONLTJOJCNQKMTAHEWLHOWIIBH
HCWNFWJPEJIWOVPTBMVCRJLSISSVNOHCKLBFMIUAIMASQWPXEYXBOXQGFEMYJLBKDCZIMJNHOJEDGGANIVYKQTUOSOVOPWHVJGXH) == ['NO']