from ..program503 import program503
def test45():
    assert program503(UIKWWKXLSHTOOZOVGXKYSOJEHAUEEG
KZXQDWJJWRXFHKJDQHJK
XMZHTFOGEXAUJXXJUYVJIFOTKLZHDKELJWERHMGAWGKWAQKEKHIDWGGZVYOHKXRPWSJDPESFJUMKQYWBYUTHQYEFZUGKQOBHYDWB) == ['NO']