from ..program503 import program503
def test41():
    assert program503(IDQRX
WETHO
ODPDGBHVUVSSISROHQJTUKPUCLXABIZQQPPBPKOSEWGEHRSRRNBAVLYEMZISMWWGKHVTXKUGUXEFBSWOIWUHRJGMWBMHQLDZHBWA) == ['NO']