from ..program503 import program503
def test27():
    assert program503(AGFIGYWJLVMYZGNQHEHWKJIAWBPUAQFERMCDROFN
PMJNHMVNRGCYZAVRWNDSMLSZHFNYIUWFPUSKKIGU
MCDVPPRXGUAYLSDRHRURZASXUWZSIIEZCPXUVEONKNGNWRYGOSFMCKESMVJZHWWUCHWDQMLASLNNMHAU) == ['NO']