from ..program503 import program503
def test21():
    assert program503(NUBKQEJHALANSHEIFUZHYEZKKDRFHQKAJHLAOWTZIMOCWOVVDW
EFVOBIGAUAUSQGVSNBKNOBDMINODMFSHDL
KLAMKNTHBFFOHVKWICHBKNDDQNEISODUSDNLUSIOAVWY) == ['NO']