from ..program503 import program503
def test14():
    assert program503(IJHHGKCXWDBRWJUPRDBZJLNTTNWKXLUGJSBWBOAUKWRAQWGFNL
NJMWRMBCNPHXTDQQNZ
WDNJRCLILNQRHWBANLTXWMJBPKUPGKJDJZAQWKTZFBRCTXHHBNXRGUQUNBNMWODGSJWW) == ['YES']