from ..program503 import program503
def test32():
    assert program503(OSKFHGYNQLSRFSAHPXKGPXUHXTRBJNAQRBSSWJVEENLJCDDHFXVCUNPZAIVVO
FNUOCXAGRRHNDJAHVVLGGEZQHWARYHENBKHP
UOEFNWVXCUNERLKVTHAGPSHKHDYFPYWZHJKHQLSNFBJHVJANRXCNSDUGVDABGHVAOVHBJZXGRACHRXEGNRPQEAPORQSILNXFS) == ['YES']