from ..program503 import program503
def test12():
    assert program503(OVQELLOGFIOLEHXMEMBJDIGBPGEYFG
JNKFPFFIJOFHRIFHXEWYZOPDJBZTJZKBWQTECNHRFSJPJOAPQT
YAIPFFFEXJJNEJPLREIGODEGQZVMCOBDFKWTMWJSBEBTOFFQOHIQJLHFNXIGOHEZRZLFOKJBJPTPHPGY) == ['YES']