from ..program785 import program785
def test70():
    assert program785(10 10
WPPPPWPPWP
PPPWPPPPPP
PWPPPPWPPP
PPPPWPPPWP
WPPPPPPPPP
PPPWPPWPPP
PWPPPPPPWP
PPPPWPPPPP
WPPPPPWPPP
PPPWPPPPWP) == ['18']