from ..program785 import program785
def test63():
    assert program785(10 10
WPPPWPPPWP
PPPPPPPPPP
PPPPPPPPPP
PPPPPPPPPP
WPPPWPPPWP
PPPPPPPPPP
PPPPPPPPPP
PPPPPPPPPP
WPPPWPPPWP
PPPPPPPPPP) == ['9']