from ..program785 import program785
def test64():
    assert program785(10 10
PPPPPPPPPP
WWWWWWWWWW
WWWWWWWWWW
PPPPPPPPPP
PPPPPPPPPP
WWWWWWWWWW
WWWWWWWWWW
PPPPPPPPPP
PPPPPPPPPP
WWWWWWWWWW) == ['50']