from ..program785 import program785
def test69():
    assert program785(10 10
PPPWPPPWPP
PWPPPWPPPP
PPPPPPPPPP
WPPWPPWPPW
PPPPPPPPPP
PWPPWPPWPP
PPPPPPPPPP
PPWPPWPPWP
PPPPPPPPPP
WPPWPPWPPW) == ['18']