from ..program785 import program785
def test48():
    assert program785(10 10
PPPPPPPPWP
PPPWPPPPPP
PPPPPPPPPP
PWWPPWPPPP
PPPPPPPPPP
PPPPWPPPPP
PPPPPPPPPP
PPPPPPWPPW
PPPPPPPPPP
PPWPPPPPWP) == ['10']