from ..program787 import program787
def test63():
    assert program787(10 10
WPPPWPPPWP
PPPPPPPPPP
PPPPPPPPPP
PPPPPPPPPP
WPPPWPPPWP
PPPPPPPPPP
PPPPPPPPPP
PPPPPPPPPP
WPPPWPPPWP
PPPPPPPPPP) == ['9']