from ..program787 import program787
def test70():
    assert program787(10 10
WPPPPWPPWP
PPPWPPPPPP
PWPPPPWPPP
PPPPWPPPWP
WPPPPPPPPP
PPPWPPWPPP
PWPPPPPPWP
PPPPWPPPPP
WPPPPPWPPP
PPPWPPPPWP) == ['18']