from ..program2511 import program2511
def test10():
    assert program2511(16) == ['ROYGROYGROYGRVIB', 'ROYGBIVROYGBIOYG', 'ROYGBIVOYGBOYGIV', 'ROYGBIVROYGBIVGB', 'ROYGBIVGBIVGBIVG', 'ROYGBIVROYGBIVYG', 'ROYGROYGROYGRBIV', 'ROYBIVGBIVGBIVGB', 'ROYVGBIVGBIVGBIV']