from ..program2511 import program2511
def test13():
    assert program2511(19) == ['ROYGROYGROYGROYGBIV', 'ROYGBIVROYGBIVGBIVG', 'ROYGROYGROYGROYGVIB', 'ROYGBIVGBIVGBIVGBIV', 'ROYVGBIVGBIVGBIVGBI', 'ROYBIVGBIVGBIVGBIVG', 'ROYGBIVROYGBIVROYGB', 'ROYGBIVOYGBOYGBOYIV']