from ..program2511 import program2511
def test22():
    assert program2511(34) == ['ROYGBIVROYGBIVROYGBIVROYGBIVROYGBI', 'ROYGBIVGBIVGBIVGBIVGBIVGBIVGBIVGBI', 'ROYGROYGROYGROYGROYGROYGROYGROYBIV', 'ROYGROYGROYGROYGROYGROYGROYGROYVIB', 'ROYVGBIVGBIVGBIVGBIVGBIVGBIVGBIVGB', 'ROYGBIVROYGBIVROYGBIVROYGBIVGBIVGB', 'ROYGBIVOYGBOYGBOYGBOYGBOYGBOYGBOIV', 'ROYBIVGBIVGBIVGBIVGBIVGBIVGBIVGBIV']