from ..program2511 import program2511
def test19():
    assert program2511(25) == ['ROYGBIVROYGBIVROYGBIVGBIV', 'ROYGROYGROYGROYGROYGROVIB', 'ROYVGBIVGBIVGBIVGBIVGBIVG', 'ROYGBIVGBIVGBIVGBIVGBIVGB', 'ROYGROYGROYGROYGROYGROBIV', 'ROYGBIVOYGBOYGBOYGBOYGBIV', 'ROYGBIVROYGBIVROYGBIVROYG', 'ROYBIVGBIVGBIVGBIVGBIVGBI']