from ..program2511 import program2511
def test18():
    assert program2511(24) == ['ROYBIVGBIVGBIVGBIVGBIVGB', 'ROYGROYGROYGROYGROYGRBIV', 'ROYGBIVROYGBIVROYGBIVOYG', 'ROYGBIVROYGBIVROYGBIVGBI', 'ROYGBIVOYGBOYGBOYGBOYGIV', 'ROYGBIVGBIVGBIVGBIVGBIVG', 'ROYGROYGROYGROYGROYGRVIB', 'ROYVGBIVGBIVGBIVGBIVGBIV']