from ..program2511 import program2511
def test11():
    assert program2511(17) == ['ROYGBIVROYGBIVOYG', 'ROYGBIVGBIVGBIVGB', 'ROYGBIVOYGBOYGBIV', 'ROYVGBIVGBIVGBIVG', 'ROYGROYGROYGROVIB', 'ROYGBIVROYGBIVGBI', 'ROYGROYGROYGROBIV', 'ROYBIVGBIVGBIVGBI']