from ..program2511 import program2511
def test17():
    assert program2511(23) == ['ROYVGBIVGBIVGBIVGBIVGBI', 'ROYGBIVOYGBOYGBOYGBOYIV', 'ROYGBIVGBIVGBIVGBIVGBIV', 'ROYGBIVROYGBIVROYGBIOYG', 'ROYBIVGBIVGBIVGBIVGBIVG', 'ROYGROYGROYGROYGROYGVIB', 'ROYGBIVROYGBIVROYGBIVGB', 'ROYGBIVROYGBIVROYGBIVYG', 'ROYGROYGROYGROYGROYGBIV']