from ..program2511 import program2511
def test14():
    assert program2511(20) == ['ROYGBIVGBIVGBIVGBIVG', 'ROYGBIVROYGBIVROYGBI', 'ROYBIVGBIVGBIVGBIVGB', 'ROYGBIVROYGBIVGBIVGB', 'ROYGROYGROYGROYGRVIB', 'ROYGBIVOYGBOYGBOYGIV', 'ROYVGBIVGBIVGBIVGBIV', 'ROYGROYGROYGROYGRBIV']