from ..program2511 import program2511
def test21():
    assert program2511(29) == ['ROYGBIVGBIVGBIVGBIVGBIVGBIVGB', 'ROYBIVGBIVGBIVGBIVGBIVGBIVGBI', 'ROYGBIVROYGBIVROYGBIVROYGBIVG', 'ROYGBIVOYGBOYGBOYGBOYGBOYGBIV', 'ROYGROYGROYGROYGROYGROYGROBIV', 'ROYGBIVROYGBIVROYGBIVROYGBOYG', 'ROYGROYGROYGROYGROYGROYGROVIB', 'ROYVGBIVGBIVGBIVGBIVGBIVGBIVG']