from ..program2511 import program2511
def test15():
    assert program2511(21) == ['ROYVGBIVGBIVGBIVGBIVG', 'ROYBIVGBIVGBIVGBIVGBI', 'ROYGBIVROYGBIVROYGBIV', 'ROYGROYGROYGROYGROBIV', 'ROYGBIVGBIVGBIVGBIVGB', 'ROYGROYGROYGROYGROVIB', 'ROYGBIVOYGBOYGBOYGBIV']