from ..program2511 import program2511
def test16():
    assert program2511(22) == ['ROYGROYGROYGROYGROYVIB', 'ROYVGBIVGBIVGBIVGBIVGB', 'ROYGBIVOYGBOYGBOYGBOIV', 'ROYGROYGROYGROYGROYBIV', 'ROYGBIVROYGBIVROYGBOYG', 'ROYBIVGBIVGBIVGBIVGBIV', 'ROYGBIVROYGBIVROYGBIVG', 'ROYGBIVGBIVGBIVGBIVGBI']