from ..program2511 import program2511
def test20():
    assert program2511(28) == ['ROYGBIVGBIVGBIVGBIVGBIVGBIVG', 'ROYGROYGROYGROYGROYGROYGRBIV', 'ROYGBIVROYGBIVROYGBIVROYGBIV', 'ROYBIVGBIVGBIVGBIVGBIVGBIVGB', 'ROYVGBIVGBIVGBIVGBIVGBIVGBIV', 'ROYGBIVOYGBOYGBOYGBOYGBOYGIV', 'ROYGROYGROYGROYGROYGROYGRVIB']