from ..program2511 import program2511
def test12():
    assert program2511(18) == ['ROYGROYGROYGROYBIV', 'ROYGBIVROYGBIVGBIV', 'ROYBIVGBIVGBIVGBIV', 'ROYGBIVROYGBIVROYG', 'ROYGROYGROYGROYVIB', 'ROYGBIVGBIVGBIVGBI', 'ROYVGBIVGBIVGBIVGB', 'ROYGBIVOYGBOYGBOIV']