from ..program2511 import program2511
def test9():
    assert program2511(15) == ['ROYGBIVROYGBIVG', 'ROYGROYGROYGVIB', 'ROYGBIVROYGBOYG', 'ROYBIVGBIVGBIVG', 'ROYGROYGROYGBIV', 'ROYGBIVOYGBOYIV', 'ROYVGBIVGBIVGBI', 'ROYGBIVGBIVGBIV']