from ..program2511 import program2511
def test4():
    assert program2511(14) == ['ROYGROYGROYBIV', 'ROYGBIVROYGBIV', 'ROYVGBIVGBIVGB', 'ROYGBIVOYGBOIV', 'ROYBIVGBIVGBIV', 'ROYGROYGROYVIB', 'ROYGBIVGBIVGBI']