from ..program4663 import program4663
def test11():
    assert program4663(10
XXOOOOOXXO
OXOOXOOXXO
XOOXOXXXXO
OXXXXOXOXO
XXXOXXOXOO
OXOOOOOXOX
XOXOXOOOXO
OXXXOOOOOX
XXOOOOOXOO
XOXXXOOXXX
XXOXOXOXOX
OXXOXXXOXX
XOXXOXXOOO
XOXOOOXXOO
XOOXOXXOXO
OOOOOXOXOO
OXOOOOXXOO
XXOOXXOXXX
XOOXOOXXXX
XOXOXOOOOO) == ['No', 'NO']