from ..program4663 import program4663
def test12():
    assert program4663(10
XOOXOXXXXX
XOXXOXOXXX
OOOXOXOOOX
OOOXXXOOXX
OXOXXOXOXO
OXXOXOOOOO
OXOOXXOXXO
OOXOXXXXOX
XOXXXXOOXX
XOOOOXXOOX
XXXOOOXXXX
OXOXOXXOXX
OOXXOOOOXX
XOXOOXOOOX
XXXXOOXXXX
OXXXXXXOOO
OXOOOXXXXX
OXXOXOOOXO
OOOXXXOOOO
XXOOOOOOXX) == ['YES', 'Yes']