from ..program4663 import program4663
def test9():
    assert program4663(10
XXXOOOOXOX
OOOXXXOXXO
XOXXXXOOXX
XOOOXXOXOO
OOXOOOOOOX
XXXXOXOOOO
XXXOOXOXOX
OOOOXOXOXX
XOXXOXOOXO
OOOOOXOOOO
XXXOOOOXOX
OOOXXXOXXO
XOXXXXOOXX
XOOOXXOXOO
OOXOOOOOOX
XXXXOXOOOO
XXXOOXOXOX
OOOOXOXOXX
XOXXOXOOXO
OOOOOXOOOO) == ['YES', 'Yes']