from ..program4663 import program4663
def test18():
    assert program4663(10
XXXOOOOOXO
XXOXOOXOXX
XOXXXXXXXO
XOXOXOOXXX
XXOOXXOXXO
OOOOOOOOXX
OOXOXXOOXX
XXXXOXXOOO
XOXOXXXOXX
OXXOXXOOOO
OXOXOXXOXO
XXXXXXXOXO
OOXXXOOOOO
OXXOOOOXXO
OOXOXOXXXX
OOXXXOXOXX
OXXOOOOXOO
XOXXOOXXXX
XXOOXOOXOX
XXXXXOOXXO) == ['YES', 'Yes']