from ..program4663 import program4663
def test21():
    assert program4663(10
XXOOOOOXOX
OOOOXXXOXX
OOOXOOOOXX
OXXXXXXOOX
XOOXOXOOXX
XOOOOOOXXO
XXXOOOOXOO
OOOOXOXOOO
OXOOOOOXOX
XXOXXXOXOX
XXOOOXXXXO
OOOOXXOOXO
XXOXXOOOOX
XOXOOOXOXO
XOOOOXXOXO
XOXOOOXOXO
XOOXOXXXXO
OOOXOOXOOO
XXOXOXXOOX
XOOXXXOOOX) == ['No', 'NO']