from ..program4663 import program4663
def test17():
    assert program4663(10
XOXXXXXXXX
OOOOXXXOXO
XOXXXXOOXX
XXXOXXXXXO
OXXXXOXOOO
OOOOOXOXXX
XOOOXOOXXX
XOOOXXXXOO
OXOOXOXXOX
OXOXXOXXOX
XXOXXOOXOX
OOOXXOXXXX
XXXXXOXOOX
XXXOOXXOXO
OOXOXOXXXX
XXXXOXXXXX
XOOOOXOXOX
OOOXOXXXXX
XXOOOXXOOO
OOXXOOXOOX) == ['No', 'NO']