from ..program4663 import program4663
def test35():
    assert program4663(9
OXOXXXXOX
XOXXOXOOO
OOXOOOXOO
OOOXXOXOX
OOXOOOOXX
OXXXOXOOO
OOOXXOXOO
OOXOXXOXO
OOXOOOXOX
OXOOOOXOO
XOOOOXOOO
OXXOXXOXO
XXOXOXXOO
XOOOOOOXO
XXOOOXOXO
XOXOOOXOX
OOXOXOOXO
XOOXXOOOX) == ['No', 'NO']