from ..program4663 import program4663
def test20():
    assert program4663(10
XOXXXXXOOO
OXXOOXXOXX
XXXXXOOXOX
OOOOOXOXOX
OXXOXXXOXO
XOOXOXXXXX
XOOOOOOOOX
OOXXOOXXXX
OOOOXXOOOX
XXXXXOOOXX
XXOOOXXXXX
XOOOXXOOOO
XXXXOOXXOO
XOOOOOOOOX
XXXXXOXOOX
OXOXXXOXXO
XOXOXOOOOO
XOXOOXXXXX
XXOXXOOXXO
OOOXXXXXOX) == ['YES', 'Yes']