from ..program4663 import program4663
def test14():
    assert program4663(10
XOOOOXOOOX
OOOOOOOXXX
OXOOOXXOXO
OOXXXOOXOX
OOXXOOOXXO
XXXXOXOXXX
XXXOOXOOOO
XXXXOOXXXO
OXXXXXXOXX
XXXOOOXOXO
XOOOXOOOOX
XXXOOOOOOO
OXOXXOOOXO
XOXOOXXXOO
OXXOOOXXOO
XXXOXOXXXX
OOOOXOOXXX
OXXXOOXXXX
XXOXXXXXXO
OXOXOOOXXX) == ['YES', 'Yes']