from ..program4663 import program4663
def test13():
    assert program4663(10
XXOOXOOOXO
XXOXXXXXXX
XOOOXOOXXX
OXOOOXXXXO
XOOOOOOOOO
XXOXXXXOOX
OOOXOXOOOX
XOXOOXOOXO
OOXOOXOXXO
XOXOXOXXOO
OOOXXOOXXO
OXXOOOOXOX
XXOOOOXXXO
XOOOXOXOXO
OXXXXOXOXO
XOOOXOOXXX
OOOXXOOOXO
XXXOOOOOOO
OOOOXOXOXX
XOXOXXOXXX) == ['No', 'NO']