from ..program4663 import program4663
def test33():
    assert program4663(8
OXOOOOOO
XOXOXXXO
OXXXXXOX
OOXXOXOO
XOOOXOOO
XOOXXOXO
OOXXXXXX
XXXOOXXX
OXOOXXOO
XOXOOOOX
OOXXOOXX
OOXXOXXO
OXXOXXXX
OXOXXOXO
OXOOOXXX
OOXOOOXX) == ['No', 'NO']