from ..program4663 import program4663
def test32():
    assert program4663(8
OXOXXXXX
XXXXOXOO
OXOXOXOX
XXXOXXOX
OXXOXXXX
XXOXXXOO
XXXXOOOO
OXXXOOOO
OOOOXXXO
OOOOXXXX
OOXXXOXX
XXXXOXXO
XOXXOXXX
XOXOXOXO
OOXOXXXX
XXXXXOXO) == ['YES', 'Yes']