from ..program4663 import program4663
def test16():
    assert program4663(10
XXXOXOOXXX
OOXXOXXOXO
OOOOXOOXOX
XOOXOXOOXX
XOXXOXOOXX
OOOXXOXOXX
OOOXOOOOXO
OOXOOXXOXX
XXOXOOXOOX
OXXXOOXOXX
XXOXOOXXXO
XOOXOOXOXX
XXOXXOOXOO
OXOOOOXOOO
XXOXOXXOOO
XXOOXOXXOX
XXOOXOXOOX
XOXOOXOOOO
OXOXXOXXOO
XXXOOXOXXX) == ['YES', 'Yes']