from ..program4663 import program4663
def test19():
    assert program4663(10
XXOXOOOOXX
XOXXXOXOXO
OXXXOOXOOO
XXOXOOXXOX
XXOXXOXXOO
OOOXXXXOXO
OXXXOXOXOO
OXOXXXXXXX
XXXOOXXXXX
XXOOXOOXXO
XOOOOXXOXX
XXXXOXXXOX
OXOXOOOXXO
OOXXXXXXXX
XOXOXXOOXO
OXXXXOOOXX
OXXXXXXXXO
XXXXOXXOOO
XXXOXOOOXX
OXXXOOXOOX) == ['No', 'NO']