from ..program4663 import program4663
def test34():
    assert program4663(9
XXXOXOOXO
XOOOOXOOO
OOXXOXOXO
XXXXOXOXX
XXXXXXOXO
OOXOXXOXX
XXOXXXXXO
XXXOXOOOO
XXOOXOOXX
XXXOXOOXO
XOOOOXOOO
OOXXOXOXO
XXXXOXOXX
XXXXXXOXO
OOXOXXOXX
XXOXXXXXO
XXXOXOOOO
XXOOXOOXX) == ['YES', 'Yes']