from ..program4663 import program4663
def test15():
    assert program4663(10
XOXXOXXOOX
OXXOXOXXXX
XXOOXOXOOO
OXOOOOXOOO
OOOOOOOXOX
XXOXXOOXOX
XOXOXOOOOX
OXOXOOXXOX
XOXOXOXXXO
OOXOXXXXXX
OOXOOXXXXX
XOXOXOXXXO
OXOXOOXXOX
XOXXXOOOOX
XXOXXOOXOX
OOOOOOOXOX
OXOOOOXOOO
XXOOXOXOOO
OXXOXOXXXX
XOXOOXXOOX) == ['No', 'NO']