from ..program1752 import program1752
def test73():
    assert program1752(OOOOX.....
..........
..X.......
.X........
X.........
..........
..........
..........
..........
..........) == ['YES']