from ..program1752 import program1752
def test116():
    assert program1752(..........
.....OOOO.
..........
..........
..........
..........
..........
..........
..........
......XXXX) == ['YES']