from ..program1752 import program1752
def test144():
    assert program1752(.......XXX
X.........
..........
..........
..........
..........
..........
..........
..........
......OOOO) == ['NO']