from ..program1752 import program1752
def test150():
    assert program1752(..........
..........
OXXXXOOOO.
.........X
..........
..........
..........
..........
..........
..........) == ['NO']