from ..program1752 import program1752
def test40():
    assert program1752(OOO.......
...O....X.
.......X..
..........
.....X....
....X.....
..........
..........
..........
..........) == ['YES']