from ..program1752 import program1752
def test35():
    assert program1752(.........X
.....OOOO.
X.........
.X........
..X.......
..........
..........
..........
..........
..........) == ['NO']