from ..program1752 import program1752
def test94():
    assert program1752(..........
X.O.......
X..O......
X...O.....
X....O....
..........
..........
..........
..........
..........) == ['YES']