from ..program1752 import program1752
def test44():
    assert program1752(..O.......
OO.O......
......X...
..........
....X.....
...X......
..X.......
..........
..........
..........) == ['YES']