from ..program1752 import program1752
def test108():
    assert program1752(X.XX..XXXX
..........
..........
..........
..........
..........
..........
..........
..........
OOO.O.O.OO) == ['YES']