from ..program1752 import program1752
def test56():
    assert program1752(.....OOOOX
.XXX......
..........
..........
..........
..........
..........
..........
..........
..........) == ['NO']