from ..program1752 import program1752
def test64():
    assert program1752(O.....X...
.....X....
..........
...X..OOO.
..X.......
..........
..........
..........
..........
..........) == ['YES']