from ..program1752 import program1752
def test50():
    assert program1752(..O.......
OO.O......
..........
..........
..........
..........
..........
..........
..........
XXX.X.....) == ['YES']