from ..program1752 import program1752
def test9():
    assert program1752(..........
..........
..........
..........
..........
X.........
.........X
..........
..O.......
.O...X...O) == ['NO']