from ..program1752 import program1752
def test131():
    assert program1752(..........
..O.......
...O......
....O.....
.....O....
..........
.X........
..X.......
...X......
....X.....) == ['YES']