from ..program1752 import program1752
def test17():
    assert program1752(..........
..........
..........
.OOO.OOO..
.XXX.XXX..
..........
..........
..........
..........
..........) == ['YES']