from ..program1752 import program1752
def test129():
    assert program1752(XXXXOOOO..
..........
..........
..........
..........
..........
..........
..........
..........
..........) == ['NO']