from ..program1752 import program1752
def test46():
    assert program1752(XXOXXOOO..
..........
..........
..........
..O..X....
..O.X.....
..OXO.....
..X.......
..........
..........) == ['YES']