from ..program1752 import program1752
def test23():
    assert program1752(..........
..........
..........
..........
..........
..........
......X...
OOOO...X..
........X.
.........X) == ['YES']