from ..program1752 import program1752
def test32():
    assert program1752(..........
..........
..........
..........
..........
X.........
X.........
X.........
XOOOO.....
..........) == ['YES']