from ..program1752 import program1752
def test118():
    assert program1752(X.........
O.O.......
X..O......
X...O.....
X.........
..........
..........
..........
..........
..........) == ['NO']