from ..program1752 import program1752
def test28():
    assert program1752(..........
X.........
.O........
..XXX.....
..XOXO....
OXOOOO....
X.........
..........
..........
..........) == ['YES']