from ..program1752 import program1752
def test1():
    assert program1752(XXOXX.....
OO.O......
..........
..........
..........
..........
..........
..........
..........
..........) == ['NO']