from ..program1752 import program1752
def test154():
    assert program1752(XX.XX.....
..........
..........
....O.....
..........
......O...
..........
......O...
........O.
..........) == ['YES']