from ..program1752 import program1752
def test114():
    assert program1752(......XXXX
..O.......
...O......
....O.....
.....O....
..........
..........
..........
..........
..........) == ['YES']