from ..program1752 import program1752
def test57():
    assert program1752(....X.....
...X......
..X.......
.X........
..........
..........
OOOO......
..........
..........
..........) == ['YES']