from ..program1752 import program1752
def test14():
    assert program1752(....X.....
...X.OOOO.
..X.......
.X........
..........
..........
..........
..........
..........
..........) == ['YES']