from ..program1752 import program1752
def test112():
    assert program1752(....X.....
...X...O..
..X...O...
.....O....
X...O.....
..........
..........
..........
..........
..........) == ['YES']