from ..program1752 import program1752
def test86():
    assert program1752(.O........
..X...X...
...O.X....
....X.....
...X.X....
..O...X...
..XX...O..
..OOO.OO..
..........
..........) == ['YES']