from ..program1752 import program1752
def test54():
    assert program1752(..........
..X.......
...X......
....X.....
.....X....
......O...
..........
..OOO.....
..........
..........) == ['YES']