from ..program1752 import program1752
def test21():
    assert program1752(OOOO......
..........
..........
..........
..........
..........
......X...
.......X..
........X.
.........X) == ['YES']