from ..program1752 import program1752
def test138():
    assert program1752(..........
.......OX.
......OX..
.....OX...
....OX....
..........
..........
..........
..........
..........) == ['YES']