from ..program1752 import program1752
def test25():
    assert program1752(....X.....
...X.OOOO.
..X..OOOO.
.X........
..........
..........
X.........
X.........
X.........
X.........) == ['YES']