from ..program1752 import program1752
def test71():
    assert program1752(......XXXX
OOOO......
..........
..........
..........
..........
..........
..........
..........
..........) == ['YES']