from ..program1752 import program1752
def test123():
    assert program1752(..........
.....OOOO.
..........
..........
..........
..........
..........
..........
..........
...X.X.X.X) == ['NO']