from ..program1752 import program1752
def test10():
    assert program1752(......X...
..........
..X....X..
....O.....
..........
O.........
.....O...X
..........
..........
O.........) == ['NO']