from ..program1752 import program1752
def test81():
    assert program1752(..........
...X...OO.
..X....OO.
.X........
X.........
..........
..........
..........
..........
..........) == ['YES']