from ..program1752 import program1752
def test136():
    assert program1752(XOXXX.....
..O.......
...O......
....O.....
..........
..........
..........
..........
..........
..........) == ['NO']