from ..program1752 import program1752
def test90():
    assert program1752(.....OXXXX
..........
..........
..........
..........
..........
..........
..........
..........
......OOO.) == ['NO']