from ..program1752 import program1752
def test111():
    assert program1752(X.........
X.O.......
X..O......
X...O.....
O.........
..........
..........
..........
..........
..........) == ['NO']