from ..program1752 import program1752
def test16():
    assert program1752(....X.....
...X......
..........
.X........
X.........
..........
..........
..........
..........
......OOOO) == ['YES']