from ..program1752 import program1752
def test107():
    assert program1752(X.........
.OO.......
..XO......
...XO.....
....X.....
..........
..........
..........
..........
..........) == ['NO']