from ..program1752 import program1752
def test132():
    assert program1752(....X.....
.......O..
..X...O...
.X...O....
X...O.....
..........
..........
..........
..........
..........) == ['YES']