from ..program1752 import program1752
def test135():
    assert program1752(O.........
.XO.......
..XO......
...XO.....
....X.....
..........
..........
..........
..........
..........) == ['YES']