from ..program1752 import program1752
def test63():
    assert program1752(XXOXX.....
.....OOOO.
..........
.....X....
....X.....
..........
..X...O...
.X......O.
X..O..O...
..........) == ['YES']