from ..program1752 import program1752
def test84():
    assert program1752(..........
..........
..........
..........
.XXXXO....
....OOO...
..........
..........
..........
..........) == ['YES']