from ..program1752 import program1752
def test34():
    assert program1752(..........
..........
..........
OOOOX.....
..........
..X.......
.X........
X.........
..........
..........) == ['YES']