from ..program1752 import program1752
def test125():
    assert program1752(.....OXXXX
..O.......
...O......
....O.....
..........
..........
..........
..........
..........
..........) == ['NO']