from ..program1752 import program1752
def test122():
    assert program1752(....O.....
...X...O..
..X...O...
.X...O....
X.........
..........
..........
..........
..........
..........) == ['NO']