from ..program1752 import program1752
def test85():
    assert program1752(O.O.O.O.O.
..........
..........
..........
..........
..........
.XX.......
X.........
X.........
X.........) == ['NO']