from ..program1752 import program1752
def test104():
    assert program1752(XXXXO.....
..O.......
...O......
....O.....
..........
..........
..........
..........
..........
..........) == ['NO']