from ..program1752 import program1752
def test139():
    assert program1752(X.........
X.O.......
O..O......
X...O.....
X.........
..........
..........
..........
..........
..........) == ['NO']