from ..program1752 import program1752
def test36():
    assert program1752(..........
..........
..........
..........
..........
..O......X
..O.....X.
..O.......
..O...X...
.....X....) == ['YES']