from ..program1752 import program1752
def test153():
    assert program1752(.OOOOXXXX.
..........
..........
..........
..........
..........
..........
..........
..........
..........) == ['YES']