from ..program1752 import program1752
def test126():
    assert program1752(XXX.XXX...
OOO.OOO...
..........
..........
..........
..........
..........
..........
..........
..........) == ['YES']