from ..program1752 import program1752
def test146():
    assert program1752(XXXX......
..O.......
...O......
....O.....
.....O....
..........
..........
..........
..........
..........) == ['YES']