from ..program1752 import program1752
def test0():
    assert program1752(XX.XX.....
.....OOOO.
..........
..........
..........
..........
..........
..........
..........
..........) == ['YES']