from ..program1752 import program1752
def test2():
    assert program1752(XO........
.XO.......
..XO......
....O.....
....X.....
..........
..........
..........
..........
..........) == ['YES']