from ..program983 import program983
def test32():
    assert program983(CBZNWUBWUBWUBNHWUBWUBWUBYQSYWUBWUBWUBMWUBWUBWUBXRHBTMWUBWUBWUBPCRCWUBWUBWUBTZUYLYOWUBWUBWUBCYGCWUBWUBWUBCLJWUBWUBWUBSWUBWUBWUB) == ['CBZN NH YQSY M XRHBTM PCRC TZUYLYO CYGC CLJ S', 'CBZN   NH   YQSY   M   XRHBTM   PCRC   TZUYLYO   CYGC   CLJ   S']