from ..program983 import program983
def test36():
    assert program983(WUBWUBWUBMWUBWUBWUBQWUBWUBWUBITCFEYEWUBWUBWUBHEUWGNDFNZGWKLJWUBWUBWUBMZPWUBWUBWUBUWUBWUBWUBBWUBWUBWUBDTJWUBHZVIWUBWUBWUBPWUBFNHHWUBWUBWUBVTOWUB) == ['M   Q   ITCFEYE   HEUWGNDFNZGWKLJ   MZP   U   B   DTJ HZVI   P FNHH   VTO', 'M Q ITCFEYE HEUWGNDFNZGWKLJ MZP U B DTJ HZVI P FNHH VTO']