from ..program983 import program983
def test26():
    assert program983(WUBWUBNMMWCZOLYPNBELIYVDNHJUNINWUBWUBWUBDXLHYOWUBWUBWUBOJXUWUBWUBWUBRFHTGJCEFHCGWARGWUBWUBWUBJKWUBWUBSJWUBWUB) == ['NMMWCZOLYPNBELIYVDNHJUNIN   DXLHYO   OJXU   RFHTGJCEFHCGWARG   JK  SJ', 'NMMWCZOLYPNBELIYVDNHJUNIN DXLHYO OJXU RFHTGJCEFHCGWARG JK SJ']