from ..program983 import program983
def test15():
    assert program983(KWUBUPDYXGOKUWUBWUBWUBAGOAHWUBIZDWUBWUBWUBIYWUBWUBWUBVWUBWUBWUBPWUBWUBWUBE) == ['K UPDYXGOKU AGOAH IZD IY V P E', 'K UPDYXGOKU   AGOAH IZD   IY   V   P   E']