from ..program983 import program983
def test10():
    assert program983(VSRNVEATZTLGQRFEGBFPWUBWUBWUBAJWUBWUBWUBPQCHNWUBCWUB) == ['VSRNVEATZTLGQRFEGBFP AJ PQCHN C', 'VSRNVEATZTLGQRFEGBFP   AJ   PQCHN C']