from ..program983 import program983
def test22():
    assert program983(WUBWUBJWUBWUBWUBNFLWUBWUBWUBGECAWUBYFKBYJWTGBYHVSSNTINKWSINWSMAWUBWUBWUBFWUBWUBWUBOVWUBWUBLPWUBWUBWUBN) == ['J NFL GECA YFKBYJWTGBYHVSSNTINKWSINWSMA F OV LP N', 'J   NFL   GECA YFKBYJWTGBYHVSSNTINKWSINWSMA   F   OV  LP   N']