from ..program983 import program983
def test18():
    assert program983(WUBYYRTSMNWUWUBWUBWUBCWUBWUBWUBCWUBWUBWUBFSYUINDWOBVWUBWUBWUBFWUBWUBWUBAUWUBWUBWUBVWUBWUBWUBJB) == ['YYRTSMNWU C C FSYUINDWOBV F AU V JB', 'YYRTSMNWU   C   C   FSYUINDWOBV   F   AU   V   JB']