from ..program983 import program983
def test19():
    assert program983(WUBWUBYGPYEYBNRTFKOQCWUBWUBWUBUYGRTQEGWLFYWUBWUBWUBFVWUBHPWUBWUBWUBXZQWUBWUBWUBZDWUBWUBWUBM) == ['YGPYEYBNRTFKOQC   UYGRTQEGWLFY   FV HP   XZQ   ZD   M', 'YGPYEYBNRTFKOQC UYGRTQEGWLFY FV HP XZQ ZD M']