from ..program983 import program983
def test24():
    assert program983(WUBMPWUBWUBWUBORWUBWUBDLGKWUBWUBWUBVVZQCAAKVJTIKWUBWUBWUBTJLUBZJCILQDIFVZWUBWUBYXWUBWUBWUBQWUBWUBWUBLWUB) == ['MP OR DLGK VVZQCAAKVJTIK TJLUBZJCILQDIFVZ YX Q L', 'MP   OR  DLGK   VVZQCAAKVJTIK   TJLUBZJCILQDIFVZ  YX   Q   L']