from ..program983 import program983
def test35():
    assert program983(WUBWUBWUBIWUBWUBLIKNQVWUBWUBWUBPWUBWUBWUBHWUBWUBWUBMWUBWUBWUBDPRSWUBWUBWUBBSAGYLQEENWXXVWUBWUBWUBXMHOWUBWUBWUBUWUBWUBWUBYRYWUBWUBWUBCWUBWUBWUBY) == ['I LIKNQV P H M DPRS BSAGYLQEENWXXV XMHO U YRY C Y', 'I  LIKNQV   P   H   M   DPRS   BSAGYLQEENWXXV   XMHO   U   YRY   C   Y']