from ..program983 import program983
def test30():
    assert program983(WUBXEMWWVUHLSUUGRWUBWUBWUBAWUBXEGILZUNKWUBWUBWUBJDHHKSWUBWUBWUBDTSUYSJHWUBWUBWUBPXFWUBMOHNJWUBWUBWUBZFXVMDWUBWUBWUBZMWUBWUB) == ['XEMWWVUHLSUUGR A XEGILZUNK JDHHKS DTSUYSJH PXF MOHNJ ZFXVMD ZM', 'XEMWWVUHLSUUGR   A XEGILZUNK   JDHHKS   DTSUYSJH   PXF MOHNJ   ZFXVMD   ZM']