from ..program983 import program983
def test14():
    assert program983(IWUBWUBQLHDWUBYIIKZDFQWUBWUBWUBCXWUBWUBUWUBWUBWUBKWUBWUBWUBNL) == ['I  QLHD YIIKZDFQ   CX  U   K   NL', 'I QLHD YIIKZDFQ CX U K NL']