from ..program983 import program983
def test29():
    assert program983(WUBWUBWSPLAYSZSAUDSWUBWUBWUBUWUBWUBWUBKRWUBWUBWUBRSOKQMZFIYZQUWUBWUBWUBELSHUWUBWUBWUBUKHWUBWUBWUBQXEUHQWUBWUBWUBBWUBWUBWUBR) == ['WSPLAYSZSAUDS   U   KR   RSOKQMZFIYZQU   ELSHU   UKH   QXEUHQ   B   R', 'WSPLAYSZSAUDS U KR RSOKQMZFIYZQU ELSHU UKH QXEUHQ B R']