from ..program983 import program983
def test16():
    assert program983(WUBWUBOWUBWUBWUBIPVCQAFWYWUBWUBWUBQWUBWUBWUBXHDKCPYKCTWWYWUBWUBWUBVWUBWUBWUBFZWUBWUB) == ['O   IPVCQAFWY   Q   XHDKCPYKCTWWY   V   FZ', 'O IPVCQAFWY Q XHDKCPYKCTWWY V FZ']