from ..program983 import program983
def test23():
    assert program983(WUBWUBLCWUBWUBWUBZGEQUEATJVIXETVTWUBWUBWUBEXMGWUBWUBWUBRSWUBWUBWUBVWUBWUBWUBTAWUBWUBWUBCWUBWUBWUBQG) == ['LC   ZGEQUEATJVIXETVT   EXMG   RS   V   TA   C   QG', 'LC ZGEQUEATJVIXETVT EXMG RS V TA C QG']