from ..program983 import program983
def test20():
    assert program983(WUBZVMJWUBWUBWUBFOIMJQWKNZUBOFOFYCCWUBWUBWUBAUWWUBRDRADWUBWUBWUBCHQVWUBWUBWUBKFTWUBWUBWUBW) == ['ZVMJ FOIMJQWKNZUBOFOFYCC AUW RDRAD CHQV KFT W', 'ZVMJ   FOIMJQWKNZUBOFOFYCC   AUW RDRAD   CHQV   KFT   W']