from ..program983 import program983
def test12():
    assert program983(WUBWUBWUBFVWUBWUBWUBBPSWUBWUBWUBRXNETCJWUBWUBWUBJDMBHWUBWUBWUBBWUBWUBVWUBWUBB) == ['FV   BPS   RXNETCJ   JDMBH   B  V  B', 'FV BPS RXNETCJ JDMBH B V B']