from ..program983 import program983
def test27():
    assert program983(SGWLYSAUJOJBNOXNWUBWUBWUBBOSSFWKXPDPDCQEWUBWUBWUBDIRZINODWUBWUBWUBWWUBWUBWUBPPHWUBWUBWUBRWUBWUBWUBQWUBWUBWUBJWUB) == ['SGWLYSAUJOJBNOXN BOSSFWKXPDPDCQE DIRZINOD W PPH R Q J', 'SGWLYSAUJOJBNOXN   BOSSFWKXPDPDCQE   DIRZINOD   W   PPH   R   Q   J']