from ..program983 import program983
def test41():
    assert program983(WPPNMSQOQIWUBWUBWUBPNQXWUBWUBWUBHWUBWUBWUBNFLWUBWUBWUBGWSGAHVJFNUWUBWUBWUBFWUBWUBWUBWCMLRICFSCQQQTNBWUBWUBWUBSWUBWUBWUBKGWUBWUBWUBCWUBWUBWUBBMWUBWUBWUBRWUBWUB) == ['WPPNMSQOQI   PNQX   H   NFL   GWSGAHVJFNU   F   WCMLRICFSCQQQTNB   S   KG   C   BM   R', 'WPPNMSQOQI PNQX H NFL GWSGAHVJFNU F WCMLRICFSCQQQTNB S KG C BM R']