from ..program983 import program983
def test13():
    assert program983(WUBWUBWUBFBQWUBWUBWUBIDFSYWUBWUBWUBCTWDMWUBWUBWUBSXOWUBWUBWUBQIWUBWUBWUBL) == ['FBQ   IDFSY   CTWDM   SXO   QI   L', 'FBQ IDFSY CTWDM SXO QI L']