from ..program983 import program983
def test39():
    assert program983(WUBWUBWUBREHMWUBWUBWUBXWUBWUBWUBQASNWUBWUBWUBNLSMHLCMTICWUBWUBWUBVAWUBWUBWUBHNWUBWUBWUBNWUBWUBWUBUEXLSFOEULBWUBWUBWUBXWUBWUBWUBJWUBWUBWUBQWUBWUBWUBAWUBWUB) == ['REHM X QASN NLSMHLCMTIC VA HN N UEXLSFOEULB X J Q A', 'REHM   X   QASN   NLSMHLCMTIC   VA   HN   N   UEXLSFOEULB   X   J   Q   A']