from ..program983 import program983
def test17():
    assert program983(PAMJGYWUBWUBWUBXGPQMWUBWUBWUBTKGSXUYWUBWUBWUBEWUBWUBWUBNWUBWUBWUBHWUBWUBWUBEWUBWUB) == ['PAMJGY   XGPQM   TKGSXUY   E   N   H   E', 'PAMJGY XGPQM TKGSXUY E N H E']