from ..program894 import program894
def test16():
    assert program894(500
bfdalabnagjcojejahgifmbmgokfmmbnaflhbiiijnaidocachemkknjdbohmkciconnnigiciclgldngikjbmodfdfhegkcemlgngiadeffhliacnonnadnblkmmmbkicdemnjibokljonefjahllbkeaaecboadjfhnkhmmalnjfdmmkmjnabojdmfhelnkaehoaiojeajjahlhakikimbobejoeagkhcnadjogjocngaddbfekecokdhcjehenfegjjelekfjolajeibmaodkagkgfnjfinfgdcknbmgemobehekdcclmlfnkmodogedmhaieojgigklajkabjhcgldagaifoaggbibjajgilahejjcoaocncgmnefcglkjledcdcjehlondnilbnojikmomlfdagoaobmekadabiblijldngammojgkgjojhoanfclimkebkfdmoigjkmcnfmmddiahakdjdngffgdjaaklkecgj) == ['321']