from ..program894 import program894
def test36():
    assert program894(500
caccacbcaababbbacaaaacacbbcaccaaaabaacbbaaaabbbaacbbcbbaaccbcabccbbaabbbcbccbacabaabacabbbcbbacbbcbcbcacacbacbbbcccbaccccacaaccbcbcbccbacccabaaccaaabaaacbcaacccaaacacacbcaccbbcccabccacacabbcababaacbccbcbcabbabbbccbbabbbabcccbabcbababccabcaccbabbbbbcccacaccaabcbbbbaacbccccccabcccaacccbccbaabaaccbbbaaccbcacbcaaaacabaacbbaaacbcbcaabbbaccabbbcbacbbbabcbcccbccccbbcccacacbccaccacaccccaabcabcbbacccccbccbbbabbbbbbcbcccababccabaaaabccabaabbcbcbcabbccabababcabaabbabcccaabacaaaabbabaccbbacaacaabcacccbbcbcc) == ['164']