from ..program894 import program894
def test62():
    assert program894(500
aefceaacfeddedcdedacacfbeeedfabbebbeccadfaabfacceaacdcbdfeeaffebcadeecddeacadfcaffedccabdebccabbdbbbaefbfacecaacdefbddcfcbafeccfbaaadccbbccfbeaaeadebbaaafbebfaaccfbdddeedaaeddbfdadbacafcbfdffcceacceefecbcedacfbffddedcdeacbdbdedbcdcacfcbceddaadcfcdcdcaefbcbbafffccbabfdecaaeceeaaaceedaceeebdebbeaadecfefacaddefbbdaebedbfadeafdeccaeaffedefcebababceccfacceddabcecbebccdcabddfdeefcabdbddcccdbccdacddbbaeaeadcfeccbcaabfcabceadfababecccbbbcddddeabdbbeacdbcdfacaafeedeadcbabbfeffcebfcfaceaecdfddbdbbeeebaebe) == ['228']