from ..program894 import program894
def test42():
    assert program894(500
cccabbcdddcacdbdddddbabadacdcdabadbaddcbcaabddbaaaabcdcabbcccdcbdadbdcbadbaccdaccbcabbcbbcdcaacabbdcbabddccaaacadcdddaacaadcbbaabcbdcdacaddcabbcdadccdadbbacacbbaabaaccbabcbccdaacabaccaadaccdabacabbcbadddddaddaaabacdcbbddbbbcdabdacdadbdccbbccccbcbbabddadcadacabcbdacabbddcbcacbdbcccccbdbcaabbdbcbbdcbaccaabdbbcccadbddcdccbabcdcbbcbdadababcccdcddbadacbadbddbddacdadaddbaabbdcddcbdacbaabdcdacabddacabccacbcadabbadabcddaacbddbaabddabbcabbbbdbcabccdcdaccccdccccbdcbaaabdbddbdaabcdcdcdbdcbcdabaaaacaaacdbdb) == ['201']