from ..program894 import program894
def test54():
    assert program894(500
cbbbbbdeeaacadcbdcedeacaccbdababbeedcbbddacdaaacbabcedeccddeeecccddaedebcdadaacddeabbdacceedadeedacacecdcceecaaeaecbcaabdabaddabadecebdbddbadacbbcddedddadabbeddedeabdcaabccbbdadddeaecebaaeedbbbebddaecccebebcaebebddadceebedeecbbacadadcccdacecbdcebdcdcaceeedbcdddabdcabdeccadbdddabbbaebbdadadebadbeddeecebeddaaaadbaaebaeaebdaddccddbaddcadaeaacabcdeaddaedddbbacdcbeeaaecbecceadeeacceeaaddaecdadddbbeebeedecbaeacaceacccbdcbcaccaceccadcebacaebccdcacebbedeaaeccaddedccedceeedeecbaccbcebaeacbbcbeedabceaebdc) == ['213']