from ..program894 import program894
def test30():
    assert program894(500
abccacbaabaabaaccaaaacacbbcbccaababacbbbccbbcbcccabbccacbacbbacabbcbccccbcbbaccbcaacbacbbaaababccaccbcacaccccabbcbcbaacccbccabccaacccccccccbcabaacaaabccaaaabcccbcbbaabccabbbaaccbbcccbcccbabacbcabbbbccaaacaabcbabbbacacacbcaabbbacaaaaaaacbcabbcaccbcbaabacccacccabbbcbcbacccabcabbaabaacbcbaacbbccccbbbccaabcbcbbbccccccbbabcbabbacbaabaccabcabcabcbbabccacbbaacbcccbaaabacaaacaccbccbccaccccaccbbaabbaabbbccccbbcababcaaaaacbaabcaaccacbbabbbbcabbbbabbabbcaaabccacbcaccbbcabbaaababaaaccbbcccababacaabbccacccab) == ['161']