from ..program894 import program894
def test57():
    assert program894(500
edfeaaaaddffdbfbcebefebdfdadbdadcbbdbdcabfdbdeccaeebcdebdddfedcacbbefeabdbbdeceeacadbbbebffcebbaffdcabcedccddeeccdfbdedfeddcbebdadffbaacbbedbdbfdbcaecccbbcfefdbddabdeadeeeecffdbcfcbeabcdeeaaddeeddeadccdefbeaabfabadaddbfaddbecaaeccbdefececdbebbddffbbfcfdddcadbccedcecabdcfceeefcdbbfcaeccbcdcddbfabcbedfdcdfafabadbbcdcfbfccafafacacbcbfbcabefacedadfdbdbaeeffbcfdbcabdbdedbfcbadfcaafbaeadecdedcddecfdfddaadaebacabafcdcdeecefeddcfcceeddebccafbdbafffbecdbbbaaeebdabddaadadbbdceffdbbefccfbcbcbdaaefcabdebfba) == ['236']