from ..program894 import program894
def test61():
    assert program894(500
caebcfbedafeaedbedddbdecfafbbefdddcaedffbbddefacafdcfafddddfdaddddcbbaaddabadedacbbdfeaacabcbdebaadbbcacbcbdbfcfadfcfcfdabefacacdacccbebafdabdfcadcfbfdeacfccfbefebcbcadeccdcefdabcfffdbdaedeaabcdacfbaacfceafeaafcdfadcdfbdfbefdfedacecaaffefbaddbdbbbcaaddbabbeacfabceeaefeebedefbcfadbacdefeabdadcecacceaaaadfaaeaebebbdabbcbfbaddfbfcfddbaaccacabbbbcbbccedcfccffbbcededafcccbceeefcedafdebbbeebaafdbadebdfcfbbbebcbeccaccafbacffdccdcaecebcaadffffabeccfddeffcfedcadcefafcbeabcadabddbfaffbbffaccbafbacadbfbaaf) == ['233']