from ..program894 import program894
def test28():
    assert program894(500
ccbbbbaabaabccaabcaaccaabbaaaaaaaabaacccbcbccbccbbaabcbbbaacbbbacbccabbabacbcccbbaabbaaccbaacbcbcbabccbacbccccccbcbcbaaaaacabaabbbacabaababbbccaababbacbcbbacbbbbccbacaaccaaccbccbaacbcaaaaabacabbaaabcccaaacccabababbcbacaababcaabbcbacaabbcccccbccbaacacbcabaacbbababacabbcccbccccaababacbcbbaabaabcbaacaccbaacbbcbcbacbbbbabbcbbccabaabbaaabccabbbbbbaaabbbaabcabbbbbbcaaaabcbcbbcbbbbbbcabaababcabbabcacbaccaacacabbbbbcbaccacbbbcaacbbacccaabaababcbbacccababaabcabbccbbbabbaabacabcbabcaabcaacabcaaccacbcbbcaa) == ['161']