from ..program894 import program894
def test50():
    assert program894(500
cdeaeeedacbedcbbbcaaeccebccdeeddccdceabbaccbdabdeecccaeebddabbcdbedaababeaddbbecbdeaacebaebbbddeeccdeaedbdebebecccebebacdeadebedbdddcdbceacdedadeddaaaaeaddceaecdbedcdeabcacbaddcaebebdccbdcaacbacabbdabceaacdedacbcdadadeeecbceadaaaeceacadcaebcbaadddadeedbcdebcdcaccbccedcacaebcaccaadedddddaedaddaacecccbeececdeeccaaaebddeecccabbbdcbceeeedaceddaecdadcedacbdaebcbdddcedbdeadddebbaacccbabbcbaebceebacaddecadcdbccdeebabaccdcbababaaedbabbdadebeeacbbccaeabdcdceecbbcaedcadaccdaabdeabbaabebedcacedbeeaabdeeecb) == ['214']