from ..program894 import program894
def test48():
    assert program894(500
aadbeaacbbbbccaaadabcebbadddcaeeadcddeabdaaddedeceadeaeedbeaddddacbeadeeeabdcdbdedcdebabeaeeddbadbbcedbadbeddebcabaaeccecaeeeadbeccbabdecddecaeecbcedccdcddbcbbcdcedbbcbbecdadbdbbceeeabaadbacaaddebccededacadeecdbcbbedcbaeaccadcaaabcddeaeecabdebaaccecababccacbeeeabceacbbeecaebdebeddaeaeaebcacdeccbeebceddabaeedccdbaeaeebdedeecdccdcbddedcedacdceaacbadbaadcaececacaaebecaecababedebcdaceeedbbaeeadaecaadbcabacbecaecdeaeaedddeecaceabbcdceecedeacaebaddbaeacbccddcdabdedbeacccbdbabdccebaecaacacaabaeacedaaea) == ['223']