from ..program894 import program894
def test47():
    assert program894(500
ddaabdcccadcabacacdbaabacbaadcbcaadcbccabdbddbabacdaccbadaccabcddadccbdcbbacddcdccaccbddcbcdadadaabcacbddcabbaabbbdddccbdccdaadcbcabadbdccbdabacbdcacdcdacadcaaaaaaabaccccaaabcccbdabdaadbdcbaccabccddabdbabcbabbbbaccdadaaabdbdbcbdccddcdbabdaabbbcaadaaccbcbbdabbddaaacaddbbbccbbaacadcdbcbdddaaccbbcadbccccddbddbadcbcdbcbdccbcabacbabbddadcdabcbcdccddcbcdcaddadbccdbabaacddbcdbbcdcbcbdaddbdabacbdbcdbabbbcdcaabbccbabbabccdadabdccaabdadaadcdcddbbcbccbdbbbddacacddbdcdabcdaddcacdabacdacabbaddbadabcdabccbcba) == ['202']