from ..program894 import program894
def test53():
    assert program894(500
ebeeeeabaebabbacacccbcddbdadabdaedbecadecacdcdeccabdbbddbccabeccbdebdebedbaedeeaecccdadbcabbcdacadaddacbbbdaaeceaaeabbacdecacbebebbbbededccbdbbeddabcbebdabcccedabdbcccbbeebaecabcacbcdadcbebbadcbeadebccedaceebcebceeaacbbdcdacdcdedaddeedaddedadbccccdddcddccceaabcadecbebdeeeebcbcadedbdddaadcdceceaadeeadddacacaedaebbcbabacabacaaeecaebbabbeaeabecbddaaeaeadccdeebcedbdcaadceaaaaebaaccecccdecdeeccaaeeeccbdcebedbcadabceedbcecbbeacbadcccdaebbdddacaacadcdbaeeecdadbccbebebbaddeecbceebaaacdecabeabdaecaeaceac) == ['215']