from ..program894 import program894
def test31():
    assert program894(500
cbbbcababbbbbcccbcccabbcaabcabcaaacccabcbbbaacabacbbbcbbccbacbbcabbbacbbabcbccabbababcaabcbabcbababbbaaaaaabcbcccaaaabaaaccaacbcbabccaaaccabccaaabcaacbcaacccccabbbbabaacacbbaabcbcabaaabbbabababccbacbcbbcccbcabacbbbbccbbcacbbbccacacacabccacbccabbbabbabcccabbccbabccccbbbcabcabcccabbababcbcccababccacbaaacaabcbbccbbcccbcbcabbacbabacaccaaacacbbacacbccaaccbbcabcbcacabbaccaccccbacbbcacccacabccbabbbbcbbbbabccbaabbabcaaccbbbaccbacaccbbbabaacabbcbbbaacaacaabaacbcbaaccbbaabbcabbacbcaabccbbccbcbcabbcbcbaaca) == ['174']