from ..program894 import program894
def test15():
    assert program894(500
fnfckgnagbnmhglkdliekejfciahennmjahibikiimkdfcblgcgegenjeaaiddhehkdemeibehbbnahfkdbhkddbgjamfakhgjefljbfnegkgbldkknmmlailkjmmimnfgnccghgnnemignlmnedminddglamlllaekjgjnfcjiaafgnmheedlknlgacebdkgccgkchjhacbbiddjhjhgdkedbcfnaniaaimibgkkdgmnegiandbdmnchehkcidfegaakndccljlganndfbnkenmgcflhammgiggcfmdcjnmncdgfaejaadelhjemekdnlbklcfjaeblhgbccjgechgniedfngfhjidjgangcfabnlblmiadabeeahfdfjhlkfmecnddbhcjgkjfejemfilhdcihfcenmbmblijkiilndnkafdejjnlgnadcllinjnfkfjnbleljledmjbleihgdicmcefaihhbmhnejmcieamkhebme) == ['314']