from ..program894 import program894
def test34():
    assert program894(500
bbacbbaacbcabaabbaaccbbbbccacabacabbaaabcccaacbaaaaaaccbaabaaabcabbacbaacaaaabcbacbcbcbccaaccacbacbcbbcaccbccbabacbaacacacccabaabbacbcaacacbcbacaabbcacbcaccbbcbbacabacbbaccababacbccacaababbbacbbbbbaccacbaabbccccbbababaaccbbabbbcaabbbaacccacbcabbacbabbcbbbbbbcabcaabcbbcabbbcaabaaaaccaaacaccbbbcbabcacbacbacbcabccabbccaabacabbbbacacbbbabcbacbccccabcacbbbcabccacabaabcabababbbcbacabbbbccabccaacaabbbbacabaabcaccbaabcbccbabaaccbbabbbbcbcbcbcccbbbbbbbabbaaacabbaccacabcabbbabbaabcbcabacaabcabacbbbaaacabb) == ['172']