from ..program894 import program894
def test19():
    assert program894(500
bfhofhrkimdpgpnjhelnqlgbjpddbanmdfqciedrdgednbjjinlmbormkckfcqghoibpcadmnigckajnklngnmpoaiaepajkhegipdadoipgmcncncbhcjkhfechneecqmchnqgpaqkrhipgnqcojhaliokihgqbadmkkcffkeorbjorqbbojiqlpdlohbmhmlmliadlbrpcdmfckfgdqcpflghdfkqceminjlollkbmqreeilffqigjelerjpiakllbgiogqdpkochbjpnppagaooqdgocnnrpkeiekhkibrfjdbkfmlnmbgejcfklgnaacrpnhakkpinnolnbikcrqlgfhcoqpaainlklpamdeapnqpcgflfnlgkpcicdbiodgdngaeaanbjhnfbgogclpherrqodalbbpjkfiohpqngmfialgdejlgddkqrhgnblbqkamajnehebbnkcrlhnrnlcoondjhhnghecmlqfogbiaggkl) == ['335']