from ..program894 import program894
def test58():
    assert program894(500
cffaebdcbfbfbacefefbaeedaddacbdcfaeadcadcacaaacaadedebeecaebfdbcffaceadeedddbdfadcebcdffbafefcaecafcafbfccdeefadecfcbafaedbcecdbabdfbbfdeebabdaecbababcebbbdaadffbeffeffcfeefaccdfeafffeaaedfbbdafedecfdefbcaadecbffaadeadfecffaffdeeddbbadeadcfafbceaffabfefcddceeefacaceeffeefbcfcadaeeeabeebfcabbebddcdcedddddbceadbdddfeadafabfebdbcdeedadbbfacaeedefeafedbecbaafecffbaffbbfadfdfcebabddebcedacaaaafdfdefbaafdcfacfbddbfbdefcebdabcfdfaeebcbfbacffabbbbbdbfedebabbedadbaecbedbdeadddcfffaebdececfcbbbbcdecaacddb) == ['238']