from ..program1750 import program1750
def test139():
    assert program1750(X.........
X.O.......
O..O......
X...O.....
X.........
..........
..........
..........
..........
..........) == ['NO']