from ..program1750 import program1750
def test1():
    assert program1750(XXOXX.....
OO.O......
..........
..........
..........
..........
..........
..........
..........
..........) == ['NO']