from ..program1750 import program1750
def test50():
    assert program1750(..O.......
OO.O......
..........
..........
..........
..........
..........
..........
..........
XXX.X.....) == ['YES']