from ..program1750 import program1750
def test23():
    assert program1750(..........
..........
..........
..........
..........
..........
......X...
OOOO...X..
........X.
.........X) == ['YES']