from ..program1750 import program1750
def test94():
    assert program1750(..........
X.O.......
X..O......
X...O.....
X....O....
..........
..........
..........
..........
..........) == ['YES']