from ..program1750 import program1750
def test86():
    assert program1750(.O........
..X...X...
...O.X....
....X.....
...X.X....
..O...X...
..XX...O..
..OOO.OO..
..........
..........) == ['YES']