from ..program1750 import program1750
def test129():
    assert program1750(XXXXOOOO..
..........
..........
..........
..........
..........
..........
..........
..........
..........) == ['NO']