from ..program1750 import program1750
def test144():
    assert program1750(.......XXX
X.........
..........
..........
..........
..........
..........
..........
..........
......OOOO) == ['NO']