from ..program1750 import program1750
def test151():
    assert program1750(X.........
X....OOOO.
..........
X.........
X.........
..........
..........
..........
..........
..........) == ['YES']