from ..program1750 import program1750
def test32():
    assert program1750(..........
..........
..........
..........
..........
X.........
X.........
X.........
XOOOO.....
..........) == ['YES']