from ..program1750 import program1750
def test54():
    assert program1750(..........
..X.......
...X......
....X.....
.....X....
......O...
..........
..OOO.....
..........
..........) == ['YES']