from ..program1750 import program1750
def test118():
    assert program1750(X.........
O.O.......
X..O......
X...O.....
X.........
..........
..........
..........
..........
..........) == ['NO']