from ..program1750 import program1750
def test148():
    assert program1750(OOO.O.....
..........
..........
..........
..........
.......X..
..........
.....X....
....X.....
...X......) == ['YES']