from ..program1750 import program1750
def test72():
    assert program1750(..........
..........
..O.......
...O......
....O.....
.....O....
......X...
.......X..
........X.
.........X) == ['NO']