from ..program1750 import program1750
def test46():
    assert program1750(XXOXXOOO..
..........
..........
..........
..O..X....
..O.X.....
..OXO.....
..X.......
..........
..........) == ['YES']