from ..program1750 import program1750
def test109():
    assert program1750(O.........
X.O.......
X..O......
X...O.....
X.........
..........
..........
..........
..........
..........) == ['YES']