from ..program1750 import program1750
def test106():
    assert program1750(..........
.....X....
....X.....
...X......
..X.......
..........
...OOOO...
..........
..........
..........) == ['YES']