from ..program1750 import program1750
def test45():
    assert program1750(....X.....
...X......
..X.......
..........
X.........
..........
..OOOO....
..........
..........
..........) == ['YES']