from ..program1750 import program1750
def test20():
    assert program1750(..........
.....OOOO.
..........
..........
..........
..........
.....X....
....X.....
...X......
..X.......) == ['YES']