from ..program1750 import program1750
def test73():
    assert program1750(OOOOX.....
..........
..X.......
.X........
X.........
..........
..........
..........
..........
..........) == ['YES']