from ..program1750 import program1750
def test25():
    assert program1750(....X.....
...X.OOOO.
..X..OOOO.
.X........
..........
..........
X.........
X.........
X.........
X.........) == ['YES']