from ..program1750 import program1750
def test120():
    assert program1750(X.........
..O.......
X..O......
X...O.....
X....O....
..........
..........
..........
..........
..........) == ['YES']