from ..program1750 import program1750
def test112():
    assert program1750(....X.....
...X...O..
..X...O...
.....O....
X...O.....
..........
..........
..........
..........
..........) == ['YES']