from ..program1750 import program1750
def test122():
    assert program1750(....O.....
...X...O..
..X...O...
.X...O....
X.........
..........
..........
..........
..........
..........) == ['NO']