from ..program1750 import program1750
def test138():
    assert program1750(..........
.......OX.
......OX..
.....OX...
....OX....
..........
..........
..........
..........
..........) == ['YES']