from ..program1750 import program1750
def test111():
    assert program1750(X.........
X.O.......
X..O......
X...O.....
O.........
..........
..........
..........
..........
..........) == ['NO']