from ..program1750 import program1750
def test135():
    assert program1750(O.........
.XO.......
..XO......
...XO.....
....X.....
..........
..........
..........
..........
..........) == ['YES']