from ..program1750 import program1750
def test116():
    assert program1750(..........
.....OOOO.
..........
..........
..........
..........
..........
..........
..........
......XXXX) == ['YES']