from ..program1750 import program1750
def test150():
    assert program1750(..........
..........
OXXXXOOOO.
.........X
..........
..........
..........
..........
..........
..........) == ['NO']