from ..program1750 import program1750
def test28():
    assert program1750(..........
X.........
.O........
..XXX.....
..XOXO....
OXOOOO....
X.........
..........
..........
..........) == ['YES']