from ..program1750 import program1750
def test36():
    assert program1750(..........
..........
..........
..........
..........
..O......X
..O.....X.
..O.......
..O...X...
.....X....) == ['YES']