from ..program1750 import program1750
def test126():
    assert program1750(XXX.XXX...
OOO.OOO...
..........
..........
..........
..........
..........
..........
..........
..........) == ['YES']