from ..program1750 import program1750
def test114():
    assert program1750(......XXXX
..O.......
...O......
....O.....
.....O....
..........
..........
..........
..........
..........) == ['YES']