from ..program1750 import program1750
def test64():
    assert program1750(O.....X...
.....X....
..........
...X..OOO.
..X.......
..........
..........
..........
..........
..........) == ['YES']