from ..program1750 import program1750
def test153():
    assert program1750(.OOOOXXXX.
..........
..........
..........
..........
..........
..........
..........
..........
..........) == ['YES']