from ..program1750 import program1750
def test35():
    assert program1750(.........X
.....OOOO.
X.........
.X........
..X.......
..........
..........
..........
..........
..........) == ['NO']