from ..program1750 import program1750
def test84():
    assert program1750(..........
..........
..........
..........
.XXXXO....
....OOO...
..........
..........
..........
..........) == ['YES']