from ..program1750 import program1750
def test0():
    assert program1750(XX.XX.....
.....OOOO.
..........
..........
..........
..........
..........
..........
..........
..........) == ['YES']