from ..program1750 import program1750
def test44():
    assert program1750(..O.......
OO.O......
......X...
..........
....X.....
...X......
..X.......
..........
..........
..........) == ['YES']