from ..program1750 import program1750
def test154():
    assert program1750(XX.XX.....
..........
..........
....O.....
..........
......O...
..........
......O...
........O.
..........) == ['YES']