from ..program1750 import program1750
def test125():
    assert program1750(.....OXXXX
..O.......
...O......
....O.....
..........
..........
..........
..........
..........
..........) == ['NO']