from ..program1750 import program1750
def test81():
    assert program1750(..........
...X...OO.
..X....OO.
.X........
X.........
..........
..........
..........
..........
..........) == ['YES']