from ..program1750 import program1750
def test90():
    assert program1750(.....OXXXX
..........
..........
..........
..........
..........
..........
..........
..........
......OOO.) == ['NO']