from ..program1750 import program1750
def test56():
    assert program1750(.....OOOOX
.XXX......
..........
..........
..........
..........
..........
..........
..........
..........) == ['NO']