from ..program1750 import program1750
def test71():
    assert program1750(......XXXX
OOOO......
..........
..........
..........
..........
..........
..........
..........
..........) == ['YES']