from ..program1750 import program1750
def test17():
    assert program1750(..........
..........
..........
.OOO.OOO..
.XXX.XXX..
..........
..........
..........
..........
..........) == ['YES']