from ..program1750 import program1750
def test136():
    assert program1750(XOXXX.....
..O.......
...O......
....O.....
..........
..........
..........
..........
..........
..........) == ['NO']