from ..program1750 import program1750
def test99():
    assert program1750(..........
...X...O..
..X...O...
.X...O....
X...O.....
..........
..........
..........
..........
..........) == ['YES']