from ..program1750 import program1750
def test2():
    assert program1750(XO........
.XO.......
..XO......
....O.....
....X.....
..........
..........
..........
..........
..........) == ['YES']