from ..program1750 import program1750
def test76():
    assert program1750(..........
..........
......XXXX
..........
..........
..........
..........
..OOOO....
..........
..........) == ['YES']