from ..program1750 import program1750
def test104():
    assert program1750(XXXXO.....
..O.......
...O......
....O.....
..........
..........
..........
..........
..........
..........) == ['NO']