from ..program1750 import program1750
def test107():
    assert program1750(X.........
.OO.......
..XO......
...XO.....
....X.....
..........
..........
..........
..........
..........) == ['NO']