from ..program1750 import program1750
def test108():
    assert program1750(X.XX..XXXX
..........
..........
..........
..........
..........
..........
..........
..........
OOO.O.O.OO) == ['YES']