from ..program1750 import program1750
def test10():
    assert program1750(......X...
..........
..X....X..
....O.....
..........
O.........
.....O...X
..........
..........
O.........) == ['NO']