from ..program1750 import program1750
def test14():
    assert program1750(....X.....
...X.OOOO.
..X.......
.X........
..........
..........
..........
..........
..........
..........) == ['YES']