from ..program1750 import program1750
def test63():
    assert program1750(XXOXX.....
.....OOOO.
..........
.....X....
....X.....
..........
..X...O...
.X......O.
X..O..O...
..........) == ['YES']