from ..program1750 import program1750
def test40():
    assert program1750(OOO.......
...O....X.
.......X..
..........
.....X....
....X.....
..........
..........
..........
..........) == ['YES']