from ..program900 import program900
def test14():
    assert program900(HVDEBKMJTLKQORNWCZSGXYIPUAF) == ['JMKBEDVHFAUPI\r\nTLQORNWCZSGXY', 'IPUAFHVDEBKMJ\r\nYXGSZCWNROQLT', 'XGSZCWNROQKMJ\r\nYIPUAFHVDEBLT', 'TLQORNWCZSGXY\r\nJMKBEDVHFAUPI']