from ..program900 import program900
def test6():
    assert program900(BMVFGRNDOWTILZVHAKCQSXYEJUP) == ['YEJUPBMVFGRND\r\nXSQCKAHZLITWO', 'OWTILZHAKCQSX\r\nDNRGFVMBPUJEY', 'DNRGFVMBPUJEY\r\nOWTILZHAKCQSX', 'XSQCKAHVFGRND\r\nYEJUPBMZLITWO']