from ..program900 import program900
def test41():
    assert program900(ABCDEFGHIJKLMNOPQRSTUVWYXYZ) == ['YWVUTSRQPONML\r\nXZABCDEFGHIJK', 'KJIHGFEDCBAZY\r\nLMNOPQRSTUVWX', 'LMNOPQRSTUVWY\r\nKJIHGFEDCBAZX', 'XZABCDEFGHIJK\r\nYWVUTSRQPONML']