from ..program900 import program900
def test42():
    assert program900(BUVTYZFQSNRIWOXGJLKACPEMDHB) == ['WIRNSQFZYTVUB\r\nOXGJLKACPEMDH', 'BUVTYZFQSNRIW\r\nHDMEPCAKLJGXO', 'OXGJLKACPEMDH\r\nWIRNSQFZYTVUB']