from ..program900 import program900
def test4():
    assert program900(ZWMFLTCQIAJEVUPODMSGXKHRNYB) == ['HKXGSMFLTCQIA\r\nRNYBZWDOPUVEJ', 'NYBZWMFLTCQIA\r\nRHKXGSDOPUVEJ', 'AIQCTLFMWZBYN\r\nJEVUPODSGXKHR', 'JEVUPODSGXKHR\r\nAIQCTLFMWZBYN']