from ..program900 import program900
def test8():
    assert program900(YOFJVQSWBUZENPCXGQTHMDKAILR) == ['ENPCXGTHMDKAI\r\nZUBWSQVJFOYRL', 'IAKDMHTQSWBUZ\r\nLRYOFJVGXCPNE', 'ZUBWSQVJFOYRL\r\nENPCXGTHMDKAI', 'LRYOFJVQSWBUZ\r\nIAKDMHTGXCPNE']