from ..program900 import program900
def test34():
    assert program900(UOWJXRKHZDNGLSAMEIYTQBVCFJP) == ['UPJXRKHZDNGLS\r\nOWFCVBQTYIEMA', 'AMEIYTQBVCFPU\r\nSLGNDZHKRXJWO', 'OWJXRKHZDNGLS\r\nUPFCVBQTYIEMA', 'SLGNDZHKRXJWO\r\nAMEIYTQBVCFPU']