from ..program900 import program900
def test20():
    assert program900(TEGXHBUVZDPAMIJFQYCWRKSTNLO) == ['APDZVUBHXGETO\r\nMIJFQYCWRKSNL', 'NTEGXHBUVZDPA\r\nLOSKRWCYQFJIM', 'OTEGXHBUVZDPA\r\nLNSKRWCYQFJIM', 'MIJFQYCWRKSNL\r\nAPDZVUBHXGETO']