from ..program900 import program900
def test29():
    assert program900(HIDCLZUTPOQGEXFASJNYBVRMDKW) == ['WKDCLZUTPOQGE\r\nHIMRVBYNJSAFX', 'EGQOPTUZLCDIH\r\nXFASJNYBVRMKW', 'XFASJNYBVRMKW\r\nEGQOPTUZLCDIH', 'HIDCLZUTPOQGE\r\nWKMRVBYNJSAFX']