from ..program900 import program900
def test13():
    assert program900(RFKNZXHAIMVBWEBPTCSYOLJGDQU) == ['QDGJLOYSCTPBW\r\nURFKNZXHAIMVE', 'WBVMIAHXZNKFR\r\nEPTCSYOLJGDQU', 'RFKNZXHAIMVBW\r\nUQDGJLOYSCTPE', 'EPTCSYOLJGDQU\r\nWBVMIAHXZNKFR']