from ..program900 import program900
def test44():
    assert program900(ABCBDEFGHIJKLMNOPQRSTUVWXYZ) == ['PQRSTUVWXYZAB\r\nONMLKJIHGFEDC', 'CDEFGHIJKLMNO\r\nBAZYXWVUTSRQP', 'ONMLKJIHGFEDB\r\nPQRSTUVWXYZAC', 'BAZYXWVUTSRQP\r\nCDEFGHIJKLMNO']