from ..program900 import program900
def test9():
    assert program900(GYCUAXSBNAWFIJPDQVETKZOMLHR) == ['ZOMLHRGYCUAXS\r\nKTEVQDPJIFWNB', 'SXAUCYGRHLMOZ\r\nBNWFIJPDQVETK', 'BNWFIJPDQVETK\r\nSXAUCYGRHLMOZ', 'TEVQDPJIFWAXS\r\nKZOMLHRGYCUNB']