from ..program900 import program900
def test38():
    assert program900(ABCDEFGHIJKLMNOPQRSTUVWXYZG) == ['DEFGHIJKLMNOP\r\nCBAZYXWVUTSRQ', 'CBAGHIJKLMNOP\r\nDEFZYXWVUTSRQ', 'QRSTUVWXYZABC\r\nPONMLKJIHGFED', 'PONMLKJIHGFED\r\nQRSTUVWXYZABC']