from ..program900 import program900
def test17():
    assert program900(XECPFJBHINOWVLAGTUMRZYHQSDK) == ['ALVWONIHBJFPC\r\nGTUMRZYQSDKXE', 'GTUMRZYQSDKXE\r\nALVWONIHBJFPC', 'CPFJBHINOWVLA\r\nEXKDSQYZRMUTG', 'XKDSQHINOWVLA\r\nECPFJBYZRMUTG']