from ..program900 import program900
def test12():
    assert program900(XTSHBGLRJAMDUIPCWYOZVERNKQF) == ['CWYOZVENKQFXT\r\nPIUDMAJRLGBHS', 'PIUDMAJRLGBHS\r\nCWYOZVENKQFXT', 'XFQKNRJAMDUIP\r\nTSHBGLEVZOYWC', 'SHBGLRJAMDUIP\r\nTXFQKNEVZOYWC']