from ..program900 import program900
def test25():
    assert program900(UNGHFQRCIPBZTEOAYJXLDMSKNWV) == ['WNGHFQRCIPBZT\r\nVUKSMDLXJYAOE', 'EOAYJXLDMSKWV\r\nTZBPICRQFHGNU', 'TZBPICRQFHGNU\r\nEOAYJXLDMSKWV', 'UNGHFQRCIPBZT\r\nVWKSMDLXJYAOE']