from ..program900 import program900
def test28():
    assert program900(BETRFOVLPCMWKHAXSGUDQYJTZIN) == ['IZTRFOVLPCMWK\r\nNBEJYQDUGSXAH', 'KWMCPLVOFRTEB\r\nHAXSGUDQYJZIN', 'BETRFOVLPCMWK\r\nNIZJYQDUGSXAH', 'HAXSGUDQYJZIN\r\nKWMCPLVOFRTEB']