from ..program900 import program900
def test33():
    assert program900(ZWFIRJNXVKHOUSTQBLEGYMAPIDC) == ['WFIRJNXVKHOUS\r\nZCDPAMYGELBQT', 'CDIRJNXVKHOUS\r\nZWFPAMYGELBQT', 'TQBLEGYMAPDCZ\r\nSUOHKVXNJRIFW', 'SUOHKVXNJRIFW\r\nTQBLEGYMAPDCZ']