from ..program900 import program900
def test45():
    assert program900(ABCDEFGHIJKLMNOPQRSTUVWXAYZ) == ['ZABCDEFGHIJKL\r\nYXWVUTSRQPONM', 'LKJIHGFEDCBAZ\r\nMNOPQRSTUVWXY', 'MNOPQRSTUVWXY\r\nLKJIHGFEDCBAZ', 'YABCDEFGHIJKL\r\nZXWVUTSRQPONM']