from ..program900 import program900
def test0():
    assert program900(ABCDEFGHIJKLMNOPQRSGTUVWXYZ) == ['MLKJIHGFEDCBA\r\nNOPQRSTUVWXYZ', 'YXWVUTGHIJKLM\r\nZABCDEFSRQPON', 'NOPQRSTUVWXYZ\r\nMLKJIHGFEDCBA', 'ABCDEFGHIJKLM\r\nZYXWVUTSRQPON']