from ..program900 import program900
def test11():
    assert program900(XCDSLTYWJIGUBPHNFZWVMQARKOE) == ['XCDSLTYWJIGUB\r\nEOKRAQMVZFNHP', 'BUGIJWYTLSDCX\r\nPHNFZVMQARKOE', 'PHNFZVMQARKOE\r\nBUGIJWYTLSDCX', 'OKRAQMVWJIGUB\r\nEXCDSLTYZFNHP']