from ..program900 import program900
def test39():
    assert program900(ABCDEFGHGIJKLMNOPQRSTUVWXYZ) == ['TSRQPONMLKJIG\r\nUVWXYZABCDEFH', 'UVWXYZABCDEFG\r\nTSRQPONMLKJIH', 'HIJKLMNOPQRST\r\nGFEDCBAZYXWVU', 'GFEDCBAZYXWVU\r\nHIJKLMNOPQRST']