from ..program900 import program900
def test47():
    assert program900(BACDEFGHIJKLMNOPQRSTUVWXYZA) == ['NMLKJIHGFEDCA\r\nOPQRSTUVWXYZB', 'OPQRSTUVWXYZB\r\nNMLKJIHGFEDCA', 'ACDEFGHIJKLMN\r\nBZYXWVUTSRQPO']