from ..program900 import program900
def test43():
    assert program900(QWERTYUIOPASDFGHJKLZXCVBNMQ) == ['DSAPOIUYTREWQ\r\nFGHJKLZXCVBNM', 'FGHJKLZXCVBNM\r\nDSAPOIUYTREWQ', 'QWERTYUIOPASD\r\nMNBVCXZLKJHGF']