from ..program900 import program900
def test26():
    assert program900(MKBGVNDJRAWUEHFSYLIZCOPTXKQ) == ['EUWARJDNVGBKM\r\nHFSYLIZCOPTXQ', 'MKBGVNDJRAWUE\r\nQXTPOCZILYSFH', 'QKBGVNDJRAWUE\r\nMXTPOCZILYSFH', 'HFSYLIZCOPTXQ\r\nEUWARJDNVGBKM']