from ..program900 import program900
def test31():
    assert program900(LCFNHUQWXBPOSJMYTGKDAZVREIF) == ['MYTGKDAZVREIL\r\nJSOPBXWQUHNFC', 'JSOPBXWQUHNFC\r\nMYTGKDAZVREIL', 'LFNHUQWXBPOSJ\r\nCIERVZADKGTYM', 'CFNHUQWXBPOSJ\r\nLIERVZADKGTYM']