from ..program900 import program900
def test27():
    assert program900(UTGDEJHCBKRWLYFSONAQVMPIXZT) == ['YLWRKBCHJEDGT\r\nFSONAQVMPIXZU', 'FSONAQVMPIXZU\r\nYLWRKBCHJEDGT', 'TGDEJHCBKRWLY\r\nUZXIPMVQANOSF']