from ..program900 import program900
def test32():
    assert program900(OURNQJWMIXCLGSDVEKZAFBYNTPH) == ['GLCXIMWJQNRUO\r\nSDVEKZAFBYTPH', 'HPTNQJWMIXCLG\r\nOURYBFAZKEVDS', 'SDVEKZAFBYTPH\r\nGLCXIMWJQNRUO', 'OURNQJWMIXCLG\r\nHPTYBFAZKEVDS']