from ..program900 import program900
def test46():
    assert program900(ABCDEFGHIJKLMZYXWVUTSRQPONA) == ['MLKJIHGFEDCBA\r\nZYXWVUTSRQPON', 'ABCDEFGHIJKLM\r\nNOPQRSTUVWXYZ', 'ZYXWVUTSRQPON\r\nMLKJIHGFEDCBA']