from ..program900 import program900
def test36():
    assert program900(ABCDEFGHIJKLMNOPQRSTUVWXYZA) == ['MLKJIHGFEDCBA\r\nNOPQRSTUVWXYZ', 'ABCDEFGHIJKLM\r\nZYXWVUTSRQPON', 'NOPQRSTUVWXYZ\r\nMLKJIHGFEDCBA']