from ..program900 import program900
def test35():
    assert program900(IHDTJLGRFUXQSOZEMVYKWCPANBT) == ['DTJLGRFUXQSOZ\r\nHIBNAPCWKYVME', 'ITJLGRFUXQSOZ\r\nHDBNAPCWKYVME', 'ZOSQXUFRGLJTD\r\nEMVYKWCPANBIH', 'EMVYKWCPANBIH\r\nZOSQXUFRGLJTD']