from ..program900 import program900
def test7():
    assert program900(MKNTKOBFLJSXWQPVUERDHIACYGZ) == ['VPQWXSJLFBOKN\r\nUERDHIACYGZMT', 'ERDHIACYGZMKN\r\nUVPQWXSJLFBOT', 'TOBFLJSXWQPVU\r\nNKMZGYCAIHDRE', 'NKMZGYCAIHDRE\r\nTOBFLJSXWQPVU']