from ..program900 import program900
def test15():
    assert program900(XZTMCRBONHFIUVPKWSDLJQGAHYE) == ['WKPVUIFHNOBRC\r\nSDLJQGAYEXZTM', 'CRBONHFIUVPKW\r\nMTZXEYAGQJLDS', 'TZXEYHFIUVPKW\r\nMCRBONAGQJLDS', 'SDLJQGAYEXZTM\r\nWKPVUIFHNOBRC']