from ..program900 import program900
def test23():
    assert program900(NMGIFDZKBCVRYLTWOASXHEUQPJN) == ['NMGIFDZKBCVRY\r\nJPQUEHXSAOWTL', 'LTWOASXHEUQPJ\r\nYRVCBKZDFIGMN', 'YRVCBKZDFIGMN\r\nLTWOASXHEUQPJ']