from ..program900 import program900
def test37():
    assert program900(ABACDEFGHIJKLMNOPQRSTUVWXYZ) == ['NMLKJIHGFEDCA\r\nOPQRSTUVWXYZB', 'BCDEFGHIJKLMN\r\nAZYXWVUTSRQPO', 'AZYXWVUTSRQPO\r\nBCDEFGHIJKLMN', 'OPQRSTUVWXYZA\r\nNMLKJIHGFEDCB']