from ..program900 import program900
def test3():
    assert program900(UTEDBZRVWLOFUASHCYIPXGJMKNQ) == ['ZBDETUQNKMJGX\r\nRVWLOFASHCYIP', 'RVWLOFASHCYIP\r\nZBDETUQNKMJGX', 'PIYCHSAUTEDBZ\r\nXGJMKNQFOLWVR', 'XGJMKNQUTEDBZ\r\nPIYCHSAFOLWVR']