from ..program900 import program900
def test40():
    assert program900(ABCDEFGHIJKLMNOPQRSTUVWXYZX) == ['ZABCDEFGHIJKL\r\nYXWVUTSRQPONM', 'YXWVUTSRQPONM\r\nZABCDEFGHIJKL', 'MNOPQRSTUVWXY\r\nLKJIHGFEDCBAZ', 'KJIHGFEDCBAXY\r\nLMNOPQRSTUVWZ']