from ..program900 import program900
def test16():
    assert program900(YAMVOHUJLEDCWZLXNRGPIQTBSKF) == ['KFYAMVOHUJLED\r\nSBTQIPGRNXZWC', 'SBTQIPGRNXLED\r\nKFYAMVOHUJZWC', 'DELJUHOVMAYFK\r\nCWZXNRGPIQTBS', 'CWZXNRGPIQTBS\r\nDELJUHOVMAYFK']