from ..program900 import program900
def test30():
    assert program900(CNHIKJWRLPXTQZVUGYDMBAOEFHS) == ['VUGYDMBAOEFSC\r\nZQTXPLRWJKIHN', 'SHIKJWRLPXTQZ\r\nCNFEOABMDYGUV', 'ZQTXPLRWJKIHN\r\nVUGYDMBAOEFSC', 'NHIKJWRLPXTQZ\r\nCSFEOABMDYGUV']