from ..program900 import program900
def test22():
    assert program900(MIDLBEUAGTNPYKFWHVSRJOXCZMQ) == ['KFWHVSRJOXCZQ\r\nYPNTGAUEBLDIM', 'YPNTGAUEBLDIM\r\nKFWHVSRJOXCZQ', 'MIDLBEUAGTNPY\r\nQZCXOJRSVHWFK']