from ..program900 import program900
def test5():
    assert program900(QGZEMFKWLUHOVSXJTCPIYREDNAB) == ['QGZEMFKWLUHOV\r\nBANDRYIPCTJXS', 'SXJTCPIYRDNAB\r\nVOHULWKFMEZGQ', 'VOHULWKFMEZGQ\r\nSXJTCPIYRDNAB', 'ANDEMFKWLUHOV\r\nBQGZRYIPCTJXS']