from ..program900 import program900
def test21():
    assert program900(XQVBTCNIRFPLOHAYZUMKWEJSXDG) == ['OHAYZUMKWEJSD\r\nLPFRINCTBVQXG', 'DXQVBTCNIRFPL\r\nGSJEWKMUZYAHO', 'LPFRINCTBVQXG\r\nOHAYZUMKWEJSD', 'GXQVBTCNIRFPL\r\nDSJEWKMUZYAHO']