from ..program900 import program900
def test24():
    assert program900(AHGZCRJTKPMQUNBWSIYLDXEHFVO) == ['VFHGZCRJTKPMQ\r\nOAEXDLYISWBNU', 'OAHGZCRJTKPMQ\r\nVFEXDLYISWBNU', 'UNBWSIYLDXEFV\r\nQMPKTJRCZGHAO', 'QMPKTJRCZGHAO\r\nUNBWSIYLDXEFV']