from ..program4825 import program4825
def test21():
    assert program4825(gfejleepamadbcobamcodcqqbbgpjhbenlfciikqqlnekpbhcnmmnbajpqlqoenfpeebjbohlkfhhfldajgikkfmdcinneqedepidkepomqgpbbjjkncnqpcjejbknjpjqoaiipbainpknhhngjoeallqfddhfdlajdgpqbbeefodleicgqckikgcihfpfopcfqmdpqqfpkoeplgmkoohejhjpoflbffeqpbialqkmiembdaehmhmjleilpfpdf...) == ['0']