from ..program4825 import program4825
def test64():
    assert program4825(aigbdfeedcadiddafbgdffaaidbigifahgieghchddeggbigeabfiibfaefdcifebchichiehefiihieehdebcgigcihiabeaiediaeifadgbdfcebaighfceachfebdbiiffgfebeeaaaigidhcgibegfddaaaiiidgbbaeecdcediehfedifggfebhehfbbdceffihfdaabgfaaehfeeaheagfhhddaehffgheffagcdhgeadhigfbifiiifd...) == ['0']