from ..program4825 import program4825
def test34():
    assert program4825(jiibcmeabmdjmffdccbianelecbbgecebkighmjfhgjgmkbkfendaadbnfmcianhgdinabjfnbajhicdeilcmfkbjmjeichahcfegekkjgaknngmibdlifhfiiihljahknilhnihljmjhhklafcgmihinldffjgebdlagmkghabhalbihfekcbllfdgdlmcilkalaellbmdjggcbcmghkenlkljmhbfgjiimdibjnhmdfmnfammfejbbikdkhcb...) == ['835013663']