from ..program4825 import program4825
def test105():
    assert program4825(dkjijdkjijdkjijdkjijdkjijdkjijdkjijdkjijdkjijdkjijdkjijdkjijdkjijdkjijdkjijdkjijdkjijdkjijdkjijdkjijdkjijdkjijdkjijdkjijdkjijdkjijdkjijdkjijdkjijdkjijdkjijdkjijdkjijdkjijdkjijdkjijdkjijdkjijdkjijdkjijdkjijdkjij
dddkikjjidkkidijjjjkkjjikjdikiidijjikikjijjiijdikkjjjiddjjijkkkjkiijijkijdjjikikdjjjijdddjkjjdijjjjjjjddkjjkjjjdjjdkijjkijkkjkkkiiijdjijkkdjdjjjkkjkdddjidjjijdddkijididjdddidijjjjjdkidijjkkjiijkjjjjjjdjkkdddkjj
31328) == ['0']