from ..program4825 import program4825
def test36():
    assert program4825(dacemehkboajmgkialdlegndmdhhgilckmbabbfobecflnjmeocgifkcildjikmliihfbcmgbdlcnjlhefikoahadbofaflkdbamhahlohmjjoogkbaammihldgklggligmdobmjnimfngjjinfodbkklgnmebncgjgbhiianbdllbgdfjgdegkeejchobfkahheeibkniibjaiifnbonnodoombgdbceadeffccklndajkcjdlboldoagfhhoe...) == ['0']