from ..program4825 import program4825
def test44():
    assert program4825(dkfdgbbmmjdakghficginlncnmfbidnfdfclkafglnniddbbaajedkjbhijmlnddaiiknneblmfingkkblhbkkgfabngflkfhjhcgnilflhalfgmgnecbjnecfldhhlfkdbiffhmbealfdklbggjieeinmafckeclbinmjndndjkdmbfkfljgbjbjcflglmghjbhknldjbbglihbfejaaiidgfbfglalenkeiemhcnffeaglcjgakfclgbbkadf...) == ['0']