from ..program981 import program981
def test35():
    assert program981(WUBWUBWUBIWUBWUBLIKNQVWUBWUBWUBPWUBWUBWUBHWUBWUBWUBMWUBWUBWUBDPRSWUBWUBWUBBSAGYLQEENWXXVWUBWUBWUBXMHOWUBWUBWUBUWUBWUBWUBYRYWUBWUBWUBCWUBWUBWUBY) == ['I LIKNQV P H M DPRS BSAGYLQEENWXXV XMHO U YRY C Y', 'I  LIKNQV   P   H   M   DPRS   BSAGYLQEENWXXV   XMHO   U   YRY   C   Y']