from ..program981 import program981
def test17():
    assert program981(PAMJGYWUBWUBWUBXGPQMWUBWUBWUBTKGSXUYWUBWUBWUBEWUBWUBWUBNWUBWUBWUBHWUBWUBWUBEWUBWUB) == ['PAMJGY   XGPQM   TKGSXUY   E   N   H   E', 'PAMJGY XGPQM TKGSXUY E N H E']