from ..program981 import program981
def test23():
    assert program981(WUBWUBLCWUBWUBWUBZGEQUEATJVIXETVTWUBWUBWUBEXMGWUBWUBWUBRSWUBWUBWUBVWUBWUBWUBTAWUBWUBWUBCWUBWUBWUBQG) == ['LC   ZGEQUEATJVIXETVT   EXMG   RS   V   TA   C   QG', 'LC ZGEQUEATJVIXETVT EXMG RS V TA C QG']