from ..program981 import program981
def test36():
    assert program981(WUBWUBWUBMWUBWUBWUBQWUBWUBWUBITCFEYEWUBWUBWUBHEUWGNDFNZGWKLJWUBWUBWUBMZPWUBWUBWUBUWUBWUBWUBBWUBWUBWUBDTJWUBHZVIWUBWUBWUBPWUBFNHHWUBWUBWUBVTOWUB) == ['M   Q   ITCFEYE   HEUWGNDFNZGWKLJ   MZP   U   B   DTJ HZVI   P FNHH   VTO', 'M Q ITCFEYE HEUWGNDFNZGWKLJ MZP U B DTJ HZVI P FNHH VTO']