from ..program981 import program981
def test11():
    assert program981(WUBWUBEWUBWUBWUBIQMJNIQWUBWUBWUBGZZBQZAUHYPWUBWUBWUBPMRWUBWUBWUBDCV) == ['E IQMJNIQ GZZBQZAUHYP PMR DCV', 'E   IQMJNIQ   GZZBQZAUHYP   PMR   DCV']