from ..program981 import program981
def test15():
    assert program981(KWUBUPDYXGOKUWUBWUBWUBAGOAHWUBIZDWUBWUBWUBIYWUBWUBWUBVWUBWUBWUBPWUBWUBWUBE) == ['K UPDYXGOKU AGOAH IZD IY V P E', 'K UPDYXGOKU   AGOAH IZD   IY   V   P   E']