from ..program981 import program981
def test20():
    assert program981(WUBZVMJWUBWUBWUBFOIMJQWKNZUBOFOFYCCWUBWUBWUBAUWWUBRDRADWUBWUBWUBCHQVWUBWUBWUBKFTWUBWUBWUBW) == ['ZVMJ FOIMJQWKNZUBOFOFYCC AUW RDRAD CHQV KFT W', 'ZVMJ   FOIMJQWKNZUBOFOFYCC   AUW RDRAD   CHQV   KFT   W']