from ..program981 import program981
def test19():
    assert program981(WUBWUBYGPYEYBNRTFKOQCWUBWUBWUBUYGRTQEGWLFYWUBWUBWUBFVWUBHPWUBWUBWUBXZQWUBWUBWUBZDWUBWUBWUBM) == ['YGPYEYBNRTFKOQC   UYGRTQEGWLFY   FV HP   XZQ   ZD   M', 'YGPYEYBNRTFKOQC UYGRTQEGWLFY FV HP XZQ ZD M']