from ..program981 import program981
def test28():
    assert program981(TOWUBWUBWUBGBTBNWUBWUBWUBJVIOJBIZFUUYHUAIEBQLQXPQKZJMPTCWBKPOSAWUBWUBWUBSWUBWUBWUBTOLVXWUBWUBWUBNHWUBWUBWUBO) == ['TO   GBTBN   JVIOJBIZFUUYHUAIEBQLQXPQKZJMPTCWBKPOSA   S   TOLVX   NH   O', 'TO GBTBN JVIOJBIZFUUYHUAIEBQLQXPQKZJMPTCWBKPOSA S TOLVX NH O']