from ..program981 import program981
def test10():
    assert program981(VSRNVEATZTLGQRFEGBFPWUBWUBWUBAJWUBWUBWUBPQCHNWUBCWUB) == ['VSRNVEATZTLGQRFEGBFP AJ PQCHN C', 'VSRNVEATZTLGQRFEGBFP   AJ   PQCHN C']