from ..program981 import program981
def test14():
    assert program981(IWUBWUBQLHDWUBYIIKZDFQWUBWUBWUBCXWUBWUBUWUBWUBWUBKWUBWUBWUBNL) == ['I  QLHD YIIKZDFQ   CX  U   K   NL', 'I QLHD YIIKZDFQ CX U K NL']