from ..program981 import program981
def test24():
    assert program981(WUBMPWUBWUBWUBORWUBWUBDLGKWUBWUBWUBVVZQCAAKVJTIKWUBWUBWUBTJLUBZJCILQDIFVZWUBWUBYXWUBWUBWUBQWUBWUBWUBLWUB) == ['MP OR DLGK VVZQCAAKVJTIK TJLUBZJCILQDIFVZ YX Q L', 'MP   OR  DLGK   VVZQCAAKVJTIK   TJLUBZJCILQDIFVZ  YX   Q   L']