from ..program981 import program981
def test16():
    assert program981(WUBWUBOWUBWUBWUBIPVCQAFWYWUBWUBWUBQWUBWUBWUBXHDKCPYKCTWWYWUBWUBWUBVWUBWUBWUBFZWUBWUB) == ['O   IPVCQAFWY   Q   XHDKCPYKCTWWY   V   FZ', 'O IPVCQAFWY Q XHDKCPYKCTWWY V FZ']