from ..program981 import program981
def test12():
    assert program981(WUBWUBWUBFVWUBWUBWUBBPSWUBWUBWUBRXNETCJWUBWUBWUBJDMBHWUBWUBWUBBWUBWUBVWUBWUBB) == ['FV   BPS   RXNETCJ   JDMBH   B  V  B', 'FV BPS RXNETCJ JDMBH B V B']