from ..program981 import program981
def test18():
    assert program981(WUBYYRTSMNWUWUBWUBWUBCWUBWUBWUBCWUBWUBWUBFSYUINDWOBVWUBWUBWUBFWUBWUBWUBAUWUBWUBWUBVWUBWUBWUBJB) == ['YYRTSMNWU C C FSYUINDWOBV F AU V JB', 'YYRTSMNWU   C   C   FSYUINDWOBV   F   AU   V   JB']