from ..program981 import program981
def test13():
    assert program981(WUBWUBWUBFBQWUBWUBWUBIDFSYWUBWUBWUBCTWDMWUBWUBWUBSXOWUBWUBWUBQIWUBWUBWUBL) == ['FBQ   IDFSY   CTWDM   SXO   QI   L', 'FBQ IDFSY CTWDM SXO QI L']