from ..program980 import program980
def test40():
    assert program980(WUBWUBWUBSTEZTZEFFIWUBWUBWUBSWUBWUBWUBCWUBFWUBHRJPVWUBWUBWUBDYJUWUBWUBWUBPWYDKCWUBWUBWUBCWUBWUBWUBUUEOGCVHHBWUBWUBWUBEXLWUBWUBWUBVCYWUBWUBWUBMWUBWUBWUBYWUB) == ['STEZTZEFFI   S   C F HRJPV   DYJU   PWYDKC   C   UUEOGCVHHB   EXL   VCY   M   Y', 'STEZTZEFFI S C F HRJPV DYJU PWYDKC C UUEOGCVHHB EXL VCY M Y']