from ..program980 import program980
def test18():
    assert program980(WUBYYRTSMNWUWUBWUBWUBCWUBWUBWUBCWUBWUBWUBFSYUINDWOBVWUBWUBWUBFWUBWUBWUBAUWUBWUBWUBVWUBWUBWUBJB) == ['YYRTSMNWU C C FSYUINDWOBV F AU V JB', 'YYRTSMNWU   C   C   FSYUINDWOBV   F   AU   V   JB']