from ..program980 import program980
def test20():
    assert program980(WUBZVMJWUBWUBWUBFOIMJQWKNZUBOFOFYCCWUBWUBWUBAUWWUBRDRADWUBWUBWUBCHQVWUBWUBWUBKFTWUBWUBWUBW) == ['ZVMJ FOIMJQWKNZUBOFOFYCC AUW RDRAD CHQV KFT W', 'ZVMJ   FOIMJQWKNZUBOFOFYCC   AUW RDRAD   CHQV   KFT   W']