from ..program980 import program980
def test14():
    assert program980(IWUBWUBQLHDWUBYIIKZDFQWUBWUBWUBCXWUBWUBUWUBWUBWUBKWUBWUBWUBNL) == ['I  QLHD YIIKZDFQ   CX  U   K   NL', 'I QLHD YIIKZDFQ CX U K NL']