from ..program980 import program980
def test32():
    assert program980(CBZNWUBWUBWUBNHWUBWUBWUBYQSYWUBWUBWUBMWUBWUBWUBXRHBTMWUBWUBWUBPCRCWUBWUBWUBTZUYLYOWUBWUBWUBCYGCWUBWUBWUBCLJWUBWUBWUBSWUBWUBWUB) == ['CBZN NH YQSY M XRHBTM PCRC TZUYLYO CYGC CLJ S', 'CBZN   NH   YQSY   M   XRHBTM   PCRC   TZUYLYO   CYGC   CLJ   S']