from ..program980 import program980
def test21():
    assert program980(WUBWUBZBKOKHQLGKRVIMZQMQNRWUBWUBWUBDACWUBWUBNZHFJMPEYKRVSWUBWUBWUBPPHGAVVPRZWUBWUBWUBQWUBWUBAWUBG) == ['ZBKOKHQLGKRVIMZQMQNR   DAC  NZHFJMPEYKRVS   PPHGAVVPRZ   Q  A G', 'ZBKOKHQLGKRVIMZQMQNR DAC NZHFJMPEYKRVS PPHGAVVPRZ Q A G']