from ..program980 import program980
def test27():
    assert program980(SGWLYSAUJOJBNOXNWUBWUBWUBBOSSFWKXPDPDCQEWUBWUBWUBDIRZINODWUBWUBWUBWWUBWUBWUBPPHWUBWUBWUBRWUBWUBWUBQWUBWUBWUBJWUB) == ['SGWLYSAUJOJBNOXN BOSSFWKXPDPDCQE DIRZINOD W PPH R Q J', 'SGWLYSAUJOJBNOXN   BOSSFWKXPDPDCQE   DIRZINOD   W   PPH   R   Q   J']