from ..program980 import program980
def test23():
    assert program980(WUBWUBLCWUBWUBWUBZGEQUEATJVIXETVTWUBWUBWUBEXMGWUBWUBWUBRSWUBWUBWUBVWUBWUBWUBTAWUBWUBWUBCWUBWUBWUBQG) == ['LC   ZGEQUEATJVIXETVT   EXMG   RS   V   TA   C   QG', 'LC ZGEQUEATJVIXETVT EXMG RS V TA C QG']