from ..program980 import program980
def test12():
    assert program980(WUBWUBWUBFVWUBWUBWUBBPSWUBWUBWUBRXNETCJWUBWUBWUBJDMBHWUBWUBWUBBWUBWUBVWUBWUBB) == ['FV   BPS   RXNETCJ   JDMBH   B  V  B', 'FV BPS RXNETCJ JDMBH B V B']