from ..program980 import program980
def test34():
    assert program980(WUBWUBWUBISERPQITVIYERSCNWUBWUBWUBQWUBWUBWUBDGSDIPWUBWUBWUBCAHKDZWEXBIBJVVSKKVQJWUBWUBWUBKIWUBWUBWUBCWUBWUBWUBAWUBWUBWUBPWUBWUBWUBHWUBWUBWUBF) == ['ISERPQITVIYERSCN   Q   DGSDIP   CAHKDZWEXBIBJVVSKKVQJ   KI   C   A   P   H   F', 'ISERPQITVIYERSCN Q DGSDIP CAHKDZWEXBIBJVVSKKVQJ KI C A P H F']