from ..program980 import program980
def test17():
    assert program980(PAMJGYWUBWUBWUBXGPQMWUBWUBWUBTKGSXUYWUBWUBWUBEWUBWUBWUBNWUBWUBWUBHWUBWUBWUBEWUBWUB) == ['PAMJGY   XGPQM   TKGSXUY   E   N   H   E', 'PAMJGY XGPQM TKGSXUY E N H E']