from ..program980 import program980
def test10():
    assert program980(VSRNVEATZTLGQRFEGBFPWUBWUBWUBAJWUBWUBWUBPQCHNWUBCWUB) == ['VSRNVEATZTLGQRFEGBFP AJ PQCHN C', 'VSRNVEATZTLGQRFEGBFP   AJ   PQCHN C']