from ..program980 import program980
def test13():
    assert program980(WUBWUBWUBFBQWUBWUBWUBIDFSYWUBWUBWUBCTWDMWUBWUBWUBSXOWUBWUBWUBQIWUBWUBWUBL) == ['FBQ   IDFSY   CTWDM   SXO   QI   L', 'FBQ IDFSY CTWDM SXO QI L']