from ..program980 import program980
def test33():
    assert program980(DPDWUBWUBWUBEUQKWPUHLTLNXHAEKGWUBRRFYCAYZFJDCJLXBAWUBWUBWUBHJWUBOJWUBWUBWUBNHBJEYFWUBWUBWUBRWUBWUBWUBSWUBWWUBWUBWUBXDWUBWUBWUBJWUB) == ['DPD   EUQKWPUHLTLNXHAEKG RRFYCAYZFJDCJLXBA   HJ OJ   NHBJEYF   R   S W   XD   J', 'DPD EUQKWPUHLTLNXHAEKG RRFYCAYZFJDCJLXBA HJ OJ NHBJEYF R S W XD J']