from ..program980 import program980
def test28():
    assert program980(TOWUBWUBWUBGBTBNWUBWUBWUBJVIOJBIZFUUYHUAIEBQLQXPQKZJMPTCWBKPOSAWUBWUBWUBSWUBWUBWUBTOLVXWUBWUBWUBNHWUBWUBWUBO) == ['TO   GBTBN   JVIOJBIZFUUYHUAIEBQLQXPQKZJMPTCWBKPOSA   S   TOLVX   NH   O', 'TO GBTBN JVIOJBIZFUUYHUAIEBQLQXPQKZJMPTCWBKPOSA S TOLVX NH O']