from ..program980 import program980
def test16():
    assert program980(WUBWUBOWUBWUBWUBIPVCQAFWYWUBWUBWUBQWUBWUBWUBXHDKCPYKCTWWYWUBWUBWUBVWUBWUBWUBFZWUBWUB) == ['O   IPVCQAFWY   Q   XHDKCPYKCTWWY   V   FZ', 'O IPVCQAFWY Q XHDKCPYKCTWWY V FZ']