from ..program980 import program980
def test25():
    assert program980(WUBNXOLIBKEGXNWUBWUBWUBUWUBGITCNMDQFUAOVLWUBWUBWUBAIJDJZJHFMPVTPOXHPWUBWUBWUBISCIOWUBWUBWUBGWUBWUBWUBUWUB) == ['NXOLIBKEGXN U GITCNMDQFUAOVL AIJDJZJHFMPVTPOXHP ISCIO G U', 'NXOLIBKEGXN   U GITCNMDQFUAOVL   AIJDJZJHFMPVTPOXHP   ISCIO   G   U']