from ..program980 import program980
def test38():
    assert program980(WUBOJMWRSLAXXHQRTPMJNCMPGWUBWUBWUBNYGMZIXNLAKSQYWDWUBWUBWUBXNIWUBWUBWUBFWUBWUBWUBXMBWUBWUBWUBIWUBWUBWUBINWUBWUBWUBWDWUBWUBWUBDDWUBWUBWUBD) == ['OJMWRSLAXXHQRTPMJNCMPG NYGMZIXNLAKSQYWD XNI F XMB I IN WD DD D', 'OJMWRSLAXXHQRTPMJNCMPG   NYGMZIXNLAKSQYWD   XNI   F   XMB   I   IN   WD   DD   D']