from ..program980 import program980
def test11():
    assert program980(WUBWUBEWUBWUBWUBIQMJNIQWUBWUBWUBGZZBQZAUHYPWUBWUBWUBPMRWUBWUBWUBDCV) == ['E IQMJNIQ GZZBQZAUHYP PMR DCV', 'E   IQMJNIQ   GZZBQZAUHYP   PMR   DCV']