from ..program980 import program980
def test31():
    assert program980(BMBWUBWUBWUBOQKWUBWUBWUBPITCIHXHCKLRQRUGXJWUBWUBWUBVWUBWUBWUBJCWUBWUBWUBQJPWUBWUBWUBBWUBWUBWUBBMYGIZOOXWUBWUBWUBTAGWUBWUBHWUB) == ['BMB OQK PITCIHXHCKLRQRUGXJ V JC QJP B BMYGIZOOX TAG H', 'BMB   OQK   PITCIHXHCKLRQRUGXJ   V   JC   QJP   B   BMYGIZOOX   TAG  H']