from ..program980 import program980
def test24():
    assert program980(WUBMPWUBWUBWUBORWUBWUBDLGKWUBWUBWUBVVZQCAAKVJTIKWUBWUBWUBTJLUBZJCILQDIFVZWUBWUBYXWUBWUBWUBQWUBWUBWUBLWUB) == ['MP OR DLGK VVZQCAAKVJTIK TJLUBZJCILQDIFVZ YX Q L', 'MP   OR  DLGK   VVZQCAAKVJTIK   TJLUBZJCILQDIFVZ  YX   Q   L']