from ..program980 import program980
def test19():
    assert program980(WUBWUBYGPYEYBNRTFKOQCWUBWUBWUBUYGRTQEGWLFYWUBWUBWUBFVWUBHPWUBWUBWUBXZQWUBWUBWUBZDWUBWUBWUBM) == ['YGPYEYBNRTFKOQC   UYGRTQEGWLFY   FV HP   XZQ   ZD   M', 'YGPYEYBNRTFKOQC UYGRTQEGWLFY FV HP XZQ ZD M']