from ..program980 import program980
def test26():
    assert program980(WUBWUBNMMWCZOLYPNBELIYVDNHJUNINWUBWUBWUBDXLHYOWUBWUBWUBOJXUWUBWUBWUBRFHTGJCEFHCGWARGWUBWUBWUBJKWUBWUBSJWUBWUB) == ['NMMWCZOLYPNBELIYVDNHJUNIN   DXLHYO   OJXU   RFHTGJCEFHCGWARG   JK  SJ', 'NMMWCZOLYPNBELIYVDNHJUNIN DXLHYO OJXU RFHTGJCEFHCGWARG JK SJ']