from ..program980 import program980
def test39():
    assert program980(WUBWUBWUBREHMWUBWUBWUBXWUBWUBWUBQASNWUBWUBWUBNLSMHLCMTICWUBWUBWUBVAWUBWUBWUBHNWUBWUBWUBNWUBWUBWUBUEXLSFOEULBWUBWUBWUBXWUBWUBWUBJWUBWUBWUBQWUBWUBWUBAWUBWUB) == ['REHM X QASN NLSMHLCMTIC VA HN N UEXLSFOEULB X J Q A', 'REHM   X   QASN   NLSMHLCMTIC   VA   HN   N   UEXLSFOEULB   X   J   Q   A']