from ..program980 import program980
def test15():
    assert program980(KWUBUPDYXGOKUWUBWUBWUBAGOAHWUBIZDWUBWUBWUBIYWUBWUBWUBVWUBWUBWUBPWUBWUBWUBE) == ['K UPDYXGOKU AGOAH IZD IY V P E', 'K UPDYXGOKU   AGOAH IZD   IY   V   P   E']