from ..program3436 import program3436
def test6():
    assert program3436(EUCWUBAMTDIZB BERLAND 5:2
WQLRBODMAPFQAJXYXA EUCWUBAMTDIZB 5:3
YKKUZZ BERLAND 1:0
YKKUZZ EUCWUBAMTDIZB 3:5
YKKUZZ WQLRBODMAPFQAJXYXA 6:3) == ['IMPOSSIBLE']