def program746():
    n=int(input())
    k=int(input())
    a=int(input())
    b=int(input())
    coin=0
    if(n==1):
        print("0")
        return
    if(k==1):
        print((n-1)*a)
        return
    sum=0
    while(n!=1):
        if(n<k):
            sum=sum+(n-1)*a
            break
        if(n%k!=0):
            sum=sum+(a*n%k)
            n=n-n%k
        else:
            i=n-n//k
            if(b>i*a):
                n=n//k
                sum=sum+i*a
            else:
                n=n//k
                sum=sum+b
            
    print(sum)