from ..program903 import program903
def test23():
    assert program903(NMGIFDZKBCVRYLTWOASXHEUQPJN) == ['NMGIFDZKBCVRY\r\nJPQUEHXSAOWTL', 'LTWOASXHEUQPJ\r\nYRVCBKZDFIGMN', 'YRVCBKZDFIGMN\r\nLTWOASXHEUQPJ']