from ..program903 import program903
def test42():
    assert program903(BUVTYZFQSNRIWOXGJLKACPEMDHB) == ['WIRNSQFZYTVUB\r\nOXGJLKACPEMDH', 'BUVTYZFQSNRIW\r\nHDMEPCAKLJGXO', 'OXGJLKACPEMDH\r\nWIRNSQFZYTVUB']