from ..program903 import program903
def test36():
    assert program903(ABCDEFGHIJKLMNOPQRSTUVWXYZA) == ['MLKJIHGFEDCBA\r\nNOPQRSTUVWXYZ', 'ABCDEFGHIJKLM\r\nZYXWVUTSRQPON', 'NOPQRSTUVWXYZ\r\nMLKJIHGFEDCBA']