from ..program903 import program903
def test9():
    assert program903(GYCUAXSBNAWFIJPDQVETKZOMLHR) == ['ZOMLHRGYCUAXS\r\nKTEVQDPJIFWNB', 'SXAUCYGRHLMOZ\r\nBNWFIJPDQVETK', 'BNWFIJPDQVETK\r\nSXAUCYGRHLMOZ', 'TEVQDPJIFWAXS\r\nKZOMLHRGYCUNB']