from ..program903 import program903
def test44():
    assert program903(ABCBDEFGHIJKLMNOPQRSTUVWXYZ) == ['PQRSTUVWXYZAB\r\nONMLKJIHGFEDC', 'CDEFGHIJKLMNO\r\nBAZYXWVUTSRQP', 'ONMLKJIHGFEDB\r\nPQRSTUVWXYZAC', 'BAZYXWVUTSRQP\r\nCDEFGHIJKLMNO']