from ..program903 import program903
def test29():
    assert program903(HIDCLZUTPOQGEXFASJNYBVRMDKW) == ['WKDCLZUTPOQGE\r\nHIMRVBYNJSAFX', 'EGQOPTUZLCDIH\r\nXFASJNYBVRMKW', 'XFASJNYBVRMKW\r\nEGQOPTUZLCDIH', 'HIDCLZUTPOQGE\r\nWKMRVBYNJSAFX']