from ..program903 import program903
def test6():
    assert program903(BMVFGRNDOWTILZVHAKCQSXYEJUP) == ['YEJUPBMVFGRND\r\nXSQCKAHZLITWO', 'OWTILZHAKCQSX\r\nDNRGFVMBPUJEY', 'DNRGFVMBPUJEY\r\nOWTILZHAKCQSX', 'XSQCKAHVFGRND\r\nYEJUPBMZLITWO']