from ..program903 import program903
def test39():
    assert program903(ABCDEFGHGIJKLMNOPQRSTUVWXYZ) == ['TSRQPONMLKJIG\r\nUVWXYZABCDEFH', 'UVWXYZABCDEFG\r\nTSRQPONMLKJIH', 'HIJKLMNOPQRST\r\nGFEDCBAZYXWVU', 'GFEDCBAZYXWVU\r\nHIJKLMNOPQRST']