from ..program903 import program903
def test40():
    assert program903(ABCDEFGHIJKLMNOPQRSTUVWXYZX) == ['ZABCDEFGHIJKL\r\nYXWVUTSRQPONM', 'YXWVUTSRQPONM\r\nZABCDEFGHIJKL', 'MNOPQRSTUVWXY\r\nLKJIHGFEDCBAZ', 'KJIHGFEDCBAXY\r\nLMNOPQRSTUVWZ']