from ..program903 import program903
def test8():
    assert program903(YOFJVQSWBUZENPCXGQTHMDKAILR) == ['ENPCXGTHMDKAI\r\nZUBWSQVJFOYRL', 'IAKDMHTQSWBUZ\r\nLRYOFJVGXCPNE', 'ZUBWSQVJFOYRL\r\nENPCXGTHMDKAI', 'LRYOFJVQSWBUZ\r\nIAKDMHTGXCPNE']