from ..program903 import program903
def test33():
    assert program903(ZWFIRJNXVKHOUSTQBLEGYMAPIDC) == ['WFIRJNXVKHOUS\r\nZCDPAMYGELBQT', 'CDIRJNXVKHOUS\r\nZWFPAMYGELBQT', 'TQBLEGYMAPDCZ\r\nSUOHKVXNJRIFW', 'SUOHKVXNJRIFW\r\nTQBLEGYMAPDCZ']