from ..program903 import program903
def test34():
    assert program903(UOWJXRKHZDNGLSAMEIYTQBVCFJP) == ['UPJXRKHZDNGLS\r\nOWFCVBQTYIEMA', 'AMEIYTQBVCFPU\r\nSLGNDZHKRXJWO', 'OWJXRKHZDNGLS\r\nUPFCVBQTYIEMA', 'SLGNDZHKRXJWO\r\nAMEIYTQBVCFPU']