from ..program903 import program903
def test15():
    assert program903(XZTMCRBONHFIUVPKWSDLJQGAHYE) == ['WKPVUIFHNOBRC\r\nSDLJQGAYEXZTM', 'CRBONHFIUVPKW\r\nMTZXEYAGQJLDS', 'TZXEYHFIUVPKW\r\nMCRBONAGQJLDS', 'SDLJQGAYEXZTM\r\nWKPVUIFHNOBRC']