from ..program903 import program903
def test12():
    assert program903(XTSHBGLRJAMDUIPCWYOZVERNKQF) == ['CWYOZVENKQFXT\r\nPIUDMAJRLGBHS', 'PIUDMAJRLGBHS\r\nCWYOZVENKQFXT', 'XFQKNRJAMDUIP\r\nTSHBGLEVZOYWC', 'SHBGLRJAMDUIP\r\nTXFQKNEVZOYWC']