from ..program903 import program903
def test16():
    assert program903(YAMVOHUJLEDCWZLXNRGPIQTBSKF) == ['KFYAMVOHUJLED\r\nSBTQIPGRNXZWC', 'SBTQIPGRNXLED\r\nKFYAMVOHUJZWC', 'DELJUHOVMAYFK\r\nCWZXNRGPIQTBS', 'CWZXNRGPIQTBS\r\nDELJUHOVMAYFK']