from ..program903 import program903
def test47():
    assert program903(BACDEFGHIJKLMNOPQRSTUVWXYZA) == ['NMLKJIHGFEDCA\r\nOPQRSTUVWXYZB', 'OPQRSTUVWXYZB\r\nNMLKJIHGFEDCA', 'ACDEFGHIJKLMN\r\nBZYXWVUTSRQPO']