from ..program903 import program903
def test0():
    assert program903(ABCDEFGHIJKLMNOPQRSGTUVWXYZ) == ['MLKJIHGFEDCBA\r\nNOPQRSTUVWXYZ', 'YXWVUTGHIJKLM\r\nZABCDEFSRQPON', 'NOPQRSTUVWXYZ\r\nMLKJIHGFEDCBA', 'ABCDEFGHIJKLM\r\nZYXWVUTSRQPON']