from ..program903 import program903
def test26():
    assert program903(MKBGVNDJRAWUEHFSYLIZCOPTXKQ) == ['EUWARJDNVGBKM\r\nHFSYLIZCOPTXQ', 'MKBGVNDJRAWUE\r\nQXTPOCZILYSFH', 'QKBGVNDJRAWUE\r\nMXTPOCZILYSFH', 'HFSYLIZCOPTXQ\r\nEUWARJDNVGBKM']