from ..program903 import program903
def test38():
    assert program903(ABCDEFGHIJKLMNOPQRSTUVWXYZG) == ['DEFGHIJKLMNOP\r\nCBAZYXWVUTSRQ', 'CBAGHIJKLMNOP\r\nDEFZYXWVUTSRQ', 'QRSTUVWXYZABC\r\nPONMLKJIHGFED', 'PONMLKJIHGFED\r\nQRSTUVWXYZABC']