from ..program903 import program903
def test43():
    assert program903(QWERTYUIOPASDFGHJKLZXCVBNMQ) == ['DSAPOIUYTREWQ\r\nFGHJKLZXCVBNM', 'FGHJKLZXCVBNM\r\nDSAPOIUYTREWQ', 'QWERTYUIOPASD\r\nMNBVCXZLKJHGF']