from ..program903 import program903
def test14():
    assert program903(HVDEBKMJTLKQORNWCZSGXYIPUAF) == ['JMKBEDVHFAUPI\r\nTLQORNWCZSGXY', 'IPUAFHVDEBKMJ\r\nYXGSZCWNROQLT', 'XGSZCWNROQKMJ\r\nYIPUAFHVDEBLT', 'TLQORNWCZSGXY\r\nJMKBEDVHFAUPI']