from ..program903 import program903
def test5():
    assert program903(QGZEMFKWLUHOVSXJTCPIYREDNAB) == ['QGZEMFKWLUHOV\r\nBANDRYIPCTJXS', 'SXJTCPIYRDNAB\r\nVOHULWKFMEZGQ', 'VOHULWKFMEZGQ\r\nSXJTCPIYRDNAB', 'ANDEMFKWLUHOV\r\nBQGZRYIPCTJXS']