from ..program903 import program903
def test46():
    assert program903(ABCDEFGHIJKLMZYXWVUTSRQPONA) == ['MLKJIHGFEDCBA\r\nZYXWVUTSRQPON', 'ABCDEFGHIJKLM\r\nNOPQRSTUVWXYZ', 'ZYXWVUTSRQPON\r\nMLKJIHGFEDCBA']