from ..program903 import program903
def test7():
    assert program903(MKNTKOBFLJSXWQPVUERDHIACYGZ) == ['VPQWXSJLFBOKN\r\nUERDHIACYGZMT', 'ERDHIACYGZMKN\r\nUVPQWXSJLFBOT', 'TOBFLJSXWQPVU\r\nNKMZGYCAIHDRE', 'NKMZGYCAIHDRE\r\nTOBFLJSXWQPVU']