from ..program903 import program903
def test41():
    assert program903(ABCDEFGHIJKLMNOPQRSTUVWYXYZ) == ['YWVUTSRQPONML\r\nXZABCDEFGHIJK', 'KJIHGFEDCBAZY\r\nLMNOPQRSTUVWX', 'LMNOPQRSTUVWY\r\nKJIHGFEDCBAZX', 'XZABCDEFGHIJK\r\nYWVUTSRQPONML']