from ..program903 import program903
def test13():
    assert program903(RFKNZXHAIMVBWEBPTCSYOLJGDQU) == ['QDGJLOYSCTPBW\r\nURFKNZXHAIMVE', 'WBVMIAHXZNKFR\r\nEPTCSYOLJGDQU', 'RFKNZXHAIMVBW\r\nUQDGJLOYSCTPE', 'EPTCSYOLJGDQU\r\nWBVMIAHXZNKFR']