from ..program903 import program903
def test35():
    assert program903(IHDTJLGRFUXQSOZEMVYKWCPANBT) == ['DTJLGRFUXQSOZ\r\nHIBNAPCWKYVME', 'ITJLGRFUXQSOZ\r\nHDBNAPCWKYVME', 'ZOSQXUFRGLJTD\r\nEMVYKWCPANBIH', 'EMVYKWCPANBIH\r\nZOSQXUFRGLJTD']