from ..program903 import program903
def test45():
    assert program903(ABCDEFGHIJKLMNOPQRSTUVWXAYZ) == ['ZABCDEFGHIJKL\r\nYXWVUTSRQPONM', 'LKJIHGFEDCBAZ\r\nMNOPQRSTUVWXY', 'MNOPQRSTUVWXY\r\nLKJIHGFEDCBAZ', 'YABCDEFGHIJKL\r\nZXWVUTSRQPONM']