from ..program903 import program903
def test20():
    assert program903(TEGXHBUVZDPAMIJFQYCWRKSTNLO) == ['APDZVUBHXGETO\r\nMIJFQYCWRKSNL', 'NTEGXHBUVZDPA\r\nLOSKRWCYQFJIM', 'OTEGXHBUVZDPA\r\nLNSKRWCYQFJIM', 'MIJFQYCWRKSNL\r\nAPDZVUBHXGETO']