from ..program903 import program903
def test4():
    assert program903(ZWMFLTCQIAJEVUPODMSGXKHRNYB) == ['HKXGSMFLTCQIA\r\nRNYBZWDOPUVEJ', 'NYBZWMFLTCQIA\r\nRHKXGSDOPUVEJ', 'AIQCTLFMWZBYN\r\nJEVUPODSGXKHR', 'JEVUPODSGXKHR\r\nAIQCTLFMWZBYN']