from ..program903 import program903
def test25():
    assert program903(UNGHFQRCIPBZTEOAYJXLDMSKNWV) == ['WNGHFQRCIPBZT\r\nVUKSMDLXJYAOE', 'EOAYJXLDMSKWV\r\nTZBPICRQFHGNU', 'TZBPICRQFHGNU\r\nEOAYJXLDMSKWV', 'UNGHFQRCIPBZT\r\nVWKSMDLXJYAOE']