from ..program903 import program903
def test27():
    assert program903(UTGDEJHCBKRWLYFSONAQVMPIXZT) == ['YLWRKBCHJEDGT\r\nFSONAQVMPIXZU', 'FSONAQVMPIXZU\r\nYLWRKBCHJEDGT', 'TGDEJHCBKRWLY\r\nUZXIPMVQANOSF']