from ..program903 import program903
def test21():
    assert program903(XQVBTCNIRFPLOHAYZUMKWEJSXDG) == ['OHAYZUMKWEJSD\r\nLPFRINCTBVQXG', 'DXQVBTCNIRFPL\r\nGSJEWKMUZYAHO', 'LPFRINCTBVQXG\r\nOHAYZUMKWEJSD', 'GXQVBTCNIRFPL\r\nDSJEWKMUZYAHO']