from ..program903 import program903
def test37():
    assert program903(ABACDEFGHIJKLMNOPQRSTUVWXYZ) == ['NMLKJIHGFEDCA\r\nOPQRSTUVWXYZB', 'BCDEFGHIJKLMN\r\nAZYXWVUTSRQPO', 'AZYXWVUTSRQPO\r\nBCDEFGHIJKLMN', 'OPQRSTUVWXYZA\r\nNMLKJIHGFEDCB']