from ..program903 import program903
def test11():
    assert program903(XCDSLTYWJIGUBPHNFZWVMQARKOE) == ['XCDSLTYWJIGUB\r\nEOKRAQMVZFNHP', 'BUGIJWYTLSDCX\r\nPHNFZVMQARKOE', 'PHNFZVMQARKOE\r\nBUGIJWYTLSDCX', 'OKRAQMVWJIGUB\r\nEXCDSLTYZFNHP']