from ..program903 import program903
def test31():
    assert program903(LCFNHUQWXBPOSJMYTGKDAZVREIF) == ['MYTGKDAZVREIL\r\nJSOPBXWQUHNFC', 'JSOPBXWQUHNFC\r\nMYTGKDAZVREIL', 'LFNHUQWXBPOSJ\r\nCIERVZADKGTYM', 'CFNHUQWXBPOSJ\r\nLIERVZADKGTYM']