from ..program903 import program903
def test17():
    assert program903(XECPFJBHINOWVLAGTUMRZYHQSDK) == ['ALVWONIHBJFPC\r\nGTUMRZYQSDKXE', 'GTUMRZYQSDKXE\r\nALVWONIHBJFPC', 'CPFJBHINOWVLA\r\nEXKDSQYZRMUTG', 'XKDSQHINOWVLA\r\nECPFJBYZRMUTG']