from ..program903 import program903
def test30():
    assert program903(CNHIKJWRLPXTQZVUGYDMBAOEFHS) == ['VUGYDMBAOEFSC\r\nZQTXPLRWJKIHN', 'SHIKJWRLPXTQZ\r\nCNFEOABMDYGUV', 'ZQTXPLRWJKIHN\r\nVUGYDMBAOEFSC', 'NHIKJWRLPXTQZ\r\nCSFEOABMDYGUV']