from ..program903 import program903
def test3():
    assert program903(UTEDBZRVWLOFUASHCYIPXGJMKNQ) == ['ZBDETUQNKMJGX\r\nRVWLOFASHCYIP', 'RVWLOFASHCYIP\r\nZBDETUQNKMJGX', 'PIYCHSAUTEDBZ\r\nXGJMKNQFOLWVR', 'XGJMKNQUTEDBZ\r\nPIYCHSAFOLWVR']