from ..program903 import program903
def test24():
    assert program903(AHGZCRJTKPMQUNBWSIYLDXEHFVO) == ['VFHGZCRJTKPMQ\r\nOAEXDLYISWBNU', 'OAHGZCRJTKPMQ\r\nVFEXDLYISWBNU', 'UNBWSIYLDXEFV\r\nQMPKTJRCZGHAO', 'QMPKTJRCZGHAO\r\nUNBWSIYLDXEFV']