from ..program903 import program903
def test32():
    assert program903(OURNQJWMIXCLGSDVEKZAFBYNTPH) == ['GLCXIMWJQNRUO\r\nSDVEKZAFBYTPH', 'HPTNQJWMIXCLG\r\nOURYBFAZKEVDS', 'SDVEKZAFBYTPH\r\nGLCXIMWJQNRUO', 'OURNQJWMIXCLG\r\nHPTYBFAZKEVDS']