from ..program903 import program903
def test28():
    assert program903(BETRFOVLPCMWKHAXSGUDQYJTZIN) == ['IZTRFOVLPCMWK\r\nNBEJYQDUGSXAH', 'KWMCPLVOFRTEB\r\nHAXSGUDQYJZIN', 'BETRFOVLPCMWK\r\nNIZJYQDUGSXAH', 'HAXSGUDQYJZIN\r\nKWMCPLVOFRTEB']