from ..program903 import program903
def test22():
    assert program903(MIDLBEUAGTNPYKFWHVSRJOXCZMQ) == ['KFWHVSRJOXCZQ\r\nYPNTGAUEBLDIM', 'YPNTGAUEBLDIM\r\nKFWHVSRJOXCZQ', 'MIDLBEUAGTNPY\r\nQZCXOJRSVHWFK']