from ..program982 import program982
def test29():
    assert program982(WUBWUBWSPLAYSZSAUDSWUBWUBWUBUWUBWUBWUBKRWUBWUBWUBRSOKQMZFIYZQUWUBWUBWUBELSHUWUBWUBWUBUKHWUBWUBWUBQXEUHQWUBWUBWUBBWUBWUBWUBR) == ['WSPLAYSZSAUDS   U   KR   RSOKQMZFIYZQU   ELSHU   UKH   QXEUHQ   B   R', 'WSPLAYSZSAUDS U KR RSOKQMZFIYZQU ELSHU UKH QXEUHQ B R']