from ..program982 import program982
def test35():
    assert program982(WUBWUBWUBIWUBWUBLIKNQVWUBWUBWUBPWUBWUBWUBHWUBWUBWUBMWUBWUBWUBDPRSWUBWUBWUBBSAGYLQEENWXXVWUBWUBWUBXMHOWUBWUBWUBUWUBWUBWUBYRYWUBWUBWUBCWUBWUBWUBY) == ['I LIKNQV P H M DPRS BSAGYLQEENWXXV XMHO U YRY C Y', 'I  LIKNQV   P   H   M   DPRS   BSAGYLQEENWXXV   XMHO   U   YRY   C   Y']