from ..program982 import program982
def test15():
    assert program982(KWUBUPDYXGOKUWUBWUBWUBAGOAHWUBIZDWUBWUBWUBIYWUBWUBWUBVWUBWUBWUBPWUBWUBWUBE) == ['K UPDYXGOKU AGOAH IZD IY V P E', 'K UPDYXGOKU   AGOAH IZD   IY   V   P   E']