from ..program982 import program982
def test10():
    assert program982(VSRNVEATZTLGQRFEGBFPWUBWUBWUBAJWUBWUBWUBPQCHNWUBCWUB) == ['VSRNVEATZTLGQRFEGBFP AJ PQCHN C', 'VSRNVEATZTLGQRFEGBFP   AJ   PQCHN C']