from ..program982 import program982
def test25():
    assert program982(WUBNXOLIBKEGXNWUBWUBWUBUWUBGITCNMDQFUAOVLWUBWUBWUBAIJDJZJHFMPVTPOXHPWUBWUBWUBISCIOWUBWUBWUBGWUBWUBWUBUWUB) == ['NXOLIBKEGXN U GITCNMDQFUAOVL AIJDJZJHFMPVTPOXHP ISCIO G U', 'NXOLIBKEGXN   U GITCNMDQFUAOVL   AIJDJZJHFMPVTPOXHP   ISCIO   G   U']