from ..program982 import program982
def test41():
    assert program982(WPPNMSQOQIWUBWUBWUBPNQXWUBWUBWUBHWUBWUBWUBNFLWUBWUBWUBGWSGAHVJFNUWUBWUBWUBFWUBWUBWUBWCMLRICFSCQQQTNBWUBWUBWUBSWUBWUBWUBKGWUBWUBWUBCWUBWUBWUBBMWUBWUBWUBRWUBWUB) == ['WPPNMSQOQI   PNQX   H   NFL   GWSGAHVJFNU   F   WCMLRICFSCQQQTNB   S   KG   C   BM   R', 'WPPNMSQOQI PNQX H NFL GWSGAHVJFNU F WCMLRICFSCQQQTNB S KG C BM R']