from ..program982 import program982
def test22():
    assert program982(WUBWUBJWUBWUBWUBNFLWUBWUBWUBGECAWUBYFKBYJWTGBYHVSSNTINKWSINWSMAWUBWUBWUBFWUBWUBWUBOVWUBWUBLPWUBWUBWUBN) == ['J NFL GECA YFKBYJWTGBYHVSSNTINKWSINWSMA F OV LP N', 'J   NFL   GECA YFKBYJWTGBYHVSSNTINKWSINWSMA   F   OV  LP   N']