from ..program982 import program982
def test21():
    assert program982(WUBWUBZBKOKHQLGKRVIMZQMQNRWUBWUBWUBDACWUBWUBNZHFJMPEYKRVSWUBWUBWUBPPHGAVVPRZWUBWUBWUBQWUBWUBAWUBG) == ['ZBKOKHQLGKRVIMZQMQNR   DAC  NZHFJMPEYKRVS   PPHGAVVPRZ   Q  A G', 'ZBKOKHQLGKRVIMZQMQNR DAC NZHFJMPEYKRVS PPHGAVVPRZ Q A G']