from ..program982 import program982
def test14():
    assert program982(IWUBWUBQLHDWUBYIIKZDFQWUBWUBWUBCXWUBWUBUWUBWUBWUBKWUBWUBWUBNL) == ['I  QLHD YIIKZDFQ   CX  U   K   NL', 'I QLHD YIIKZDFQ CX U K NL']