from ..program982 import program982
def test39():
    assert program982(WUBWUBWUBREHMWUBWUBWUBXWUBWUBWUBQASNWUBWUBWUBNLSMHLCMTICWUBWUBWUBVAWUBWUBWUBHNWUBWUBWUBNWUBWUBWUBUEXLSFOEULBWUBWUBWUBXWUBWUBWUBJWUBWUBWUBQWUBWUBWUBAWUBWUB) == ['REHM X QASN NLSMHLCMTIC VA HN N UEXLSFOEULB X J Q A', 'REHM   X   QASN   NLSMHLCMTIC   VA   HN   N   UEXLSFOEULB   X   J   Q   A']