from ..program982 import program982
def test38():
    assert program982(WUBOJMWRSLAXXHQRTPMJNCMPGWUBWUBWUBNYGMZIXNLAKSQYWDWUBWUBWUBXNIWUBWUBWUBFWUBWUBWUBXMBWUBWUBWUBIWUBWUBWUBINWUBWUBWUBWDWUBWUBWUBDDWUBWUBWUBD) == ['OJMWRSLAXXHQRTPMJNCMPG NYGMZIXNLAKSQYWD XNI F XMB I IN WD DD D', 'OJMWRSLAXXHQRTPMJNCMPG   NYGMZIXNLAKSQYWD   XNI   F   XMB   I   IN   WD   DD   D']