from ..program982 import program982
def test20():
    assert program982(WUBZVMJWUBWUBWUBFOIMJQWKNZUBOFOFYCCWUBWUBWUBAUWWUBRDRADWUBWUBWUBCHQVWUBWUBWUBKFTWUBWUBWUBW) == ['ZVMJ FOIMJQWKNZUBOFOFYCC AUW RDRAD CHQV KFT W', 'ZVMJ   FOIMJQWKNZUBOFOFYCC   AUW RDRAD   CHQV   KFT   W']