from ..program982 import program982
def test40():
    assert program982(WUBWUBWUBSTEZTZEFFIWUBWUBWUBSWUBWUBWUBCWUBFWUBHRJPVWUBWUBWUBDYJUWUBWUBWUBPWYDKCWUBWUBWUBCWUBWUBWUBUUEOGCVHHBWUBWUBWUBEXLWUBWUBWUBVCYWUBWUBWUBMWUBWUBWUBYWUB) == ['STEZTZEFFI   S   C F HRJPV   DYJU   PWYDKC   C   UUEOGCVHHB   EXL   VCY   M   Y', 'STEZTZEFFI S C F HRJPV DYJU PWYDKC C UUEOGCVHHB EXL VCY M Y']