from ..program982 import program982
def test12():
    assert program982(WUBWUBWUBFVWUBWUBWUBBPSWUBWUBWUBRXNETCJWUBWUBWUBJDMBHWUBWUBWUBBWUBWUBVWUBWUBB) == ['FV   BPS   RXNETCJ   JDMBH   B  V  B', 'FV BPS RXNETCJ JDMBH B V B']