from ..program982 import program982
def test18():
    assert program982(WUBYYRTSMNWUWUBWUBWUBCWUBWUBWUBCWUBWUBWUBFSYUINDWOBVWUBWUBWUBFWUBWUBWUBAUWUBWUBWUBVWUBWUBWUBJB) == ['YYRTSMNWU C C FSYUINDWOBV F AU V JB', 'YYRTSMNWU   C   C   FSYUINDWOBV   F   AU   V   JB']