from ..program982 import program982
def test26():
    assert program982(WUBWUBNMMWCZOLYPNBELIYVDNHJUNINWUBWUBWUBDXLHYOWUBWUBWUBOJXUWUBWUBWUBRFHTGJCEFHCGWARGWUBWUBWUBJKWUBWUBSJWUBWUB) == ['NMMWCZOLYPNBELIYVDNHJUNIN   DXLHYO   OJXU   RFHTGJCEFHCGWARG   JK  SJ', 'NMMWCZOLYPNBELIYVDNHJUNIN DXLHYO OJXU RFHTGJCEFHCGWARG JK SJ']