from ..program982 import program982
def test34():
    assert program982(WUBWUBWUBISERPQITVIYERSCNWUBWUBWUBQWUBWUBWUBDGSDIPWUBWUBWUBCAHKDZWEXBIBJVVSKKVQJWUBWUBWUBKIWUBWUBWUBCWUBWUBWUBAWUBWUBWUBPWUBWUBWUBHWUBWUBWUBF) == ['ISERPQITVIYERSCN   Q   DGSDIP   CAHKDZWEXBIBJVVSKKVQJ   KI   C   A   P   H   F', 'ISERPQITVIYERSCN Q DGSDIP CAHKDZWEXBIBJVVSKKVQJ KI C A P H F']