from ..program982 import program982
def test27():
    assert program982(SGWLYSAUJOJBNOXNWUBWUBWUBBOSSFWKXPDPDCQEWUBWUBWUBDIRZINODWUBWUBWUBWWUBWUBWUBPPHWUBWUBWUBRWUBWUBWUBQWUBWUBWUBJWUB) == ['SGWLYSAUJOJBNOXN BOSSFWKXPDPDCQE DIRZINOD W PPH R Q J', 'SGWLYSAUJOJBNOXN   BOSSFWKXPDPDCQE   DIRZINOD   W   PPH   R   Q   J']