from ..program982 import program982
def test33():
    assert program982(DPDWUBWUBWUBEUQKWPUHLTLNXHAEKGWUBRRFYCAYZFJDCJLXBAWUBWUBWUBHJWUBOJWUBWUBWUBNHBJEYFWUBWUBWUBRWUBWUBWUBSWUBWWUBWUBWUBXDWUBWUBWUBJWUB) == ['DPD   EUQKWPUHLTLNXHAEKG RRFYCAYZFJDCJLXBA   HJ OJ   NHBJEYF   R   S W   XD   J', 'DPD EUQKWPUHLTLNXHAEKG RRFYCAYZFJDCJLXBA HJ OJ NHBJEYF R S W XD J']