from ..program982 import program982
def test24():
    assert program982(WUBMPWUBWUBWUBORWUBWUBDLGKWUBWUBWUBVVZQCAAKVJTIKWUBWUBWUBTJLUBZJCILQDIFVZWUBWUBYXWUBWUBWUBQWUBWUBWUBLWUB) == ['MP OR DLGK VVZQCAAKVJTIK TJLUBZJCILQDIFVZ YX Q L', 'MP   OR  DLGK   VVZQCAAKVJTIK   TJLUBZJCILQDIFVZ  YX   Q   L']