from ..program982 import program982
def test23():
    assert program982(WUBWUBLCWUBWUBWUBZGEQUEATJVIXETVTWUBWUBWUBEXMGWUBWUBWUBRSWUBWUBWUBVWUBWUBWUBTAWUBWUBWUBCWUBWUBWUBQG) == ['LC   ZGEQUEATJVIXETVT   EXMG   RS   V   TA   C   QG', 'LC ZGEQUEATJVIXETVT EXMG RS V TA C QG']