from ..program982 import program982
def test16():
    assert program982(WUBWUBOWUBWUBWUBIPVCQAFWYWUBWUBWUBQWUBWUBWUBXHDKCPYKCTWWYWUBWUBWUBVWUBWUBWUBFZWUBWUB) == ['O   IPVCQAFWY   Q   XHDKCPYKCTWWY   V   FZ', 'O IPVCQAFWY Q XHDKCPYKCTWWY V FZ']