from ..program982 import program982
def test17():
    assert program982(PAMJGYWUBWUBWUBXGPQMWUBWUBWUBTKGSXUYWUBWUBWUBEWUBWUBWUBNWUBWUBWUBHWUBWUBWUBEWUBWUB) == ['PAMJGY   XGPQM   TKGSXUY   E   N   H   E', 'PAMJGY XGPQM TKGSXUY E N H E']