from ..program982 import program982
def test28():
    assert program982(TOWUBWUBWUBGBTBNWUBWUBWUBJVIOJBIZFUUYHUAIEBQLQXPQKZJMPTCWBKPOSAWUBWUBWUBSWUBWUBWUBTOLVXWUBWUBWUBNHWUBWUBWUBO) == ['TO   GBTBN   JVIOJBIZFUUYHUAIEBQLQXPQKZJMPTCWBKPOSA   S   TOLVX   NH   O', 'TO GBTBN JVIOJBIZFUUYHUAIEBQLQXPQKZJMPTCWBKPOSA S TOLVX NH O']