from ..program982 import program982
def test11():
    assert program982(WUBWUBEWUBWUBWUBIQMJNIQWUBWUBWUBGZZBQZAUHYPWUBWUBWUBPMRWUBWUBWUBDCV) == ['E IQMJNIQ GZZBQZAUHYP PMR DCV', 'E   IQMJNIQ   GZZBQZAUHYP   PMR   DCV']