from ..program982 import program982
def test19():
    assert program982(WUBWUBYGPYEYBNRTFKOQCWUBWUBWUBUYGRTQEGWLFYWUBWUBWUBFVWUBHPWUBWUBWUBXZQWUBWUBWUBZDWUBWUBWUBM) == ['YGPYEYBNRTFKOQC   UYGRTQEGWLFY   FV HP   XZQ   ZD   M', 'YGPYEYBNRTFKOQC UYGRTQEGWLFY FV HP XZQ ZD M']