from ..program4742 import program4742
def test18():
    assert program4742(BBYUVCIYLNUJPSEYCAAPQSDNSDDTNEHQZDPBEKQAWNAKEYFBNEEBGPDPRLCSVOWYDEDRPPEDOROCHRCNQUSPNVXGRXHNLKDETWQC
BQCQXCAHADGJHBYIKEUWNXFUOOTVCCKJPJJCMWLAWWKSDGHFNZTCPSQNRTPCBLXDTSJLRHSCCZXQXCVLVGTROOUCUQASIQHZGNEI
RYE) == ['BBYUVCJPCASDNZPQNBDRLVROOCQSGNE', 'BBYINUJPCASDHZPQNPDRSVROOCUSHNE', 'BBYINUJPCASDHZPQNPDLSVROOCUSHNE', 'BBYUVCJPCASDNTPQNBDRLVROOCQSGNE', 'BBYUVCJPCASDNTPQNBDLCVROOCQSGNE']