from ..program4742 import program4742
def test13():
    assert program4742(KEJHTOKHMKWTYSJEAJAXGADRHUKBCRHACSRDNSZIHTPQNLOSRKYBGYIIJDINTXRPMWSVMMBODAYPVVDDTIXGDIOMWUAKZVFKDAUM
WTEVPIFAAJYIDTZSZKPPQKIOMHDZTKDMFVKSJRUFMNHZJPVSQYELWYAFACGGNRORSLGYVXAEYVLZBLDEHYDGOFDSWUYCXLXDKFSU
TUZEQBWVBVTKETQ) == ['EJTKHMKSJRUNHPQLYGNRSVAYVDDGOWUKFU', 'EJTOKMKSJRUHZPQLYGNRSVAYVDDGDWUKFU', 'EJTOKMKSJRUNZPQLYGNRSVAYVDDGDWUKFU', 'EJHTKMKSJRUHZPQLYGNRSVAYVDDGDWUKFU']