from ..program4742 import program4742
def test3():
    assert program4742(QNHRPFYMAAPJDUHBAEXNEEZSTMYHVGQPYKNMVKMBVSVLIYGUVMJHEFLJEPIWFHSLISTGOKRXNMSCXYKMAXBPKCOCNTIRPCUEPHXM
RRFCZUGFDRKKMQTOETNELXMEWGOCDHFKIXOPVHHEWTCDNXVFKFKTKNWKEIKTCMHMHDNCLLVQSGKHBCDDYVVVQIRPZEOPUGQUGRHH
R) == ['FUENEMGKIVHEFEIHLSGKBCIPEPH', 'FDENEMGKIVHEWFTKNMCKBCIPEPH', 'FMENEEHKIVHEFEIHLSGKCYPOPUH', 'QNHFPHEXNETMHMHLLSGKCYPOPUH', 'QNHFPHETVKNKMMHLLSGKBCIPEPH', 'FDENEMGKIVHEFEIHLSGKCYPOPUH']