from ..program4742 import program4742
def test4():
    assert program4742(CGPWTAPEVBTGANLCLVSHQIIKHDPVUHRSQPXHSNYAHPGBECICFQYDFRTRELLLEDZYWJSLOBSKDGRRDHNRRGIXAMEBGFJJTEIGUGRU
HAWYVKRRBEIWNOGYMIYQXDCFXMMCSAYSOXQFHHIFRRCJRAWHLDDHHHAKHXVKCVPBFGGEXUKWTFWMOUUGMXTSBUTHXCJCWHCQQTYQ
ANKFDWLYSX) == ['WVBGIQXSYHIFRRWLDDHXBGEUGU', 'WVBNIQXSYHIFRRJLDDHXBFGUGU', 'AVBIIQXSAHIFRRWLDDHXBFGUGU', 'WVBGCSSQHHIFRRWLDDHXBGFUGU', 'AVBNIQXSAHIFRRJLDDHABFGUGU', 'WVBNIDXSYHIFRRWLDDHXBGFUGU']