from ..program4742 import program4742
def test31():
    assert program4742(ASDASASDASDASDAASDASDASDASASDDAASDASSASDSDAD
DASDASSSDASDASDASASDASSDAASDASSDDSASDASDAASDDAASDASDAASDASDDASDASDASDASDASS
DASD) == ['ASDASASDASASDAASDASASDASASDDAASDASSASDSDAD']