from ..program4742 import program4742
def test26():
    assert program4742(AABABABABAAAABBAAAABABABABAAAAABABAAAA
AABABAAABABABAAABAAAAABAAABAAABABABBBABBAAABAABAAAAABABBABAAABAABAABABAAAABABAAABAAABAABABBBABBABABA
AAAAA) == ['AABABABABAAAABBAAAABABABABAAAABABAAAA']