from ..program4742 import program4742
def test17():
    assert program4742(GOZVMIRQIGYGVAGOREQTXFXPEZYOJOXPNDGAESICXHMKQDXQPRLMRVWHXFEJVCWZDLYMQLDURUXZPTLEHPTSKXGSNEQDKLVFFLDX
IMEVFCZXACKRRJVXDRKFWTLTRTLQQDHEBZLCOCNVPABQMIWJHRLKFUKWOVVWGGNWCJNRYOYOAJFQWCLHQIQRBZTVWKBFOXKEHHQP
SZ) == ['IEFZXACKRRVXFWLRTLHPKGNQLVFX', 'IVARXFEZONAIHRLVWJWLQRZTKXEQ', 'MVARXFEZOPAIHRLVWFCLQRZTKXEQ']