from ..program4742 import program4742
def test39():
    assert program4742(AAACAAACAAADAAAAAAA
AADAAAAAAAACDAAAAAAAAAAACAAAAABCACAAACAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADA
AAACAADAAAAADD) == ['AAACAAACAAAAAAAAAA']