from ..program4742 import program4742
def test34():
    assert program4742(ABAABACABADAACADABACAAB
BAACABADABACABAAAADADAABACABACABADABABADABACABAADABBADABACAAACAABACABADABBBAA
DABACA) == ['ABAABACABADAACAABACAAB', 'ABAABACABADAACADABAAAB']