from ..program4742 import program4742
def test33():
    assert program4742(ABAAAABABADABAABAABCCABADABACABACABCABADABADABACABBACAADABACABABACABADABACABABA
BACAACABABABACABCABADABAACABADABACABAA
ABBAB) == ['BACAACABABABACABCAADABAACABADABACABAA', 'BACAACABABABACABCABAABAACABADABACABAA', 'BAAACABABABACABCABADABAACABADABACABAA']