from ..program4742 import program4742
def test6():
    assert program4742(BGIIURZTEUJJULBWKHDQBRFGEUOMQSREOTILICRSBUHBGTSRDHKVDDEBVHGMHXUVFJURSMFDJOOOWCYPJDVRVKLDHICPNKTBFXDJ
XOADNTKNILGNHHBNFYNDWUNXBGDFUKUVHLPDOGOYRMOTAQELLRMHFAQEOXFWGAQUROVUSWOAWFRVIRJQVXPCXLSCQLCUWKBZUFQP
YVF) == ['TLBWKHDGOROTLRHEGUVUSOWVRVLCKBF', 'ILBWKHDGOMQELRHEGUVUSOWVRVLCKBF', 'TLBWKHDGOROTLRMHXFUROOWVRVLCKBF', 'TLBWKHDGOROTLRMHXFURSOWVRVLCKBF']