from ..program4742 import program4742
def test5():
    assert program4742(AUNBEKNURNUPHXQYKUTAHCOLMPRQZZTVDUYCTNIRACQQTQAIDTAWJXBUTIZUASDIJZWLHAQVGCAHKTZMXSDVVWAIGQEALRFKFYTT
QBVRFKPKLYZLYNRFTRJZZQEYAEKPFXVICUVFVQSDENBJYYNCFTOZHULSWJQTNELYLKCZTGHOARDCFXBXQGGSQIVUCJVNGFZEEZQE
N) == ['BKPYTRZZVICQDJTZUSJZHAQGSVVGQE', 'BRPKLZYTRQAXIUSDJZWLHACXSVVGQE', 'BRPKLRZZYACQDBTZUSWLHACXSVVGQE', 'BRPKLRZZYICQDJTZUSJZHAQGSVVGQE', 'BKPKLRZZVICQDJTZUSJZHAQGSVVGQE']