from ..program4742 import program4742
def test16():
    assert program4742(BTWZLIKDACZVLCKMVTIQHLFBNRCBDSWPFFKGPCQFPTOIJLPFCDMFGQKFHTDFFCCULUAYPXXIIIWBZIDMOPNHPZBEXLVARJFTBFOE
MDXYKKWZVASJPPWRCYNMRAOBBLUNBSMQAPCPSFAGLXWJRBQTBRWXYNQGWECYNFIAJXDMUHIIMDFMSHLPIMYQXNRRUSSNXALGNWIK
KNFVBVAOWXMZVUHAVUDKDBUVAKNHACZBGBHMUOPHWGQSDFXLHB) == ['WZACMLNBSPFGCFIJDMHDFLPIMNXL', 'WZACLMQLBRWGCFIJDMHDFLPIMNXL', 'WZACMBNBSPFGQTIJDMHDFLPIMNXA', 'WZVCMLNBSPFGCFIJDMHDFLPIMNXL', 'WZACMLNBSPFGQTIJDMHDFLPIMNXL', 'DZVCMBNBSPFGCFIJDMHDFLPIMNXA']