from ..program4742 import program4742
def test15():
    assert program4742(ZFFBNYVXOZCJPSRAEACVPAUKVTCVZYQPHVENTKOCMHNIYYMIKKLNKHLWHHWAQMWFTSYEOQQFEYAAYGMPNZCRYBVNAQTDSLXZGBCG
PIQHLNEWAMFAKGHBGZAWRWAXCSKUDZBDOCTXAHSVFZACXGFMDSYBYYDDNQNBEZCYCULSMMPBTQOJQNRPZTRCSDLIYPLVUGJPKDTG
ZBFJPLNAKWQBTUVJKMHVBATAM) == ['FBZRACKZOCHAFSYYYNZCYBQTSLGG', 'FBZAACKZOCHAFSYYYNZCYBQTSLGG', 'FBZRACKZOCHAMSYYYNZCYBNTDLGG', 'FBZRACUZOCHAMSYYYNZCYBNTDLGG']