from ..program4742 import program4742
def test19():
    assert program4742(WZRKLETJRBBRZKGHEFBVEFVLIERBPSEGJVSNUZUICONWWBOOTHCOJLLZFNOCNOFJQZTZWBLKHGIWWWPBUYWBAHYJGEBJZJDTNBGN
ZINFGDCNKHYFZYYWHTIHZTKWXXXMSWOVOPQDTRWSQKBWWCPEMYFVGARELELBLGEVJCMOCFTTUVCYUQUSFONAMWKVDWMGXVNZJBWH
AFPA) == ['WZKTRKBEFVLEBGVCOTCFONWKWGZJB', 'WZKTRBEFVELEBEJCOTCFONWKWGZJB', 'WZKTRBEFVELEBGVCOTCFONWKWGZJB', 'WZKTRKEFVELEBEJCOTCFONWKWGZJB']