from ..program521 import program521
def test8():
    assert program521(10 10
SSSSSSSSSS
..........
..........
..........
..........
..........
..........
..........
..........
..........) == ['90']