from ..program2347 import program2347
def test19():
    assert program2347(tgharsjyihroiiahwgbjezlxvlterxivdhtzjcqegzmtigqmrehvhiyjeywegxaseoyoacouijudbiruoghgxvxadwzgdxtnxlds
tghaksjsdhkoiiahegbjexlfrctercipdhmvjbgegxdtggqdpbhvhiseehhegnaseoooacnsijubbirjnghgsvpadhaadrtimfdp) == ['zzzzkzzsdzkzzzzzezzzzxzfrczzzczpzzmvzbgzzxdzgzzdpbzzzzsezhhzznzzzzozzznszzzbzzzjnzzzszpzzhaazrzimfzp', 'uhibktksdikpjjbiehckfxmfrcufscjpeimvkbgfhxdughrdpbiwijsefhhfhnbtfpopbdnsjkvbcjsjnhihswpbehaaeruimfep', 'tghaksjsdhkoiiahegbjexlfrctercipdhmvjbgegxdtggqdpbhvhiseehhegnaseoooacnsijubbirjnghgsvpadhaadrtimfdp']