from ..program2347 import program2347
def test21():
    assert program2347(nttdcfceptruiomtmwzestrfchnqpgqeztpcvthzelfyggjgqadylzubpvbrlgndrcsursczpxlnoyoadxezncqalupfzmjeqihe
kttdcfceohrjiaahmoldanpfchnfpgheqpdahqhxecfpbgigqadrkjubjfbrlgndbcgcgmcjpeleinaadretncqaiqpfkmjeqihe) == ['kuuedgdfohsjjaahnoldanpgdiofqhhfqpdahqixfcgpbhihrberkjvcjfcsmhoebdgcgmdjqemeinaberftodrbiqqgknkfrjif', 'kttdcfceohrjiaahmoldanpfchnfpgheqpdahqhxecfpbgigqadrkjubjfbrlgndbcgcgmcjpeleinaadretncqaiqpfkmjeqihe', 'kzzzzzzzohzjzaahzoldanpzzzzfzzhzqpdahqzxzczpbzizzzzrkjzzjfzzzzzzbzgcgmzjzezeinazzrztzzzziqzzkzzzzzzz']