from ..program2347 import program2347
def test17():
    assert program2347(zrvzedssbsrfldqvjpgmsefrmsatspzoitwvymahiptphiystjlsauzquzqqbmljobdhijcpdvatorwmyojqgnezvzlgjibxepcf
pesoedmqbmffldqsjggmhefkadaesijointrkmahapaahiysfjdiaupqujngbjhjobdhiecadeatgjvelojjgnepvajgeibfepaf) == ['pesofemqcmfgmerskghnhfgkadbetijpjntrknbiaqaaijztfkdibvprvjngcjhkpceijedaeebugjvelpkjhofpwajhejcffqag', 'pesozzmqzmfzzzzszgzzhzzkadzezijzzntrkzzzazaazzzzfzdizzpzzjngzjhzzzzzzezazezzgjvelzzjzzzpzajzezzfzzaz', 'pesoedmqbmffldqsjggmhefkadaesijointrkmahapaahiysfjdiaupqujngbjhjobdhiecadeatgjvelojjgnepvajgeibfepaf']