from ..program2347 import program2347
def test15():
    assert program2347(hbgwuqzougqzlxemvyjpeizjfwhgugrfnhbrlxkmkdalikfyunppwgdzmalbwewybnjzqsohwhjkdcyhhzmysflambvhpsjilsyv
fbdjdqjojdafarakvcjpeipjfehgfgrfehbolxkmkdagikflunnpvadocalbkedibhbflmohnhjkdcthhaigsfjaibqhbcjelirv) == ['fcdjdrjpjdafarakwckqfjpkgeihfhsgeicomylnlebgjlglvonqvaeocbmckfdichbflmpinikledtiiaigtgjbicqibckemirw', 'fzdjdzjzjdafarakzczzzzpzzezzfzzzezzozzzzzzzgzzzlzznzvazoczzzkzdizhbflmzznzzzzztzzaigzzjzizqzbczezirz', 'fbdjdqjojdafarakvcjpeipjfehgfgrfehbolxkmkdagikflunnpvadocalbkedibhbflmohnhjkdcthhaigsfjaibqhbcjelirv']