from ..program2347 import program2347
def test11():
    assert program2347(eufycwztywhbjrpqobvknwfqmnboqcfdiahkagykeibbsqpljcghhmsgfmswwsanzyiwtvuirwmppfivtekaywkzskyydfvkjgxb
ecfwavookadbcilfobojnweqinbcpcfdiahkabwkeibbacpljcghhksgfajgmianfnivmhfifogpffiheegayfkxkkcmdfvihgdb) == ['ecfwavookadbcilfobojnweqinbcpcfdiahkabwkeibbacpljcghhksgfajgmianfnivmhfifogpffiheegayfkxkkcmdfvihgdb', 'zczwavookadzcilfzzojzzezizzcpzzzzzzzzbwzzzzzaczzzzzzzkzzzajgmizzfnzvmhfzfogzfzzhezgzzfzxkzcmzzzihzdz', 'fcgwavookadccilfpcojoxerioccpdgejbilbbwlfjccacqmkdhiikthgajgmibofnjvmhfjfogqfgjhefgbzflxklcmegwihhdc']