from ..program2347 import program2347
def test13():
    assert program2347(nmuwjdihouqrnsuahimssnrbxdpwvxiyqtenahtrlshjkmnfuttnpqhgcagoptinnaptxaccptparldzrhpgbyrzedghudtsswxi
nilhbdghosqnbebafimconrbvdodjsipqmekahhrllhjkemeketapfhgcagopfidnahtlaccpfpafedqicpcbvfgedghudhddwib) == ['nilhbdghosqnbebafimconrbvdodjsipqmekahhrllhjkemeketapfhgcagopfidnahtlaccpfpafedqicpcbvfgedghudhddwib', 'zilhbzgzzsznbebzfzzcozzzvzodjszpzmzkzzhzzlzzzemekezazfzzzzzzzfzdzzhzlzzzzfzzfezqiczczvfgzzzzzzhddzib', 'oilhbegipsrnbebbfjncooscveodjsjprmfkbihsmliklemekeuaqfihdbhpqfjdobhulbddqfqbfeeqicqccvfgfehivehddxib']