from ..program3871 import program3871
def test7():
    assert program3871(RBGYRBGYRBGYRBGYRBGYRBGYRBGYRBGYRBGYRBGYRBGYRBGYRBGYRBGYRBGYRBGYRBGYRBGYRBGYRBGYRBGYRBGYRBGYRBGYRBGY) == ['0\r\n0\r\n0\r\n0', '0 0 0 0']