def program3076():
    ###########################################
    ## this code is Generated by Nour Alhadi ##
    ###########################################
    
    
    s = ""
    
    n = int (input())
    
    for i in range (n+1):
    	s = s+str(i)
    print s[n]