from ..program3872 import program3872
def test7():
    assert program3872(RBGYRBGYRBGYRBGYRBGYRBGYRBGYRBGYRBGYRBGYRBGYRBGYRBGYRBGYRBGYRBGYRBGYRBGYRBGYRBGYRBGYRBGYRBGYRBGYRBGY) == ['0\r\n0\r\n0\r\n0', '0 0 0 0']