from ..program504 import program504
def test27():
    assert program504(AGFIGYWJLVMYZGNQHEHWKJIAWBPUAQFERMCDROFN
PMJNHMVNRGCYZAVRWNDSMLSZHFNYIUWFPUSKKIGU
MCDVPPRXGUAYLSDRHRURZASXUWZSIIEZCPXUVEONKNGNWRYGOSFMCKESMVJZHWWUCHWDQMLASLNNMHAU) == ['NO']