from ..program504 import program504
def test21():
    assert program504(NUBKQEJHALANSHEIFUZHYEZKKDRFHQKAJHLAOWTZIMOCWOVVDW
EFVOBIGAUAUSQGVSNBKNOBDMINODMFSHDL
KLAMKNTHBFFOHVKWICHBKNDDQNEISODUSDNLUSIOAVWY) == ['NO']