from ..program504 import program504
def test12():
    assert program504(OVQELLOGFIOLEHXMEMBJDIGBPGEYFG
JNKFPFFIJOFHRIFHXEWYZOPDJBZTJZKBWQTECNHRFSJPJOAPQT
YAIPFFFEXJJNEJPLREIGODEGQZVMCOBDFKWTMWJSBEBTOFFQOHIQJLHFNXIGOHEZRZLFOKJBJPTPHPGY) == ['YES']