from ..program504 import program504
def test45():
    assert program504(UIKWWKXLSHTOOZOVGXKYSOJEHAUEEG
KZXQDWJJWRXFHKJDQHJK
XMZHTFOGEXAUJXXJUYVJIFOTKLZHDKELJWERHMGAWGKWAQKEKHIDWGGZVYOHKXRPWSJDPESFJUMKQYWBYUTHQYEFZUGKQOBHYDWB) == ['NO']