from ..program504 import program504
def test41():
    assert program504(IDQRX
WETHO
ODPDGBHVUVSSISROHQJTUKPUCLXABIZQQPPBPKOSEWGEHRSRRNBAVLYEMZISMWWGKHVTXKUGUXEFBSWOIWUHRJGMWBMHQLDZHBWA) == ['NO']