from ..program504 import program504
def test14():
    assert program504(IJHHGKCXWDBRWJUPRDBZJLNTTNWKXLUGJSBWBOAUKWRAQWGFNL
NJMWRMBCNPHXTDQQNZ
WDNJRCLILNQRHWBANLTXWMJBPKUPGKJDJZAQWKTZFBRCTXHHBNXRGUQUNBNMWODGSJWW) == ['YES']