from ..program504 import program504
def test48():
    assert program504(GXPZFSELJJNDAXYRV
UYBKPMVBSOVOJWMONLTJOJCNQKMTAHEWLHOWIIBH
HCWNFWJPEJIWOVPTBMVCRJLSISSVNOHCKLBFMIUAIMASQWPXEYXBOXQGFEMYJLBKDCZIMJNHOJEDGGANIVYKQTUOSOVOPWHVJGXH) == ['NO']