from ..program504 import program504
def test32():
    assert program504(OSKFHGYNQLSRFSAHPXKGPXUHXTRBJNAQRBSSWJVEENLJCDDHFXVCUNPZAIVVO
FNUOCXAGRRHNDJAHVVLGGEZQHWARYHENBKHP
UOEFNWVXCUNERLKVTHAGPSHKHDYFPYWZHJKHQLSNFBJHVJANRXCNSDUGVDABGHVAOVHBJZXGRACHRXEGNRPQEAPORQSILNXFS) == ['YES']