from ..program4738 import program4738
def test7():
    assert program4738(AXBPBDEYIYKKCZBTLKBUNEQLCXXLKIUTOOATYDXYYQCLFAXAEIGTFMNTTQKCQRMEEFRYVYXAOLMUQNPJBMFBUGVXFZAJSBXWALSI
VWFONLLKSHGHHQSFBBFWTXAITPUKNDANOCLMNFTAAMJVDLXYPILPCJCFWTNBQWEOMMXHRYHEGBJIVSXBBGQKXRIYNZFIWSZPPUUM
PPKKLHXWWT) == ['BBITKNCLTADXYCFTNQMRYVXBBGXFWS', 'BBITUNCLTADXYLFTNQERYVXBBGXZWS', 'BBITKNCLTADXYCFTNQMRYVXBBGXZWS']