from ..program4738 import program4738
def test15():
    assert program4738(ZFFBNYVXOZCJPSRAEACVPAUKVTCVZYQPHVENTKOCMHNIYYMIKKLNKHLWHHWAQMWFTSYEOQQFEYAAYGMPNZCRYBVNAQTDSLXZGBCG
PIQHLNEWAMFAKGHBGZAWRWAXCSKUDZBDOCTXAHSVFZACXGFMDSYBYYDDNQNBEZCYCULSMMPBTQOJQNRPZTRCSDLIYPLVUGJPKDTG
ZBFJPLNAKWQBTUVJKMHVBATAM) == ['FBZRACKZOCHAFSYYYNZCYBQTSLGG', 'FBZAACKZOCHAFSYYYNZCYBQTSLGG', 'FBZRACKZOCHAMSYYYNZCYBNTDLGG', 'FBZRACUZOCHAMSYYYNZCYBNTDLGG']