from ..program4738 import program4738
def test39():
    assert program4738(AAACAAACAAADAAAAAAA
AADAAAAAAAACDAAAAAAAAAAACAAAAABCACAAACAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADA
AAACAADAAAAADD) == ['AAACAAACAAAAAAAAAA']