from ..program4738 import program4738
def test26():
    assert program4738(AABABABABAAAABBAAAABABABABAAAAABABAAAA
AABABAAABABABAAABAAAAABAAABAAABABABBBABBAAABAABAAAAABABBABAAABAABAABABAAAABABAAABAAABAABABBBABBABABA
AAAAA) == ['AABABABABAAAABBAAAABABABABAAAABABAAAA']