from ..program4738 import program4738
def test34():
    assert program4738(ABAABACABADAACADABACAAB
BAACABADABACABAAAADADAABACABACABADABABADABACABAADABBADABACAAACAABACABADABBBAA
DABACA) == ['ABAABACABADAACAABACAAB', 'ABAABACABADAACADABAAAB']