from ..program4738 import program4738
def test31():
    assert program4738(ASDASASDASDASDAASDASDASDASASDDAASDASSASDSDAD
DASDASSSDASDASDASASDASSDAASDASSDDSASDASDAASDDAASDASDAASDASDDASDASDASDASDASS
DASD) == ['ASDASASDASASDAASDASASDASASDDAASDASSASDSDAD']