from ..program4738 import program4738
def test13():
    assert program4738(KEJHTOKHMKWTYSJEAJAXGADRHUKBCRHACSRDNSZIHTPQNLOSRKYBGYIIJDINTXRPMWSVMMBODAYPVVDDTIXGDIOMWUAKZVFKDAUM
WTEVPIFAAJYIDTZSZKPPQKIOMHDZTKDMFVKSJRUFMNHZJPVSQYELWYAFACGGNRORSLGYVXAEYVLZBLDEHYDGOFDSWUYCXLXDKFSU
TUZEQBWVBVTKETQ) == ['EJTKHMKSJRUNHPQLYGNRSVAYVDDGOWUKFU', 'EJTOKMKSJRUHZPQLYGNRSVAYVDDGDWUKFU', 'EJTOKMKSJRUNZPQLYGNRSVAYVDDGDWUKFU', 'EJHTKMKSJRUHZPQLYGNRSVAYVDDGDWUKFU']