from ..program4738 import program4738
def test5():
    assert program4738(AUNBEKNURNUPHXQYKUTAHCOLMPRQZZTVDUYCTNIRACQQTQAIDTAWJXBUTIZUASDIJZWLHAQVGCAHKTZMXSDVVWAIGQEALRFKFYTT
QBVRFKPKLYZLYNRFTRJZZQEYAEKPFXVICUVFVQSDENBJYYNCFTOZHULSWJQTNELYLKCZTGHOARDCFXBXQGGSQIVUCJVNGFZEEZQE
N) == ['BKPYTRZZVICQDJTZUSJZHAQGSVVGQE', 'BRPKLZYTRQAXIUSDJZWLHACXSVVGQE', 'BRPKLRZZYACQDBTZUSWLHACXSVVGQE', 'BRPKLRZZYICQDJTZUSJZHAQGSVVGQE', 'BKPKLRZZVICQDJTZUSJZHAQGSVVGQE']