from ..program4738 import program4738
def test16():
    assert program4738(BTWZLIKDACZVLCKMVTIQHLFBNRCBDSWPFFKGPCQFPTOIJLPFCDMFGQKFHTDFFCCULUAYPXXIIIWBZIDMOPNHPZBEXLVARJFTBFOE
MDXYKKWZVASJPPWRCYNMRAOBBLUNBSMQAPCPSFAGLXWJRBQTBRWXYNQGWECYNFIAJXDMUHIIMDFMSHLPIMYQXNRRUSSNXALGNWIK
KNFVBVAOWXMZVUHAVUDKDBUVAKNHACZBGBHMUOPHWGQSDFXLHB) == ['WZACMLNBSPFGCFIJDMHDFLPIMNXL', 'WZACLMQLBRWGCFIJDMHDFLPIMNXL', 'WZACMBNBSPFGQTIJDMHDFLPIMNXA', 'WZVCMLNBSPFGCFIJDMHDFLPIMNXL', 'WZACMLNBSPFGQTIJDMHDFLPIMNXL', 'DZVCMBNBSPFGCFIJDMHDFLPIMNXA']