from ..program4738 import program4738
def test18():
    assert program4738(BBYUVCIYLNUJPSEYCAAPQSDNSDDTNEHQZDPBEKQAWNAKEYFBNEEBGPDPRLCSVOWYDEDRPPEDOROCHRCNQUSPNVXGRXHNLKDETWQC
BQCQXCAHADGJHBYIKEUWNXFUOOTVCCKJPJJCMWLAWWKSDGHFNZTCPSQNRTPCBLXDTSJLRHSCCZXQXCVLVGTROOUCUQASIQHZGNEI
RYE) == ['BBYUVCJPCASDNZPQNBDRLVROOCQSGNE', 'BBYINUJPCASDHZPQNPDRSVROOCUSHNE', 'BBYINUJPCASDHZPQNPDLSVROOCUSHNE', 'BBYUVCJPCASDNTPQNBDRLVROOCQSGNE', 'BBYUVCJPCASDNTPQNBDLCVROOCQSGNE']