from ..program4738 import program4738
def test6():
    assert program4738(BGIIURZTEUJJULBWKHDQBRFGEUOMQSREOTILICRSBUHBGTSRDHKVDDEBVHGMHXUVFJURSMFDJOOOWCYPJDVRVKLDHICPNKTBFXDJ
XOADNTKNILGNHHBNFYNDWUNXBGDFUKUVHLPDOGOYRMOTAQELLRMHFAQEOXFWGAQUROVUSWOAWFRVIRJQVXPCXLSCQLCUWKBZUFQP
YVF) == ['TLBWKHDGOROTLRHEGUVUSOWVRVLCKBF', 'ILBWKHDGOMQELRHEGUVUSOWVRVLCKBF', 'TLBWKHDGOROTLRMHXFUROOWVRVLCKBF', 'TLBWKHDGOROTLRMHXFURSOWVRVLCKBF']