from ..program4738 import program4738
def test14():
    assert program4738(EGQYYSKTFTURZNRDVIWBYXMRDGFWMYKFXGIFOGYJSXKDCJUAGZPVTYCHIXVFTVTCXMKHZFTXSMMQVFXZGKHCIYODDRZEYECDLKNG
PEXXCTRFJAAKPOTBAEFRLDRZKORNMXHHXTLKMKCGPVPUOBELPLFQFXOBZWIVIQCHEJQPXKGSCQAWIMETCJVTAGXJIINTADDXJTKQ
QURSEKPMSSEVQZI) == ['ETFTBRDKOXKCGPVFVCHQXKCIECDK', 'EKTFRZRXMGFFXOZVCHXCMTVGIDDK', 'ETFTBRDKOXKCGPVXVCHQXKCIECDK', 'EKTFRZNXMGFFXIJXKCATCVTXTDDK', 'EKTFRZNXMGFFXIJXKCATCVTXIDDK']