from ..program4738 import program4738
def test17():
    assert program4738(GOZVMIRQIGYGVAGOREQTXFXPEZYOJOXPNDGAESICXHMKQDXQPRLMRVWHXFEJVCWZDLYMQLDURUXZPTLEHPTSKXGSNEQDKLVFFLDX
IMEVFCZXACKRRJVXDRKFWTLTRTLQQDHEBZLCOCNVPABQMIWJHRLKFUKWOVVWGGNWCJNRYOYOAJFQWCLHQIQRBZTVWKBFOXKEHHQP
SZ) == ['IEFZXACKRRVXFWLRTLHPKGNQLVFX', 'IVARXFEZONAIHRLVWJWLQRZTKXEQ', 'MVARXFEZOPAIHRLVWFCLQRZTKXEQ']