from ..program4738 import program4738
def test33():
    assert program4738(ABAAAABABADABAABAABCCABADABACABACABCABADABADABACABBACAADABACABABACABADABACABABA
BACAACABABABACABCABADABAACABADABACABAA
ABBAB) == ['BACAACABABABACABCAADABAACABADABACABAA', 'BACAACABABABACABCABAABAACABADABACABAA', 'BAAACABABABACABCABADABAACABADABACABAA']