from ..program4738 import program4738
def test3():
    assert program4738(QNHRPFYMAAPJDUHBAEXNEEZSTMYHVGQPYKNMVKMBVSVLIYGUVMJHEFLJEPIWFHSLISTGOKRXNMSCXYKMAXBPKCOCNTIRPCUEPHXM
RRFCZUGFDRKKMQTOETNELXMEWGOCDHFKIXOPVHHEWTCDNXVFKFKTKNWKEIKTCMHMHDNCLLVQSGKHBCDDYVVVQIRPZEOPUGQUGRHH
R) == ['FUENEMGKIVHEFEIHLSGKBCIPEPH', 'FDENEMGKIVHEWFTKNMCKBCIPEPH', 'FMENEEHKIVHEFEIHLSGKCYPOPUH', 'QNHFPHEXNETMHMHLLSGKCYPOPUH', 'QNHFPHETVKNKMMHLLSGKBCIPEPH', 'FDENEMGKIVHEFEIHLSGKCYPOPUH']