from ..program4738 import program4738
def test19():
    assert program4738(WZRKLETJRBBRZKGHEFBVEFVLIERBPSEGJVSNUZUICONWWBOOTHCOJLLZFNOCNOFJQZTZWBLKHGIWWWPBUYWBAHYJGEBJZJDTNBGN
ZINFGDCNKHYFZYYWHTIHZTKWXXXMSWOVOPQDTRWSQKBWWCPEMYFVGARELELBLGEVJCMOCFTTUVCYUQUSFONAMWKVDWMGXVNZJBWH
AFPA) == ['WZKTRKBEFVLEBGVCOTCFONWKWGZJB', 'WZKTRBEFVELEBEJCOTCFONWKWGZJB', 'WZKTRBEFVELEBGVCOTCFONWKWGZJB', 'WZKTRKEFVELEBEJCOTCFONWKWGZJB']