from ..program4662 import program4662
def test34():
    assert program4662(9
XXXOXOOXO
XOOOOXOOO
OOXXOXOXO
XXXXOXOXX
XXXXXXOXO
OOXOXXOXX
XXOXXXXXO
XXXOXOOOO
XXOOXOOXX
XXXOXOOXO
XOOOOXOOO
OOXXOXOXO
XXXXOXOXX
XXXXXXOXO
OOXOXXOXX
XXOXXXXXO
XXXOXOOOO
XXOOXOOXX) == ['YES', 'Yes']