from ..program4662 import program4662
def test10():
    assert program4662(10
XXOXXOXOOX
OOOOXOOXXO
OXXXOOXOOO
OOXOOOOOOO
XXXOXOXXXX
OXXXXOXXOO
OXXXXOOXXX
XXOXXOXOXO
OOOXOOOOOO
XOOXOOOOXX
XOOXOOOOXX
OOOXOOOOOO
XXOXXOXOXO
OXXXXOOXXX
OXXXXOXXOO
XXXOXOXXXX
OOXOOOOOOO
OXXXOOXOOO
OOOOXOOXXO
XXOXXOXOOX) == ['YES', 'Yes']