from ..program4662 import program4662
def test14():
    assert program4662(10
XOOOOXOOOX
OOOOOOOXXX
OXOOOXXOXO
OOXXXOOXOX
OOXXOOOXXO
XXXXOXOXXX
XXXOOXOOOO
XXXXOOXXXO
OXXXXXXOXX
XXXOOOXOXO
XOOOXOOOOX
XXXOOOOOOO
OXOXXOOOXO
XOXOOXXXOO
OXXOOOXXOO
XXXOXOXXXX
OOOOXOOXXX
OXXXOOXXXX
XXOXXXXXXO
OXOXOOOXXX) == ['YES', 'Yes']