from ..program4662 import program4662
def test13():
    assert program4662(10
XXOOXOOOXO
XXOXXXXXXX
XOOOXOOXXX
OXOOOXXXXO
XOOOOOOOOO
XXOXXXXOOX
OOOXOXOOOX
XOXOOXOOXO
OOXOOXOXXO
XOXOXOXXOO
OOOXXOOXXO
OXXOOOOXOX
XXOOOOXXXO
XOOOXOXOXO
OXXXXOXOXO
XOOOXOOXXX
OOOXXOOOXO
XXXOOOOOOO
OOOOXOXOXX
XOXOXXOXXX) == ['No', 'NO']