from ..program4662 import program4662
def test21():
    assert program4662(10
XXOOOOOXOX
OOOOXXXOXX
OOOXOOOOXX
OXXXXXXOOX
XOOXOXOOXX
XOOOOOOXXO
XXXOOOOXOO
OOOOXOXOOO
OXOOOOOXOX
XXOXXXOXOX
XXOOOXXXXO
OOOOXXOOXO
XXOXXOOOOX
XOXOOOXOXO
XOOOOXXOXO
XOXOOOXOXO
XOOXOXXXXO
OOOXOOXOOO
XXOXOXXOOX
XOOXXXOOOX) == ['No', 'NO']