from ..program4662 import program4662
def test12():
    assert program4662(10
XOOXOXXXXX
XOXXOXOXXX
OOOXOXOOOX
OOOXXXOOXX
OXOXXOXOXO
OXXOXOOOOO
OXOOXXOXXO
OOXOXXXXOX
XOXXXXOOXX
XOOOOXXOOX
XXXOOOXXXX
OXOXOXXOXX
OOXXOOOOXX
XOXOOXOOOX
XXXXOOXXXX
OXXXXXXOOO
OXOOOXXXXX
OXXOXOOOXO
OOOXXXOOOO
XXOOOOOOXX) == ['YES', 'Yes']