from ..program4662 import program4662
def test33():
    assert program4662(8
OXOOOOOO
XOXOXXXO
OXXXXXOX
OOXXOXOO
XOOOXOOO
XOOXXOXO
OOXXXXXX
XXXOOXXX
OXOOXXOO
XOXOOOOX
OOXXOOXX
OOXXOXXO
OXXOXXXX
OXOXXOXO
OXOOOXXX
OOXOOOXX) == ['No', 'NO']