from ..program4662 import program4662
def test20():
    assert program4662(10
XOXXXXXOOO
OXXOOXXOXX
XXXXXOOXOX
OOOOOXOXOX
OXXOXXXOXO
XOOXOXXXXX
XOOOOOOOOX
OOXXOOXXXX
OOOOXXOOOX
XXXXXOOOXX
XXOOOXXXXX
XOOOXXOOOO
XXXXOOXXOO
XOOOOOOOOX
XXXXXOXOOX
OXOXXXOXXO
XOXOXOOOOO
XOXOOXXXXX
XXOXXOOXXO
OOOXXXXXOX) == ['YES', 'Yes']