from ..program4662 import program4662
def test35():
    assert program4662(9
OXOXXXXOX
XOXXOXOOO
OOXOOOXOO
OOOXXOXOX
OOXOOOOXX
OXXXOXOOO
OOOXXOXOO
OOXOXXOXO
OOXOOOXOX
OXOOOOXOO
XOOOOXOOO
OXXOXXOXO
XXOXOXXOO
XOOOOOOXO
XXOOOXOXO
XOXOOOXOX
OOXOXOOXO
XOOXXOOOX) == ['No', 'NO']