from ..program4662 import program4662
def test17():
    assert program4662(10
XOXXXXXXXX
OOOOXXXOXO
XOXXXXOOXX
XXXOXXXXXO
OXXXXOXOOO
OOOOOXOXXX
XOOOXOOXXX
XOOOXXXXOO
OXOOXOXXOX
OXOXXOXXOX
XXOXXOOXOX
OOOXXOXXXX
XXXXXOXOOX
XXXOOXXOXO
OOXOXOXXXX
XXXXOXXXXX
XOOOOXOXOX
OOOXOXXXXX
XXOOOXXOOO
OOXXOOXOOX) == ['No', 'NO']