from ..program4662 import program4662
def test19():
    assert program4662(10
XXOXOOOOXX
XOXXXOXOXO
OXXXOOXOOO
XXOXOOXXOX
XXOXXOXXOO
OOOXXXXOXO
OXXXOXOXOO
OXOXXXXXXX
XXXOOXXXXX
XXOOXOOXXO
XOOOOXXOXX
XXXXOXXXOX
OXOXOOOXXO
OOXXXXXXXX
XOXOXXOOXO
OXXXXOOOXX
OXXXXXXXXO
XXXXOXXOOO
XXXOXOOOXX
OXXXOOXOOX) == ['No', 'NO']