from ..program4662 import program4662
def test15():
    assert program4662(10
XOXXOXXOOX
OXXOXOXXXX
XXOOXOXOOO
OXOOOOXOOO
OOOOOOOXOX
XXOXXOOXOX
XOXOXOOOOX
OXOXOOXXOX
XOXOXOXXXO
OOXOXXXXXX
OOXOOXXXXX
XOXOXOXXXO
OXOXOOXXOX
XOXXXOOOOX
XXOXXOOXOX
OOOOOOOXOX
OXOOOOXOOO
XXOOXOXOOO
OXXOXOXXXX
XOXOOXXOOX) == ['No', 'NO']