from ..program4662 import program4662
def test18():
    assert program4662(10
XXXOOOOOXO
XXOXOOXOXX
XOXXXXXXXO
XOXOXOOXXX
XXOOXXOXXO
OOOOOOOOXX
OOXOXXOOXX
XXXXOXXOOO
XOXOXXXOXX
OXXOXXOOOO
OXOXOXXOXO
XXXXXXXOXO
OOXXXOOOOO
OXXOOOOXXO
OOXOXOXXXX
OOXXXOXOXX
OXXOOOOXOO
XOXXOOXXXX
XXOOXOOXOX
XXXXXOOXXO) == ['YES', 'Yes']