from ..program4662 import program4662
def test9():
    assert program4662(10
XXXOOOOXOX
OOOXXXOXXO
XOXXXXOOXX
XOOOXXOXOO
OOXOOOOOOX
XXXXOXOOOO
XXXOOXOXOX
OOOOXOXOXX
XOXXOXOOXO
OOOOOXOOOO
XXXOOOOXOX
OOOXXXOXXO
XOXXXXOOXX
XOOOXXOXOO
OOXOOOOOOX
XXXXOXOOOO
XXXOOXOXOX
OOOOXOXOXX
XOXXOXOOXO
OOOOOXOOOO) == ['YES', 'Yes']