from ..program4662 import program4662
def test32():
    assert program4662(8
OXOXXXXX
XXXXOXOO
OXOXOXOX
XXXOXXOX
OXXOXXXX
XXOXXXOO
XXXXOOOO
OXXXOOOO
OOOOXXXO
OOOOXXXX
OOXXXOXX
XXXXOXXO
XOXXOXXX
XOXOXOXO
OOXOXXXX
XXXXXOXO) == ['YES', 'Yes']