from ..program4662 import program4662
def test11():
    assert program4662(10
XXOOOOOXXO
OXOOXOOXXO
XOOXOXXXXO
OXXXXOXOXO
XXXOXXOXOO
OXOOOOOXOX
XOXOXOOOXO
OXXXOOOOOX
XXOOOOOXOO
XOXXXOOXXX
XXOXOXOXOX
OXXOXXXOXX
XOXXOXXOOO
XOXOOOXXOO
XOOXOXXOXO
OOOOOXOXOO
OXOOOOXXOO
XXOOXXOXXX
XOOXOOXXXX
XOXOXOOOOO) == ['No', 'NO']